import { expect, test, type APIResponse, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

/* eslint-disable @typescript-eslint/no-explicit-any -- this journey joins independently governed public resources */

const run = promisify(execFile);
async function git(cwd:string,...args:string[]){return (await run("git",args,{cwd,env:{...process.env,GIT_TERMINAL_PROMPT:"0"}})).stdout.trim()}
async function account(page:Page,name:string,handle:string){await page.goto("/");await page.getByLabel("Display name").fill(name);await page.getByLabel("Handle").fill(handle);await page.getByRole("button",{name:"Create account and continue"}).click();await expect(page.getByRole("heading",{name:"Create a repository"})).toBeVisible();const token=await page.evaluate(()=>localStorage.getItem("vivarium.access-token"));expect(token).toBeTruthy();const headers={Authorization:`Bearer ${token}`};const user=await (await page.request.get("/api/user",{headers})).json();return {headers,user}}
async function json(page:Page,method:"get"|"post"|"put",path:string,headers:Record<string,string>,data?:unknown){const response=await page.request[method](`/api${path}`,{headers,data});const body=await response.text();expect(response.status(),`${method.toUpperCase()} ${path}: ${body}`).toBeGreaterThanOrEqual(200);expect(response.status(),`${method.toUpperCase()} ${path}: ${body}`).toBeLessThan(300);return body?JSON.parse(body):undefined}
async function rejected(response:APIResponse,status:number,code:string){expect(response.status(),await response.text()).toBe(status);await expect(response.json()).resolves.toMatchObject({error:{code}})}

test("a released service moves from obligations to independently verified signed assurance",async({browser})=>{
  test.setTimeout(300_000);const copies:string[]=[];
  try{
    const suffix=Date.now().toString(36),ownerPage=await(await browser.newContext()).newPage(),engineerPage=await(await browser.newContext()).newPage(),auditorPage=await(await browser.newContext()).newPage();
    const owner=await account(ownerPage,"Control Owner",`assurance-owner-${suffix}`),engineer=await account(engineerPage,"Service Engineer",`assurance-engineer-${suffix}`),auditor=await account(auditorPage,"Independent Auditor",`assurance-auditor-${suffix}`);
    const repository=await json(ownerPage,"post","/repositories",owner.headers,{name:`payments-${suffix}`});await json(ownerPage,"post",`/repositories/${repository.id}/collaborators`,owner.headers,{user_id:engineer.user.id});
    const credential=await json(ownerPage,"post","/auth/credentials",owner.headers,{kind:"git",name:"assurance journey",scopes:["git:read","git:write"],expires_in:3600}),copy=await mkdtemp(join(tmpdir(),"vivarium-assurance-"));copies.push(copy);
    await git(tmpdir(),"clone",`http://git:${credential.token}@localhost:3000/git/${repository.id}.git`,copy);await git(copy,"config","user.name","Control Owner");await git(copy,"config","user.email","owner@example.test");await writeFile(join(copy,"service.conf"),"retention_days=unbounded\naudit_log=partial\n");await git(copy,"add","service.conf");await git(copy,"commit","-m","Release payment service candidate");await git(copy,"push","origin","main");const candidateRevision=await git(copy,"rev-parse","HEAD");
    const candidateRelease=await json(ownerPage,"post",`/repositories/${repository.id}/releases`,owner.headers,{version:"v1.0.0-rc1",notes:"Candidate for independent assurance",commit_id:candidateRevision});
    const revision={title:"Payment service assurance",summary:"Contractual retention and auditability for the released payment service",owner_ids:[owner.user.id],review_period_days:90,requirements:[{id:"retain",kind:"contractual",authority:"Merchant agreement",citation:"Schedule 4.2",title:"Bound retention",summary:"Payment metadata is retained only for the agreed window",applicability:"Released payment service",owner_ids:[owner.user.id],interpretation:"Configuration and audit evidence prove a 30-day bound"}],scopes:[{id:"service",kind:"repository",resource_id:repository.id,description:"Payment service source"},{id:"candidate",kind:"release",resource_id:candidateRelease.id,description:"Assessed candidate release"}],controls:[{id:"retention",title:"Payment retention",objective:"Delete payment metadata after 30 days and retain attributable audit events",requirement_ids:["retain"],owner_ids:[owner.user.id],review_period_days:30,mappings:[{scope_id:"service",purpose:"Implements retention"},{scope_id:"candidate",purpose:"Candidate under review"}],evidence_criteria:[{id:"released",description:"Exact release ledger proves the assessed revision",kind:"automated",resource_kind:"release",resource_id:candidateRelease.id}],claim:"The exact release enforces 30-day retention with complete audit events"}],exceptions:[]};
    const rejectedException={...revision,exceptions:[{id:"skip-audit",requirement_ids:["retain"],control_ids:["retention"],rationale:"Ship without complete audit events",granted_by:auditor.user.id,expires_at:new Date(Date.now()+86400000).toISOString(),follow_up:"none"}]};
    await rejected(await ownerPage.request.post(`/api/repositories/${repository.id}/assurance-programs`,{headers:owner.headers,data:{revision:rejectedException}}),403,"assurance_program_forbidden");
    let program=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-programs`,owner.headers,{revision});
    const periodStart=new Date(Date.now()-3600000).toISOString(),periodEnd=new Date(Date.now()+86400000).toISOString();
    const definition=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-evidence/definitions`,owner.headers,{program_id:program.id,program_version:1,control_id:"retention",title:"Daily release provenance",period_starts_at:periodStart,period_ends_at:periodEnd,schedule:"daily",audience:["repository"],queries:[{id:"release",kind:"release",resource_id:candidateRelease.id,revision:candidateRevision,required:true,max_age_hours:24}]});
    await rejected(await ownerPage.request.post(`/api/repositories/${repository.id}/assurance-evidence/definitions/${definition.id}/packages`,{headers:owner.headers,data:{query_ids:[]}}),400,"invalid_assurance_evidence");
    const candidateEvidence=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-evidence/definitions/${definition.id}/packages`,owner.headers,{query_ids:["release"]});expect(candidateEvidence).toMatchObject({coverage_percent:100,gaps:[],contradictions:[]});
    const now=new Date(),assessment=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-assessments`,owner.headers,{program_id:program.id,program_version:1,title:"Independent candidate assessment",assessor:{user_id:auditor.user.id,kind:"external",organization:"Independent Controls LLP",conflict_disclosure:"none"},scope:{control_ids:["retention"],system_ids:["service"],release_ids:["candidate"],period_starts_at:periodStart,period_ends_at:periodEnd},evidence_package_ids:[candidateEvidence.id],starts_at:new Date(now.getTime()-1000).toISOString(),expires_at:new Date(now.getTime()+86400000).toISOString()});
    await rejected(await auditorPage.request.get(`/api/repositories/${repository.id}`,{headers:auditor.headers}),404,"repository_not_found");expect((await json(auditorPage,"get",`/repositories/${repository.id}/assurance-assessments/${assessment.id}`,auditor.headers)).evidence_packages).toHaveLength(1);
    let assessed=await json(auditorPage,"post",`/repositories/${repository.id}/assurance-assessments/${assessment.id}/events`,auditor.headers,{expected_version:assessment.version,kind:"question",body:"Show that deletion and every administrative change are attributable.",control_id:"retention",evidence_package_ids:[candidateEvidence.id]});
    assessed=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-assessments/${assessment.id}/events`,owner.headers,{expected_version:assessed.version,kind:"response",body:"The candidate proves provenance but its partial audit mode does not support that claim.",control_id:"retention",parent_id:assessed.events.at(-1).id});
    assessed=await json(auditorPage,"post",`/repositories/${repository.id}/assurance-assessments/${assessment.id}/events`,auditor.headers,{expected_version:assessed.version,kind:"finding",body:"Retention is unbounded and administrative audit events are incomplete.",control_id:"retention",status:"contested"});const finding=assessed.events.at(-1);
    assessed=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-assessments/${assessment.id}/events`,owner.headers,{expected_version:assessed.version,kind:"disagreement",body:"Deletion is absent, but partial audit records cover automated changes; correction will make both explicit.",control_id:"retention",parent_id:finding.id,status:"contested"});
    const remediation=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-assessments/${assessment.id}/remediations`,owner.headers,{expected_version:assessed.version,finding_event_id:finding.id,affected_revision:candidateRevision,deadline:new Date(Date.now()+86400000).toISOString(),acceptance_criteria:["retention_days equals 30","audit_log equals complete"],title:"Correct payment retention assurance",tasks:[{title:"Enforce bounded retention",assignee_type:"human",assignee_id:engineer.user.id},{title:"Complete administrative audit events",assignee_type:"agent",assignee_id:""}]});assessed=remediation.assessment;const [humanTask,agentTask]=remediation.tasks;
    const acknowledgeImpact=async(pullID:string)=>{let impact=await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pullID}/assurance-impact`,owner.headers,{program_id:program.id,program_version:1,decisions:[{control_id:"retention",applicability:"affected",rationale:"This correction changes the mapped retention configuration.",tests:[],notices:[],retention_actions:[],exception_ids:[],mitigation:"Independent review and exact-release evidence remain required.",residual_risk:"Deployment configuration remains outside Git authority."}]});impact=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-impacts/${impact.id}/acknowledgements`,owner.headers,{expected_version:impact.version,control_id:"retention"});expect(impact.ready).toBe(true)};
    const waitReady=async(pullID:string)=>expect.poll(async()=>(await json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pullID}/merge-readiness`,owner.headers)).blockers,{timeout:60_000}).toEqual([]);
    const engineerCredential=await json(engineerPage,"post","/auth/credentials",engineer.headers,{kind:"git",name:"human assurance repair",scopes:["git:read","git:write"],expires_in:3600}),humanCopy=await mkdtemp(join(tmpdir(),"vivarium-assurance-human-"));copies.push(humanCopy);await git(tmpdir(),"clone",`http://git:${engineerCredential.token}@localhost:3000/git/${repository.id}.git`,humanCopy);await git(humanCopy,"config","user.name","Service Engineer");await git(humanCopy,"config","user.email","engineer@example.test");await git(humanCopy,"switch","-c","retention-fix");await writeFile(join(humanCopy,"service.conf"),"retention_days=30\naudit_log=partial\n");await git(humanCopy,"add","service.conf");await git(humanCopy,"commit","-m","Enforce thirty day retention");await git(humanCopy,"push","origin","retention-fix");
    const humanPull=await json(engineerPage,"post",`/repositories/${repository.id}/proposals/${remediation.proposal.id}/tasks/${humanTask.id}/contributions`,engineer.headers,{title:"Enforce bounded retention",body:"Human-authored correction for the exact finding.",source_branch:"retention-fix",target_branch:"main"});await acknowledgeImpact(humanPull.id);await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${humanPull.id}/reviews`,owner.headers,{decision:"approved"});await waitReady(humanPull.id);const humanMerged=await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${humanPull.id}/merge`,owner.headers,{});
    const taskList=await json(ownerPage,"get",`/repositories/${repository.id}/proposals/${remediation.proposal.id}/tasks`,owner.headers),readyAgent=taskList.tasks.find((x:any)=>x.id===agentTask.id);expect(readyAgent.ready).toBe(true);const rebasedAgent=await json(ownerPage,"put",`/repositories/${repository.id}/proposals/${remediation.proposal.id}/tasks/${agentTask.id}/assignment`,owner.headers,{assignee_type:"agent",mandate:"Complete administrative audit events on the merged human retention correction.",repository_id:repository.id,base_revision:humanMerged.merge_commit_id,expected_assignment_id:readyAgent.assignment.id});
    const launched=await json(ownerPage,"post",`/repositories/${repository.id}/proposals/${remediation.proposal.id}/tasks/${agentTask.id}/sessions`,owner.headers,{expected_assignment_id:rebasedAgent.assignment.id,context_paths:["service.conf"],expires_in:3600}),agentCopy=await mkdtemp(join(tmpdir(),"vivarium-assurance-agent-"));copies.push(agentCopy);await git(tmpdir(),"clone",`http://git:${launched.credential.token}@localhost:3000/git/${repository.id}.git`,agentCopy);await git(agentCopy,"config","user.name","Assurance Repair Agent");await git(agentCopy,"config","user.email","agent@agents.vivarium");await git(agentCopy,"switch",launched.run.working_branch);await writeFile(join(agentCopy,"service.conf"),"retention_days=30\naudit_log=complete\n");await git(agentCopy,"add","service.conf");await git(agentCopy,"commit","-m","Complete administrative audit events");await git(agentCopy,"push","origin",launched.run.working_branch);const agentCommit=await git(agentCopy,"rev-parse","HEAD"),runPath=`/repositories/${repository.id}/proposals/${remediation.proposal.id}/tasks/${agentTask.id}/sessions/${launched.session.id}/runs/${launched.run.id}`;
    await json(ownerPage,"post",`${runPath}/completion`,{Authorization:`Bearer ${launched.credential.token}`},{summary:"Completed only the assigned audit setting and retained uncertainty about production configuration.",commit_id:agentCommit,checks:[{name:"assurance configuration",status:"passed",details:"Exact candidate has bounded retention and complete audit mode."}],unresolved_concerns:["Deployment remains human-controlled."]});
    const agentPull=await json(ownerPage,"post",`/repositories/${repository.id}/proposals/${remediation.proposal.id}/tasks/${agentTask.id}/contributions`,owner.headers,{title:"Complete administrative audit events",body:"Agent-authored bounded correction for independent review.",source_branch:launched.run.working_branch,target_branch:"main",session_id:launched.session.id,run_id:launched.run.id});await acknowledgeImpact(agentPull.id);await json(engineerPage,"post",`/repositories/${repository.id}/pulls/${agentPull.id}/reviews`,engineer.headers,{decision:"approved"});await waitReady(agentPull.id);const merged=await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${agentPull.id}/merge`,owner.headers,{});
    const delivered=await json(ownerPage,"post",`/repositories/${repository.id}/releases`,owner.headers,{version:"v1.0.0",notes:"Reviewed retention and complete audit correction",commit_id:merged.merge_commit_id});
    const freshDefinition=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-evidence/definitions`,owner.headers,{program_id:program.id,program_version:1,control_id:"retention",title:"Delivered release provenance",period_starts_at:periodStart,period_ends_at:periodEnd,schedule:"manual",audience:["repository"],queries:[{id:"delivered",kind:"release",resource_id:delivered.id,revision:merged.merge_commit_id,required:true,max_age_hours:24}]}),fresh=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-evidence/definitions/${freshDefinition.id}/packages`,owner.headers,{query_ids:["delivered"]});
    assessed=await json(auditorPage,"post",`/repositories/${repository.id}/assurance-assessments/${assessment.id}/remediations/${assessed.remediations[0].id}/verification`,auditor.headers,{expected_version:assessed.version,verification:"The exact merged release now satisfies both acceptance criteria.",disposition:"accepted",evidence_package_ids:[fresh.id]});
    assessed=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-assessments/${assessment.id}/events`,owner.headers,{expected_version:assessed.version,kind:"scope_change",body:"Select the exact corrected descendant release for the final claim.",release_id:delivered.id});expect(assessed.status).toBe("scope_changed");assessed=await json(auditorPage,"post",`/repositories/${repository.id}/assurance-assessments/${assessment.id}/events`,auditor.headers,{expected_version:assessed.version,kind:"scope_acknowledgement",body:"I acknowledge the exact corrected release as the delivered assessment scope.",release_id:delivered.id});
    const statementResult=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-statements`,owner.headers,{assessment_id:assessment.id,release_id:delivered.id,release_revision:merged.merge_commit_id,control_ids:["retention"],exception_ids:[],audience:[owner.user.id,auditor.user.id],claim:"Payment service v1.0.0 enforces 30-day retention with complete administrative audit events.",expires_at:new Date(Date.now()+86400000).toISOString()}),statement=statementResult.statement;expect(statementResult).toMatchObject({status:"current",signature_algorithm:"Ed25519"});
    expect((await json(auditorPage,"get",`/repositories/${repository.id}/assurance-statements/${statement.id}`,auditor.headers)).status).toBe("current");
    const evolved={...revision,summary:"Successor interpretation after post-publication control drift",scopes:[...revision.scopes,{id:"delivered",kind:"release",resource_id:delivered.id,description:"Delivered release"}],controls:[{...revision.controls[0],claim:"The release also requires quarterly restore sampling",mappings:[...revision.controls[0].mappings,{scope_id:"delivered",purpose:"Delivered correction"}]}]};program=await json(ownerPage,"post",`/repositories/${repository.id}/assurance-programs/${program.id}/revisions`,owner.headers,{expected_version:1,revision:evolved});expect((await json(auditorPage,"get",`/repositories/${repository.id}/assurance-statements/${statement.id}`,auditor.headers)).status).toBe("drifted");await json(ownerPage,"post",`/repositories/${repository.id}/assurance-statements/${statement.id}/revocation`,owner.headers,{reason:"Successor control interpretation requires reassessment."});expect((await json(auditorPage,"get",`/repositories/${repository.id}/assurance-statements/${statement.id}`,auditor.headers)).status).toBe("revoked");
    await ownerPage.goto(`/repositories/${repository.id}/assurance`);await expect(ownerPage.getByRole("heading",{name:"Assurance"})).toBeVisible();await expect(ownerPage.getByText("Independent candidate assessment")).toBeVisible();await expect(ownerPage.getByText("Retention is unbounded and administrative audit events are incomplete.")).toBeVisible();await expect(ownerPage.getByText("Correction · retention")).toBeVisible();
  }finally{await Promise.all(copies.map(path=>rm(path,{recursive:true,force:true})))}
});
