import { expect, test, type APIResponse, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

/* eslint-disable @typescript-eslint/no-explicit-any -- this journey joins the complete public capacity ledger */
const run = promisify(execFile);
async function git(token: string, cwd: string, ...args: string[]) {
  return (await run("git", ["-c", "credential.helper=", ...args], { cwd, env: { ...process.env, GIT_ASKPASS: join(__dirname, "git-askpass.sh"), GIT_TERMINAL_PROMPT: "0", VIVARIUM_GIT_TOKEN: token } })).stdout.trim();
}
async function account(page: Page, suffix: string, role: string) {
  await page.goto("/");
  await page.getByLabel("Display name").fill(`${role} owner`);
  await page.getByLabel("Handle").fill(`capacity-${role.toLowerCase()}-${suffix}`);
  await page.getByRole("button", { name: "Create account and continue" }).click();
  await expect(page.getByRole("heading", { name: "Create a repository" })).toBeVisible();
  const token = await page.evaluate(() => localStorage.getItem("vivarium.access-token"));
  expect(token).toBeTruthy();
  const headers = { Authorization: `Bearer ${token}` };
  return { headers, user: await (await page.request.get("/api/user", { headers })).json() };
}
async function json(page: Page, method: "get" | "post" | "put" | "delete", path: string, headers: Record<string, string>, data?: unknown) {
  const response = await page.request[method](`/api${path}`, { headers, data });
  const body = await response.text();
  expect(response.status(), `${method.toUpperCase()} ${path}: ${body}`).toBeGreaterThanOrEqual(200);
  expect(response.status(), `${method.toUpperCase()} ${path}: ${body}`).toBeLessThan(300);
  return body ? JSON.parse(body) : undefined;
}
async function rejected(response: APIResponse, status: number, code: string) {
  const body = await response.text(); expect(response.status(), body).toBe(status); expect(JSON.parse(body)).toMatchObject({ error: { code } });
}
async function eventually<T>(operation: () => Promise<T>, predicate: (value: T) => boolean, label: string) {
  let value = await operation();
  await expect.poll(async () => { value = await operation(); return predicate(value); }, { timeout: 60_000, message: label, intervals: [250, 500, 1000] }).toBeTruthy();
  return value;
}

test("a roadmap forecast becomes reviewed, delivered, and verified capacity", async ({ browser }) => {
  test.setTimeout(300_000);
  test.skip(!(await run("docker", ["info"]).then(() => true, () => false)), "protected delivery requires Docker");
  await run("docker", ["image", "inspect", "alpine:3.22"]).catch(() => run("docker", ["pull", "alpine:3.22"]));
  const copy = await mkdtemp(join(tmpdir(), "vivarium-capacity-"));
  try {
    const suffix = Date.now().toString(36), ownerPage = await (await browser.newContext()).newPage(), dependencyPage = await (await browser.newContext()).newPage();
    const owner = await account(ownerPage, suffix, "Service"), dependency = await account(dependencyPage, suffix, "Database");
    const repository = await json(ownerPage, "post", "/repositories", owner.headers, { name: `roadmap-capacity-${suffix}` });
    await json(ownerPage, "post", `/repositories/${repository.id}/collaborators`, owner.headers, { user_id: dependency.user.id });
    const credential = await json(ownerPage, "post", "/auth/credentials", owner.headers, { kind: "git", name: "capacity journey", scopes: ["git:read", "git:write"], expires_in: 3600 });
    await git(credential.token, tmpdir(), "clone", `http://localhost:3000/git/${repository.id}.git`, copy);
    await git("", copy, "config", "user.name", "Capacity Engineer"); await git("", copy, "config", "user.email", "capacity@example.test"); await mkdir(join(copy, ".vivarium"));
    await writeFile(join(copy, ".vivarium", "checks.json"), JSON.stringify({ version: 1, checks: [{ name: "capacity contract", image: "alpine:3.22", command: "grep -q 'workers=4' service.conf" }] }));
    await writeFile(join(copy, ".vivarium", "release.json"), JSON.stringify({ version: 1, steps: [{ name: "package", image: "alpine:3.22", command: "cp service.conf \"$VIVARIUM_OUTPUT/service.conf\"" }] }));
    await writeFile(join(copy, ".vivarium", "deployment.json"), JSON.stringify({ version: 1, stages: [{ name: "progressive", signals: [{ name: "four workers", command: "grep -q 'workers=4' \"$VIVARIUM_ARTIFACT\"" }] }] }));
    await writeFile(join(copy, ".vivarium", "packages.json"), JSON.stringify({ version: 1, dependencies: [], lock: [] }));
    await writeFile(join(copy, "service.conf"), "workers=2\n"); await writeFile(join(copy, "capacity.json"), "{\"synthetic\":true}\n");
    await git("", copy, "add", "."); await git("", copy, "commit", "-m", "Release roadmap baseline"); await git(credential.token, copy, "push", "origin", "main");
    const baseline = await git("", copy, "rev-parse", "HEAD");
    const release = await json(ownerPage, "post", `/repositories/${repository.id}/releases`, owner.headers, { version: `v1-${suffix}`, notes: "Roadmap demand baseline", commit_id: baseline });
    const now = Date.now(), iso = (offset: number) => new Date(now + offset).toISOString();
    const objectiveRevision = { title: "Prepare checkout for accepted roadmap growth", summary: "Serve the accepted team-checkout outcome before launch", scope: { kind: "service", name: "checkout" }, demand_forecasts: [{ id: "roadmap-peak", segment: "teams", start: iso(86400_000), end: iso(90 * 86400_000), value: 80, unit: "rps", confidence: "uncertain", evidence: ["accepted roadmap outcome guided-checkout"] }], traffic_shapes: [{ name: "launch", pattern: "bursty", peak_multiplier: 2, burst_duration: "10m" }], seasonality: [{ name: "launch week", window: "week one", multiplier: 1.5, rationale: "roadmap launch" }], service_levels: [{ name: "availability", indicator: "success", target: 99.9, unit: "percent", window: "30d" }], bottleneck_thresholds: [{ resource: "workers", signal: "queue_depth", warning: 70, critical: 90, unit: "percent" }], dependency_limits: [{ name: "database", limit: 100, unit: "connections", signal: "pool_used" }], regions: [{ name: "primary", demand_share: 1 }], owner_ids: [owner.user.id, dependency.user.id], budget: { amount: 120, currency: "USD", period: "month" }, lead_time: { duration: "14d", trigger: "accepted roadmap launch" }, success_criteria: [{ name: "headroom", condition: "20 rps at forecast", evidence: "production observation" }], rollback_criteria: [{ name: "protect users", condition: "reliability or cost breach", evidence: "production observation" }], links: [{ id: "roadmap", kind: "roadmap", resource_id: "guided-checkout", version: "accepted-v1", label: "Accepted guided checkout outcome" }], assumptions: [{ id: "adoption", statement: "All invited teams arrive in week one", evidence: [], expires_at: iso(30 * 86400_000) }], rationale: "Move capacity planning into the accepted product outcome" };
    const objective = await json(ownerPage, "post", `/repositories/${repository.id}/capacity-objectives`, owner.headers, { request_id: `objective-${suffix}`, revision: objectiveRevision });
    const modelRevision = (title: string, baselineDemand: number, anomalous = false) => ({ title, summary: "Release-bound demand and worker saturation", objective_id: objective.id, objective_version: 1, method: "Project sanitized requests per worker", evidence: [{ id: "usage", kind: "usage", label: "hourly aggregate", resource_id: "checkout-usage", release_id: release.id, release_revision: baseline, observation_window: { start: iso(-30 * 86400_000), end: iso(-1000) }, sanitization: "hourly totals; identifiers removed", instrumentation_version: "otel-v1", anomalous, anomaly_reason: anomalous ? "launch bot traffic polluted the first sample" : "" }], assumptions: [{ id: "mix", statement: "interactive mix remains stable", evidence_ids: ["usage"], confidence: anomalous ? .2 : .8 }], workload_segments: [{ id: "teams", name: "team checkout", demand_unit: "rps", baseline: baselineDemand, growth_rate: .2, evidence_ids: ["usage"] }], saturation_points: [{ id: "workers", segment_id: "teams", resource: "worker pool", limit: 80, unit: "rps", expected_at: iso(45 * 86400_000), lower_at: iso(30 * 86400_000), upper_at: iso(60 * 86400_000), evidence_ids: ["usage"], assumption_ids: ["mix"], explanation: "four workers preserve the declared headroom" }], cost_curve: [{ demand: 40, cost: 50, demand_unit: "rps", currency: "USD", period: "month" }, { demand: 100, cost: 100, demand_unit: "rps", currency: "USD", period: "month" }], demand_scenarios: [{ id: "roadmap", name: "Accepted roadmap", description: "guided checkout adoption", demand_multiplier: 1, assumption_ids: ["mix"], saturation_ids: ["workers"] }] });
    let model = await json(ownerPage, "post", `/repositories/${repository.id}/capacity-models`, owner.headers, { request_id: `bad-model-${suffix}`, revision: modelRevision("Bot-skewed first forecast", 120, true) });
    model = await json(dependencyPage, "post", `/repositories/${repository.id}/capacity-models/${model.id}/events`, dependency.headers, { expected_version: model.current_version, event: { request_id: `challenge-${suffix}`, kind: "challenge", statement: "Database owner rejects the bot-skewed forecast and needs a clean observation window.", evidence_ids: ["usage"] } });
    model = await json(ownerPage, "post", `/repositories/${repository.id}/capacity-models/${model.id}/revisions`, owner.headers, { request_id: `correct-model-${suffix}`, expected_version: model.current_version, revision: modelRevision("Corrected roadmap forecast", 40) });
    const component = { kind: "release", resource_id: release.id, revision: baseline }, candidate = (id: string, name: string, cost: number) => ({ id, name, strategy: id === "larger" ? "vertical" : "horizontal", components: [component], expected_cost: cost, currency: "USD" });
    const capacityTest = await json(ownerPage, "post", `/repositories/${repository.id}/capacity-tests`, owner.headers, { request_id: `test-${suffix}`, plan: { title: "Bounded roadmap peak alternatives", objective_id: objective.id, objective_version: 1, model_id: model.id, model_version: 2, environment_kind: "isolated", candidates: [candidate("larger", "Larger workers", 90), candidate("more", "More workers", 100)], scenarios: [{ id: "peak", name: "Peak with database pressure", kind: "load_failure", command: ["./capacity-test"], workload: { kind: "synthetic", source_path: "capacity.json", sanitization: "generated", contains_production_data: false }, limits: { max_duration_seconds: 60, max_requests: 1000, max_concurrency: 20, max_cost: 12, coordinated_load_key: "checkout/peak", production_impact_allowed: false }, correctness_criteria: ["checkout response remains correct"] }] } });
    const metrics = (cost: number) => ({ throughput: 100, throughput_unit: "rps", duration_seconds: 30, request_count: 900, max_concurrency: 20, latency_p50_ms: 30, latency_p95_ms: 80, latency_p99_ms: 100, error_rate: .001, saturation: .7, recovery_seconds: 5, resource_amount: 4, resource_unit: "workers", cost, currency: "USD" });
    const evidence = (candidate_id: string, request_id: string, extra: any = {}) => json(ownerPage, "post", `/repositories/${repository.id}/capacity-tests/${capacityTest.id}/runs`, owner.headers, { request_id, run: { candidate_id, scenario_id: "peak", status: "succeeded", repetitions: 3, noise_ratio: .02, comparable: true, correctness_passed: true, metrics: metrics(10), logs_digest: "a".repeat(64), ...extra } });
    const noisy = await evidence("larger", `noisy-${suffix}`, { noise_ratio: .4 }); expect(noisy.quality).not.toBe("proof");
    const breached = await evidence("more", `agent-budget-${suffix}`, { metrics: metrics(20) }); expect(breached.limit_breaches).toContain("max_cost");
    await evidence("larger", `proof-${suffix}`); const comparison = await json(ownerPage, "get", `/repositories/${repository.id}/capacity-tests/${capacityTest.id}/comparison`, owner.headers); expect(comparison.proven_candidate_ids).toEqual(["larger"]);
    await json(ownerPage, "delete", `/repositories/${repository.id}/collaborators/${dependency.user.id}`, owner.headers);
    const planBody = { objective_id: objective.id, objective_version: 1, model_id: model.id, model_version: 2, test_id: capacityTest.id, candidate_id: "larger", title: "Phase worker capacity before launch", rationale: "The corrected model and bounded proof support the cheaper alternative", reservations: [{ id: "quota", kind: "provider_quota", owner_id: owner.user.id, description: "Provider initially denied worker quota; retained retry approved", status: "approved", required_by: iso(7 * 86400_000) }], dependencies: [{ id: "database", kind: "dependency", owner_id: dependency.user.id, description: "Database owner must confirm pool headroom", status: "approved", required_by: iso(7 * 86400_000) }], total_budget: 110, currency: "USD", phases: [{ id: "application", name: "Tune application workers", kind: "application", owner_id: dependency.user.id, budget: 40, currency: "USD", depends_on: [], acceptance_criteria: ["ordinary checks prove four workers"], decision_point: "continue after dependency owner review", exit_strategy: "restore two workers" }, { id: "infrastructure", name: "Provision bounded worker capacity", kind: "infrastructure", owner_id: owner.user.id, budget: 60, currency: "USD", depends_on: ["application"], acceptance_criteria: ["protected production reaches 20 rps headroom"], decision_point: "continue only with current infrastructure plan and quota", exit_strategy: "release unused reservation" }] };
    await rejected(await ownerPage.request.post(`/api/repositories/${repository.id}/capacity-plans`, { headers: owner.headers, data: { request_id: `unavailable-owner-${suffix}`, plan: planBody } }), 422, "capacity_plan_invalid");
    await json(ownerPage, "post", `/repositories/${repository.id}/collaborators`, owner.headers, { user_id: dependency.user.id });
    const plan = await json(ownerPage, "post", `/repositories/${repository.id}/capacity-plans`, owner.headers, { request_id: `plan-${suffix}`, plan: planBody });
    const delivery = await json(ownerPage, "post", `/repositories/${repository.id}/capacity-plans/${plan.id}/delivery`, owner.headers, { title: "Deliver reviewed roadmap capacity", body: "Application and infrastructure changes retain their ordinary authority boundaries.", tasks: [{ phase_id: "application", assignee_type: "human", assignee_id: dependency.user.id }, { phase_id: "infrastructure", assignee_type: "agent", assignee_id: owner.user.id }] });
    expect(delivery.tasks.map((x: any) => x.assignment.assignee_type)).toEqual(["human", "agent"]);
    await git("", copy, "switch", "-c", "scale-roadmap"); await writeFile(join(copy, "service.conf"), "workers=4\n"); await git("", copy, "add", "."); await git("", copy, "commit", "-m", "Scale application and infrastructure workers"); await git(credential.token, copy, "push", "origin", "scale-roadmap");
    const pull = await json(dependencyPage, "post", `/repositories/${repository.id}/pulls`, dependency.headers, { title: "Deliver reviewed roadmap capacity", body: "Human application and delegated infrastructure tasks converge through ordinary review.", source_branch: "scale-roadmap", target_branch: "main" });
    await json(ownerPage, "post", `/repositories/${repository.id}/pulls/${pull.id}/reviews`, owner.headers, { decision: "approved" }); const merged = await json(ownerPage, "post", `/repositories/${repository.id}/pulls/${pull.id}/merge`, owner.headers, {});
    const environment = await json(ownerPage, "post", `/repositories/${repository.id}/environments`, owner.headers, { name: "production", position: 1, image: "alpine:3.22", command: "true", timeout_seconds: 30, configuration: {}, credentials: {}, required_approvals: 0, concurrency: 1 });
    await json(ownerPage, "post", `/repositories/${repository.id}/dependency-inventories`, owner.headers, { commit_id: merged.merge_commit_id });
    const finalRelease = await json(ownerPage, "post", `/repositories/${repository.id}/releases`, owner.headers, { version: `v2-${suffix}`, notes: "Reviewed capacity", commit_id: merged.merge_commit_id }); await json(ownerPage, "post", `/repositories/${repository.id}/releases/${finalRelease.id}/builds`, owner.headers, {});
    const builds = await eventually(() => json(ownerPage, "get", `/repositories/${repository.id}/releases/${finalRelease.id}/builds`, owner.headers), (x: any) => x.builds?.some((b: any) => b.state === "succeeded"), "capacity build"); const build = builds.builds.find((x: any) => x.state === "succeeded");
    const pending = await json(ownerPage, "post", `/repositories/${repository.id}/deployments`, owner.headers, { environment_id: environment.id, release_id: finalRelease.id, build_id: build.id, artifact_id: build.artifacts[0].id });
    const deployments = await eventually(() => json(ownerPage, "get", `/repositories/${repository.id}/deployments`, owner.headers), (x: any) => x.deployments?.some((d: any) => d.id === pending.id && d.state === "succeeded"), "protected capacity deployment"); const deployment = deployments.deployments.find((x: any) => x.id === pending.id);
    let rollout = await json(ownerPage, "post", `/repositories/${repository.id}/capacity-rollouts`, owner.headers, { request_id: `rollout-${suffix}`, plan_id: plan.id, phases: [{ id: "application", name: "Tune application workers", controller_type: "human", controller_id: dependency.user.id, environment_id: environment.id, deployment_ids: [deployment.id], deployed_revisions: [merged.merge_commit_id] }, { id: "infrastructure", name: "Provision bounded worker capacity", controller_type: "human", controller_id: owner.user.id, environment_id: environment.id, deployment_ids: [deployment.id], deployed_revisions: [merged.merge_commit_id] }] });
    const observation = (load: number, usable: number, cost: number, failure_kinds: string[] = []) => ({ source: "production", observation_start: iso(-3600_000), observation_end: iso(-1000), deployment_ids: [deployment.id], deployed_revisions: [merged.merge_commit_id], regions: [{ region: "primary", allocated_capacity: 120, usable_capacity: usable, load, unit: "rps" }], allocated_capacity: 120, usable_capacity: usable, load, unit: "rps", service_levels: { availability: 99.99 }, dependency_health: { database: "healthy" }, cost, currency: "USD", forecast_demand: 80, failure_kinds });
    rollout = await json(dependencyPage, "post", `/repositories/${repository.id}/capacity-rollouts/${rollout.id}/events`, dependency.headers, { expected_version: rollout.version, event: { request_id: `regression-${suffix}`, kind: "observe", phase_id: "application", reason: "progressive load exposed a scaling regression", decision_id: "capacity-choice" }, evidence: observation(70, 60, 70, ["scaling_regression"]) }); expect(rollout.status).toBe("contained");
    rollout = await json(dependencyPage, "post", `/repositories/${repository.id}/capacity-rollouts/${rollout.id}/events`, dependency.headers, { expected_version: rollout.version, event: { request_id: `rollback-${suffix}`, kind: "rollback", phase_id: "application", reason: "restore reliable worker behavior" } });
    rollout = await json(dependencyPage, "post", `/repositories/${repository.id}/capacity-rollouts/${rollout.id}/events`, dependency.headers, { expected_version: rollout.version, event: { request_id: `application-recovered-${suffix}`, kind: "observe", phase_id: "application", reason: "reviewed correction restores reliability at forecast load" }, evidence: observation(82, 102, 70) });
    rollout = await json(ownerPage, "post", `/repositories/${repository.id}/capacity-rollouts/${rollout.id}/events`, owner.headers, { expected_version: rollout.version, event: { request_id: `waste-${suffix}`, kind: "observe", phase_id: "infrastructure", reason: "unused reservation is overprovisioned", decision_id: "capacity-choice" }, evidence: observation(35, 110, 105, ["unused_reservation"]) }); expect(rollout.status).toBe("contained");
    rollout = await json(ownerPage, "post", `/repositories/${repository.id}/capacity-rollouts/${rollout.id}/events`, owner.headers, { expected_version: rollout.version, event: { request_id: `throttle-${suffix}`, kind: "throttle", phase_id: "infrastructure", reason: "release waste before final validation", throttle_percent: 75 } });
    rollout = await json(ownerPage, "post", `/repositories/${repository.id}/capacity-rollouts/${rollout.id}/events`, owner.headers, { expected_version: rollout.version, event: { request_id: `verified-${suffix}`, kind: "observe", phase_id: "infrastructure", reason: "real roadmap demand validates headroom, reliability, dependency health, and cost" }, evidence: observation(82, 102, 90) }); expect(rollout).toMatchObject({ status: "verified", evidence: expect.arrayContaining([expect.objectContaining({ headroom: 20, forecast_validated: true, objective_satisfied: true })]) });
    await ownerPage.goto(`/repositories/${repository.id}/capacity`); await expect(ownerPage.getByRole("heading", { name: "Capacity objectives" })).toBeVisible(); await expect(ownerPage.getByText("Corrected roadmap forecast", { exact: true }).first()).toBeVisible(); await expect(ownerPage.getByText("Phase worker capacity before launch", { exact: true })).toBeVisible(); await expect(ownerPage.getByText("verified", { exact: true }).first()).toBeVisible();
    await json(ownerPage, "delete", `/auth/credentials/${credential.id}`, owner.headers);
  } finally { await rm(copy, { recursive: true, force: true }); }
});
