import { expect, test, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

/* eslint-disable @typescript-eslint/no-explicit-any -- this proof follows one retained public-API trail */
const run = promisify(execFile);
async function git(cwd:string,...args:string[]){return(await run("git",args,{cwd,env:{...process.env,GIT_TERMINAL_PROMPT:"0"}})).stdout.trim()}
async function account(page:Page,name:string,handle:string){await page.goto("/");await page.getByLabel("Display name").fill(name);await page.getByLabel("Handle").fill(handle);await page.getByRole("button",{name:"Create account and continue"}).click();await expect(page.getByRole("heading",{name:"Create a repository"})).toBeVisible();const token=await page.evaluate(()=>localStorage.getItem("vivarium.access-token"));expect(token).toBeTruthy();const headers={Authorization:`Bearer ${token}`};const user=await(await page.request.get("/api/user",{headers})).json();return{headers,user}}
async function json(page:Page,method:"get"|"post"|"put"|"patch"|"delete",path:string,headers:Record<string,string>,data?:unknown){const response=await page.request[method](`/api${path}`,{headers,data});const body=await response.text();expect(response.status(),`${method} ${path}: ${body}`).toBeGreaterThanOrEqual(200);expect(response.status(),`${method} ${path}: ${body}`).toBeLessThan(300);return body?JSON.parse(body):undefined}
async function waitForState(page:Page,path:string,headers:Record<string,string>,id:string,state:string){await expect.poll(async()=>{const result=await json(page,"get",path,headers);return result.previews.find((item:any)=>item.id===id)?.state},{timeout:60_000}).toBe(state)}

test("a stakeholder proves an agent-repaired preview before release",async({browser})=>{
  test.setTimeout(180_000);const dockerAvailable=await run("docker",["info"]).then(()=>true,()=>false);test.skip(!dockerAvailable,"preview builds and checks require Docker");await run("docker",["image","inspect","alpine:3.22"]).catch(()=>run("docker",["pull","alpine:3.22"]));
  const copies:string[]=[];try{
    const suffix=Date.now().toString(36),ownerPage=await(await browser.newContext()).newPage(),contributorPage=await(await browser.newContext()).newPage(),stakeholderPage=await(await browser.newContext()).newPage();
    const owner=await account(ownerPage,"Preview Maintainer",`preview-owner-${suffix}`),contributor=await account(contributorPage,"Preview Contributor",`preview-contributor-${suffix}`),stakeholder=await account(stakeholderPage,"Support Stakeholder",`preview-stakeholder-${suffix}`);
    const repository=await json(ownerPage,"post","/repositories",owner.headers,{name:`preview-loop-${suffix}`});await json(ownerPage,"post",`/repositories/${repository.id}/collaborators`,owner.headers,{user_id:contributor.user.id});
    const credential=await json(ownerPage,"post","/auth/credentials",owner.headers,{kind:"git",name:"preview journey",scopes:["git:read","git:write"],expires_in:3600});const copy=await mkdtemp(join(tmpdir(),"vivarium-preview-"));copies.push(copy);await git(tmpdir(),"clone",`http://git:${credential.token}@localhost:3000/git/${repository.id}.git`,copy);await git(copy,"config","user.name","Preview Contributor");await git(copy,"config","user.email","contributor@example.test");await mkdir(join(copy,".vivarium"));
    const preview=(build:string)=>JSON.stringify({version:1,image:"alpine:3.22",build,output_path:"dist",resources:{cpus:1,memory_mb:256,storage_mb:64,timeout_seconds:30},access:{network:"none",data:"preview_artifacts",identity:"named_users",actions:["view","test","feedback"]}});
    await writeFile(join(copy,"README.md"),"# Collaborative preview\n");await writeFile(join(copy,"experience.txt"),"baseline\n");await git(copy,"add",".");await git(copy,"commit","-m","Establish preview baseline");await git(copy,"push","origin","main");await git(copy,"switch","-c","customer-preview");await writeFile(join(copy,"experience.txt"),"broken navigation\n");await writeFile(join(copy,".vivarium","preview.json"),preview("exit 7"));await writeFile(join(copy,".vivarium","checks.json"),JSON.stringify({version:1,checks:[{name:"experience verification",image:"alpine:3.22",command:"grep -qx 'clear navigation' experience.txt"}]}));await git(copy,"add",".");await git(copy,"commit","-m","Propose customer navigation");await git(copy,"push","origin","customer-preview");
    const proposal=await json(contributorPage,"post",`/repositories/${repository.id}/proposals`,contributor.headers,{title:"Make customer navigation clear",body:"Support should validate the exact candidate before delivery."});const pull=await json(contributorPage,"post",`/repositories/${repository.id}/pulls`,contributor.headers,{title:"Clarify customer navigation",body:"Preview-first implementation of the shared proposal.",source_branch:"customer-preview",target_branch:"main",proposal_id:proposal.id});const base=`/repositories/${repository.id}/pulls/${pull.id}`;
    await json(ownerPage,"put",`/repositories/${repository.id}/branches/main/required-checks`,owner.headers,{checks:["experience verification"]});await json(ownerPage,"put",`/repositories/${repository.id}/branches/main/preview-acceptance`,owner.headers,{requirements:[{id:"support-experience",paths:["experience.txt"],risk_classes:[],scenarios:[{name:"support can navigate",role:"stakeholder",blocking:true}]}]});
    await contributorPage.goto(`/pulls/${repository.id}/${pull.id}`);const failedLaunch=contributorPage.waitForResponse(response=>response.request().method()==="POST"&&response.url().endsWith(`${base}/previews`));await contributorPage.getByRole("button",{name:"Launch preview"}).click();const failed=await(await failedLaunch).json();await waitForState(contributorPage,`${base}/previews`,contributor.headers,failed.id,"failed");await contributorPage.reload();await expect(contributorPage.locator("#previews").getByText("failed",{exact:true})).toBeVisible();
    await writeFile(join(copy,".vivarium","preview.json"),preview("mkdir -p dist && printf '<h1>Customer navigation</h1>' > dist/index.html"));await git(copy,"add",".");await git(copy,"commit","-m","Recover preview publication");await git(copy,"push","origin","customer-preview");const candidate=await git(copy,"rev-parse","HEAD");await json(contributorPage,"post",`${base}/synchronize`,contributor.headers);const good=await json(contributorPage,"post",`${base}/previews`,contributor.headers);await waitForState(contributorPage,`${base}/previews`,contributor.headers,good.id,"succeeded");
    const expired=await json(ownerPage,"post",`${base}/previews/${good.id}/invitations`,owner.headers,{source_kind:"user",user_id:stakeholder.user.id,role:"feedback",expires_at:new Date(Date.now()+1200).toISOString()});await new Promise(resolve=>setTimeout(resolve,1500));const expiredResponse=await stakeholderPage.request.get(`/api${base}/previews/${good.id}/findings`,{headers:stakeholder.headers});expect(expiredResponse.status()).toBe(404);expect(expired.invitations.at(-1).user_id).toBe(stakeholder.user.id);
    await json(ownerPage,"post",`${base}/previews/${good.id}/invitations`,owner.headers,{source_kind:"user",user_id:stakeholder.user.id,role:"feedback",expires_at:new Date(Date.now()+3_600_000).toISOString()});await stakeholderPage.goto(`/pulls/${repository.id}/${pull.id}/previews/${good.id}`);await expect(stakeholderPage.getByText("An invitation grants no repository",{exact:false})).toBeVisible();await stakeholderPage.getByPlaceholder("What did you observe?").fill("Navigation label is unclear");await stakeholderPage.getByPlaceholder("Expected and observed behavior").fill("Expected a clear navigation label; observed an ambiguous label with token=secret-value.");await stakeholderPage.getByPlaceholder("One reproduction step per line").fill("Open the customer navigation\nRead the primary label");await stakeholderPage.getByPlaceholder("Optional console output").fill("Authorization: Bearer stakeholder-secret");await stakeholderPage.getByRole("button",{name:"Record finding"}).click();await expect(stakeholderPage.getByText("Navigation label is unclear",{exact:true})).toBeVisible();
    let origin=await json(ownerPage,"get",`${base}/previews/${good.id}/findings`,owner.headers);const finding=origin.findings[0];expect(atob(finding.evidence[0].data)).toContain("[REDACTED]");await json(stakeholderPage,"post",`${base}/preview-acceptance/decisions`,stakeholder.headers,{idempotency_key:`before-repair-${suffix}`,revision:candidate,requirement_id:"support-experience",scenario:"support can navigate",role:"stakeholder",outcome:"accepted",risk_classes:[]});
    const repair=await json(contributorPage,"post",`${base}/previews/${good.id}/findings/${finding.id}/repair`,contributor.headers,{version:finding.version,acceptance_criteria:["experience.txt contains the clear navigation label"]});const session=repair.session;const launched=await json(contributorPage,"post",`${base}/sessions/${session.id}/runs`,contributor.headers,{instructions:"Apply the stakeholder's exact criterion and retain verification evidence.",source_commit_id:session.source_commit_id,context_paths:["experience.txt"],working_branch:"customer-preview",expires_in:3600});const agentCopy=await mkdtemp(join(tmpdir(),"vivarium-preview-agent-"));copies.push(agentCopy);await git(tmpdir(),"clone",`http://git:${launched.credential.token}@localhost:3000/git/${repository.id}.git`,agentCopy);await git(agentCopy,"config","user.name","Vivarium Preview Agent");await git(agentCopy,"config","user.email","agent@users.vivarium");await git(agentCopy,"switch","customer-preview");await writeFile(join(agentCopy,"experience.txt"),"clear navigation\n");await git(agentCopy,"add","experience.txt");await git(agentCopy,"commit","-m","Repair stakeholder preview finding");await git(agentCopy,"push","origin","customer-preview");const repaired=await git(agentCopy,"rev-parse","HEAD"),agentHeaders={Authorization:`Bearer ${launched.credential.token}`};
    const completed=await json(contributorPage,"post",`${base}/sessions/${session.id}/runs/${launched.run.id}/completion`,agentHeaders,{summary:"Applied and verified the exact stakeholder-requested label.",commit_id:repaired,checks:[{name:"experience verification",status:"passed",details:"Exact label is present."}],commands:[{command:"grep -qx 'clear navigation' experience.txt",exit_code:0,summary:"Verified the repaired behavior."}],completion_criteria:[{criterion:"experience.txt contains the clear navigation label",status:"met",evidence:"Focused grep passed."}],unresolved_concerns:[]});expect(completed.preview_attempt.revision).toBe(repaired);await waitForState(contributorPage,`${base}/previews`,contributor.headers,completed.preview_attempt.id,"succeeded");
    const stale=await json(ownerPage,"get",`${base}/merge-readiness`,owner.headers);expect(stale.preview_acceptance.stale_decisions).toHaveLength(1);expect(stale.preview_acceptance.missing).toHaveLength(1);origin=await json(stakeholderPage,"get",`${base}/previews/${good.id}/findings`,stakeholder.headers);await json(stakeholderPage,"post",`${base}/previews/${good.id}/findings/${finding.id}/decision`,stakeholder.headers,{version:origin.findings[0].version,status:"resolved"});await json(ownerPage,"post",`${base}/previews/${completed.preview_attempt.id}/invitations`,owner.headers,{source_kind:"user",user_id:stakeholder.user.id,role:"feedback",expires_at:new Date(Date.now()+3_600_000).toISOString()});await json(stakeholderPage,"post",`${base}/preview-acceptance/decisions`,stakeholder.headers,{idempotency_key:`repaired-${suffix}`,revision:repaired,requirement_id:"support-experience",scenario:"support can navigate",role:"stakeholder",outcome:"accepted",risk_classes:[]});
    await expect.poll(async()=>{const readiness=await json(ownerPage,"get",`${base}/merge-readiness`,owner.headers);return readiness.required_checks.every((check:any)=>check.status==="passed")},{timeout:60_000}).toBeTruthy();await json(ownerPage,"post",`${base}/reviews`,owner.headers,{decision:"approved"});const merged=await json(ownerPage,"post",`${base}/merge`,owner.headers);const release=await json(ownerPage,"post",`/repositories/${repository.id}/releases`,owner.headers,{version:"v1.0.0",notes:"Release the stakeholder-accepted navigation.",commit_id:merged.merge_commit_id});expect(release.commit_id).toBe(merged.merge_commit_id);
    await ownerPage.goto(`/pulls/${repository.id}/${pull.id}`);await expect(ownerPage.getByText("Merged",{exact:true})).toBeVisible();await expect(ownerPage.getByText("Navigation label is unclear",{exact:true})).toBeVisible();const retained=await json(ownerPage,"get",`${base}/previews`,owner.headers);expect(retained.previews).toEqual(expect.arrayContaining([expect.objectContaining({id:failed.id,state:"failed",stale:true}),expect.objectContaining({id:good.id,revision:candidate,stale:true}),expect.objectContaining({id:completed.preview_attempt.id,revision:repaired})]));expect(repair.session.preview_evidence.finding_id).toBe(finding.id);expect(merged.proposal_id).toBe(proposal.id);
  }finally{await Promise.all(copies.map(path=>rm(path,{recursive:true,force:true})))}
});
