import { expect, test, type Page } from "@playwright/test";
import { createHash, createPublicKey, verify } from "node:crypto";
import { execFile, spawn, type ChildProcess } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

/* eslint-disable @typescript-eslint/no-explicit-any -- the journey joins broad public API projections */

const run = promisify(execFile);
async function git(cwd:string,...args:string[]){return (await run("git",args,{cwd,env:{...process.env,GIT_TERMINAL_PROMPT:"0"}})).stdout.trim()}
async function account(page:Page,name:string,handle:string){await page.goto("/");await page.getByLabel("Display name").fill(name);await page.getByLabel("Handle").fill(handle);await page.getByRole("button",{name:"Create account and continue"}).click();await expect(page.getByRole("heading",{name:"Create a repository"})).toBeVisible();const token=await page.evaluate(()=>localStorage.getItem("vivarium.access-token"));expect(token).toBeTruthy();const headers={Authorization:`Bearer ${token}`};const user=await (await page.request.get("/api/user",{headers})).json();return {headers,user}}
async function json(page:Page,method:"get"|"post"|"put",path:string,headers:Record<string,string>,data?:unknown){const response=await page.request[method](`/api${path}`,{headers,data});const body=await response.text();expect(response.status(),`${method.toUpperCase()} ${path}: ${body}`).toBeGreaterThanOrEqual(200);expect(response.status(),`${method.toUpperCase()} ${path}: ${body}`).toBeLessThan(300);return body?JSON.parse(body):undefined}

test("a developer extension carries a pull event through governed repair and revocation",async({browser})=>{
  test.setTimeout(240_000);
  const suffix=Date.now().toString(36),root=await mkdtemp(join(tmpdir(),"vivarium-extension-")),copy=join(root,"repository");let service:ChildProcess|undefined;
  try{
    const serviceFile=join(root,"sample-extension.ts"),serviceToken=`repair-lens-${suffix}`;
    await writeFile(serviceFile,`const token=${JSON.stringify(serviceToken)};const server=Bun.serve({hostname:"127.0.0.1",port:0,fetch(request){const challenge=request.headers.get("Vivarium-Extension-Challenge");return new Response(request.url.endsWith("/health")?token:null,{status:request.url.endsWith("/health")?200:204,headers:{"Vivarium-Sample-Extension":token,...(challenge?{"Vivarium-Extension-Challenge":challenge}:{})}})}});console.log("EXTENSION_READY "+server.port);`);
    service=spawn("bun",["run",serviceFile],{stdio:["ignore","pipe","pipe"]});
    const port=await new Promise<number>((resolve,reject)=>{let stdout="",stderr="";const fail=(message:string)=>reject(new Error(`${message}${stderr?`: ${stderr}`:""}`));service!.stderr!.on("data",chunk=>{stderr+=String(chunk)});service!.stdout!.on("data",chunk=>{stdout+=String(chunk);const match=stdout.match(/EXTENSION_READY (\d+)/);if(match)resolve(Number(match[1]))});service!.once("error",error=>fail(`sample extension failed to start: ${error.message}`));service!.once("exit",code=>fail(`sample extension exited before readiness with code ${code}`))});
    await expect.poll(async()=>fetch(`http://127.0.0.1:${port}/health`).then(async response=>response.headers.get("Vivarium-Sample-Extension")===serviceToken&&(await response.text())===serviceToken,()=>false)).toBe(true);

    const developerPage=await(await browser.newContext()).newPage(),ownerPage=await(await browser.newContext()).newPage(),contributorPage=await(await browser.newContext()).newPage();
    const developer=await account(developerPage,"Extension Developer",`extension-dev-${suffix}`),owner=await account(ownerPage,"Extension Owner",`extension-owner-${suffix}`),contributor=await account(contributorPage,"Extension Contributor",`extension-contributor-${suffix}`);
    const repository=await json(ownerPage,"post","/repositories",owner.headers,{name:`extension-loop-${suffix}`});
    await json(ownerPage,"post",`/repositories/${repository.id}/collaborators`,owner.headers,{user_id:contributor.user.id});
    const registration={name:"Repair Lens",description:"Publishes revision-bound repair evidence.",operator_contact:"operator@example.test",capabilities:["annotate","repair"],callback_endpoint:`http://127.0.0.1:${port}/events`,action_endpoint:`http://127.0.0.1:${port}/actions`,requested_permissions:[{resource:"pull_requests",actions:["read","write"]}],supported_events:["pull_request.created"],credential_rotation:{interval_days:30,overlap_hours:0}};
    let extension=await json(developerPage,"post","/extensions",developer.headers,registration);expect(extension.authority_preview.installed).toBe(false);
    let installation=await json(ownerPage,"post",`/extensions/${extension.id}/installations`,owner.headers,{owner_type:"repository",owner_id:repository.id,repository_ids:[repository.id],resource_types:["pull_requests"],capability_decisions:[{capability:"annotate",decision:"approved"},{capability:"repair",decision:"approved"}],settings:{profile:"strict"}});
    const issued=await json(ownerPage,"post",`/extension-installations/${installation.id}/credentials`,owner.headers,{version:installation.version,expires_in:3600});installation=issued.installation;

    const ownerGit=await json(ownerPage,"post","/auth/credentials",owner.headers,{kind:"git",name:"extension baseline",scopes:["git:read","git:write"],expires_in:3600});
    await git(tmpdir(),"clone",`http://git:${ownerGit.token}@localhost:3000/git/${repository.id}.git`,copy);await git(copy,"config","user.name","Extension Owner");await git(copy,"config","user.email","owner@example.test");await writeFile(join(copy,"README.md"),"# Extension loop\n");await git(copy,"add","README.md");await git(copy,"commit","-m","Create extension baseline");await git(copy,"push","origin","main");
    const contributorGit=await json(contributorPage,"post","/auth/credentials",contributor.headers,{kind:"git",name:"extension contribution",scopes:["git:read","git:write"],expires_in:3600});await git(copy,"remote","set-url","origin",`http://git:${contributorGit.token}@localhost:3000/git/${repository.id}.git`);await git(copy,"switch","-c","extension-repair");await writeFile(join(copy,"policy.txt"),"unsafe=true\n");await git(copy,"add","policy.txt");await git(copy,"commit","-m","Propose policy configuration");await git(copy,"push","origin","extension-repair");const revision=await git(copy,"rev-parse","HEAD");
    const pull=await json(contributorPage,"post",`/repositories/${repository.id}/pulls`,contributor.headers,{title:"Configure policy",body:"Exercise independently governed extension repair.",source_branch:"extension-repair",target_branch:"main"});
    await expect.poll(async()=>(await json(ownerPage,"get",`/extension-installations/${installation.id}/deliveries`,owner.headers)).deliveries.length,{timeout:30_000}).toBeGreaterThan(0);
    const deliveries=await json(ownerPage,"get",`/extension-installations/${installation.id}/deliveries`,owner.headers) as {deliveries:any[];contract:{public_key:string}},delivery=deliveries.deliveries[0],payload=Buffer.from(JSON.stringify(delivery.signed_payload));
    expect(createHash("sha256").update(payload).digest("hex")).toBe(delivery.payload_sha256);
    const key=createPublicKey({key:Buffer.concat([Buffer.from("302a300506032b6570032100","hex"),Buffer.from(deliveries.contract.public_key,"hex")]),format:"der",type:"spki"});expect(verify(null,payload,key,Buffer.from(delivery.signature,"hex"))).toBe(true);
    await json(ownerPage,"post",`/extension-installations/${installation.id}/deliveries/${delivery.id}/attempts`,owner.headers,{status:"failed",response_code:503,error:"sample worker unavailable"});const replay=await json(ownerPage,"post",`/extension-installations/${installation.id}/deliveries/${delivery.id}/replay`,owner.headers,{});expect(replay.event_id).toBe(delivery.event_id);expect(replay.sequence).toBeGreaterThan(delivery.sequence);

    const extensionHeaders={Authorization:`Bearer ${issued.credential.token}`,"Vivarium-Installation-ID":installation.id};
    const contribution=await json(developerPage,"post","/extension-contributions",extensionHeaders,{idempotency_key:`repair-${suffix}`,repository_id:repository.id,resource_type:"pull_requests",resource_id:pull.id,revision,kind:"check",state:"failure",title:"Policy configuration needs repair",body:"The extension found one bounded issue.",annotations:["policy.txt:1 unsafe must be false"],artifacts:[{name:"policy-report.json",url:"https://example.com/policy-report.json",sha256:"a".repeat(64)}],actions:[{id:"repair",label:"Request safe repair",description:"Ask the extension to prepare a revision-bound repair.",inputs:[{name:"mode",label:"Repair mode",required:true,default:"safe"}],effects:["Creates an attributed request only; it does not change Git or merge the pull."]}]});
    await ownerPage.goto(`/pulls/${repository.id}/${pull.id}`);await expect(ownerPage.getByText("policy.txt:1 unsafe must be false")).toBeVisible();await expect(ownerPage.getByRole("link",{name:"policy-report.json"})).toBeVisible();await ownerPage.getByRole("button",{name:"Request action"}).click();await expect(ownerPage.getByText(/Requested by/)).toBeVisible();

    extension=await json(developerPage,"post",`/extensions/${extension.id}/contract`,developer.headers,{...registration,version:extension.contract_version,capabilities:[...registration.capabilities,"summarize"]});const pending=await json(ownerPage,"get",`/extension-installations/${installation.id}`,owner.headers);expect(pending.contract_version).toBeLessThan(extension.contract_version);expect(pending.status).toBe("active");
    installation=await json(ownerPage,"post",`/extension-installations/${installation.id}/upgrade`,owner.headers,{version:pending.version,installation:{owner_type:"repository",owner_id:repository.id,repository_ids:[repository.id],resource_types:["pull_requests"],capability_decisions:[{capability:"annotate",decision:"approved"},{capability:"repair",decision:"approved"},{capability:"summarize",decision:"denied",reason:"fresh consent withheld"}],settings:{profile:"strict"}}});
    await writeFile(join(copy,"policy.txt"),"unsafe=false\n");await git(copy,"add","policy.txt");await git(copy,"commit","-m","Apply requested safe repair");await git(copy,"push","origin","extension-repair");await json(contributorPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/synchronize`,contributor.headers,{});await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/reviews`,owner.headers,{decision:"approved"});const merged=await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/merge`,owner.headers,{});expect(merged.status).toBe("merged");
    installation=await json(ownerPage,"post",`/extension-installations/${installation.id}/remove`,owner.headers,{version:installation.version});expect(installation.status).toBe("removed");const denied=await developerPage.request.post("/api/extension-contributions",{headers:extensionHeaders,data:{...contribution,idempotency_key:`after-remove-${suffix}`}});expect([401,403,409,422]).toContain(denied.status());const retained=await json(ownerPage,"get",`/repositories/${repository.id}/extension-contributions/pull_requests/${pull.id}`,owner.headers);expect(retained.contributions[0].invocations).toHaveLength(1);expect(installation.events.some((event:any)=>event.type==="installation.remove")).toBe(true);
  }finally{service?.kill("SIGTERM");await rm(root,{recursive:true,force:true})}
});
