import { expect, test, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

/* eslint-disable @typescript-eslint/no-explicit-any -- this proof joins the complete public collaboration contract */
const run=promisify(execFile);
async function git(cwd:string,...args:string[]){return(await run("git",args,{cwd,env:{...process.env,GIT_TERMINAL_PROMPT:"0"}})).stdout.trim()}
async function account(page:Page,name:string,handle:string){await page.goto("/");await page.getByLabel("Display name").fill(name);await page.getByLabel("Handle").fill(handle);await page.getByRole("button",{name:"Create account and continue"}).click();await expect(page.getByRole("heading",{name:"Create a repository"})).toBeVisible();const token=await page.evaluate(()=>localStorage.getItem("vivarium.access-token"));expect(token).toBeTruthy();const headers={Authorization:`Bearer ${token}`};const user=await(await page.request.get("/api/user",{headers})).json();return{headers,user}}
async function json(page:Page,method:"get"|"post"|"put"|"patch",path:string,headers:Record<string,string>,data?:unknown){const response=await page.request[method](`/api${path}`,{headers,data});const text=await response.text();expect(response.status(),`${method} ${path}: ${text}`).toBeGreaterThanOrEqual(200);expect(response.status(),`${method} ${path}: ${text}`).toBeLessThan(300);return text?JSON.parse(text):undefined}

test("an unknown developer becomes a credited repeat contributor through guided work",async({browser})=>{
  test.setTimeout(180_000); const dockerAvailable=await run("docker",["info"]).then(()=>true,()=>false);test.skip(!dockerAvailable,"guided work requires Docker-backed workspaces and checks");await run("docker",["image","inspect","alpine:3.22"]).catch(()=>run("docker",["pull","alpine:3.22"]));
  const copies:string[]=[];try{
    const suffix=Date.now().toString(36),ownerPage=await(await browser.newContext()).newPage(),newcomerPage=await(await browser.newContext()).newPage();ownerPage.setDefaultTimeout(10_000);newcomerPage.setDefaultTimeout(10_000);
    const owner=await account(ownerPage,"Welcoming Maintainer",`guide-owner-${suffix}`),newcomer=await account(newcomerPage,"First Contributor",`guide-new-${suffix}`);
    const repository=await json(ownerPage,"post","/repositories",owner.headers,{name:`welcoming-${suffix}`});await json(ownerPage,"patch",`/repositories/${repository.id}`,owner.headers,{visibility:"public"});
    const credential=await json(ownerPage,"post","/auth/credentials",owner.headers,{kind:"git",name:"guided baseline",scopes:["git:read","git:write"],expires_in:3600});
    const copy=await mkdtemp(join(tmpdir(),"vivarium-guided-"));copies.push(copy);await git(tmpdir(),"clone",`http://git:${credential.token}@localhost:3000/git/${repository.id}.git`,copy);await git(copy,"config","user.name","Welcoming Maintainer");await git(copy,"config","user.email","maintainer@example.test");await mkdir(join(copy,".vivarium"));
    await writeFile(join(copy,"welcome.txt"),"needs example\n");await writeFile(join(copy,".vivarium","workspace.json"),JSON.stringify({version:1,image:"alpine:3.22",tools:[{name:"sh",version:"3.22"}],dependencies:["sh"],setup:["test -f missing-guide"],resources:{cpus:1,memory_mb:256,storage_mb:128,setup_seconds:30}}));await git(copy,"add",".");await git(copy,"commit","-m","Retain broken newcomer setup");await git(copy,"push","origin","main");const brokenRevision=await git(copy,"rev-parse","HEAD");await git(copy,"branch","broken-onboarding",brokenRevision);await git(copy,"push","origin","broken-onboarding");
    await writeFile(join(copy,"missing-guide"),"present\n");await writeFile(join(copy,".vivarium","checks.json"),JSON.stringify({version:1,checks:[{name:"welcome verification",image:"alpine:3.22",command:"grep -qx 'documented example' welcome.txt"}]}));await git(copy,"add",".");await git(copy,"commit","-m","Repair reproducible onboarding");await git(copy,"push","origin","main");const readyRevision=await git(copy,"rev-parse","HEAD");
    await ownerPage.goto(`/repositories/${repository.id}`);await ownerPage.getByLabel("Required check names").fill("welcome verification");await ownerPage.getByRole("button",{name:"Save requirements"}).click();
    const proposal=await json(ownerPage,"post",`/repositories/${repository.id}/proposals`,owner.headers,{title:"Add the first documented example",body:"A newcomer can make the smallest useful, verified improvement."});
    await json(ownerPage,"put",`/repositories/${repository.id}/contributor-pathway`,owner.headers,{expected_version:0,pathway:{goals:"Make the project understandable through tested examples.",prerequisites:["Basic shell and documentation editing"],conduct:"Be kind and preserve attribution.",security:"Never paste credentials into workspaces.",setup:{summary:"Use the pinned isolated workspace.",verification_commands:["test -f missing-guide"]},communication:"Ask in the retained help thread.",review_policy:"A maintainer other than the author approves passing work.",work_categories:[{audience:"human_or_agent",name:"Examples",description:"Small documented behavior with one exact check."}],requirements:[]}});
    const publish=async(title:string,revision:string)=>json(ownerPage,"put",`/repositories/${repository.id}/contribution-opportunities/new`,owner.headers,{expected_version:0,opportunity:{source:{kind:"proposal",id:proposal.id},title,expected_outcome:"welcome.txt contains one verified documented example.",scope:"Only welcome.txt.",required_skills:["documentation"],interests:["onboarding"],dependency_ids:[],risk:"low",estimated_minutes:60,agent_assistance:true,mentors:[{user_id:owner.user.id,note:"Replies within the guided thread."}],revision,status:"open"}});
    let abandoned=await publish("Unclaimed onboarding cleanup",readyRevision),broken=await publish("Diagnose the broken setup",brokenRevision),ready=await publish("Add a verified welcome example",readyRevision);const next=await publish("Add a second bounded example",readyRevision);
    abandoned=await json(newcomerPage,"post",`/repositories/${repository.id}/contribution-opportunities/${abandoned.id}/claim`,newcomer.headers,{expected_version:abandoned.version,hours:1,note:"Testing availability"});await json(newcomerPage,"post",`/repositories/${repository.id}/contribution-opportunities/${abandoned.id}/release`,newcomer.headers,{expected_version:abandoned.version});
    await newcomerPage.goto(`/repositories/${repository.id}/contribute`);await newcomerPage.getByRole("button",{name:"I understand these expectations"}).click();await expect(newcomerPage.getByText("Acknowledged",{exact:true})).toBeVisible();
    broken=await json(newcomerPage,"post",`/repositories/${repository.id}/contribution-opportunities/${broken.id}/claim`,newcomer.headers,{expected_version:broken.version,hours:1,note:"Report setup friction"});const failed=await json(newcomerPage,"post",`/repositories/${repository.id}/contribution-opportunities/${broken.id}/launch`,newcomer.headers,{expected_version:broken.version,fork_name:`broken-${suffix}`,sample_attachment_ids:[]});expect(failed.workspace.setup_evidence.some((item:any)=>item.state==="failed"&&item.command.includes("missing-guide"))).toBeTruthy();expect(failed.workspace.state).toBe("failed");
    await newcomerPage.getByPlaceholder("Go, testing, documentation").fill("documentation");await newcomerPage.getByPlaceholder("accessibility, API design").fill("onboarding");await newcomerPage.getByRole("button",{name:"Suggest work"}).click();const card=newcomerPage.getByText("Add a verified welcome example",{exact:true}).locator("xpath=ancestor::div[contains(@class,'rounded-xl')][1]");await card.getByRole("button",{name:"Reserve for 72 hours"}).click();await card.getByRole("button",{name:"Fork and launch workspace"}).click();await expect(newcomerPage).toHaveURL(/\/workspaces\/[a-f0-9]{32}$/);const workspaceID=new URL(newcomerPage.url()).pathname.split("/").pop()!;await expect(newcomerPage.getByText("passed",{exact:true}).first()).toBeVisible();
    let help=await json(newcomerPage,"get",`/workspaces/${workspaceID}/contribution-help`,newcomer.headers);await json(newcomerPage,"post",`/workspaces/${workspaceID}/contribution-help/entries`,newcomer.headers,{expected_version:help.workspace.contributor_context.help.version,kind:"question",body:"Should the example mention the exact verification command?",decision_owner:"contributor"});help=await json(ownerPage,"get",`/workspaces/${workspaceID}/contribution-help`,owner.headers);await json(ownerPage,"post",`/workspaces/${workspaceID}/contribution-help/entries`,owner.headers,{expected_version:help.workspace.contributor_context.help.version,kind:"advice",body:"Yes—keep the example bounded and name what the check proves.",decision_owner:"contributor"});
    await newcomerPage.getByRole("button",{name:"welcome.txt"}).click();await newcomerPage.getByLabel("Edit welcome.txt").fill("documented example\n");await newcomerPage.getByRole("button",{name:"Save change"}).click();await newcomerPage.getByLabel("Command").fill("grep -qx 'documented example' welcome.txt");await newcomerPage.getByRole("button",{name:"Run",exact:true}).click();await expect(newcomerPage.getByText("exit 0",{exact:true})).toBeVisible();await newcomerPage.getByPlaceholder("Checkpoint title").fill("Verified welcome example");await newcomerPage.getByRole("button",{name:"Create attributed checkpoint"}).click();const checkpoint=newcomerPage.locator("li").filter({hasText:"Verified welcome example"});await checkpoint.getByRole("button",{name:"Check contribution requirements"}).click();for(const criterion of await checkpoint.locator('input[name="criterion"]').all())await criterion.check();await checkpoint.getByPlaceholder("contribution/change-name").fill("contributors/welcome-example");await checkpoint.getByRole("button",{name:"Commit checkpoint and open upstream review"}).click();await checkpoint.getByRole("link",{name:"Open governed review"}).click();await expect(newcomerPage.getByText("Guided contribution context")).toBeVisible();const pullID=new URL(newcomerPage.url()).pathname.split("/").pop()!;
    await expect(newcomerPage.locator("#checks").getByText("succeeded",{exact:true})).toBeVisible({timeout:60_000});await ownerPage.goto(newcomerPage.url());await ownerPage.getByRole("button",{name:"Approve"}).click();await ownerPage.getByRole("button",{name:"Merge into main"}).click();await expect(ownerPage.getByText("Merged",{exact:true})).toBeVisible();const merged=await json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pullID}`,owner.headers);const release=await json(ownerPage,"post",`/repositories/${repository.id}/releases`,owner.headers,{version:"v1.0.0",notes:"Release the supported first contribution.",commit_id:merged.merge_commit_id});const opportunities=await json(ownerPage,"get",`/repositories/${repository.id}/contribution-opportunities`,owner.headers);ready=opportunities.opportunities.find((item:any)=>item.id===ready.id);
    await json(ownerPage,"post",`/repositories/${repository.id}/contribution-opportunities/${ready.id}/completion`,owner.headers,{expected_version:ready.version,pull_request_id:pullID,release_id:release.id,feedback:"The contributor kept scope small, used guidance well, and responded with exact verification.",credit:["documentation","verification","review follow-up"],ready_for_next:true,skills_recognized:["documentation","bounded verification"],next_opportunity_id:next.id,readiness_note:"Ready for the next low-risk example with lighter mentor support."});await newcomerPage.goto(`/repositories/${repository.id}/contribute`);await expect(newcomerPage.getByText("Trusted contributor outcomes")).toBeVisible();await expect(newcomerPage.getByText("ready for next contribution")).toBeVisible();await expect(newcomerPage.getByText(/lighter mentor support/)).toBeVisible();
  }finally{await Promise.all(copies.map(path=>rm(path,{recursive:true,force:true})))}
});
