import { expect, test, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

const run = promisify(execFile), digest = "a".repeat(64);
async function git(token: string, cwd: string, ...args: string[]) {
  return (await run("git", ["-c", "credential.helper=", ...args], { cwd, env: { ...process.env, GIT_ASKPASS: join(__dirname, "git-askpass.sh"), GIT_TERMINAL_PROMPT: "0", VIVARIUM_GIT_TOKEN: token } })).stdout.trim();
}
async function account(page: Page, suffix: string, role: string) {
  await page.goto("/"); await page.getByLabel("Display name").fill(`${role} maintainer`); await page.getByLabel("Handle").fill(`history-${role}-${suffix}`); await page.getByRole("button", { name: "Create account and continue" }).click();
  await expect(page.getByRole("heading", { name: "Create a repository" })).toBeVisible();
  const token = await page.evaluate(() => localStorage.getItem("vivarium.access-token")); expect(token).toBeTruthy(); const headers = { Authorization: `Bearer ${token}` };
  return { headers, user: await (await page.request.get("/api/user", { headers })).json() };
}
async function json(page: Page, method: "get" | "post", path: string, headers: Record<string, string>, data?: unknown) {
  const response = await page.request[method](`/api${path}`, { headers, data }), body = await response.text();
  expect(response.status(), `${method.toUpperCase()} ${path}: ${body}`).toBeGreaterThanOrEqual(200); expect(response.status(), body).toBeLessThan(300); return body ? JSON.parse(body) : undefined;
}

test("a distributed project recovers from committed sensitive history without claiming erasure", async ({ browser }) => {
  test.setTimeout(300_000); test.skip(!(await run("docker", ["info"]).then(() => true, () => false)), "bounded rehearsals require Docker");
  await run("docker", ["image", "inspect", "alpine:3.22"]).catch(() => run("docker", ["pull", "alpine:3.22"]));
  const copies: string[] = [], credentials: { page: Page; headers: Record<string, string>; id: string }[] = [];
  try {
    const suffix = Date.now().toString(36), ownerPage = await (await browser.newContext()).newPage(), forkPage = await (await browser.newContext()).newPage();
    const owner = await account(ownerPage, suffix, "owner"), forkOwner = await account(forkPage, suffix, "fork");
    const repository = await json(ownerPage, "post", "/repositories", owner.headers, { name: `history-recovery-${suffix}` }), fork = await json(forkPage, "post", "/repositories", forkOwner.headers, { name: `independent-fork-${suffix}` });
    const credential = async (page: Page, headers: Record<string, string>, name: string) => { const x = await json(page, "post", "/auth/credentials", headers, { kind: "git", name, scopes: ["git:read", "git:write"], expires_in: 3600 }); credentials.push({ page, headers, id: x.id }); return x; };
    const ownerGit = await credential(ownerPage, owner.headers, "history owner"), forkGit = await credential(forkPage, forkOwner.headers, "fork owner");
    const source = await mkdtemp(join(tmpdir(), "vivarium-history-source-")), stale = await mkdtemp(join(tmpdir(), "vivarium-history-stale-")), forkCopy = await mkdtemp(join(tmpdir(), "vivarium-history-fork-")); copies.push(source, stale, forkCopy);
    await git(ownerGit.token, tmpdir(), "clone", `http://localhost:3000/git/${repository.id}.git`, source); await git("", source, "config", "user.name", "History Owner"); await git("", source, "config", "user.email", "owner@example.test");
    await writeFile(join(source, "credential.txt"), "synthetic exposed category\n"); await writeFile(join(source, "README.md"), "safe project content\n"); await git("", source, "add", "."); await git("", source, "commit", "-m", "Add deployment configuration");
    const oldTip = await git("", source, "rev-parse", "HEAD"), affected = await git("", source, "rev-parse", "HEAD:credential.txt"); await git("", source, "branch", "release"); await git(ownerGit.token, source, "push", "origin", "main", "release");
    await git(ownerGit.token, tmpdir(), "clone", `http://localhost:3000/git/${repository.id}.git`, stale);
    await git(forkGit.token, tmpdir(), "clone", `http://localhost:3000/git/${fork.id}.git`, forkCopy); await git(ownerGit.token, forkCopy, "remote", "add", "upstream", `http://localhost:3000/git/${repository.id}.git`); await git(ownerGit.token, forkCopy, "fetch", "upstream", "main"); await git("", forkCopy, "reset", "--hard", "upstream/main"); await git(forkGit.token, forkCopy, "push", "origin", "main");

    let remediation = await json(ownerPage, "post", `/repositories/${repository.id}/history-remediations`, owner.headers, { request_id: `open-${suffix}`, title: "Rotate and remove exposed deployment credential", source: { kind: "selected_object", resource_id: affected, revision: oldTip }, content_description: "A committed deployment credential identified only by object digest", reason: "Rotate access and replace every authoritative lineage", scopes: [{ repository_id: repository.id, kind: "git_object", object_id: affected, revision: oldTip }], discovery_evidence: [{ id: "match", kind: "scanner", resource_id: oldTip, sha256: digest, state: "matched", note: "Digest match in committed history", attributed_to: owner.user.id }, { id: "false", kind: "scanner", resource_id: "documentation-example", sha256: "b".repeat(64), state: "false_match", note: "Known placeholder was reviewed and excluded", attributed_to: owner.user.id }], constraints: [{ id: "peer", kind: "inaccessible_resource", resource_id: "offline-peer", state: "unreachable", reason: "Federated peer is temporarily unavailable", attributed_to: owner.user.id }, { id: "backup", kind: "legal_hold", resource_id: "protected-backup", state: "retained", reason: "Encrypted recovery copy remains under legal control", attributed_to: owner.user.id }], audience_ids: [owner.user.id], owner_ids: [owner.user.id], required_approvals: [{ role: "security", approver_ids: [owner.user.id], required: 1 }] });
    for (const [copy_kind, resource_id, state, independent = false] of [["branch", "main", "confirmed"], ["branch", "release", "confirmed"], ["fork", fork.id, "independently_controlled", true], ["pull_request", "pull-legacy", "suspected"], ["package", "sdk@1.0.0", "confirmed"], ["release_artifact", "release-1", "confirmed"], ["deployment", "production", "confirmed"]] as const) remediation = await json(ownerPage, "post", `/repositories/${repository.id}/history-remediations/${remediation.id}/exposure-findings`, owner.headers, { expected_version: remediation.version, finding: { request_id: `${copy_kind}-${resource_id}`, copy_kind, resource_id, repository_id: copy_kind === "fork" ? fork.id : repository.id, object_ids: [affected], derived_kinds: ["credential"], state, independently_controlled: independent, citation_kind: "digest_observation", citation_resource_id: resource_id, citation_sha256: digest, note: "Payload-free reachability analysis", uncertainty: state === "suspected" ? "Pull head may move" : "" } });
    remediation = await json(ownerPage, "post", `/repositories/${repository.id}/history-remediations/${remediation.id}/rewrite-candidates`, owner.headers, { expected_version: remediation.version, candidate: { request_id: `candidate-${suffix}`, rules: [{ id: "remove-credential", affected_object_id: affected, action: "remove", reason: "Remove the affected blob from selected history" }], selected_refs: [{ name: "refs/heads/main", expected_tip: oldTip }, { name: "refs/heads/release", expected_tip: oldTip }], rollback_limit: "Independent clones and protected backups retain their own authority.", collaborator_actions: ["Fetch replacement refs and rebase local work", "Fork owners rewrite under their own authority"] } });
    const candidate = remediation.rewrite_candidates[0], scenarios = (command: string) => ["repository_integrity", "build", "check", "release", "dependency", "clone", "fetch"].map((kind, i) => ({ id: `${kind}-${i}`, kind, image: ["build", "check", "release", "dependency"].includes(kind) ? "alpine:3.22" : "", command: ["build", "check", "release", "dependency"].includes(kind) ? command : "", expectation: "sanitized history remains usable", timeout_seconds: 30 }));
    remediation = await json(ownerPage, "post", `/repositories/${repository.id}/history-remediations/${remediation.id}/rewrite-candidates/${candidate.id}/rehearsals`, owner.headers, { expected_version: remediation.version, rehearsal: { request_id: `failed-${suffix}`, scenarios: scenarios("false") } }); expect(remediation.rewrite_candidates[0].rehearsals.at(-1).state).toBe("failed");
    remediation = await json(ownerPage, "post", `/repositories/${repository.id}/history-remediations/${remediation.id}/rewrite-candidates/${candidate.id}/rehearsals`, owner.headers, { expected_version: remediation.version, rehearsal: { request_id: `passed-${suffix}`, scenarios: scenarios("test ! -e credential.txt && test -f README.md") } }); expect(remediation.rewrite_candidates[0].rehearsals.at(-1).state).toBe("passed");
    remediation = await json(ownerPage, "post", `/repositories/${repository.id}/history-remediations/${remediation.id}/publication-approvals`, owner.headers, { expected_version: remediation.version, role: "security" });
    remediation = await json(ownerPage, "post", `/repositories/${repository.id}/history-remediations/${remediation.id}/rewrite-candidates/${candidate.id}/publish`, owner.headers, { expected_version: remediation.version, publication: { request_id: `publish-${suffix}`, revoked_credentials: ["rotated-deployment-credential"], paused_systems: ["pushes"], migration_targets: [{ id: "local", kind: "local_branch", resource_id: "main", owner_id: owner.user.id, replacement_ref: "refs/heads/main", instructions: "Fetch, back up local work, and reset to the replacement." }, { id: "fork", kind: "fork", resource_id: fork.id, repository_id: fork.id, owner_id: forkOwner.user.id, independently_controlled: true, replacement_ref: "refs/heads/main", instructions: "Rewrite and force-update the fork under its owner's authority." }, { id: "pull", kind: "pull_request", resource_id: "pull-legacy", owner_id: owner.user.id, replacement_ref: "refs/heads/main", instructions: "Rebase the pull and preserve discussion against the replacement revision." }] } });
    await expect(git(ownerGit.token, stale, "push", "origin", "main")).rejects.toThrow(/push rejected: authoritative history was rewritten/);
    await git("", forkCopy, "filter-branch", "-f", "--index-filter", "git rm --cached --ignore-unmatch credential.txt", "--", "main"); await git(forkGit.token, forkCopy, "push", "--force", "origin", "main");
    const evidenceKinds = ["fork_acknowledgement", "federation_acknowledgement", "package_replacement", "artifact_replacement", "credential_rotation", "deployment", "cache", "recovery_copy"];
    const observations = (state = "passed") => evidenceKinds.map((kind) => ({ kind, resource_id: kind, state, evidence_sha256: digest, summary: `${kind.replaceAll("_", " ")} rechecked without retaining payloads` }));
    remediation = await json(ownerPage, "post", `/repositories/${repository.id}/history-remediations/${remediation.id}/containment-passes`, owner.headers, { expected_version: remediation.version, pass: { request_id: `blocked-${suffix}`, observations: observations().map((x) => x.kind === "recovery_copy" ? { ...x, state: "retained_legal" } : x) } }); expect(remediation.containment_passes.at(-1).state).toBe("blocked");
    remediation = await json(ownerPage, "post", `/repositories/${repository.id}/history-remediations/${remediation.id}/containment-passes`, owner.headers, { expected_version: remediation.version, pass: { request_id: `contained-${suffix}`, observations: observations() } }); const contained = remediation.containment_passes.at(-1); expect(contained).toMatchObject({ state: "passing", erasure_claim: false });
    remediation = await json(ownerPage, "post", `/repositories/${repository.id}/history-remediations/${remediation.id}/restorations`, owner.headers, { expected_version: remediation.version, restoration: { request_id: `restore-${suffix}`, containment_pass_id: contained.id, systems: ["pushes", "automation", "releases", "contributions"] } }); expect(remediation.publication).toMatchObject({ state: "contained_with_residuals", paused_systems: [] });
    await ownerPage.goto(`/repositories/${repository.id}/history-remediation`); await expect(ownerPage.getByRole("heading", { name: "Sensitive history remediation" })).toBeVisible(); await expect(ownerPage.getByText("Rotate and remove exposed deployment credential", { exact: true })).toBeVisible(); await expect(ownerPage.getByText("contained with residuals", { exact: true })).toBeVisible(); await expect(ownerPage.getByText(/owner must perform this rewrite under their own authority/)).toBeVisible();
  } finally { for (const x of credentials) await x.page.request.delete(`/api/auth/credentials/${x.id}`, { headers: x.headers }).catch(() => undefined); for (const copy of copies) await rm(copy, { recursive: true, force: true }); }
});
