import { expect, test, type APIResponse, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

/* eslint-disable @typescript-eslint/no-explicit-any -- this is one connected cross-product trail */
const run = promisify(execFile);
async function git(cwd: string, ...args: string[]) { return (await run("git", args, { cwd, env: { ...process.env, GIT_TERMINAL_PROMPT: "0" } })).stdout.trim(); }
async function authenticatedGit(token: string, cwd: string, ...args: string[]) { return (await run("git", ["-c", "credential.helper=", ...args], { cwd, env: { ...process.env, GIT_ASKPASS: join(__dirname, "git-askpass.sh"), GIT_TERMINAL_PROMPT: "0", VIVARIUM_GIT_TOKEN: token } })).stdout.trim(); }
async function account(page: Page, suffix: string, name: string) {
  await page.goto("/"); await page.getByLabel("Display name").fill(name); await page.getByLabel("Handle").fill(`${name.toLowerCase().replaceAll(" ", "-")}-${suffix}`); await page.getByRole("button", { name: "Create account and continue" }).click(); await expect(page.getByRole("heading", { name: "Create a repository" })).toBeVisible();
  const token = await page.evaluate(() => localStorage.getItem("vivarium.access-token")); expect(token).toBeTruthy();
  const headers = { Authorization: `Bearer ${token}` }; return { headers, user: await (await page.request.get("/api/user", { headers })).json() as any };
}
async function json(page: Page, method: "get" | "post" | "put", path: string, headers: Record<string, string>, data?: unknown) {
  const response = await page.request[method](`/api${path}`, { headers, data }); const body = await response.text();
  expect(response.status(), `${method.toUpperCase()} ${path}: ${body}`).toBeGreaterThanOrEqual(200); expect(response.status(), `${method.toUpperCase()} ${path}: ${body}`).toBeLessThan(300); return body ? JSON.parse(body) : undefined;
}
async function rejected(response: APIResponse, status: number) { expect(response.status(), await response.text()).toBe(status); return response.json(); }

test("people and agents carry a shared need into an operating project", async ({ browser }) => {
  test.setTimeout(300_000);
  const pages = await Promise.all(Array.from({ length: 3 }, async () => (await browser.newContext()).newPage()));
  const copy = await mkdtemp(join(tmpdir(), "vivarium-incubator-"));
  try {
    const suffix = Date.now().toString(36), [ownerPage, expertPage, userPage] = pages;
    const owner = await account(ownerPage, suffix, "Incubator Owner"), expert = await account(expertPage, suffix, "Domain Expert"), targetUser = await account(userPage, suffix, "Invited User");
    const organization = await json(ownerPage, "post", "/organizations", owner.headers, { name: `Needs Lab ${suffix}`, slug: `needs-lab-${suffix}`, description: "Incubate a useful project before choosing its repository." });
    const orgInvite = await json(ownerPage, "post", `/organizations/${organization.id}/invitations`, owner.headers, { user_id: expert.user.id });
    await json(expertPage, "post", `/organizations/${organization.id}/invitations/${orgInvite.invitations.at(-1).id}/accept`, expert.headers);
    let org = await json(ownerPage, "post", `/organizations/${organization.id}/agents`, owner.headers, { name: "Incubation Researcher", slug: `incubation-researcher-${suffix}`, capabilities: ["compare bounded project alternatives"], operator_ids: [expert.user.id], team_ids: [] });
    const agent = org.agents.at(-1);

    const intent = (title: string) => ({ title, audience: "Small maintainer teams", problem: "Release coordinators cannot see whether a change is safe to announce.", desired_outcome: "A revision-exact launch brief shared with invited users.", constraints: ["No repository before direction", "Bounded monthly cost"], success_measures: ["Invited user validates the slice", "A contributor can find a first task"], sponsor_ids: [owner.user.id], decision_rights: [{ kind: "scope_change", decision: "Change product scope", principal_ids: [owner.user.id, expert.user.id], rule: "consensus" }, { kind: "visibility_change", decision: "Publish incubator", principal_ids: [owner.user.id], rule: "owner" }], visibility: "participants", source: { kind: "new_idea", label: "Release coordinator interview" }, invitations: [{ principal_type: "human", principal_id: expert.user.id, role: "release domain expert" }, { principal_type: "agent", principal_id: agent.id, organization_id: organization.id, role: "bounded architecture researcher" }] });
    let incubator = await json(ownerPage, "post", "/incubators", owner.headers, intent("Revision Brief"));
    const duplicate = await json(ownerPage, "post", "/incubators", owner.headers, intent("Revision Brief follow-up"));
    expect(duplicate.potential_duplicates).toEqual([expect.objectContaining({ incubator_id: incubator.id })]);
    await rejected(await expertPage.request.get(`/api/incubators/${incubator.id}`, { headers: expert.headers }), 404);
    incubator = await json(expertPage, "post", `/incubators/${incubator.id}/invitations/${incubator.invitations.find((x: any) => x.principal_id === expert.user.id).id}/consent`, expert.headers, { expected_version: incubator.version, decision: "accepted" });
    incubator = await json(expertPage, "post", `/incubators/${incubator.id}/events`, expert.headers, { expected_version: incubator.version, kind: "evidence", body: "Three release coordinators asked for a single revision-exact brief.", visibility: "participants" });

    const researchContext = await json(ownerPage, "post", `/organizations/${organization.id}/repositories`, owner.headers, { name: `existing-research-context-${suffix}` });
    const access = await json(expertPage, "post", `/organizations/${organization.id}/access-requests`, expert.headers, { principal_type: "agent", principal_id: agent.id, role: "viewer", resources: [{ kind: "repository", id: researchContext.id }], exceptions: [], reason: "Compare only public evidence inside the research-only incubator boundary.", expires_at: new Date(Date.now() + 3_600_000).toISOString() });
    org = await json(ownerPage, "post", `/organizations/${organization.id}/access-requests/${access.access_requests.at(-1).id}/decision`, owner.headers, { decision: "approve" });
    const grant = org.access_grants.find((x: any) => x.principal_id === agent.id);
    const agentCredential = await json(expertPage, "post", `/organizations/${organization.id}/access-grants/${grant.id}/credentials`, expert.headers, { agent_id: agent.id, repository_id: researchContext.id, expires_in: 3600, purpose: "api_read" });
    const agentHeaders = { Authorization: `Bearer ${agentCredential.token}` };
    const alternative = (name: string, architecture: string, cost: string) => ({ name, product_boundary: "Revision brief creation and invited-user reading", architecture, interfaces: ["HTTP API", "responsive web workspace"], dependencies: ["platform identity and release ledger"], licenses: ["MIT"], operating_costs: [cost], security_risks: ["overbroad release visibility"], data_risks: ["feedback identity disclosure"], build_or_adopt: "build", unknowns: ["first-month adoption"] });
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/alternatives`, owner.headers, { expected_version: incubator.version, sources: [{ kind: "public", label: "Release usability study", url: "https://example.test/release-study" }], alternative: alternative("Static prototype", "Generated static site", "$800/month hosting and manual upkeep") });
    const rejectedAlternative = incubator.alternatives.at(-1);
    incubator = await json(expertPage, "post", `/incubators/${incubator.id}/research-notes`, expert.headers, { expected_version: incubator.version, note: { kind: "dissent", alternative_id: rejectedAlternative.id, source_ids: incubator.research_sources.map((x: any) => x.id), body: "Reject: manual regeneration hides revision drift and breaches the operating budget." } });
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/alternatives`, owner.headers, { expected_version: incubator.version, sources: [], alternative: { ...alternative("Ledger-backed brief", "Small API resource rendered by the web application", "$25/month bounded estimate"), supersedes_id: rejectedAlternative.id } });
    const acceptedAlternative = incubator.alternatives.at(-1);
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/experiments`, owner.headers, { expected_version: incubator.version, experiment: { alternative_id: acceptedAlternative.id, question: "Can an invited user identify the exact released revision in under one minute?", environment: "ephemeral synthetic browser fixture", commands: ["render synthetic release brief", "measure invited-user lookup"], inputs: ["synthetic release metadata"], expected_measures: ["lookup_seconds", "monthly_cost_usd"], safety_limits: ["no repository creation", "no production access", "cost below 50 USD"], source_ids: [] } });
    const experiment = incubator.experiments.at(-1); expect(experiment.authority).toBe("research_only_no_code_or_infrastructure_authority");
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/experiments/${experiment.id}/results`, agentHeaders, { expected_version: incubator.version, result: { outcome: "passed", measurements: [{ name: "lookup_seconds", value: 34, unit: "seconds" }, { name: "monthly_cost_usd", value: 25, unit: "USD" }], artifact_sha256: ["a".repeat(64)], notes: "Bounded synthetic run; no authoritative project resources created.", unknowns: ["production adoption remains unmeasured"] } });

    const repository = await json(ownerPage, "post", `/organizations/${organization.id}/repositories`, owner.headers, { name: `revision-brief-${suffix}` });
    const credential = await json(ownerPage, "post", "/auth/credentials", owner.headers, { kind: "git", name: "incubator delivery", scopes: ["git:read", "git:write"], expires_in: 3600 });
    const gitURL = `http://localhost:3000/git/${repository.id}.git`; await authenticatedGit(credential.token, tmpdir(), "clone", gitURL, copy); expect(await git(copy, "remote", "get-url", "origin")).toBe(gitURL);
    await git(copy, "config", "user.name", "Incubator Owner"); await git(copy, "config", "user.email", "owner@example.test"); await mkdir(join(copy, "docs"));
    await writeFile(join(copy, "brief.txt"), "revision brief baseline\n"); await writeFile(join(copy, "openapi.json"), JSON.stringify({ openapi: "3.1.0", info: { title: "Revision Brief", version: "1.0.0" }, paths: { "/brief": { get: { responses: { "200": { description: "brief" } } } } } })); await writeFile(join(copy, "API.md"), "# Revision Brief API\nRead-only exact-release metadata.\n"); await writeFile(join(copy, "docs", "index.md"), "# Revision Brief\nFind an exact released revision and contributor pathway.\n"); await git(copy, "add", "."); await git(copy, "commit", "-m", "Establish reviewed incubation baseline"); await authenticatedGit(credential.token, copy, "push", "origin", "main"); const base = await git(copy, "rev-parse", "HEAD");
    const kinds = ["organization", "repository", "team", "package", "agent_role", "contributor_pathway", "documentation", "environment", "review_policy", "security_policy", "privacy_policy", "quality_policy", "release_policy"];
    const resources = kinds.map(kind => ({ kind, mode: kind === "organization" || kind === "repository" ? "connect" : "create", name: `revision-brief-${kind}`, resource_id: kind === "organization" ? organization.id : kind === "repository" ? repository.id : undefined, owner_ids: [owner.user.id], monthly_cost_estimate_cents: kind === "environment" ? 2500 : 0 }));
    const unavailableOwner = await ownerPage.request.post(`/api/incubators/${incubator.id}/bootstrap-previews`, { headers: owner.headers, data: { expected_version: incubator.version, alternative_id: acceptedAlternative.id, resources: resources.map(x => x.kind === "team" ? { ...x, owner_ids: [targetUser.user.id] } : x) } }); await rejected(unavailableOwner, 422);
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/bootstrap-previews`, owner.headers, { expected_version: incubator.version, alternative_id: acceptedAlternative.id, resources: resources.map(x => ({ ...x, monthly_cost_estimate_cents: x.kind === "environment" ? 80_000 : 0 })) });
    let plan = incubator.bootstrap_plans.at(-1); incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/bootstrap-plans/${plan.id}/decisions`, owner.headers, { expected_version: incubator.version, plan_version: plan.version, decision: "rejected" }); plan = incubator.bootstrap_plans.at(-1);
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/bootstrap-plans/${plan.id}/actions`, owner.headers, { expected_version: incubator.version, plan_version: plan.version, action: "rollback" }); expect(incubator.bootstrap_plans.at(-1).status).toBe("rolled_back");
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/bootstrap-previews`, owner.headers, { expected_version: incubator.version, alternative_id: acceptedAlternative.id, resources }); plan = incubator.bootstrap_plans.at(-1);
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/bootstrap-plans/${plan.id}/decisions`, owner.headers, { expected_version: incubator.version, plan_version: plan.version, decision: "approved" }); plan = incubator.bootstrap_plans.at(-1);
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/bootstrap-plans/${plan.id}/actions`, owner.headers, { expected_version: incubator.version, plan_version: plan.version, action: "activate" }); plan = incubator.bootstrap_plans.at(-1); expect(plan.recurring_cost_estimate_cents).toBe(2500);

    await git(copy, "switch", "-c", "first-slice"); await writeFile(join(copy, "brief.txt"), "revision brief exact-release lookup and contributor entry\n"); await git(copy, "add", "."); await git(copy, "commit", "-m", "Deliver the first revision brief slice"); await authenticatedGit(credential.token, copy, "push", "origin", "first-slice"); const candidate = await git(copy, "rev-parse", "HEAD");
    const pull = await json(ownerPage, "post", `/repositories/${repository.id}/pulls`, owner.headers, { title: "Deliver the first revision brief slice", body: "Human-authored representative journey from exact release to contributor entry.", source_branch: "first-slice", target_branch: "main" });
    await json(ownerPage, "post", `/repositories/${repository.id}/collaborators`, owner.headers, { user_id: expert.user.id }); await json(expertPage, "post", `/repositories/${repository.id}/pulls/${pull.id}/reviews`, expert.headers, { decision: "approved" });
    const merged = await json(ownerPage, "post", `/repositories/${repository.id}/pulls/${pull.id}/merge`, owner.headers, {}), revision = merged.merge_commit_id;
    const workKinds = ["code", "tests", "documentation", "infrastructure", "interface"];
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/delivery-plans`, owner.headers, { expected_version: incubator.version, plan: { bootstrap_plan_id: plan.id, journey: "Invited user opens a brief and finds the exact release plus first contribution", participants: [{ principal_type: "human", principal_id: owner.user.id, role: "builder" }, { principal_type: "human", principal_id: expert.user.id, role: "reviewer" }, { principal_type: "agent", principal_id: agent.id, role: "research assistant" }], work_items: workKinds.map((kind, index) => ({ kind, title: `${kind} for revision brief`, repository_id: repository.id, base_revision: index === 0 ? base : revision, owner_type: index === 2 ? "agent" : "human", owner_id: index === 2 ? agent.id : owner.user.id, dependency_ids: index ? [`${index}`] : [], acceptance_criteria: [`${kind} supports the invited-user journey`], integration_order: index + 1 })) } });
    const delivery = incubator.delivery_plans.at(-1);
    const failedPreview = await ownerPage.request.post(`/api/incubators/${incubator.id}/delivery-plans/${delivery.id}/reports`, { headers: owner.headers, data: { expected_version: incubator.version, plan_version: delivery.version, report: { work_item_id: delivery.work_items.at(-1).id, kind: "preview", repository_id: repository.id, resource_id: `${pull.id}:missing-preview`, revision: candidate, summary: "First preview failed to resolve." } } }); await rejected(failedPreview, 422);
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/delivery-plans/${delivery.id}/reports`, owner.headers, { expected_version: incubator.version, plan_version: delivery.version, report: { work_item_id: delivery.work_items[0].id, kind: "pull_request", repository_id: repository.id, resource_id: pull.id, revision: candidate, summary: "Ordinary reviewed human implementation retained exact authorship." } });
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/delivery-plans/${delivery.id}/reports`, agentHeaders, { expected_version: incubator.version, plan_version: delivery.version + 1, report: { work_item_id: delivery.work_items[2].id, kind: "agent_action", repository_id: repository.id, resource_id: experiment.id, revision, summary: "Agent connected the bounded research result without gaining Git or launch authority.", cost_cents: 25 } });
    await json(ownerPage, "post", `/repositories/${repository.id}/collaborators`, owner.headers, { user_id: targetUser.user.id });
    const feedback = await json(userPage, "post", `/repositories/${repository.id}/feedback`, targetUser.headers, { target: { kind: "project", label: "Invited revision brief preview" }, need: "The exact revision is visible, but contributor setup should stay beside it.", desired_outcome: "Keep release and contribution context together.", frequency: "first preview", impact: "A contributor can act without asking elsewhere.", audience: "project", identity_visibility: "audience", contact_preference: "discussion", evidence: [], links: [] });
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/delivery-plans/${delivery.id}/reports`, owner.headers, { expected_version: incubator.version, plan_version: delivery.version + 2, report: { work_item_id: delivery.work_items[4].id, kind: "target_user_feedback", repository_id: repository.id, resource_id: feedback.id, revision, summary: "Invited user validated the central journey and requested adjacent contributor setup." } });

    const release = await json(ownerPage, "post", `/repositories/${repository.id}/releases`, owner.headers, { version: "v1.0.0", notes: "First incubated revision brief", commit_id: revision });
    const docs = await json(ownerPage, "put", `/repositories/${repository.id}/documentation/new`, owner.headers, { expected_version: 0, collection: { name: "Revision Brief docs", description: "Adoption and contribution guide", root_path: "docs", source_ref: "main", audience: "public", owners: [{ actor_id: owner.user.id, role: "maintainer" }], supported_versions: [{ label: "v1", release_id: release.id }], navigation: [{ label: "Start", slug: "index", position: 0 }], rendering: { format: "markdown", syntax_highlighting: true, table_of_contents: true }, publication_policy: { review_required: true, source_branch: "main", publish_on_merge: true } } });
    const opportunity = await json(ownerPage, "put", `/repositories/${repository.id}/contribution-opportunities/new`, owner.headers, { expected_version: 0, opportunity: { source: { kind: "stewardship", id: incubator.id }, title: "Improve the first-launch brief", expected_outcome: "A newcomer clarifies one revision label with a focused reviewed change.", scope: "docs/index.md only", required_skills: ["Markdown"], interests: ["developer experience"], dependency_ids: [], risk: "low", estimated_minutes: 30, agent_assistance: true, mentors: [{ user_id: expert.user.id }], revision } });
    const environment = await json(ownerPage, "post", `/repositories/${repository.id}/environments`, owner.headers, { name: "public", position: 1, image: "alpine:3.22", command: "true", timeout_seconds: 30, configuration: {}, credentials: {}, required_approvals: 0, concurrency: 1 });
    const contract = await json(ownerPage, "post", `/repositories/${repository.id}/api-contracts`, owner.headers, { expected_version: 0, revision: { version_label: "v1.0.0", title: "Revision Brief API", summary: "Read-only exact release briefs", source: { commit_id: revision, pull_request_id: pull.id, release_id: release.id, definition_path: "openapi.json", documentation_path: "API.md" }, operations: [{ id: "brief", method: "GET", path: "/brief", summary: "Read brief", authentication: ["app"], parameters: [], response_schema_ids: ["brief"], error_ids: ["failed"], stability: "stable", owner_ids: [owner.user.id] }], schemas: [{ id: "brief", name: "Brief", kind: "object", definition: '{"type":"object"}', required_fields: [], description: "Exact release brief" }], errors: [{ id: "failed", code: "failed", http_status: 503, meaning: "Unavailable", recovery: "Retry" }], authentication: [{ id: "app", mode: "application", description: "Read only", scopes: ["brief.read"] }], environments: [{ id: "public", name: "Public", base_url: "https://example.test", availability: "available", regions: ["test"] }], limits: { requests: 20, window_seconds: 3600, burst: 2, payload_bytes: 4096, concurrency: 1 }, owner_ids: [owner.user.id], stability: "stable", support_policy: { channels: ["repository"], response_target: "two days", deprecation_notice_days: 30, sunset_notice_days: 30 }, links: [{ kind: "documentation", url: "https://example.test/docs", label: "Guide" }], compatibility: { from_version: "none", level: "initial", promise: "Exact versions remain inspectable", breaking_changes: [] }, known_gaps: [], rationale: "Support invited users and adopters" } });

    const dimensions = ["ownership", "support_governance", "licensing_provenance", "security_privacy", "accessibility", "documentation", "package_api_adoption", "service_objectives", "continuity", "contributor_setup", "operating_budget", "prototype_debt", "user_validation"];
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/launch-readiness`, owner.headers, { expected_version: incubator.version, readiness: { bootstrap_plan_id: plan.id, delivery_plan_id: delivery.id, declared_audience: "public", evidence: dimensions.map(dimension => ({ dimension, owner_id: owner.user.id, summary: dimension === "user_validation" ? "Invited user validated the exact-release journey." : `${dimension} is current for the bounded first launch.`, reference: dimension === "user_validation" ? feedback.id : `${dimension}:${revision}`, status: "current" })) } });
    let readiness = incubator.launch_readiness.at(-1);
    for (const dimension of dimensions) { incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/launch-readiness/${readiness.id}/decisions`, owner.headers, { expected_version: incubator.version, readiness_version: readiness.version, decision: { dimension, kind: "accepted", rationale: `Current ${dimension} evidence reviewed for v1.` } }); readiness = incubator.launch_readiness.at(-1); }
    expect(readiness).toMatchObject({ ready: true, effective_audience: "public" });
    const artifacts = [{ kind: "release", resource_id: release.id, revision }, { kind: "documentation", resource_id: docs.collection_id, revision }, { kind: "contributor_opportunity", resource_id: opportunity.id, revision }, { kind: "environment", resource_id: environment.id }, { kind: "api_contract", resource_id: contract.id, revision }].map(x => ({ ...x, repository_id: repository.id, audience: "public" }));
    await rejected(await ownerPage.request.post(`/api/incubators/${incubator.id}/launches`, { headers: owner.headers, data: { expected_version: incubator.version, launch: { readiness_id: readiness.id, audience: "public", artifacts: artifacts.filter(x => x.kind !== "contributor_opportunity") } } }), 422);
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/launches`, owner.headers, { expected_version: incubator.version, launch: { readiness_id: readiness.id, audience: "public", artifacts } }); let launch = incubator.project_launches[0];
    incubator = await json(expertPage, "post", `/incubators/${incubator.id}/launches/${launch.id}/observations`, expert.headers, { expected_version: incubator.version, launch_version: launch.version, observation: { kind: "adoption", repository_id: repository.id, resource_id: feedback.id, summary: "First invited user found the release and asked to keep the contributor pathway adjacent." } }); launch = incubator.project_launches[0];
    const charter = { title: "Operating project stewardship", summary: "Maintainers govern roadmap work while repository controls remain independent.", roles: [{ name: "maintainer", description: "Own the continuing project", eligibility: ["repository_owner"] }], decision_classes: [{ name: "stewardship", description: "Decide continuing roadmap work", eligible_roles: ["maintainer"], participation: 1, quorum: 1, approval: "majority", protected_resources: ["branch:main"] }], procedures: { terms: "Annual review", removal: "Attributable removal", succession: "Explicit handoff", amendments: "Reviewed successor revision" } };
    await json(ownerPage, "post", `/repositories/${repository.id}/charter/revisions`, owner.headers, { expected_version: 0, charter }); await json(ownerPage, "post", `/repositories/${repository.id}/charter/revisions/1/approvals`, owner.headers, { version: 1, decision: "approved", reason: "Accept continuing ownership." }); await json(ownerPage, "post", `/repositories/${repository.id}/charter/revisions/1/activate`, owner.headers, { version: 1 });
    const standingView = await json(ownerPage, "get", `/repositories/${repository.id}/charter`, owner.headers); const standingState = await json(ownerPage, "post", `/repositories/${repository.id}/charter/standing`, owner.headers, { expected_version: standingView.charter.standings.length, charter_version: 1, principal_type: "human", principal_id: owner.user.id, role: "maintainer", responsibilities: "Own evidence-backed continuing work.", evidence: [{ kind: "ownership", resource_id: repository.id, summary: "Founding maintainer" }], expires_at: new Date(Date.now() + 86_400_000).toISOString() }); await json(ownerPage, "post", `/repositories/${repository.id}/charter/standing/${standingState.charter.standings.at(-1).id}/actions`, owner.headers, { action: "accept", reason: "Accept continuing stewardship." });
    const proposal = await json(ownerPage, "post", "/governance/proposals", owner.headers, { scope_type: "repository", scope_id: repository.id, source: { kind: "initiative", resource_id: feedback.id, label: "First-launch adoption" }, title: "Keep contribution context beside each brief", summary: "Adoption feedback becomes governed roadmap work after launch.", scope: "The contributor entry beside each revision brief.", alternatives: [{ id: "adopt", title: "Adopt", summary: "Keep the contexts adjacent.", effects: ["Open reviewed follow-up work"] }, { id: "defer", title: "Defer", summary: "Retain v1.", effects: ["No change"] }], evidence: [{ kind: "feedback", resource_id: feedback.id, label: "Invited-user feedback" }], affected_resources: [{ kind: "documentation", resource_id: docs.collection_id, revision, label: "Launch guide" }], disclosure_requirements: ["Retain invited-user attribution"], implementation_effects: ["Ordinary review remains required"], rule: { decision_class: "stewardship", opens_at: new Date(Date.now() - 1000).toISOString(), closes_at: new Date(Date.now() + 60_000).toISOString() } });
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/launches/${launch.id}/work`, owner.headers, { expected_version: incubator.version, launch_version: launch.version, work: { kind: "proposal_task", repository_id: repository.id, resource_id: proposal.id, owner_type: "human", owner_id: expert.user.id, rationale: "Invited-user adoption feedback shapes the next maintained revision." } }); launch = incubator.project_launches[0];
    incubator = await json(ownerPage, "post", `/incubators/${incubator.id}/launches/${launch.id}/transition`, owner.headers, { expected_version: incubator.version, launch_version: launch.version, transition: { disposition: "experimental", rationale: "The useful v1 is operating with accountable owners and connected next work.", resolved_resources: [], resolved_obligations: [] } });
    await ownerPage.goto("/incubators"); const incubatorHeading = ownerPage.getByRole("heading", { name: "Revision Brief", exact: true }); await expect(incubatorHeading).toBeVisible(); await incubatorHeading.click(); await expect(ownerPage.getByText("launch and continuing stewardship", { exact: false })).toBeVisible(); await expect(ownerPage.getByText("First invited user found the release", { exact: false })).toBeVisible(); await expect(ownerPage.getByText("experimental", { exact: true }).last()).toBeVisible();
  } finally { await rm(copy, { recursive: true, force: true }); }
});
