import { expect, test, type APIResponse, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

/* eslint-disable @typescript-eslint/no-explicit-any -- this journey intentionally joins the complete public runbook trail */
const run = promisify(execFile);
async function git(token:string,cwd:string,...args:string[]){return(await run("git",["-c","credential.helper=",...args],{cwd,env:{...process.env,GIT_ASKPASS:join(__dirname,"git-askpass.sh"),GIT_TERMINAL_PROMPT:"0",VIVARIUM_GIT_TOKEN:token}})).stdout.trim()}
async function account(page:Page,suffix:string,role:string){await page.goto("/");await page.getByLabel("Display name").fill(`${role} operator`);await page.getByLabel("Handle").fill(`runbook-${role.toLowerCase()}-${suffix}`);await page.getByRole("button",{name:"Create account and continue"}).click();await expect(page.getByRole("heading",{name:"Create a repository"})).toBeVisible();const token=await page.evaluate(()=>localStorage.getItem("vivarium.access-token"));expect(token).toBeTruthy();const headers={Authorization:`Bearer ${token}`};return{headers,user:await(await page.request.get("/api/user",{headers})).json()}}
async function json(page:Page,method:"get"|"post"|"put"|"delete",path:string,headers:Record<string,string>,data?:unknown){const response=await page.request[method](`/api${path}`,{headers,data});const body=await response.text();expect(response.status(),`${method.toUpperCase()} ${path}: ${body}`).toBeGreaterThanOrEqual(200);expect(response.status(),`${method.toUpperCase()} ${path}: ${body}`).toBeLessThan(300);return body?JSON.parse(body):undefined}
async function rejected(response:APIResponse,status:number,code:string){const body=await response.text();expect(response.status(),body).toBe(status);expect(JSON.parse(body)).toMatchObject({error:{code}})}

test("a rehearsed runbook carries an exact alert through recovery and reviewed improvement",async({browser})=>{
  test.setTimeout(180_000);const copy=await mkdtemp(join(tmpdir(),"vivarium-runbook-"));
  try{
    const suffix=Date.now().toString(36),ownerPage=await(await browser.newContext()).newPage(),operatorPage=await(await browser.newContext()).newPage(),nextPage=await(await browser.newContext()).newPage();
    const owner=await account(ownerPage,suffix,"Owner"),operator=await account(operatorPage,suffix,"Primary"),next=await account(nextPage,suffix,"Next");
    const organization=await json(ownerPage,"post","/organizations",owner.headers,{name:`Runbook team ${suffix}`,slug:`runbook-team-${suffix}`,description:"Own proven checkout recovery."});
    for(const member of [operator,next]){const state=await json(ownerPage,"post",`/organizations/${organization.id}/invitations`,owner.headers,{user_id:member.user.id});await json(member===operator?operatorPage:nextPage,"post",`/organizations/${organization.id}/invitations/${state.invitations.at(-1).id}/accept`,member.headers)}
    const repository=await json(ownerPage,"post",`/organizations/${organization.id}/repositories`,owner.headers,{name:`degraded-checkout-${suffix}`});
    const orgWithAgent=await json(ownerPage,"post",`/organizations/${organization.id}/agents`,owner.headers,{name:"Runbook Analyst",slug:`runbook-analyst-${suffix}`,capabilities:["analyze bounded runbook evidence"],operator_ids:[owner.user.id],team_ids:[]});const agent=orgWithAgent.agents.find((x:any)=>x.slug===`runbook-analyst-${suffix}`);
    const access=await json(ownerPage,"post",`/organizations/${organization.id}/access-requests`,owner.headers,{principal_type:"agent",principal_id:agent.id,role:"viewer",resources:[{kind:"repository",id:repository.id}],exceptions:[],reason:"Rehearse and analyze exact bounded runbook steps.",expires_at:new Date(Date.now()+3600_000).toISOString()});const decided=await json(ownerPage,"post",`/organizations/${organization.id}/access-requests/${access.access_requests.at(-1).id}/decision`,owner.headers,{decision:"approve"});const grant=decided.access_grants.find((x:any)=>x.principal_id===agent.id);const issued=await json(ownerPage,"post",`/organizations/${organization.id}/access-grants/${grant.id}/credentials`,owner.headers,{agent_id:agent.id,repository_id:repository.id,expires_in:3600,purpose:"api_read"});const agentHeaders={Authorization:`Bearer ${issued.token}`};
    const credential=await json(ownerPage,"post","/auth/credentials",owner.headers,{kind:"git",name:"runbook journey",scopes:["git:read","git:write"],expires_in:3600});await git(credential.token,tmpdir(),"clone",`http://localhost:3000/git/${repository.id}.git`,copy);await git("",copy,"config","user.name","Runbook Owner");await git("",copy,"config","user.email","owner@example.test");await writeFile(join(copy,"service.txt"),"checkout retries=8\n");await writeFile(join(copy,"health-check.sh"),"#!/bin/sh\ngrep retries service.txt\n");await writeFile(join(copy,"RUNBOOK.md"),"# Checkout recovery\n\nInspect, reduce retries with approval, verify, communicate.\n");await git("",copy,"add",".");await git("",copy,"commit","-m","Publish degraded checkout and reviewed recovery material");await git(credential.token,copy,"push","origin","main");const base=await git("",copy,"rev-parse","HEAD");
    const criteria=["health","containment","recovery","communication","rollback"].map(kind=>({kind,criterion:`${kind} criterion is satisfied`}));
    const step=(id:string,position:number,kind:string,title:string,changes:string[]=[],approval=false)=>({id,position,kind,title,purpose:`Retain ${title.toLowerCase()} evidence`,instructions:`Perform ${title.toLowerCase()} against the exact alert context.`,preconditions:["Exact alert remains active"],expected_evidence:[`${id} digest`],rollback_criteria:changes.length?["Restore the prior retry limit"]:[],owner_ids:[owner.user.id,operator.user.id,next.user.id],required_skills:["checkout operations"],references:[{kind:"command",resource_id:"health-check.sh",revision:base}],authority:{required_access:["repository:read"],inspects:["checkout health"],changes,prohibited_actions:["read secrets","expand authority"],human_approval_required:approval},assumptions:[],policy_rule_ids:[]});
    const revision={title:"Checkout degraded-service recovery",purpose:"Diagnose revision-exact checkout degradation and bound mitigation",scope:{kind:"service",resource_id:"checkout",name:"Checkout",revision:base},preconditions:["Exact alert remains active"],steps:[step("diagnose",1,"diagnostic","Diagnose"),step("mitigate",2,"action","Reduce retries",["checkout retry limit"],true),step("verify",3,"diagnostic","Verify recovery"),step("communicate",4,"communication","Communicate recovery")],rollback_criteria:["Rollback when errors or user impact rise"],outcome_criteria:criteria,owner_ids:[owner.user.id],required_skills:["checkout operations"],escalations:[{condition:"Evidence or authority is missing",owner_id:owner.user.id,path:"Repository owner",expected_action:"Contain the response"}],policy_revision_ids:[],change_reason:"Initial reviewed degraded-service procedure"};
    let book=await json(ownerPage,"post",`/repositories/${repository.id}/runbooks`,owner.headers,{request_id:`book-${suffix}`,revision});expect(book.diagnostics).toEqual([]);
    const now=()=>new Date().toISOString(),scenario=(name:string)=>({id:name,name,failure:"Synthetic retry saturation",inputs:[{kind:"service",resource_id:"checkout",revision:base,evidence_kind:"synthetic",digest:`sha256:${name}-input`}],decisions:[],steps:revision.steps.map((s:any)=>({step_id:s.id,output:`bounded ${s.id} output`,started_at:now(),finished_at:now(),artifacts:[],cost_cents:s.id==="diagnose"?3:0,permissions:["repository:read"],outcome:"passed",manual_gaps:[],destructive_handling:s.authority.changes.length?"simulated":"not_applicable",assertions:[]})),achieved_outcome:"achieved"});
    book=await json(operatorPage,"post",`/repositories/${repository.id}/runbooks/${book.id}/rehearsals`,operator.headers,{request_id:`human-rehearsal-${suffix}`,runbook_version:1,environment_kind:"isolated",environment_id:"operator-sandbox",scenarios:[scenario("operator-case")]});book=await json(ownerPage,"post",`/repositories/${repository.id}/runbooks/${book.id}/rehearsals`,agentHeaders,{request_id:`agent-rehearsal-${suffix}`,runbook_version:1,environment_kind:"isolated",environment_id:"agent-sandbox",scenarios:[scenario("agent-case")]});expect(book.rehearsals.map((x:any)=>x.actor_type)).toEqual(expect.arrayContaining(["human","agent"]));
    const policyRevision={title:"Checkout response",summary:"Route checkout degradation",resources:[{id:"checkout",kind:"service",name:"Checkout",owner_team_ids:["service"]}],teams:[{id:"service",name:"Checkout operators",member_ids:[operator.user.id,next.user.id,owner.user.id],skills:["checkout operations"],contact:"runbook workspace"}],rules:[{id:"degraded",resource_ids:["checkout"],signal_class:"reliability",severity:"high",accountable_team_id:"service",required_skills:["checkout operations"],acknowledge_seconds:60,resolve_seconds:3600,expected_actions:["launch exact runbook"],escalations:[{after_seconds:60,team_id:"service",audience_ids:[owner.user.id],expected_action:"contain"}],communication_audience_ids:[owner.user.id,next.user.id],incident_criteria:["recovery fails"],authority:{required_access:["repository:read"],permitted_actions:["launch runbook"],prohibited_actions:["infer production authority"]}}],exceptions:[],change_reason:"Cover the released checkout service"};await json(ownerPage,"post",`/repositories/${repository.id}/response-policies`,owner.headers,{request_id:`policy-${suffix}`,revision:policyRevision});
    const alert=await json(ownerPage,"post",`/repositories/${repository.id}/response-alerts`,owner.headers,{request_id:`alert-${suffix}`,signal:{signal_class:"reliability",severity:"high",resource_ids:["checkout"],affected_user_count:27,affected_user_groups:["buyers"],summary:"Checkout retries degraded",uncertainty:"Exact release metric",occurred_at:now(),source_revision:base,correlation_key:`checkout-${suffix}`,evidence:[{kind:"release_health",resource_id:"checkout",revision:base,digest:"a".repeat(64),summary:"Retry saturation",accessible_to:[owner.user.id,operator.user.id,next.user.id],available:true}]}});
    const context={origin_kind:"alert",origin_id:alert.id,origin_revision:base,summary:"Exact checkout alert",affected_resources:["checkout"],signal_class:"reliability",window_from:new Date(Date.now()-60_000).toISOString(),window_to:new Date(Date.now()+60_000).toISOString(),release_ids:[],environment_id:"",environment_revision:"",evidence:[{kind:"metric",resource_id:"checkout",revision:base,digest:"sha256:live",summary:"Bounded retry metric"}],timeline_refs:[`${alert.id}:created`],audience_ids:[owner.user.id,next.user.id]};await json(ownerPage,"post",`/repositories/${repository.id}/response-alerts/${alert.id}/outcomes`,owner.headers,{request_id:`pause-${suffix}`,classification:"actionable",routing_action:"pause",rationale:"Pause routing while the alert binding is checked"});const outcomePaused=await json(operatorPage,"post",`/repositories/${repository.id}/runbooks/${book.id}/executions`,operator.headers,{request_id:`paused-${suffix}`,runbook_version:1,context});expect(outcomePaused).toMatchObject({status:"blocked",current_access:[]});expect(outcomePaused.preconditions??[]).toEqual([]);await json(ownerPage,"post",`/repositories/${repository.id}/response-alerts/${alert.id}/outcomes`,owner.headers,{request_id:`resume-${suffix}`,classification:"actionable",routing_action:"resume",rationale:"Resume after correcting the routing boundary"});
    const stale={...context,origin_revision:"stale-revision"};const blocked=await json(operatorPage,"post",`/repositories/${repository.id}/runbooks/${book.id}/executions`,operator.headers,{request_id:`stale-${suffix}`,runbook_version:1,context:stale,preconditions:[{condition:"Exact alert remains active",status:"met"}],current_access:["repository:read"]});expect(blocked.status).toBe("blocked");const mixed=await json(operatorPage,"post",`/repositories/${repository.id}/runbooks/${book.id}/executions`,operator.headers,{request_id:`mixed-${suffix}`,runbook_version:1,context:{...context,affected_resources:["checkout","billing"]}});expect(mixed).toMatchObject({status:"blocked",blockers:expect.arrayContaining([expect.objectContaining({kind:"precondition_not_met"})])});
    let execution=await json(operatorPage,"post",`/repositories/${repository.id}/runbooks/${book.id}/executions`,operator.headers,{request_id:`execute-${suffix}`,runbook_version:1,context});expect(execution.status,JSON.stringify(execution)).toBe("ready");await rejected(await operatorPage.request.post(`/api/repositories/${repository.id}/runbooks/${book.id}/executions`,{headers:operator.headers,data:{request_id:`duplicate-${suffix}`,runbook_version:1,context}}),409,"runbook_execution_conflict");
    const action=(page:Page,headers:Record<string,string>,data:any)=>json(page,"post",`/repositories/${repository.id}/runbook-executions/${execution.id}/actions`,headers,{expected_version:execution.version,...data});execution=await action(nextPage,next.headers,{request_id:`join-${suffix}`,action:"join"});execution=await action(operatorPage,operator.headers,{request_id:`delegate-${suffix}`,action:"delegate",step_id:"diagnose",target_id:agent.id,delegated_actions:["analyze","perform"]});await rejected(await ownerPage.request.post(`/api/repositories/${repository.id}/runbook-executions/${execution.id}/actions`,{headers:agentHeaders,data:{request_id:`unsafe-agent-${suffix}`,expected_version:execution.version,action:"perform",step_id:"mitigate",message:"Change production directly"}}),409,"runbook_action_conflict");execution=await action(ownerPage,agentHeaders,{request_id:`agent-diagnose-${suffix}`,action:"perform",step_id:"diagnose",evidence:[{kind:"diagnosis",resource_id:"checkout",revision:base,digest:"sha256:diagnosis",summary:"Retries amplify latency; bounded mitigation is indicated"}],cost_cents:7,health:"degraded"});
    await rejected(await operatorPage.request.post(`/api/repositories/${repository.id}/runbook-executions/${execution.id}/actions`,{headers:operator.headers,data:{request_id:`denied-effect-${suffix}`,expected_version:execution.version,action:"perform",step_id:"mitigate"}}),409,"runbook_action_conflict");execution=await action(ownerPage,owner.headers,{request_id:`approve-${suffix}`,action:"approve",step_id:"mitigate",message:"Exact diagnosis supports only the bounded retry change"});execution=await action(operatorPage,operator.headers,{request_id:`mitigate-${suffix}`,action:"perform",step_id:"mitigate",evidence:[{kind:"mitigation",resource_id:"checkout",revision:base,digest:"sha256:mitigation",summary:"Authorized operator reduced retries from eight to two"}],cost_cents:4,health:"degraded"});execution=await action(operatorPage,operator.headers,{request_id:`handoff-${suffix}`,action:"handoff",target_id:next.user.id,message:"Mitigation complete; verify exact recovery and communicate"});execution=await action(nextPage,next.headers,{request_id:`verify-${suffix}`,action:"perform",step_id:"verify",evidence:[{kind:"health",resource_id:"checkout",revision:base,digest:"sha256:healthy",summary:"Checkout succeeds and retry saturation cleared"}],health:"healthy"});execution=await action(nextPage,next.headers,{request_id:`communicate-${suffix}`,action:"perform",step_id:"communicate",evidence:[{kind:"timeline",resource_id:alert.id,revision:base,digest:"sha256:audience",summary:"Declared audience received recovery state"}]});expect(execution).toMatchObject({status:"completed",controller_id:next.user.id,health:"healthy",cost_cents:11});
    const results=criteria.map((x:any)=>({...x,status:x.kind==="communication"?"unmet":"met",evidence_digests:[x.kind==="communication"?"sha256:audience":"sha256:healthy"],explanation:x.kind==="communication"?"The audience template required manual clarification":"Retained execution evidence satisfies the criterion"}));execution=await json(ownerPage,"post",`/repositories/${repository.id}/runbook-executions/${execution.id}/assessment`,owner.headers,{request_id:`assessment-${suffix}`,expected_version:execution.version,outcome:"completed",criteria:results,deviations:[{kind:"manual_work",step_id:"communicate",summary:"Next shift manually clarified the audience update",evidence_digests:["sha256:audience"]}],findings:[{id:"audience-gap",kind:"code",summary:"Add a reviewed audience check and explicit runbook instruction",evidence_digests:["sha256:audience"]}],feedback:[{participant_type:"human",participant_id:next.user.id,summary:"Handoff retained the diagnosis, mitigation, and remaining verification."}],require_fresh_rehearsal:true});
    const retainedFinding=execution.assessment.findings[0];const improvement=await json(ownerPage,"post",`/repositories/${repository.id}/runbook-executions/${execution.id}/improvements`,owner.headers,{request_id:"b".repeat(32),finding_id:retainedFinding.id,kind:"code",title:"Verify recovery communication",outcome:"Add reviewed code and runbook guidance for the declared audience",assignee_type:"human",assignee_id:next.user.id,base_revision:base,due_at:new Date(Date.now()+86400_000).toISOString()});const finding=improvement.execution.assessment.findings.find((x:any)=>x.id===retainedFinding.id);
    await git("",copy,"switch","-c","improve-runbook");await writeFile(join(copy,"health-check.sh"),"#!/bin/sh\ngrep retries service.txt && echo audience=verified\n");await writeFile(join(copy,"RUNBOOK.md"),"# Checkout recovery\n\nInspect exact evidence, request approval, reduce retries, hand off exact context, verify health, and confirm every declared audience received recovery.\n");await git("",copy,"add",".");await git("",copy,"commit","-m","Verify checkout recovery communication");await git(credential.token,copy,"push","origin","improve-runbook");const pull=await json(nextPage,"post",`/repositories/${repository.id}/proposals/${finding.proposal_id}/tasks/${finding.task_id}/contributions`,next.headers,{title:"Verify checkout recovery communication",body:"Close the supported execution finding with reviewed code and runbook guidance.",source_branch:"improve-runbook",target_branch:"main"});await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/reviews`,owner.headers,{decision:"approved"});const merged=await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/merge`,owner.headers,{});
    const successor={...revision,scope:{...revision.scope,revision:merged.merge_commit_id},steps:revision.steps.map((s:any)=>({...s,references:s.references.map((r:any)=>({...r,revision:merged.merge_commit_id}))})),change_reason:"Apply the reviewed communication finding"};book=await json(ownerPage,"post",`/repositories/${repository.id}/runbooks/${book.id}/revisions`,owner.headers,{request_id:`successor-${suffix}`,expected_version:1,revision:successor});expect(book.rehearsals.every((x:any)=>x.stale)).toBe(true);const freshScenario=scenario("successor-case");freshScenario.inputs[0].revision=merged.merge_commit_id;book=await json(operatorPage,"post",`/repositories/${repository.id}/runbooks/${book.id}/rehearsals`,operator.headers,{request_id:`fresh-${suffix}`,runbook_version:2,environment_kind:"isolated",environment_id:"fresh-sandbox",scenarios:[freshScenario]});expect(book.rehearsals.some((x:any)=>x.runbook_version===2&&x.status==="passed"&&!x.stale)).toBe(true);
    const current=await json(ownerPage,"get",`/organizations/${organization.id}`,owner.headers),currentGrant=current.access_grants.find((x:any)=>x.id===grant.id);await json(ownerPage,"delete",`/organizations/${organization.id}/access-grants/${grant.id}`,owner.headers,{expected_version:currentGrant.version});await rejected(await ownerPage.request.post(`/api/repositories/${repository.id}/runbooks/${book.id}/rehearsals`,{headers:agentHeaders,data:{request_id:`revoked-${suffix}`,runbook_version:2,environment_kind:"isolated",environment_id:"revoked",scenarios:[freshScenario]}}),401,"unauthorized");
    await ownerPage.goto(`/repositories/${repository.id}/runbooks`);await expect(ownerPage.getByRole("heading",{name:"Operational runbooks"})).toBeVisible();await expect(ownerPage.getByText("Checkout degraded-service recovery",{exact:true}).first()).toBeVisible();await expect(ownerPage.getByText("v2", { exact:true }).first()).toBeVisible();
  }finally{await rm(copy,{recursive:true,force:true})}
});
