import { expect, test, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

/* eslint-disable @typescript-eslint/no-explicit-any -- one connected privacy evidence trail */
const run=promisify(execFile);
async function git(cwd:string,...args:string[]){return(await run("git",args,{cwd,env:{...process.env,GIT_TERMINAL_PROMPT:"0"}})).stdout.trim()}
async function account(page:Page,name:string,handle:string){await page.goto("/");await page.getByLabel("Display name").fill(name);await page.getByLabel("Handle").fill(handle);await page.getByRole("button",{name:"Create account and continue"}).click();await expect(page.getByRole("heading",{name:"Create a repository"})).toBeVisible();const token=await page.evaluate(()=>localStorage.getItem("vivarium.access-token"));expect(token).toBeTruthy();const headers={Authorization:`Bearer ${token}`};return{headers,user:await(await page.request.get("/api/user",{headers})).json()}}
async function json(page:Page,method:"get"|"post"|"put",path:string,headers:Record<string,string>,data?:unknown){const response=await page.request[method](`/api${path}`,{headers,data});const body=await response.text();expect(response.status(),`${method} ${path}: ${body}`).toBeGreaterThanOrEqual(200);expect(response.status(),`${method} ${path}: ${body}`).toBeLessThan(300);return body?JSON.parse(body):undefined}
async function eventually<T>(read:()=>Promise<T>,ready:(v:T)=>boolean,label:string){let value=await read();await expect.poll(async()=>{value=await read();return ready(value)},{timeout:60_000,message:label}).toBeTruthy();return value}

test("collaborators evolve and restore a declared product data journey",async({browser})=>{
  test.setTimeout(300_000);const docker=await run("docker",["info"]).then(()=>true,()=>false);test.skip(!docker,"previews, release builds, and deployments require Docker");await run("docker",["image","inspect","alpine:3.22"]).catch(()=>run("docker",["pull","alpine:3.22"]));
  const copy=await mkdtemp(join(tmpdir(),"vivarium-privacy-"));try{
    const suffix=Date.now().toString(36),ownerPage=await(await browser.newContext()).newPage(),privacyPage=await(await browser.newContext()).newPage();const owner=await account(ownerPage,"Data Owner",`data-owner-${suffix}`),privacy=await account(privacyPage,"Privacy Reviewer",`privacy-reviewer-${suffix}`);const repo=await json(ownerPage,"post","/repositories",owner.headers,{name:`private-journey-${suffix}`});await json(ownerPage,"post",`/repositories/${repo.id}/collaborators`,owner.headers,{user_id:privacy.user.id});const credential=await json(ownerPage,"post","/auth/credentials",owner.headers,{kind:"git",name:"privacy journey",scopes:["git:read","git:write"],expires_in:3600});await git(tmpdir(),"clone",`http://git:${credential.token}@localhost:3000/git/${repo.id}.git`,copy);await git(copy,"config","user.name","Data Owner");await git(copy,"config","user.email","owner@example.test");await mkdir(join(copy,".vivarium"));
    const preview={version:1,image:"alpine:3.22",build:"mkdir -p dist && cp journey.txt dist/index.html",output_path:"dist",resources:{cpus:1,memory_mb:256,storage_mb:64,timeout_seconds:30},access:{network:"none",data:"preview_artifacts",identity:"named_users",actions:["view","test","feedback"]}};await writeFile(join(copy,"journey.txt"),"account -> service\n");await writeFile(join(copy,".vivarium","preview.json"),JSON.stringify(preview));await writeFile(join(copy,".vivarium","release.json"),JSON.stringify({version:1,steps:[{name:"package",image:"alpine:3.22",command:"cp journey.txt \"$VIVARIUM_OUTPUT/journey.txt\""}]}));await writeFile(join(copy,".vivarium","deployment.json"),JSON.stringify({version:1,stages:[{name:"production",signals:[{name:"artifact readable",command:"test -r \"$VIVARIUM_ARTIFACT\""}]}]}));await writeFile(join(copy,".vivarium","packages.json"),JSON.stringify({version:1,dependencies:[],lock:[]}));await git(copy,"add",".");await git(copy,"commit","-m","Map existing account journey");await git(copy,"push","origin","main");const base=await git(copy,"rev-parse","HEAD");
    const revision={title:"Account lifecycle",summary:"People control a minimal account event.",scopes:[{kind:"repository",name:"Account journey"}],owner_ids:[owner.user.id,privacy.user.id],data_uses:[{id:"account-event",category:"account",subjects:["users"],purposes:["provide account service"],collection:"explicit account action",processing:["validate","store"],sharing:["none"],retention:"30 days",residency:["EU"],deletion:"self-service within 24 hours",consent:"explicit before collection",owner_ids:[owner.user.id,privacy.user.id],supported:true}],links:[{kind:"policy",url:"https://example.test/privacy",label:"Privacy policy"},{kind:"notice",url:"https://example.test/account-notice",label:"Account notice"}],exceptions:[],rationale:"Set the inspectable user expectation before change."};const commitment=await json(ownerPage,"post",`/repositories/${repo.id}/data-commitments`,owner.headers,{revision});const ref={commitment_id:commitment.id,version:1,data_use_ids:["account-event"]};const flow=(sha:string,recipient=false)=>({code_revision:sha,title:"Account journey",affected_paths:["journey.txt"],entry_points:["account"],nodes:[{id:"account",kind:"interaction",name:"Account action",accessible:true},{id:"service",kind:"package",name:"Account service",accessible:true},...(recipient?[{id:"vendor",kind:"external_recipient",name:"Deletion processor",accessible:false,uncertainty:"Processor internals remain outside repository access."}]:[])],edges:[{id:"account-service",from:"account",to:"service",operation:"send",data_categories:["account"],purpose:"provide account service",retained_copy:true,commitment_refs:[ref]},...(recipient?[{id:"service-vendor",from:"service",to:"vendor",operation:"delete",data_categories:["account"],purpose:"provide account service",retained_copy:false,commitment_refs:[ref]}]:[])],commitment_refs:[ref],rationale:"Exact implementation path."});const baseline=await json(ownerPage,"post",`/repositories/${repo.id}/data-flows`,owner.headers,{revision:flow(base)});
    await git(copy,"switch","-c","bounded-deletion");await writeFile(join(copy,"journey.txt"),"account -> service -> deletion-processor\nconsent before send; retain 30 days; delete within 24 hours\n");await git(copy,"add","journey.txt");await git(copy,"commit","-m","Add bounded deletion processor");await git(copy,"push","origin","bounded-deletion");let candidate=await git(copy,"rev-parse","HEAD");const pull=await json(privacyPage,"post",`/repositories/${repo.id}/pulls`,privacy.headers,{title:"Add consent-bound deletion processor",body:"Human design with bounded agent analysis.",source_branch:"bounded-deletion",target_branch:"main"});let candidateFlow=await json(ownerPage,"post",`/repositories/${repo.id}/data-flows`,owner.headers,{revision:flow(candidate,true)});let review=await json(privacyPage,"post",`/repositories/${repo.id}/pulls/${pull.id}/privacy-review`,privacy.headers,{source_flow_id:candidateFlow.id,source_flow_version:1,target_flow_id:baseline.id,target_flow_version:1});await json(privacyPage,"post",`/repositories/${repo.id}/pulls/${pull.id}/privacy-review/comments`,privacy.headers,{kind:"challenge",body:"The inaccessible processor must remain deletion-only and receive no independent retention authority.",finding_kinds:["recipient"],evidence:[{path:"journey.txt",start_line:1,end_line:2,claim:"The exact candidate names consent, retention, and deletion bounds."}]});
    await writeFile(join(copy,"journey.txt"),"account -> service -> deletion-processor\nconsent before send; minimize to account id; retain 30 days; delete within 24 hours\n");await git(copy,"add","journey.txt");await git(copy,"commit","-m","Minimize processor payload");await git(copy,"push","origin","bounded-deletion");candidate=await git(copy,"rev-parse","HEAD");await json(privacyPage,"post",`/repositories/${repo.id}/pulls/${pull.id}/synchronize`,privacy.headers,{});const stale=await json(ownerPage,"get",`/repositories/${repo.id}/pulls/${pull.id}/privacy-review`,owner.headers);expect(stale.requirements.every((x:any)=>x.status==="stale")).toBe(true);candidateFlow=await json(ownerPage,"post",`/repositories/${repo.id}/data-flows`,owner.headers,{revision:flow(candidate,true)});review=await json(privacyPage,"post",`/repositories/${repo.id}/pulls/${pull.id}/privacy-review`,privacy.headers,{source_flow_id:candidateFlow.id,source_flow_version:1,target_flow_id:baseline.id,target_flow_version:1});expect(review.history).toHaveLength(1);const kinds=review.requirements.map((x:any)=>x.kind);await json(privacyPage,"post",`/repositories/${repo.id}/pulls/${pull.id}/privacy-review/acceptance`,privacy.headers,{source_revision:candidate,residual_risk:"Processor availability can delay deletion; the bounded receipt remains observable.",requirement_kinds:kinds});
    const policy=await json(ownerPage,"post",`/repositories/${repo.id}/privacy-check-policies`,owner.headers,{branch:"main",paths:["journey.txt"],required_rules:["consent","minimization","retention","deletion","recipient"],required_journeys:["account-deletion"],privacy_owner_ids:[privacy.user.id]});const rejected=await privacyPage.request.post(`/api/repositories/${repo.id}/privacy-check-exceptions`,{headers:privacy.headers,data:{policy_id:policy.id,revision:candidate,pull_request_id:pull.id,rules:["deletion"],rationale:"Skip deletion proof",follow_up_work:"none",expires_at:new Date(Date.now()+3600000).toISOString()}});expect(rejected.status()).toBe(403);const pv=await json(ownerPage,"post",`/repositories/${repo.id}/pulls/${pull.id}/previews`,owner.headers);await eventually(()=>json(ownerPage,"get",`/repositories/${repo.id}/pulls/${pull.id}/previews`,owner.headers),(x:any)=>x.previews.some((p:any)=>p.id===pv.id&&p.state==="succeeded"),"bounded preview succeeds");await json(ownerPage,"post",`/repositories/${repo.id}/pulls/${pull.id}/privacy-check-runs`,owner.headers,{preview_id:pv.id,revision:candidate,journey:"account-deletion",data_flow_id:candidateFlow.id,data_flow_version:1,isolation:"ephemeral_network_none",production_data:false,results:["consent","minimization","retention","deletion","recipient"].map(rule=>({rule,outcome:"passed",summary:`${rule} passed for synthetic account`})),artifacts:[{kind:"trace",name:"synthetic-trace.json",digest:"a".repeat(64),summary:"Synthetic identifiers only",size_bytes:128}]});await json(privacyPage,"post",`/repositories/${repo.id}/privacy-check-acknowledgements`,privacy.headers,{policy_id:policy.id,revision:candidate,pull_request_id:pull.id,rationale:"Current isolated evidence verifies every declared bound."});expect((await json(ownerPage,"get",`/repositories/${repo.id}/pulls/${pull.id}/privacy-readiness`,owner.headers)).ready).toBe(true);await json(ownerPage,"post",`/repositories/${repo.id}/pulls/${pull.id}/reviews`,owner.headers,{decision:"approved"});const merged=await json(ownerPage,"post",`/repositories/${repo.id}/pulls/${pull.id}/merge`,owner.headers,{});const release=await json(ownerPage,"post",`/repositories/${repo.id}/releases`,owner.headers,{version:"v1.0.0",notes:"Consent-bound minimized deletion journey.",commit_id:merged.merge_commit_id});
    await ownerPage.goto(`/repositories/${repo.id}/data`);await expect(ownerPage.getByRole("heading",{name:"Permitted data handling"})).toBeVisible();await expect(ownerPage.getByRole("heading",{name:"Account lifecycle",exact:true})).toBeVisible();const retained=await json(ownerPage,"get",`/repositories/${repo.id}/pulls/${pull.id}/privacy-review`,owner.headers);expect(retained.accepted_by).toBe(privacy.user.id);expect(release.commit_id).toBe(merged.merge_commit_id);
  }finally{await rm(copy,{recursive:true,force:true})}
});
