import { expect, test, type APIResponse, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

/* eslint-disable @typescript-eslint/no-explicit-any -- one trail joins independently owned repositories and resources */
const run = promisify(execFile);
async function git(token:string,cwd:string,...args:string[]){return(await run("git",["-c","credential.helper=",...args],{cwd,env:{...process.env,GIT_ASKPASS:join(__dirname,"git-askpass.sh"),GIT_TERMINAL_PROMPT:"0",VIVARIUM_GIT_TOKEN:token}})).stdout.trim()}
async function account(page:Page,suffix:string,role:string){await page.goto("/");await page.getByLabel("Display name").fill(`${role} maintainer`);await page.getByLabel("Handle").fill(`restructure-${role}-${suffix}`);await page.getByRole("button",{name:"Create account and continue"}).click();await expect(page.getByRole("heading",{name:"Create a repository"})).toBeVisible();const token=await page.evaluate(()=>localStorage.getItem("vivarium.access-token"));expect(token).toBeTruthy();const headers={Authorization:`Bearer ${token}`};return{headers,user:await(await page.request.get("/api/user",{headers})).json()}}
async function json(page:Page,method:"get"|"post",path:string,headers:Record<string,string>,data?:unknown){const response=await page.request[method](`/api${path}`,{headers,data});const body=await response.text();expect(response.status(),`${method.toUpperCase()} ${path}: ${body}`).toBeGreaterThanOrEqual(200);expect(response.status(),body).toBeLessThan(300);return body?JSON.parse(body):undefined}
async function rejected(response:APIResponse,status:number,code:string){const body=await response.text();expect(response.status(),body).toBe(status);expect(JSON.parse(body)).toMatchObject({error:{code}})}
test("a monorepo extraction retains collaboration through adoption and cleanup",async({browser})=>{
  test.setTimeout(360_000);test.skip(!(await run("docker",["info"]).then(()=>true,()=>false)),"bounded restructuring rehearsal requires Docker");
  await run("docker",["image","inspect","alpine:3.22"]).catch(()=>run("docker",["pull","alpine:3.22"]));
  const copies:string[]=[],credentials:{page:Page;headers:Record<string,string>;id:string}[]=[];
  try{
    const suffix=Date.now().toString(36),leadPage=await(await browser.newContext()).newPage(),componentPage=await(await browser.newContext()).newPage();
    const lead=await account(leadPage,suffix,"lead"),componentOwner=await account(componentPage,suffix,"component");
    const source=await json(leadPage,"post","/repositories",lead.headers,{name:`collaboration-monorepo-${suffix}`});
    await json(leadPage,"post",`/repositories/${source.id}/collaborators`,lead.headers,{user_id:componentOwner.user.id});
    const remaining=await json(leadPage,"post","/repositories",lead.headers,{name:`product-app-${suffix}`}),component=await json(componentPage,"post","/repositories",componentOwner.headers,{name:`shared-kit-${suffix}`});
    const credential=async(page:Page,headers:Record<string,string>,name:string)=>{const x=await json(page,"post","/auth/credentials",headers,{kind:"git",name,scopes:["git:read","git:write"],expires_in:3600});credentials.push({page,headers,id:x.id});return x};
    const sourceGit=await credential(leadPage,lead.headers,"restructuring source"),remainingGit=await credential(leadPage,lead.headers,"restructuring app"),componentGit=await credential(componentPage,componentOwner.headers,"restructuring component");
    const sourceCopy=await mkdtemp(join(tmpdir(),"vivarium-restructure-source-"));copies.push(sourceCopy);await git(sourceGit.token,tmpdir(),"clone",`http://localhost:3000/git/${source.id}.git`,sourceCopy);await git("",sourceCopy,"config","user.name","Shared Component Maintainer");await git("",sourceCopy,"config","user.email","maintainer@example.test");
    await mkdir(join(sourceCopy,"packages","shared"),{recursive:true});await mkdir(join(sourceCopy,"apps","product"),{recursive:true});await writeFile(join(sourceCopy,"packages","shared","index.txt"),"shared=v1\n");await writeFile(join(sourceCopy,"apps","product","index.txt"),"uses=packages/shared\n");await writeFile(join(sourceCopy,"LICENSE"),"MIT\n");await git("",sourceCopy,"add",".");await git("",sourceCopy,"commit","-m","Establish shared component history");await writeFile(join(sourceCopy,"packages","shared","index.txt"),"shared=v2\n");await git("",sourceCopy,"add",".");await git("",sourceCopy,"commit","-m","Prepare cross-cutting component change");const revision=await git("",sourceCopy,"rev-parse","HEAD");await git(sourceGit.token,sourceCopy,"push","origin","main");
    await git("",sourceCopy,"switch","-c","cross-cutting-review");await writeFile(join(sourceCopy,"packages","shared","index.txt"),"shared=v3-review\n");await writeFile(join(sourceCopy,"apps","product","index.txt"),"uses=@project/shared-v3\n");await git("",sourceCopy,"add",".");await git("",sourceCopy,"commit","-m","Update shared API and product consumer");const pullRevision=await git("",sourceCopy,"rev-parse","HEAD");await git(sourceGit.token,sourceCopy,"push","origin","cross-cutting-review");const pull=await json(leadPage,"post",`/repositories/${source.id}/pulls`,lead.headers,{title:"Update shared API and product consumer",body:"One review spans the component and its in-tree consumer.",source_branch:"cross-cutting-review",target_branch:"main"});
    const kinds=["ref","pull_request","issue","task","release","package","documentation","policy","workspace","automation","consumer","federated_relationship"];
    const inventory=kinds.map((kind,i)=>({id:`inventory-${kind}`,kind,repository_id:source.id,resource_id:kind==="ref"?"refs/heads/main":kind==="pull_request"?pull.id:`retained-${kind}-${suffix}`,revision:kind==="pull_request"?pullRevision:revision,owner_ids:[lead.user.id],destination_ids:["app","shared"],disposition:"divide",state:["ref","pull_request"].includes(kind)?"resolved":"inaccessible",summary:kind==="federated_relationship"?"Federated consumer is unavailable during the migration window":`${kind} entry point must be recreated or retained by its current owner`,citation:`topology inventory ${i+1}`}));
    let plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans`,lead.headers,{request_id:`extract-${suffix}`,title:"Extract shared kit without stranding its contributors",intent:"Preserve component history and divide the open API-and-consumer pull into connected contributions.",sources:[{repository_id:source.id,revision,role:"primary"}],destinations:[{id:"app",name:remaining.name,owner_ids:[lead.user.id],visibility:"public",default_branch:"main",retained_identity:"product application"},{id:"shared",name:component.name,owner_ids:[componentOwner.user.id],visibility:"public",default_branch:"main",retained_identity:"shared component"}],mappings:[{id:"app-history",source_repository_id:source.id,source_path:"apps/product",destination_id:"app",destination_path:".",history_mode:"full",retain_identity:true,disposition:"move"},{id:"shared-history",source_repository_id:source.id,source_path:"packages/shared",destination_id:"shared",destination_path:".",history_mode:"full",retain_identity:true,disposition:"move"}],inventory,deadline:new Date(Date.now()+14*86400_000).toISOString(),success_criteria:["Both repositories clone and build","Connected work and supported consumers remain attributable"],rollback_limits:["Restore source writes before independent destination changes are overwritten"]});
    const mapping={request_id:`map-${suffix}`,inventory_item_id:"inventory-pull_request",kind:"pull_request",source_repository_id:source.id,source_resource_id:pull.id,source_revision:pullRevision,disposition:"divide",snapshot:{authorship_ids:[lead.user.id],discussion_ids:[`pull:${pull.id}`],review_ids:["unmappable-pre-split-review"],dependency_ids:[],acceptance_criteria:["Shared API and product consumer change together"]},destinations:[{destination_id:"shared",resource_id:"shared-api-contribution",revision:pullRevision,owner_ids:[componentOwner.user.id],acceptance_criteria:["component change passes"]},{destination_id:"app",resource_id:"consumer-contribution",revision:pullRevision,owner_ids:[lead.user.id],dependency_ids:["shared-api-contribution"],acceptance_criteria:["consumer uses released component"]}]};
    plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/collaboration-mappings`,lead.headers,{expected_version:plan.version,mapping});plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/collaboration-mappings/${plan.collaboration_mappings[0].id}/decisions`,lead.headers,{expected_version:plan.version,decision:{request_id:`approve-map-${suffix}`,decision:"approve",source_revision:pullRevision,note:"Approve the connected replacement; the old review remains evidence only."}});
    plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/candidate-sets`,lead.headers,{request_id:`candidate-${suffix}`,expected_version:plan.version,cross_repository_links:["app depends on the versioned shared package and connected contribution"]});const candidate=plan.candidate_sets[0];expect(candidate.repositories.every((x:any)=>x.signature_state.includes("unsigned"))).toBe(true);
    for(const gap of candidate.gaps){plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/candidate-sets/${candidate.id}/gap-decisions`,lead.headers,{expected_version:plan.version,decision:{request_id:`gap-${gap.kind}-${suffix}`,gap_kind:gap.kind,resource_id:gap.resource_id,decision:gap.kind==="federated_relationship"?"retain_external":"recreate",rationale:gap.kind==="federated_relationship"?"The unavailable peer remains independently controlled and must acknowledge later.":"Recreate through ordinary destination work while retaining the old identity."}})}
    const scenarioKinds=["repository_integrity","clone","fetch","push","build","check","package_resolution","api_resolution","documentation","workspace","consumer_journey"],scenarios:any[]=[];for(const destination of ["app","shared"])for(const kind of scenarioKinds)scenarios.push({id:`${destination}-${kind}`,kind,destination_id:destination,image:["repository_integrity","clone","fetch","push"].includes(kind)?"":"alpine:3.22",command:["repository_integrity","clone","fetch","push"].includes(kind)?"":"find . -type f | grep -q .",expectation:`${kind} works in ${destination}`,timeout_seconds:20});
    plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/candidate-sets/${candidate.id}/rehearsals`,lead.headers,{expected_version:plan.version,rehearsal:{request_id:`rehearse-${suffix}`,scenarios}});expect(plan.candidate_sets[0].rehearsals[0].state).toBe("passed");
    const window={starts_at:new Date().toISOString(),ends_at:new Date(Date.now()+7*86400_000).toISOString()};for(const [kind,resource,owner,actorKind] of [["package",`@project/shared-${suffix}`,lead.user.id,"human"],["dependency",remaining.id,lead.user.id,"agent"],["federated_follower",`https://offline.example/${suffix}`,componentOwner.user.id,"human"]]){plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/dependent-migrations`,lead.headers,{expected_version:plan.version,migration:{request_id:`dependent-${kind}-${suffix}`,kind,resource_id:resource,owner_id:owner,audience:"public",state:kind==="federated_follower"?"unavailable":"in_progress",compatibility_window:window,next_action:"Adopt the extracted component and verify the replacement entry point",replacement_remotes:kind==="federated_follower"?[{destination_id:"shared",remote_url:`http://localhost:3000/git/${component.id}.git`,ref:"main"}]:[],mappings:kind!=="federated_follower"?[{kind:kind==="package"?"package":"dependency",from:"packages/shared",to:`@project/shared-${suffix}`}]:[],synchronization:["fetch without credentials in the URL","verify the selected revision before changing authority"],propagation:{actor_kind:actorKind,repository_id:remaining.id,task_id:`migration-${kind}`}}})}
    const dependencyMap=await json(leadPage,"get",`/repositories/${source.id}/restructuring-plans/${plan.id}/dependency-map`,lead.headers);expect(dependencyMap.schema).toBe("vivarium.restructuring-dependency-map/v1");
    for(const migration of plan.dependent_migrations){const page=migration.owner_id===componentOwner.user.id?componentPage:leadPage,headers=migration.owner_id===componentOwner.user.id?componentOwner.headers:lead.headers;plan=await json(page,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/dependent-migrations/${migration.id}/events`,headers,{expected_version:plan.version,event:{request_id:`adopt-${migration.kind}-${suffix}`,state:"adopted",evidence:migration.kind==="federated_follower"?"Peer owner acknowledged the replacement after connectivity recovered":"Human or bounded agent pull and package-client resolution passed",next_action:"Compatibility redirect may retire after topology verification"}})}
    plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/cutover`,lead.headers,{expected_version:plan.version,cutover:{request_id:`cutover-${suffix}`,candidate_id:candidate.id,pause_kinds:["git","collaboration","automation","release"],cleanup_policy:"archive"}});plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/cutover/approvals`,lead.headers,{expected_version:plan.version,approval:{request_id:`approve-app-${suffix}`,destination_id:"app",decision:"approve"}});plan=await json(componentPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/cutover/approvals`,componentOwner.headers,{expected_version:plan.version,approval:{request_id:`approve-shared-${suffix}`,destination_id:"shared",decision:"approve"}});
    await rejected(await componentPage.request.post(`/api/repositories/${source.id}/restructuring-plans/${plan.id}/cutover/activate`,{headers:componentOwner.headers,data:{expected_version:plan.version,repositories:{app:remaining.id,shared:component.id}}}),409,"restructuring_activation_blocked");
    plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/cutover/activate`,lead.headers,{expected_version:plan.version,repositories:{app:remaining.id,shared:component.id}});expect(plan.cutover.state).toBe("active");
    const prematureRelease=await json(componentPage,"post",`/repositories/${component.id}/releases`,componentOwner.headers,{version:"v3.0.0-rc1",notes:"Candidate package release after extraction",commit_id:plan.cutover.destinations.find((x:any)=>x.destination_id==="shared").revision});await rejected(await componentPage.request.post(`/api/repositories/${component.id}/releases/${prematureRelease.id}/packages`,{headers:componentOwner.headers,data:{name:`shared-kit-${suffix}`,version:"3.0.0",build_id:"missing-build",artifact_id:"missing-artifact",platform:{os:"linux",architecture:"amd64"},visibility:"public",summary:"Extracted shared kit",documentation:"Use the replacement dependency map",license:"MIT",support:"project maintainers"}}),422,"invalid_package_build");
    await leadPage.goto(`/repositories/${source.id}/restructuring`);await expect(leadPage.getByRole("button",{name:"Restore source authority without changing destination refs"})).toBeVisible();
    await writeFile(join(sourceCopy,"late-write.txt"),"must not land during cutover\n");await git("",sourceCopy,"add","late-write.txt");await git("",sourceCopy,"commit","-m","Concurrent source push");await expect(git(sourceGit.token,sourceCopy,"push","origin","HEAD:main")).rejects.toThrow(/HTTP 409|restructuring|paused|rejected/i);
    const componentCopy=await mkdtemp(join(tmpdir(),"vivarium-restructure-component-"));copies.push(componentCopy);await git(componentGit.token,tmpdir(),"clone",`http://localhost:3000/git/${component.id}.git`,componentCopy);expect(await git("",componentCopy,"log","--format=%s","--all")).toContain("Immutable restructuring candidate");await git("",componentCopy,"config","user.name","Independent Component Owner");await git("",componentCopy,"config","user.email","component@example.test");await writeFile(join(componentCopy,"index.txt"),"shared=v3-after-cutover\n");await git("",componentCopy,"add",".");await git("",componentCopy,"commit","-m","Deliver through independently owned shared repository");await git(componentGit.token,componentCopy,"push","origin","main");
    expect(await git(remainingGit.token,tmpdir(),"ls-remote",`http://localhost:3000/git/${remaining.id}.git`,"refs/heads/main")).toContain("refs/heads/main");
    for(const destination of ["app","shared"])for(const kind of ["build","release","permission","link","consumer","contribution","git_traffic"]){plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/cutover/observations`,lead.headers,{expected_version:plan.version,observation:{request_id:`observe-${destination}-${kind}-${suffix}`,kind,resource_id:destination,state:"passed",evidence:`Verified ${kind} through the authoritative ${destination} repository and retained migration trail`}})}
    plan=await json(leadPage,"post",`/repositories/${source.id}/restructuring-plans/${plan.id}/cutover/finish`,lead.headers,{expected_version:plan.version,rollback:false});expect(plan.cutover).toMatchObject({state:"completed",source_state:"archive"});
    await componentPage.goto(`/repositories/${source.id}/restructuring`);await expect(componentPage.getByRole("heading",{name:"Restructuring plans"})).toBeVisible();await expect(componentPage.getByText("Extract shared kit without stranding its contributors",{exact:true})).toBeVisible();await expect(componentPage.getByText("completed",{exact:true}).first()).toBeVisible();await expect(componentPage.getByText(/unavailable peer remains independently controlled/i)).toBeVisible();
  }finally{for(const x of credentials)await x.page.request.delete(`/api/auth/credentials/${x.id}`,{headers:x.headers}).catch(()=>undefined);for(const copy of copies)await rm(copy,{recursive:true,force:true})}
});
