import { expect, test, type APIResponse, type Page } from "@playwright/test";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

/* eslint-disable @typescript-eslint/no-explicit-any -- this journey joins all review ledgers */
const run = promisify(execFile);
async function git(token:string,cwd:string,...args:string[]){return(await run("git",["-c","credential.helper=",...args],{cwd,env:{...process.env,GIT_ASKPASS:join(__dirname,"git-askpass.sh"),GIT_TERMINAL_PROMPT:"0",VIVARIUM_GIT_TOKEN:token}})).stdout.trim()}
async function account(page:Page,suffix:string,role:string){await page.goto("/");await page.getByLabel("Display name").fill(`${role} reviewer`);await page.getByLabel("Handle").fill(`review-${role.toLowerCase()}-${suffix}`);await page.getByRole("button",{name:"Create account and continue"}).click();await expect(page.getByRole("heading",{name:"Create a repository"})).toBeVisible();const token=await page.evaluate(()=>localStorage.getItem("vivarium.access-token"));expect(token).toBeTruthy();const headers={Authorization:`Bearer ${token}`};return{headers,user:await(await page.request.get("/api/user",{headers})).json()}}
async function json(page:Page,method:"get"|"post"|"put"|"delete",path:string,headers:Record<string,string>,data?:unknown){const response=await page.request[method](`/api${path}`,{headers,data});const body=await response.text();expect(response.status(),`${method.toUpperCase()} ${path}: ${body}`).toBeGreaterThanOrEqual(200);expect(response.status(),body).toBeLessThan(300);return body?JSON.parse(body):undefined}
async function rejected(response:APIResponse,status:number,code:string){const body=await response.text();expect(response.status(),body).toBe(status);expect(JSON.parse(body)).toMatchObject({error:{code}})}
async function eventually<T>(read:()=>Promise<T>,ready:(value:T)=>boolean){await expect.poll(async()=>ready(await read()),{timeout:60_000,intervals:[250,500,1000]}).toBe(true);return read()}

test("a cross-cutting change reaches exact coordinated review and integration",async({browser})=>{
  test.setTimeout(300_000);test.skip(!(await run("docker",["info"]).then(()=>true,()=>false)),"review checks require Docker");await run("docker",["image","inspect","alpine:3.22"]).catch(()=>run("docker",["pull","alpine:3.22"]));
  const copies:string[]=[];
  try{
    const suffix=Date.now().toString(36),pages=await Promise.all(Array.from({length:6},async()=>await(await browser.newContext()).newPage()));
    const [ownerPage,authorPage,codePage,securityPage,accessibilityPage,consumerPage]=pages;
    const owner=await account(ownerPage,suffix,"Owner"),author=await account(authorPage,suffix,"Author"),code=await account(codePage,suffix,"Code"),security=await account(securityPage,suffix,"Security"),accessibility=await account(accessibilityPage,suffix,"Accessibility"),consumer=await account(consumerPage,suffix,"Consumer");
    const organization=await json(ownerPage,"post","/organizations",owner.headers,{name:`Review Guild ${suffix}`,slug:`review-guild-${suffix}`});
    for(const actor of [{page:authorPage,value:author},{page:codePage,value:code},{page:securityPage,value:security},{page:accessibilityPage,value:accessibility},{page:consumerPage,value:consumer}]){const state=await json(ownerPage,"post",`/organizations/${organization.id}/invitations`,owner.headers,{user_id:actor.value.user.id});await json(actor.page,"post",`/organizations/${organization.id}/invitations/${state.invitations.at(-1).id}/accept`,actor.value.headers)}
    const repository=await json(ownerPage,"post",`/organizations/${organization.id}/repositories`,owner.headers,{name:`reviewed-console-${suffix}`});
    let org=await json(ownerPage,"post",`/organizations/${organization.id}/agents`,owner.headers,{name:"Read-only Review Analyst",slug:`review-analyst-${suffix}`,capabilities:["review exact repository changes"],operator_ids:[owner.user.id],team_ids:[]});const agent=org.agents.find((x:any)=>x.slug===`review-analyst-${suffix}`);
    org=await json(ownerPage,"put",`/organizations/${organization.id}/agents/${agent.id}/profile`,owner.headers,{expected_version:0,profile:{summary:"Bounded pull reviewer",supported_tasks:["review exact repository changes"],tools:["repository reader"],model_provenance:"review-model-1",execution_provenance:"networkless",deployment_boundaries:["platform"],data_use:"Current pull only",retention:"none",pricing:"internal",resource_requirements:["one CPU"],requested_capabilities:["repository.read"],availability:"available",support:"owners@example.test",subprocessors:[],remote_execution_boundaries:["none"],conflict_disclosures:[],change_summary:"Initial read-only review profile"}});
    const requestState=await json(ownerPage,"post",`/organizations/${organization.id}/access-requests`,owner.headers,{principal_type:"agent",principal_id:agent.id,role:"viewer",resources:[{kind:"repository",id:repository.id}],exceptions:[],reason:"Inspect one exact assigned review area.",expires_at:new Date(Date.now()+3600_000).toISOString()});org=await json(ownerPage,"post",`/organizations/${organization.id}/access-requests/${requestState.access_requests.at(-1).id}/decision`,owner.headers,{decision:"approve"});const grant=org.access_grants.find((x:any)=>x.principal_id===agent.id),agentCredential=await json(ownerPage,"post",`/organizations/${organization.id}/access-grants/${grant.id}/credentials`,owner.headers,{agent_id:agent.id,repository_id:repository.id,expires_in:3600,purpose:"api_read"}),agentHeaders={Authorization:`Bearer ${agentCredential.token}`};
    const credential=await json(ownerPage,"post","/auth/credentials",owner.headers,{kind:"git",name:"cross-cutting review",scopes:["git:read","git:write"],expires_in:3600}),copy=await mkdtemp(join(tmpdir(),"vivarium-review-"));copies.push(copy);await git(credential.token,tmpdir(),"clone",`http://localhost:3000/git/${repository.id}.git`,copy);await git("",copy,"config","user.name","Pull Author");await git("",copy,"config","user.email","author@example.test");await mkdir(join(copy,".vivarium"));await writeFile(join(copy,".vivarium","checks.json"),JSON.stringify({version:1,checks:[{name:"cross-cutting contract",image:"alpine:3.22",command:"grep -q 'safe=true' api/security-accessibility.tsx && grep -q 'consumer=v2' api/schema.ts"}]}));await mkdir(join(copy,"api"));await writeFile(join(copy,"api","security-accessibility.tsx"),"export const policy = 'safe=true keyboard=visible'\n");await writeFile(join(copy,"api","schema.ts"),"export const contract = 'consumer=v1'\n");await git("",copy,"add",".");await git("",copy,"commit","-m","Establish reviewed console");await git(credential.token,copy,"push","origin","HEAD:main");await json(ownerPage,"put",`/repositories/${repository.id}/branches/main/required-checks`,owner.headers,{checks:["cross-cutting contract"]});await json(ownerPage,"put",`/repositories/${repository.id}/branches/main/integration-queue`,owner.headers,{enabled:true,concurrency:1,failure_behavior:"remove"});
    await git("",copy,"switch","-c","cross-cutting");await writeFile(join(copy,"api","schema.ts"),"export const contract = 'consumer=v2'\n");await writeFile(join(copy,"api","security-accessibility.tsx"),"export const policy = 'safe=true keyboard=visible contract=v2'\n");await git("",copy,"add",".");await git("",copy,"commit","-m","Evolve secure accessible consumer contract");await git(credential.token,copy,"push","origin","cross-cutting");let revision=await git("",copy,"rev-parse","HEAD");
    const pull=await json(authorPage,"post",`/repositories/${repository.id}/pulls`,author.headers,{title:"Evolve the secure accessible consumer contract",body:"Change the public consumer contract while preserving authentication and keyboard behavior.",source_branch:"cross-cutting",target_branch:"main"});let plan=await json(authorPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-plans`,author.headers,{request_id:`plan-initial-${suffix}`,risk_summary:"Security, accessibility, and consumer compatibility need independent review."});expect(plan.areas.map((x:any)=>x.id)).toEqual(["change-intent","security","accessibility","interface"]);
    const actors:any={"change-intent":code,"security":security,"accessibility":accessibility,"interface":consumer},actorPages:any={"change-intent":codePage,"security":securityPage,"accessibility":accessibilityPage,"interface":consumerPage};const assignments:any={};
    for(const area of plan.areas){assignments[area.id]=await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-assignments`,owner.headers,{request_id:`assign-${area.id}-${suffix}`,plan_id:plan.id,area_id:area.id,principal_type:"human",principal_id:actors[area.id].user.id,deadline:new Date(Date.now()+86400_000).toISOString(),escalation_path:"Repository owner"});await json(actorPages[area.id],"post",`/repositories/${repository.id}/pulls/${pull.id}/review-assignments/${assignments[area.id].id}/transitions`,actors[area.id].headers,{action:"accept"})}
    const overloaded=await json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pull.id}/review-assignments`,owner.headers);expect(overloaded.suggestions.find((x:any)=>x.principal_id===code.user.id)).toMatchObject({availability:"available"});
    await json(securityPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-assignments/${assignments.security.id}/transitions`,security.headers,{action:"recuse",reason:"Authored the earlier authentication design."});await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-assignments/${assignments.security.id}/transitions`,owner.headers,{action:"replace",reason:"Recusal needs independent coverage.",request_id:`security-agent-${suffix}`,principal_type:"agent",principal_id:agent.id,agent_grant_id:grant.id});const reassigned=await json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pull.id}/review-assignments`,owner.headers);assignments.security=reassigned.assignments.find((x:any)=>x.principal_id===agent.id);await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-assignments/${assignments.security.id}/transitions`,agentHeaders,{action:"accept"});
    const cite=(area:any)=>area.id==="change-intent"?[{kind:"diff",value:area.paths[0]}]:[{kind:"file",value:area.paths[0],domain:area.id,covered_paths:area.paths}];const area=(id:string)=>plan.areas.find((x:any)=>x.id===id);
    const agentFinding=await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-work`,agentHeaders,{request_id:`agent-finding-${suffix}`,plan_id:plan.id,area_id:"security",kind:"finding",conclusion:"blocking",body:"The contract revision may bypass the authentication guard.",uncertainty:"The consumer fixture is inaccessible to the read-only agent.",citations:cite(area("security"))});await json(codePage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-work`,code.headers,{request_id:`code-progress-${suffix}`,plan_id:plan.id,area_id:"change-intent",kind:"progress",conclusion:"compatible",body:"The implementation is narrow but depends on consumer confirmation.",citations:cite(area("change-intent"))});await json(accessibilityPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-work`,accessibility.headers,{request_id:`a11y-handoff-${suffix}`,plan_id:plan.id,area_id:"accessibility",kind:"handoff",body:"I am unavailable for keyboard reproduction; hand this exact area to the owner.",citations:cite(area("accessibility")),recipient_type:"human",recipient_id:owner.user.id});await json(consumerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-work`,consumer.headers,{request_id:`consumer-finding-${suffix}`,plan_id:plan.id,area_id:"interface",kind:"finding",conclusion:"blocking",body:"The v2 consumer fixture fails because the compatibility alias is absent.",citations:cite(area("interface"))});
    await json(authorPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-findings/resolutions`,author.headers,{request_id:`challenge-agent-${suffix}`,finding_id:agentFinding.id,action:"challenge",classification:"disputed",rationale:"The authentication guard is unchanged; the failed consumer fixture points to compatibility instead.",dissent:"Agent uncertainty remains retained."});await json(codePage,"post",`/repositories/${repository.id}/pulls/${pull.id}/reviews`,code.headers,{decision:"approved"});await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/reviews`,owner.headers,{decision:"changes_requested"});
    await writeFile(join(copy,"api","schema.ts"),"export const contract = 'consumer=v2 alias=v1'\n");await git("",copy,"add",".");await git("",copy,"commit","-m","Restore the reviewed compatibility alias");await git(credential.token,copy,"push","origin","cross-cutting");revision=await git("",copy,"rev-parse","HEAD");await json(authorPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/synchronize`,author.headers,{});const history=await json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pull.id}/review-plans`,owner.headers);expect(history.review_plans[0]).toMatchObject({stale:true});plan=await json(authorPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-plans`,author.headers,{request_id:`plan-repair-${suffix}`,risk_summary:"The compatibility repair narrows consumer risk; security and accessibility still require current evidence."});
    const oldWork=await json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pull.id}/review-work`,owner.headers);expect(oldWork.finding_resolutions.find((x:any)=>x.finding.id===agentFinding.id)).toMatchObject({current_state:"stale"});
    const currentOrg=await json(ownerPage,"get",`/organizations/${organization.id}`,owner.headers),currentGrant=currentOrg.access_grants.find((x:any)=>x.id===grant.id);await json(ownerPage,"delete",`/organizations/${organization.id}/access-grants/${grant.id}`,owner.headers,{expected_version:currentGrant.version});const revoked=await json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pull.id}/review-assignments`,owner.headers);expect(revoked.assignments.find((x:any)=>x.principal_id===agent.id)).toMatchObject({status:"revoked"});await rejected(await ownerPage.request.post(`/api/repositories/${repository.id}/pulls/${pull.id}/review-work`,{headers:agentHeaders,data:{request_id:`revoked-agent-${suffix}`,plan_id:plan.id,area_id:"security",kind:"progress",body:"Continue after revocation.",citations:[]}}),401,"unauthorized");
    const checks=await eventually(()=>json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pull.id}/checks`,owner.headers),(x:any)=>x.check_runs?.some((c:any)=>c.commit_id===revision&&c.state==="succeeded"));const check=checks.check_runs.find((c:any)=>c.commit_id===revision&&c.state==="succeeded");
    for(const a of plan.areas){const assignment=await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-assignments`,owner.headers,{request_id:`final-owner-${a.id}-${suffix}`,plan_id:plan.id,area_id:a.id,principal_type:"human",principal_id:owner.user.id,escalation_path:"Current owner"});await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-assignments/${assignment.id}/transitions`,owner.headers,{action:"accept"});const citations=a.id==="change-intent"?[{kind:"diff",value:a.paths[0]},{kind:"check",value:check.id}]:[{kind:"file",value:a.paths[0],domain:a.id,covered_paths:a.paths}];await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/review-work`,owner.headers,{request_id:`final-decision-${a.id}-${suffix}`,plan_id:plan.id,area_id:a.id,kind:"decision",conclusion:"approved",body:`Current ${a.id} evidence covers every planned path and the repaired intent.`,citations})}
    await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/reviews`,owner.headers,{decision:"approved"});const readiness=await json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pull.id}/review-readiness`,owner.headers);expect(readiness).toMatchObject({current:true,complete:true});expect(readiness.stale_approvals).toEqual(expect.arrayContaining([expect.objectContaining({decision:"approved"})]));const mergeReady=await json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pull.id}/merge-readiness`,owner.headers);expect(mergeReady).toMatchObject({mergeable:true,can_enqueue:true});await ownerPage.goto(`/pulls/${repository.id}/${pull.id}`);await expect(ownerPage.getByText("Review coverage matrix",{exact:true})).toBeVisible();await expect(ownerPage.getByText("Shared review work",{exact:true})).toBeVisible();await expect(ownerPage.getByText(/compatibility repair narrows consumer risk/i)).toBeVisible();const queued=await json(ownerPage,"post",`/repositories/${repository.id}/pulls/${pull.id}/queue`,owner.headers,{});expect(queued.integration_candidates).toHaveLength(1);await eventually(()=>json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pull.id}/candidates`,owner.headers),(x:any)=>x.candidates?.some((c:any)=>c.state==="passed"));const merged=await eventually(()=>json(ownerPage,"get",`/repositories/${repository.id}/pulls/${pull.id}`,owner.headers),(x:any)=>x.status==="merged");expect(merged).toMatchObject({status:"merged"});expect(merged.merge_commit_id).toBeTruthy();
  }finally{await Promise.all(copies.map(path=>rm(path,{recursive:true,force:true})))}
});
