"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Diagnostic={kind:string;severity:string;message:string;resource_id?:string;attributed_to:string};
type Revision={version:number;title:string;summary:string;subject:{kind:string;resource_id?:string;name:string};standards:{name:string;version:string;level:string;criteria:string[]}[];assistive_technologies:{id:string;name:string;version:string;input:string;environment_ids:string[]}[];target_audiences:{id:string;name:string;access_needs:string[]}[];environments:{id:string;browser:string;browser_version:string;os:string;device:string;supported:boolean;note?:string}[];required_scenarios:{id:string;name:string;steps:string[];expected_outcome:string;standard_criteria:string[];audience_ids:string[];technology_ids:string[];environment_ids:string[];owner_ids:string[]}[];severity_policy:{severity:string;definition:string;response:string;resolution_days:number}[];owner_ids:string[];requirements:{id:string;statement:string;conflicts_with?:string[]}[];exceptions:{id:string;scope:string;reason:string;approved_by:string;expires_at:string;mitigation:string}[];links:{kind:string;resource_id:string;label:string;added_by?:string}[];rationale:string;created_by:string;created_at:string};
type Commitment={id:string;current_version:number;revisions:Revision[];diagnostics:Diagnostic[]};
const value=(f:FormData,n:string)=>String(f.get(n)??"").trim();
const list=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);

export function AccessibilityCommitmentsWorkspace({repositoryID}:{repositoryID:string}){
 const {token,user}=useAuth(),[items,setItems]=useState<Commitment[]>([]),[selected,setSelected]=useState<Commitment>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!token)return;try{const out=await api<{commitments:Commitment[]}>(`/repositories/${repositoryID}/accessibility-commitments`,{},token);setItems(out.commitments);setSelected(x=>out.commitments.find(v=>v.id===x?.id)??out.commitments[0])}catch(e){setError(e instanceof Error?e.message:"Commitments could not be loaded.")}},[repositoryID,token]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
 const current=selected?.revisions.at(-1);
 function revision(f:FormData):Omit<Revision,"version"|"created_by"|"created_at">{
  const environment=value(f,"environment_id"),audience=value(f,"audience_id"),technology=value(f,"technology_id"),owners=list(value(f,"owners")),exceptionID=value(f,"exception_id"),linkID=value(f,"link_id"),conflict=value(f,"conflicts_with");
  return {title:value(f,"title"),summary:value(f,"summary"),subject:{kind:value(f,"subject_kind"),resource_id:value(f,"subject_id"),name:value(f,"subject_name")},
   standards:[{name:value(f,"standard_name"),version:value(f,"standard_version"),level:value(f,"standard_level"),criteria:list(value(f,"criteria"))},...(current?.standards.slice(1)??[])],
   assistive_technologies:[{id:technology,name:value(f,"technology_name"),version:value(f,"technology_version"),input:value(f,"technology_input"),environment_ids:[environment,...(current?.assistive_technologies[0]?.environment_ids.slice(1)??[])]},...(current?.assistive_technologies.slice(1)??[])],
   target_audiences:[{id:audience,name:value(f,"audience_name"),access_needs:list(value(f,"access_needs"))},...(current?.target_audiences.slice(1)??[])],
   environments:[{id:environment,browser:value(f,"browser"),browser_version:value(f,"browser_version"),os:value(f,"os"),device:value(f,"device"),supported:value(f,"supported")==="yes",note:value(f,"environment_note")},...(current?.environments.slice(1)??[])],
   required_scenarios:[{id:value(f,"scenario_id"),name:value(f,"scenario_name"),steps:value(f,"steps").split("\n").map(x=>x.trim()).filter(Boolean),expected_outcome:value(f,"expected_outcome"),standard_criteria:list(value(f,"criteria")),audience_ids:[audience,...(current?.required_scenarios[0]?.audience_ids.slice(1)??[])],technology_ids:[technology,...(current?.required_scenarios[0]?.technology_ids.slice(1)??[])],environment_ids:[environment,...(current?.required_scenarios[0]?.environment_ids.slice(1)??[])],owner_ids:owners},...(current?.required_scenarios.slice(1)??[])],
   severity_policy:[{severity:value(f,"severity"),definition:value(f,"severity_definition"),response:value(f,"severity_response"),resolution_days:Number(value(f,"resolution_days"))},...(current?.severity_policy.slice(1)??[])],owner_ids:owners,
   requirements:[{id:value(f,"requirement_id"),statement:value(f,"requirement"),conflicts_with:[...(conflict?[conflict]:[]),...(current?.requirements[0]?.conflicts_with?.slice(1)??[])]},...(current?.requirements.slice(1)??[])],
   exceptions:[...(exceptionID?[{id:exceptionID,scope:value(f,"exception_scope"),reason:value(f,"exception_reason"),approved_by:user?.id??"",expires_at:new Date(value(f,"exception_expiry")).toISOString(),mitigation:value(f,"mitigation")}]:[]),...(current?.exceptions.slice(1)??[])],
   links:[...(linkID?[{kind:value(f,"link_kind"),resource_id:linkID,label:value(f,"link_label")}]:[]),...(current?.links.slice(1)??[])],rationale:value(f,"rationale")}
 }
 async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;setBusy(true);setError("");const path=selected?`/repositories/${repositoryID}/accessibility-commitments/${selected.id}/revisions`:`/repositories/${repositoryID}/accessibility-commitments`;try{const out=await api<Commitment>(path,{method:"POST",body:JSON.stringify({revision:revision(new FormData(e.currentTarget)),...(selected?{expected_version:selected.current_version}:{})})},token);setSelected(out);setItems(v=>[out,...v.filter(x=>x.id!==out.id)])}catch(reason){setError(reason instanceof Error?reason.message:"Commitment could not be published.")}finally{setBusy(false)}}
 return <div className="space-y-6"><header><Link href={`/repositories/${repositoryID}`} className="text-sm text-[var(--muted)] hover:text-[var(--brand)]">Repository</Link><h1 className="mt-2 text-2xl font-semibold">Accessibility commitments</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Define who and what must be supported, how required experiences are judged, and who owns gaps before review. Every complete successor retains its author and rationale.</p></header>
 <Card className="p-5"><div className="flex justify-between"><h2 className="font-semibold">{selected?"Publish a complete successor":"Define an accessibility contract"}</h2>{selected&&<Button type="button" variant="secondary" onClick={()=>setSelected(undefined)}>New commitment</Button>}</div><form onSubmit={publish} className="mt-4 space-y-4"><div className="grid gap-3 md:grid-cols-3"><Field n="title" l="Commitment title" v={current?.title}/><Field n="subject_name" l="Experience name" v={current?.subject.name}/><Select n="subject_kind" l="Experience type" v={current?.subject.kind??"repository"} options={["repository","documented_journey","component","release"]}/><Field n="subject_id" l="Resource ID (optional)" v={current?.subject.resource_id} required={false}/><Field n="owners" l="Owner IDs" v={current?.owner_ids.join(", ")??user?.id}/></div><Area n="summary" l="Commitment outcome" v={current?.summary}/><Area n="rationale" l="Revision rationale" v={current?.rationale}/>
 <Group title="Applicable standard"><Field n="standard_name" l="Standard" v={current?.standards[0]?.name??"WCAG"}/><Field n="standard_version" l="Version" v={current?.standards[0]?.version??"2.2"}/><Field n="standard_level" l="Conformance level" v={current?.standards[0]?.level??"AA"}/><Field n="criteria" l="Criteria (comma separated)" v={current?.standards[0]?.criteria.join(", ")}/></Group>
 <Group title="Audience and assistive technology"><Field n="audience_id" l="Audience key" v={current?.target_audiences[0]?.id}/><Field n="audience_name" l="Target audience" v={current?.target_audiences[0]?.name}/><Field n="access_needs" l="Access needs" v={current?.target_audiences[0]?.access_needs.join(", ")}/><Field n="technology_id" l="Technology key" v={current?.assistive_technologies[0]?.id}/><Field n="technology_name" l="Assistive technology" v={current?.assistive_technologies[0]?.name}/><Field n="technology_version" l="Supported version" v={current?.assistive_technologies[0]?.version}/><Field n="technology_input" l="Input/output mode" v={current?.assistive_technologies[0]?.input}/></Group>
 <Group title="Supported environment"><Field n="environment_id" l="Environment key" v={current?.environments[0]?.id}/><Field n="browser" l="Browser" v={current?.environments[0]?.browser}/><Field n="browser_version" l="Browser version" v={current?.environments[0]?.browser_version}/><Field n="os" l="Operating system" v={current?.environments[0]?.os}/><Field n="device" l="Device" v={current?.environments[0]?.device}/><Select n="supported" l="Support status" v={current?.environments[0]?.supported===false?"no":"yes"} options={["yes","no"]}/><Field n="environment_note" l="Support note" v={current?.environments[0]?.note} required={false}/></Group>
 <Group title="Required test scenario"><Field n="scenario_id" l="Scenario key" v={current?.required_scenarios[0]?.id}/><Field n="scenario_name" l="Scenario name" v={current?.required_scenarios[0]?.name}/><Area n="steps" l="Steps (one per line)" v={current?.required_scenarios[0]?.steps.join("\n")}/><Area n="expected_outcome" l="Observable success" v={current?.required_scenarios[0]?.expected_outcome}/></Group>
 <Group title="Severity policy and requirement"><Select n="severity" l="Severity" v={current?.severity_policy[0]?.severity??"critical"} options={["critical","major","minor","advisory"]}/><Field n="severity_definition" l="Definition" v={current?.severity_policy[0]?.definition}/><Field n="severity_response" l="Required response" v={current?.severity_policy[0]?.response}/><Field n="resolution_days" l="Resolution days" type="number" v={String(current?.severity_policy[0]?.resolution_days??1)}/><Field n="requirement_id" l="Requirement key" v={current?.requirements[0]?.id}/><Field n="requirement" l="Testable requirement" v={current?.requirements[0]?.statement}/><Field n="conflicts_with" l="Conflicting requirement key" v={current?.requirements[0]?.conflicts_with?.[0]} required={false}/></Group>
 <Group title="Permitted exception (optional)"><Field n="exception_id" l="Exception key" v={current?.exceptions[0]?.id} required={false}/><Field n="exception_scope" l="Narrow scope" v={current?.exceptions[0]?.scope} required={false}/><Field n="exception_reason" l="Reason" v={current?.exceptions[0]?.reason} required={false}/><Field n="exception_expiry" l="Expires" type="datetime-local" v={current?.exceptions[0]?.expires_at?.slice(0,16)} required={false}/><Field n="mitigation" l="Interim mitigation" v={current?.exceptions[0]?.mitigation} required={false}/></Group>
 <Group title="Linked product context (optional)"><Select n="link_kind" l="Link type" v={current?.links[0]?.kind??"roadmap_outcome"} options={["roadmap_outcome","documentation","preview","release_policy"]}/><Field n="link_id" l="Resource ID" v={current?.links[0]?.resource_id} required={false}/><Field n="link_label" l="Label" v={current?.links[0]?.label} required={false}/></Group><Button disabled={busy}>{busy?"Publishing…":selected?`Publish version ${selected.current_version+1}`:"Create commitment"}</Button></form></Card>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
 {selected&&current&&<Card className="p-5"><div className="flex flex-wrap gap-2"><h2 className="text-lg font-semibold">{current.title}</h2><Badge>version {selected.current_version}</Badge><Badge tone={selected.diagnostics.some(x=>x.severity==="blocking")?"danger":"success"}>{selected.diagnostics.length?`${selected.diagnostics.length} explicit gap(s)`:"coverage declared"}</Badge></div><p className="mt-2 text-sm text-[var(--muted)]">{current.subject.kind.replaceAll("_"," ")} · {current.subject.name} · owned by {current.owner_ids.join(", ")}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{selected.diagnostics.map((x,i)=><div className="rounded-lg border p-3" key={`${x.kind}-${i}`}><Badge tone={x.severity==="blocking"?"danger":"warning"}>{x.kind.replaceAll("_"," ")}</Badge><p className="mt-2 text-sm">{x.message}</p><p className="mt-1 text-xs text-[var(--muted)]">{x.resource_id} · attributed to {x.attributed_to}</p></div>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Version history</summary>{selected.revisions.map(x=><p className="mt-2 rounded-lg border p-3 text-sm" key={x.version}><strong>v{x.version}</strong> · {x.rationale} · {x.created_by} · {new Date(x.created_at).toLocaleString()}</p>)}</details></Card>}
 <section><h2 className="text-lg font-semibold">Repository commitments</h2><div className="mt-3 space-y-2">{items.map(x=>{const r=x.revisions.at(-1)!;return <button type="button" className="w-full rounded-xl border bg-white p-4 text-left hover:border-[var(--brand)]" key={x.id} onClick={()=>setSelected(x)}><span className="font-semibold">{r.title}</span><span className="block text-xs text-[var(--muted)]">{r.subject.name} · v{x.current_version} · {x.diagnostics.length} explicit state(s)</span></button>})}</div></section></div>
}
function Group({title,children}:{title:string;children:React.ReactNode}){return <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">{title}</legend>{children}</fieldset>}
function Field({n,l,v,type="text",required=true}:{n:string;l:string;v?:string;type?:string;required?:boolean}){return <label className="text-xs font-semibold">{l}<input key={v} name={n} type={type} required={required} defaultValue={v} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label>}
function Area({n,l,v}:{n:string;l:string;v?:string}){return <label className="text-xs font-semibold">{l}<textarea key={v} name={n} required rows={2} defaultValue={v} className="mt-1 w-full rounded-lg border p-3 font-normal"/></label>}
function Select({n,l,v,options}:{n:string;l:string;v:string;options:string[]}){return <label className="text-xs font-semibold">{l}<select name={n} defaultValue={v} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal">{options.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>}
