"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Check={id:string;name:string;category:string;outcome:string;summary:string;source_locations:string[];audience_ids:string[];journey_id?:string;requires_human:boolean;invalidated_at?:string};
type Finding={id:string;author_kind:string;author_id:string;title:string;detail:string;severity:string;audience_ids:string[];source_locations:string[];journey_ids:string[];uncertainty:string;requires_human:boolean;duplicate_of?:string;citations:{kind:string;resource_id:string;location?:string;evidence_ref:string}[];decision?:{classification:string;reason:string;actor_id:string};invalidated_at?:string};
type Assessment={id:string;revision:string;pull_request_id?:string;checks:Check[];findings:Finding[]};
const value=(f:FormData,n:string)=>String(f.get(n)??"").trim();
const list=(f:FormData,n:string)=>value(f,n).split(",").map(x=>x.trim()).filter(Boolean);
const tone=(x:string)=>x==="passed"||x==="accepted"?"success":x==="failed"||x==="critical"||x==="major"?"danger":x==="unevaluated"?"warning":"neutral";

export function AccessibilityAssessmentsWorkspace({repositoryID,revision,pullRequestID,participant=true}:{repositoryID:string;revision?:string;pullRequestID?:string;participant?:boolean}){
  const {token}=useAuth(),[items,setItems]=useState<Assessment[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!token)return;const query=new URLSearchParams();if(revision)query.set("revision",revision);if(pullRequestID)query.set("pull_request_id",pullRequestID);try{setItems((await api<{assessments:Assessment[]}>(`/repositories/${repositoryID}/accessibility-assessments?${query}`,{},token)).assessments);setError("")}catch(e){setError(e instanceof Error?e.message:"Accessibility evidence could not be loaded.")}},[pullRequestID,repositoryID,revision,token]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;setBusy(true);const f=new FormData(e.currentTarget);try{await api(`/repositories/${repositoryID}/accessibility-assessments`,{method:"POST",body:JSON.stringify({revision:value(f,"revision"),pull_request_id:value(f,"pull"),checks:[{name:value(f,"name"),category:value(f,"category"),outcome:value(f,"outcome"),journey_id:value(f,"journey"),source_locations:list(f,"sources"),audience_ids:list(f,"audiences"),summary:value(f,"summary"),evidence_ref:value(f,"evidence"),requires_human:f.get("human")==="on"}]})},token);e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Assessment could not be published.")}finally{setBusy(false)}}
  async function finding(e:FormEvent<HTMLFormElement>,assessment:Assessment){e.preventDefault();if(!token)return;const f=new FormData(e.currentTarget);try{await api(`/repositories/${repositoryID}/accessibility-assessments/${assessment.id}/findings`,{method:"POST",body:JSON.stringify({title:value(f,"title"),detail:value(f,"detail"),severity:value(f,"severity"),audience_ids:list(f,"audiences"),source_locations:list(f,"sources"),journey_ids:list(f,"journeys"),uncertainty:value(f,"uncertainty"),requires_human:f.get("human")==="on",duplicate_of:value(f,"duplicate"),citations:[{kind:value(f,"citation_kind"),resource_id:value(f,"resource"),revision:assessment.revision,location:value(f,"location"),evidence_ref:value(f,"evidence")}]})},token);e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Finding could not be added.")}}
  async function decide(assessment:string,finding:string,classification:string){if(!token)return;const reason=window.prompt(`Why is this finding ${classification.replace("_"," ")}?`);if(!reason)return;try{await api(`/repositories/${repositoryID}/accessibility-assessments/${assessment}/findings/${finding}/decision`,{method:"POST",body:JSON.stringify({classification,reason})},token);await load()}catch(x){setError(x instanceof Error?x.message:"Decision could not be recorded.")}}
  async function invalidate(e:FormEvent<HTMLFormElement>,assessment:string){e.preventDefault();if(!token)return;const f=new FormData(e.currentTarget);try{await api(`/repositories/${repositoryID}/accessibility-assessments/${assessment}/invalidate`,{method:"POST",body:JSON.stringify({source_locations:list(f,"changed_sources"),journey_ids:list(f,"changed_journeys")})},token);e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Affected evidence could not be invalidated.")}}
  return <section className="space-y-4" id="accessibility-assessments"><header><h2 className="text-xl font-semibold">Accessibility assessment</h2><p className="mt-1 max-w-3xl text-sm text-[var(--muted)]">Revision-exact automation shows what it covered. Cited human and read-only-agent findings retain lived experience, uncertainty, and the work still requiring human judgment.</p></header>
    {participant&&!pullRequestID&&<Card className="p-5"><form onSubmit={create} className="grid gap-3 md:grid-cols-3"><Field n="revision" l="Exact revision" v={revision}/><Field n="pull" l="Pull request ID (optional)" required={false}/><Field n="name" l="Check name"/><Select n="category" l="Coverage" options={["semantics","keyboard","focus","contrast","motion","captions","journey"]}/><Select n="outcome" l="Outcome" options={["passed","failed","unevaluated"]}/><Field n="journey" l="Declared journey ID" required={false}/><Field n="sources" l="Source locations"/><Field n="audiences" l="Affected audiences"/><Field n="summary" l="What automation proved"/><Field n="evidence" l="Evidence reference" required={false}/><label className="text-sm"><input name="human" type="checkbox"/> Requires human evaluation</label><div><Button disabled={busy}>{busy?"Publishing…":"Publish check evidence"}</Button></div></form></Card>}
    {error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
    {items.length===0&&<Card className="p-5 text-sm text-[var(--muted)]">No accessibility assessment is attached to this exact revision. Semantics, keyboard, focus, contrast, motion, captions, and declared journeys remain unevaluated.</Card>}
    {items.map(a=><Card className="p-5" key={a.id}><div className="flex flex-wrap gap-2"><Badge>{a.revision.slice(0,12)}</Badge>{a.pull_request_id&&<Badge>pull {a.pull_request_id}</Badge>}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{a.checks.map(c=><div key={c.id} className="rounded-lg border border-[var(--line)] p-3"><div className="flex flex-wrap gap-2"><Badge tone={tone(c.outcome)}>{c.invalidated_at?"invalidated":c.outcome}</Badge><strong>{c.name}</strong><Badge>{c.category}</Badge></div><p className="mt-2 text-sm">{c.summary}</p><p className="mt-1 text-xs text-[var(--muted)]">Audiences: {c.audience_ids.join(", ")} · Sources: {c.source_locations.join(", ")||"declared journey"}{c.requires_human?" · human evaluation required":""}</p></div>)}</div>
      <h3 className="mt-5 font-semibold">Cited findings</h3>{a.findings.length===0?<p className="mt-2 text-sm text-[var(--muted)]">No person or agent has added a cited finding.</p>:<div className="mt-2 space-y-3">{a.findings.map(f=><div className="rounded-lg border border-[var(--line)] p-3" key={f.id}><div className="flex flex-wrap gap-2"><Badge tone={tone(f.severity)}>{f.severity}</Badge><strong>{f.title}</strong><Badge>{f.author_kind}</Badge>{f.invalidated_at&&<Badge tone="warning">invalidated</Badge>}{f.duplicate_of&&<Badge>duplicate</Badge>}{f.decision&&<Badge tone={tone(f.decision.classification)}>{f.decision.classification.replace("_"," ")}</Badge>}</div><p className="mt-2 text-sm">{f.detail}</p><p className="mt-1 text-xs text-[var(--muted)]">Audiences: {f.audience_ids.join(", ")} · Sources: {f.source_locations.join(", ")||"journey evidence"} · Uncertainty: {f.uncertainty}{f.requires_human?" · human evaluation required":""}</p>{f.citations.map((c,i)=><p className="mt-1 break-all text-xs" key={i}>Citation: {c.kind} {c.resource_id}{c.location?` at ${c.location}`:""} · <code>{c.evidence_ref}</code></p>)}{f.decision&&<p className="mt-2 text-xs">Decision: {f.decision.reason}</p>}{participant&&!f.invalidated_at&&<div className="mt-2 flex gap-2"><Button variant="secondary" onClick={()=>void decide(a.id,f.id,"accepted")}>Accept</Button><Button variant="quiet" onClick={()=>void decide(a.id,f.id,"false_positive")}>False positive</Button></div>}</div>)}</div>}
      {participant&&<form onSubmit={e=>finding(e,a)} className="mt-5 grid gap-3 rounded-lg bg-[var(--surface-soft)] p-4 md:grid-cols-3"><Field n="title" l="Finding title"/><Field n="detail" l="Experienced behavior"/><Select n="severity" l="Severity" options={["critical","major","moderate","minor","note"]}/><Field n="audiences" l="Affected audiences"/><Field n="sources" l="Source locations" required={false}/><Field n="journeys" l="Journey IDs" required={false}/><Field n="uncertainty" l="Uncertainty and limits"/><Field n="duplicate" l="Duplicate finding ID" required={false}/><Select n="citation_kind" l="Evidence source" options={["preview","reproduction"]}/><Field n="resource" l="Preview or reproduction ID"/><Field n="location" l="Evidence location" required={false}/><Field n="evidence" l="Cited artifact reference"/><label className="text-sm"><input name="human" type="checkbox"/> Requires human evaluation</label><div><Button>Add cited finding</Button></div></form>}
      {participant&&<form onSubmit={e=>invalidate(e,a.id)} className="mt-3 grid gap-3 rounded-lg border border-[var(--line)] p-4 md:grid-cols-3"><Field n="changed_sources" l="Changed source locations" required={false}/><Field n="changed_journeys" l="Changed journey IDs" required={false}/><div><Button variant="secondary">Invalidate affected evidence</Button></div><p className="text-xs text-[var(--muted)] md:col-span-3">Exact names only; unrelated checks, findings, and acceptance remain current.</p></form>}
    </Card>)}</section>
}
function Field({n,l,v,required=true}:{n:string;l:string;v?:string;required?:boolean}){return <label className="text-sm font-semibold">{l}<input name={n} defaultValue={v} required={required} className="mt-1 w-full rounded-lg border border-[var(--line-strong)] bg-transparent p-2 font-normal"/></label>}
function Select({n,l,options}:{n:string;l:string;options:string[]}){return <label className="text-sm font-semibold">{l}<select name={n} className="mt-1 w-full rounded-lg border border-[var(--line-strong)] bg-transparent p-2 font-normal">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
