"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import Link from "next/link";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Check={id:string;name:string;category:string;outcome:string;summary:string;source_locations:string[];audience_ids:string[];journey_id?:string;requires_human:boolean;invalidated_at?:string};
type Repair={recovery_id:string;state:"pending"|"linked";proposal_id:string;task_id:string;base_revision:string;acceptance_criteria:string[];commitment_id:string;commitment_version:number;commitment_title:string;component_guidance:string[]};
type Finding={id:string;author_kind:string;author_id:string;title:string;detail:string;severity:string;audience_ids:string[];source_locations:string[];journey_ids:string[];uncertainty:string;requires_human:boolean;duplicate_of?:string;citations:{kind:string;resource_id:string;location?:string;evidence_ref:string}[];decision?:{classification:string;reason:string;actor_id:string};invalidated_at?:string;repair?:Repair};
type Assessment={id:string;revision:string;pull_request_id?:string;checks:Check[];findings:Finding[]};
type RepairProgress={task?:{status:string;contribution?:{pull_request_id:string;source_commit_id:string}};pull_request?:{id:string;status:string;source_commit_id:string};previews:{id:string;revision:string;state:string}[]};
const value=(f:FormData,n:string)=>String(f.get(n)??"").trim();
const list=(f:FormData,n:string)=>value(f,n).split(",").map(x=>x.trim()).filter(Boolean);
const tone=(x:string)=>x==="passed"||x==="accepted"?"success":x==="failed"||x==="critical"||x==="major"?"danger":x==="unevaluated"?"warning":"neutral";

export function AccessibilityAssessmentsWorkspace({repositoryID,revision,pullRequestID,participant=true}:{repositoryID:string;revision?:string;pullRequestID?:string;participant?:boolean}){
  const {token}=useAuth(),[items,setItems]=useState<Assessment[]>([]),[progress,setProgress]=useState<Record<string,RepairProgress>>({}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!token)return;const query=new URLSearchParams();if(revision)query.set("revision",revision);if(pullRequestID)query.set("pull_request_id",pullRequestID);try{const raw=(await api<{assessments:Assessment[]}>(`/repositories/${repositoryID}/accessibility-assessments?${query}`,{},token)).assessments;const assessments=raw.map(a=>({...a,checks:a.checks??[],findings:a.findings??[]}));setItems(assessments);const repairs=await Promise.all(assessments.flatMap(a=>a.findings.filter(f=>f.repair).map(async f=>[f.id,await api<RepairProgress>(`/repositories/${repositoryID}/accessibility-assessments/${a.id}/findings/${f.id}/repair`,{},token)] as const)));setProgress(Object.fromEntries(repairs));setError("")}catch(e){setError(e instanceof Error?e.message:"Accessibility evidence could not be loaded.")}},[pullRequestID,repositoryID,revision,token]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;setBusy(true);const f=new FormData(e.currentTarget);try{await api(`/repositories/${repositoryID}/accessibility-assessments`,{method:"POST",body:JSON.stringify({revision:value(f,"revision"),pull_request_id:value(f,"pull"),checks:[{name:value(f,"name"),category:value(f,"category"),outcome:value(f,"outcome"),journey_id:value(f,"journey"),source_locations:list(f,"sources"),audience_ids:list(f,"audiences"),summary:value(f,"summary"),evidence_ref:value(f,"evidence"),requires_human:f.get("human")==="on"}]})},token);e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Assessment could not be published.")}finally{setBusy(false)}}
  async function finding(e:FormEvent<HTMLFormElement>,assessment:Assessment){e.preventDefault();if(!token)return;const f=new FormData(e.currentTarget);try{await api(`/repositories/${repositoryID}/accessibility-assessments/${assessment.id}/findings`,{method:"POST",body:JSON.stringify({title:value(f,"title"),detail:value(f,"detail"),severity:value(f,"severity"),audience_ids:list(f,"audiences"),source_locations:list(f,"sources"),journey_ids:list(f,"journeys"),uncertainty:value(f,"uncertainty"),requires_human:f.get("human")==="on",duplicate_of:value(f,"duplicate"),citations:[{kind:value(f,"citation_kind"),resource_id:value(f,"resource"),revision:assessment.revision,location:value(f,"location"),evidence_ref:value(f,"evidence")}]})},token);e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Finding could not be added.")}}
  async function decide(assessment:string,finding:string,classification:string){if(!token)return;const reason=window.prompt(`Why is this finding ${classification.replace("_"," ")}?`);if(!reason)return;try{await api(`/repositories/${repositoryID}/accessibility-assessments/${assessment}/findings/${finding}/decision`,{method:"POST",body:JSON.stringify({classification,reason})},token);await load()}catch(x){setError(x instanceof Error?x.message:"Decision could not be recorded.")}}
  async function invalidate(e:FormEvent<HTMLFormElement>,assessment:string){e.preventDefault();if(!token)return;const f=new FormData(e.currentTarget);try{await api(`/repositories/${repositoryID}/accessibility-assessments/${assessment}/invalidate`,{method:"POST",body:JSON.stringify({source_locations:list(f,"changed_sources"),journey_ids:list(f,"changed_journeys")})},token);e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Affected evidence could not be invalidated.")}}
  async function repair(e:FormEvent<HTMLFormElement>,assessment:string,finding:string){e.preventDefault();if(!token)return;const form=e.currentTarget,f=new FormData(form);setBusy(true);try{await api(`/repositories/${repositoryID}/accessibility-assessments/${assessment}/findings/${finding}/repair`,{method:"POST",body:JSON.stringify({commitment_id:value(f,"commitment"),commitment_version:Number(value(f,"commitment_version")),acceptance_criteria:list(f,"criteria"),component_guidance:list(f,"guidance"),assignee_type:value(f,"assignee_type"),assignee_id:value(f,"assignee")})},token);form.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Governed repair could not be created.")}finally{setBusy(false)}}
  return <section className="space-y-4" id="accessibility-assessments"><header><h2 className="text-xl font-semibold">Accessibility assessment</h2><p className="mt-1 max-w-3xl text-sm text-[var(--muted)]">Revision-exact automation shows what it covered. Cited human and read-only-agent findings retain lived experience, uncertainty, and the work still requiring human judgment.</p></header>
    {participant&&!pullRequestID&&<Card className="p-5"><form onSubmit={create} className="grid gap-3 md:grid-cols-3"><Field n="revision" l="Exact revision" v={revision}/><Field n="pull" l="Pull request ID (optional)" required={false}/><Field n="name" l="Check name"/><Select n="category" l="Coverage" options={["semantics","keyboard","focus","contrast","motion","captions","journey"]}/><Select n="outcome" l="Outcome" options={["passed","failed","unevaluated"]}/><Field n="journey" l="Declared journey ID" required={false}/><Field n="sources" l="Source locations"/><Field n="audiences" l="Affected audiences"/><Field n="summary" l="What automation proved"/><Field n="evidence" l="Evidence reference" required={false}/><label className="text-sm"><input name="human" type="checkbox"/> Requires human evaluation</label><div><Button disabled={busy}>{busy?"Publishing…":"Publish check evidence"}</Button></div></form></Card>}
    {error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
    {items.length===0&&<Card className="p-5 text-sm text-[var(--muted)]">No accessibility assessment is attached to this exact revision. Semantics, keyboard, focus, contrast, motion, captions, and declared journeys remain unevaluated.</Card>}
    {items.map(a=><Card className="p-5" key={a.id}><div className="flex flex-wrap gap-2"><Badge>{a.revision.slice(0,12)}</Badge>{a.pull_request_id&&<Badge>pull {a.pull_request_id}</Badge>}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{a.checks.map(c=><div key={c.id} className="rounded-lg border border-[var(--line)] p-3"><div className="flex flex-wrap gap-2"><Badge tone={tone(c.outcome)}>{c.invalidated_at?"invalidated":c.outcome}</Badge><strong>{c.name}</strong><Badge>{c.category}</Badge></div><p className="mt-2 text-sm">{c.summary}</p><p className="mt-1 text-xs text-[var(--muted)]">Audiences: {c.audience_ids.join(", ")} · Sources: {c.source_locations.join(", ")||"declared journey"}{c.requires_human?" · human evaluation required":""}</p></div>)}</div>
      <h3 className="mt-5 font-semibold">Cited findings</h3>{a.findings.length===0?<p className="mt-2 text-sm text-[var(--muted)]">No person or agent has added a cited finding.</p>:<div className="mt-2 space-y-3">{a.findings.map(f=><div className="rounded-lg border border-[var(--line)] p-3" key={f.id}><div className="flex flex-wrap gap-2"><Badge tone={tone(f.severity)}>{f.severity}</Badge><strong>{f.title}</strong><Badge>{f.author_kind}</Badge>{f.invalidated_at&&<Badge tone="warning">invalidated</Badge>}{f.duplicate_of&&<Badge>duplicate</Badge>}{f.decision&&<Badge tone={tone(f.decision.classification)}>{f.decision.classification.replace("_"," ")}</Badge>}</div><p className="mt-2 text-sm">{f.detail}</p><p className="mt-1 text-xs text-[var(--muted)]">Audiences: {f.audience_ids.join(", ")} · Sources: {f.source_locations.join(", ")||"journey evidence"} · Uncertainty: {f.uncertainty}{f.requires_human?" · human evaluation required":""}</p>{f.citations.map((c,i)=><p className="mt-1 break-all text-xs" key={i}>Citation: {c.kind} {c.resource_id}{c.location?` at ${c.location}`:""} · <code>{c.evidence_ref}</code></p>)}{f.decision&&<p className="mt-2 text-xs">Decision: {f.decision.reason}</p>}{participant&&!f.invalidated_at&&<div className="mt-2 flex gap-2"><Button variant="secondary" onClick={()=>void decide(a.id,f.id,"accepted")}>Accept</Button><Button variant="quiet" onClick={()=>void decide(a.id,f.id,"false_positive")}>False positive</Button></div>}
        {f.repair?<div className="mt-3 rounded-lg bg-[var(--surface-soft)] p-3 text-sm"><div className="flex flex-wrap items-center gap-2"><Badge tone={progress[f.id]?.pull_request?.status==="merged"?"success":f.repair.state==="pending"?"warning":"neutral"}>{f.repair.state==="pending"?"link recovery pending":progress[f.id]?.task?.status??"planned"}</Badge>{f.repair.state==="linked"&&<Link className="font-semibold underline" href={`/proposals/${repositoryID}/${f.repair.proposal_id}`}>Inspect repair plan</Link>}{progress[f.id]?.pull_request&&<Link className="underline" href={`/pulls/${repositoryID}/${progress[f.id].pull_request?.id}`}>Pull request</Link>}</div><p className="mt-2">Frozen at <code>{f.repair.base_revision.slice(0,12)}</code> against {f.repair.commitment_title} v{f.repair.commitment_version}. {progress[f.id]?.previews.length??0} exact-revision preview(s) attached.</p>{f.repair.state==="pending"&&<p className="mt-1 text-xs text-[var(--warning)]">Retry the exact repair request to complete recovery <code>{f.repair.recovery_id}</code>.</p>}<p className="mt-1 text-xs text-[var(--muted)]">Acceptance: {f.repair.acceptance_criteria.join(" · ")} · Guidance: {f.repair.component_guidance.join(" · ")}</p></div>:participant&&f.decision?.classification==="accepted"&&!f.invalidated_at&&<form onSubmit={e=>repair(e,a.id,f.id)} className="mt-3 grid gap-3 rounded-lg bg-[var(--surface-soft)] p-3 md:grid-cols-3"><Field n="commitment" l="Accessibility commitment ID"/><Field n="commitment_version" l="Commitment version"/><Field n="criteria" l="Acceptance criteria (comma separated)"/><Field n="guidance" l="Component guidance (comma separated)"/><Select n="assignee_type" l="Owner type" options={["human","agent"]}/><Field n="assignee" l="Owner ID (blank uses you)" required={false}/><div><Button disabled={busy}>{busy?"Creating…":"Create governed repair"}</Button></div><p className="text-xs text-[var(--muted)] md:col-span-3">The task freezes only permitted evidence and does not attribute implementation claims to the affected user. Existing repository and agent permissions still apply.</p></form>}
      </div>)}</div>}
      {participant&&<form onSubmit={e=>finding(e,a)} className="mt-5 grid gap-3 rounded-lg bg-[var(--surface-soft)] p-4 md:grid-cols-3"><Field n="title" l="Finding title"/><Field n="detail" l="Experienced behavior"/><Select n="severity" l="Severity" options={["critical","major","moderate","minor","note"]}/><Field n="audiences" l="Affected audiences"/><Field n="sources" l="Source locations" required={false}/><Field n="journeys" l="Journey IDs" required={false}/><Field n="uncertainty" l="Uncertainty and limits"/><Field n="duplicate" l="Duplicate finding ID" required={false}/><Select n="citation_kind" l="Evidence source" options={["preview","reproduction"]}/><Field n="resource" l="Preview or reproduction ID"/><Field n="location" l="Evidence location" required={false}/><Field n="evidence" l="Cited artifact reference"/><label className="text-sm"><input name="human" type="checkbox"/> Requires human evaluation</label><div><Button>Add cited finding</Button></div></form>}
      {participant&&<form onSubmit={e=>invalidate(e,a.id)} className="mt-3 grid gap-3 rounded-lg border border-[var(--line)] p-4 md:grid-cols-3"><Field n="changed_sources" l="Changed source locations" required={false}/><Field n="changed_journeys" l="Changed journey IDs" required={false}/><div><Button variant="secondary">Invalidate affected evidence</Button></div><p className="text-xs text-[var(--muted)] md:col-span-3">Exact names only; unrelated checks, findings, and acceptance remain current.</p></form>}
    </Card>)}</section>
}
function Field({n,l,v,required=true}:{n:string;l:string;v?:string;required?:boolean}){return <label className="text-sm font-semibold">{l}<input name={n} defaultValue={v} required={required} className="mt-1 w-full rounded-lg border border-[var(--line-strong)] bg-transparent p-2 font-normal"/></label>}
function Select({n,l,options}:{n:string;l:string;options:string[]}){return <label className="text-sm font-semibold">{l}<select name={n} className="mt-1 w-full rounded-lg border border-[var(--line-strong)] bg-transparent p-2 font-normal">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
