"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { AccessGate, useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Evidence={id:string;dimension:string;summary:string;reference:string;observed_version?:string;resolution:"resolved"|"stale"|"missing"|"inaccessible";detail?:string};
type Candidate={id:string;name:string;provider:string;version:string;fit_status:string;gaps:string[];evidence:Evidence[]};
type Workspace={id:string;version:number;title:string;outcome:string;source:{kind:string;label:string;resolution:string;detail?:string};required_journeys:string[];environments:string[];constraints:string[];budget_cents:number;currency:string;owners:{principal_id:string;responsibility:string}[];evaluation_criteria:{id:string;name:string;requirement:string;weight:number;owner_id:string}[];candidates:Candidate[];invitations:{id:string;principal_id:string;role:string;access:string;status:string}[]};
const lines=(v:FormDataEntryValue|null)=>String(v??"").split("\n").map(x=>x.trim()).filter(Boolean);
const tone=(v:string)=>v==="resolved"?"success":v==="stale"?"warning":"danger" as const;

export function AdoptionWorkspace(){
 const {user,token}=useAuth();const [items,setItems]=useState<Workspace[]>([]);const [current,setCurrent]=useState<Workspace|null>(null);const [creating,setCreating]=useState(false);const [pending,setPending]=useState(false);const [error,setError]=useState("");
 const load=useCallback(async()=>{if(!token)return;try{const r=await api<{adoption_workspaces:Workspace[]}>("/adoption-workspaces",{},token);setItems(r.adoption_workspaces);setCurrent(x=>x?r.adoption_workspaces.find(v=>v.id===x.id)??null:null)}catch(e){setError(e instanceof Error?e.message:"Unable to load adoption workspaces.")}},[token]);
 useEffect(()=>{void Promise.resolve().then(load)},[load]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!user)return;setPending(true);setError("");const f=new FormData(e.currentTarget);const sourceKind=String(f.get("source_kind"));const version=String(f.get("candidate_version"));try{const x=await api<Workspace>("/adoption-workspaces",{method:"POST",body:JSON.stringify({title:f.get("title"),outcome:f.get("outcome"),source:{kind:sourceKind,label:f.get("source_label"),repository_id:sourceKind==="federated_repository"?undefined:f.get("repository_id"),resource_id:f.get("resource_id")},required_journeys:lines(f.get("journeys")),environments:lines(f.get("environments")),constraints:lines(f.get("constraints")),budget_cents:Number(f.get("budget_cents")),currency:f.get("currency"),owners:[{principal_id:user.id,responsibility:f.get("responsibility")}],evaluation_criteria:lines(f.get("criteria")).map((v,i)=>{const [name,requirement,weight]=v.split("|").map(s=>s.trim());return{name,requirement,weight:Number(weight||100/(i+1)),owner_id:user.id}}),candidates:[{name:f.get("candidate_name"),provider:f.get("provider"),version,source_kind:f.get("candidate_source_kind"),source_reference:f.get("candidate_source"),evidence:lines(f.get("evidence")).map(v=>{const [dimension,summary,reference,observed_version,visibility]=v.split("|").map(s=>s.trim());return{dimension,summary,reference,observed_version:observed_version||version,visibility:visibility||"participants"}})}],invitations:lines(f.get("invitees")).map(v=>{const [principal_id,role]=v.split("|").map(s=>s.trim());return{principal_type:"human",principal_id,role:role||"affected_user"}})})},token);setItems(v=>[x,...v]);setCurrent(x);setCreating(false)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to open adoption workspace.")}finally{setPending(false)}}
 return <AccessGate><div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--brand)]">Shared fit evaluation</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Software adoption</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Compare exact candidates against real journeys and inspectable evidence. Missing, restricted, and stale material remains a gap—not proof of fit.</p></div><Button onClick={()=>setCreating(v=>!v)}>{creating?"Close":"Open workspace"}</Button></header>{error&&<p role="alert" className="rounded-lg bg-[var(--danger-soft)] p-3 text-sm text-[var(--danger)]">{error}</p>}
 {creating&&<Card className="p-5"><h2 className="font-semibold">Define the adoption question</h2><form onSubmit={create} className="mt-4 grid gap-4 lg:grid-cols-2"><Field name="title" label="Workspace title" placeholder="Adopt the event router"/><Field name="outcome" label="Outcome" placeholder="Reduce delivery latency without losing auditability"/><Select name="source_kind" label="Starting context" options={["roadmap_outcome","support_gap","incubator","decision","package","api","federated_repository"]}/><Field name="source_label" label="Source label" placeholder="Reliable delivery outcome"/><Field name="repository_id" label="Source repository ID"/><Field name="resource_id" label="Source resource or federation reference"/><Area name="journeys" label="Required journeys" placeholder="Publish and replay an event"/><Area name="environments" label="Environments" placeholder="Linux amd64\nStaging Kubernetes"/><Area name="constraints" label="Constraints" placeholder="Apache-2.0 compatible\nNo customer payload retention"/><div className="grid grid-cols-2 gap-3"><Field name="budget_cents" label="Budget (minor units)" type="number" defaultValue="100000"/><Field name="currency" label="Currency" defaultValue="USD"/></div><Field name="responsibility" label="Your ownership" placeholder="Adoption decision and budget"/><Area name="criteria" label="Evaluation criteria" placeholder="Delivery fit | Completes the required journey | 50\nOperating fit | Fits the declared budget | 50"/><Field name="candidate_name" label="Candidate" placeholder="Relay"/><Field name="provider" label="Provider" placeholder="Relay maintainers"/><Field name="candidate_version" label="Exact candidate version" placeholder="2.4.1"/><Select name="candidate_source_kind" label="Candidate source" options={["package","api","repository","federated_repository"]}/><Field name="candidate_source" label="Candidate reference" placeholder="https://provider.example/releases/2.4.1"/><Area name="evidence" label="Evidence comparisons" hint="dimension | summary | HTTPS reference | observed version | visibility" placeholder="capabilities | Declares ordered delivery | https://example.test/capabilities | 2.4.1 | public\nknown_gaps | Windows support is experimental | https://example.test/gaps | 2.3.0 | participants"/><Area name="invitees" label="Provider maintainers and affected users" hint="user ID | provider_maintainer or affected_user"/><div className="lg:col-span-2"><Button type="submit" disabled={pending}>{pending?"Resolving evidence…":"Open evaluation"}</Button></div></form></Card>}
 <div className="grid gap-5 xl:grid-cols-[20rem_minmax(0,1fr)]"><Card className="p-3"><h2 className="px-2 py-2 text-sm font-semibold">Evaluations</h2>{items.length===0?<p className="px-2 pb-3 text-sm text-[var(--muted)]">No shared evaluations yet.</p>:items.map(x=><button key={x.id} onClick={()=>setCurrent(x)} className={`mb-1 w-full rounded-lg p-3 text-left ${current?.id===x.id?"bg-[var(--brand-soft)]":"hover:bg-black/[.035]"}`}><span className="block text-sm font-semibold">{x.title}</span><span className="mt-1 block text-xs text-[var(--muted)]">{x.candidates.length} exact candidate{x.candidates.length===1?"":"s"}</span></button>)}</Card>
 <div>{current?<div className="space-y-5"><Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge tone={current.source.resolution==="resolved"?"success":"warning"}>{current.source.resolution}</Badge><h2 className="mt-3 text-xl font-semibold">{current.title}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{current.outcome}</p></div><p className="text-sm font-semibold">{current.currency} {(current.budget_cents/100).toLocaleString()}</p></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><Summary label="Journeys" values={current.required_journeys}/><Summary label="Environments" values={current.environments}/><Summary label="Constraints" values={current.constraints}/></div></Card>{current.candidates.map(c=><Card key={c.id} className="p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{c.name} <span className="font-mono text-sm text-[var(--muted)]">{c.version}</span></h3><p className="text-sm text-[var(--muted)]">{c.provider}</p></div><Badge tone={c.fit_status==="evidence_complete"?"success":"warning"}>{c.fit_status.replaceAll("_"," ")}</Badge></div><div className="mt-4 grid gap-3 md:grid-cols-2">{c.evidence.map(v=><div key={v.id} className="rounded-lg border border-[var(--line)] p-3"><div className="flex justify-between gap-2"><strong className="text-sm capitalize">{v.dimension.replaceAll("_"," ")}</strong><Badge tone={tone(v.resolution)}>{v.resolution}</Badge></div><p className="mt-2 text-sm">{v.summary}</p><p className="mt-1 text-xs text-[var(--muted)]">{v.detail}</p></div>)}</div>{c.gaps.length>0&&<div className="mt-4 rounded-lg bg-[var(--warning-soft)] p-3"><strong className="text-sm text-[var(--warning)]">Evidence gaps</strong><ul className="mt-2 list-disc pl-5 text-sm text-[var(--muted)]">{c.gaps.map(g=><li key={g}>{g}</li>)}</ul></div>}</Card>)}<Card className="p-5"><h3 className="font-semibold">Permission-aware participants</h3><div className="mt-3 flex flex-wrap gap-2"><Badge tone="info">owner · {current.owners[0]?.principal_id}</Badge>{current.invitations.map(v=><Badge key={v.id} tone={v.status==="accepted"?"success":"neutral"}>{v.role} · {v.access} · {v.status}</Badge>)}</div></Card></div>:<Card className="grid min-h-64 place-items-center p-8 text-center text-sm text-[var(--muted)]">Select an evaluation to inspect requirements and evidence.</Card>}</div></div></div></AccessGate>
}
function Field({label,...props}:{label:string;name:string;hint?:string}&React.InputHTMLAttributes<HTMLInputElement>){const hint=props.hint;delete props.hint;return <label className="grid gap-1.5 text-sm font-medium">{label}<input required className="min-h-10 rounded-lg border border-[var(--line-strong)] bg-white px-3 font-normal" {...props}/>{hint&&<span className="text-xs font-normal text-[var(--muted)]">{hint}</span>}</label>}
function Area({label,hint,...props}:{label:string;name:string;hint?:string}&React.TextareaHTMLAttributes<HTMLTextAreaElement>){return <label className="grid gap-1.5 text-sm font-medium">{label}<textarea required rows={3} className="rounded-lg border border-[var(--line-strong)] bg-white p-3 font-normal" {...props}/>{hint&&<span className="text-xs font-normal text-[var(--muted)]">{hint}</span>}</label>}
function Select({label,options,...props}:{label:string;name:string;options:string[]}){return <label className="grid gap-1.5 text-sm font-medium">{label}<select className="min-h-10 rounded-lg border border-[var(--line-strong)] bg-white px-3 font-normal" {...props}>{options.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>}
function Summary({label,values}:{label:string;values:string[]}){return <div><h3 className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">{label}</h3><ul className="mt-2 space-y-1 text-sm">{values.map(x=><li key={x}>{x}</li>)}</ul></div>}
