"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Revision = { version:number; title:string; purpose:string; owner_ids:string[]; sources:{id:string;kind:string;repository_id:string;revision:string;path:string;purpose:string}[]; tools:{name:string;purpose:string;actions:string[];boundary:string}[]; models:{provider:string;name:string;version:string;purpose:string}[]; supported_tasks:string[]; expected_outputs:string[]; prohibited_actions:string[]; memory_policy:string; data_use_terms:string; guarantees:string[]; budget:{max_cost_usd:number;max_tokens:number;max_tool_actions:number;max_runtime_seconds:number}; escalations:{trigger:string;owner_ids:string[];action:string}[]; deployment_boundaries:{environment:string;repository_access:string;network_access:string;data_classes:string[];approval_required:boolean}[]; change_summary:string; created_by:string; created_at:string };
type Project = { id:string; current_version:number; revisions:Revision[]; diagnostics:{kind:string;severity:string;message:string;source_id?:string;attributed_to:string}[]; effective_capability:{tasks:string[];tools:string[];stops:string[];human_escalation_required:boolean} };
const text=(f:FormData,n:string)=>String(f.get(n)||"").trim();
const list=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);
function Field({name,label,placeholder=""}:{name:string;label:string;placeholder?:string}){return <label className="text-sm font-medium">{label}<input required name={name} placeholder={placeholder} className="mt-1 w-full rounded-lg border bg-transparent p-2.5"/></label>}

export function AgentProjectsWorkspace({repositoryID}:{repositoryID:string}){
 const {token,user,loading}=useAuth(),[projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState<Project|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{if(loading||!token)return;try{const x=await api<{projects:Project[]}>(`/repositories/${repositoryID}/agent-projects`,{},token);setProjects(x.projects);setSelected(s=>x.projects.find(p=>p.id===s?.id)??x.projects[0]??null);setError("")}catch(e){setError(e instanceof Error?e.message:"Agent projects could not be loaded.")}},[loading,repositoryID,token]);
 useEffect(()=>{void Promise.resolve().then(load)},[load]);
 async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),owner=text(f,"owner")||user?.id||"",sourceRepo=text(f,"source_repo")||repositoryID;const revision={title:text(f,"title"),purpose:text(f,"purpose"),owner_ids:list(owner),sources:[{id:"prompt",kind:"prompt",repository_id:sourceRepo,revision:text(f,"revision"),path:text(f,"path"),purpose:"Reviewed operating prompt and instructions"}],tools:[{name:text(f,"tool"),purpose:text(f,"tool_purpose"),actions:list(text(f,"actions")),boundary:text(f,"tool_boundary")}],models:[{provider:text(f,"provider"),name:text(f,"model"),version:text(f,"model_version"),purpose:"Primary reasoning model"}],supported_tasks:list(text(f,"tasks")),expected_outputs:list(text(f,"outputs")),prohibited_actions:list(text(f,"prohibited")),memory_policy:text(f,"memory"),data_use_terms:text(f,"data_terms"),guarantees:list(text(f,"guarantees")),budget:{max_cost_usd:Number(text(f,"cost")),max_tokens:Number(text(f,"tokens")),max_tool_actions:Number(text(f,"tool_actions")),max_runtime_seconds:Number(text(f,"runtime"))},escalations:[{trigger:text(f,"escalation_trigger"),owner_ids:list(owner),action:text(f,"escalation_action")}],deployment_boundaries:[{environment:text(f,"environment"),repository_access:text(f,"repository_access"),network_access:text(f,"network_access"),data_classes:list(text(f,"data_classes")),approval_required:true}],change_summary:text(f,"change_summary")};try{const url=selected?`/repositories/${repositoryID}/agent-projects/${selected.id}/revisions`:`/repositories/${repositoryID}/agent-projects`;await api(url,{method:"POST",body:JSON.stringify({expected_version:selected?.current_version??0,revision})},token);e.currentTarget.reset();await load()}catch(reason){setError(reason instanceof Error?reason.message:"Agent project could not be published.")}}
 const current=selected?.revisions.at(-1);
 return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--brand)]">Agent project</p><h1 className="mt-1 text-2xl font-bold">Review intent before granting access</h1><p className="mt-2 text-sm text-[var(--muted)]">Versioned prompts, context, capabilities, limits, ownership, and escalation remain inspectable project state. A project definition grants no agent, Git, tool, deployment, or data authority.</p></header>{error&&<p role="alert" className="rounded-lg bg-[var(--danger-soft)] p-3 text-sm text-[var(--danger)]">{error}</p>}
 <div className="flex flex-wrap gap-2">{projects.map(p=><Button key={p.id} variant={selected?.id===p.id?"primary":"secondary"} onClick={()=>setSelected(p)}>{p.revisions.at(-1)?.title} · v{p.current_version}</Button>)}<Button variant="secondary" onClick={()=>setSelected(null)}>New project</Button></div>
 {current&&selected&&<Card className="space-y-5 p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{current.title}</h2><p className="mt-1 text-sm text-[var(--muted)]">{current.purpose}</p></div><Badge tone={selected.diagnostics.some(d=>d.severity==="blocking")?"danger":"success"}>{selected.diagnostics.length?`${selected.diagnostics.length} review notices`:"reviewable"}</Badge></div>
 <section><h3 className="font-semibold">Effective capability</h3><p className="mt-1 text-sm">Tasks: {selected.effective_capability.tasks.join(", ")} · Tools: {selected.effective_capability.tools.join("; ")||"none"}</p><p className="mt-1 text-sm text-[var(--danger)]">Must stop: {selected.effective_capability.stops.join(", ")}</p></section>
 <div className="grid gap-4 md:grid-cols-2"><section><h3 className="font-semibold">Provenance</h3>{current.sources.map(s=><p key={s.id} className="mt-1 break-all text-xs"><Badge>{s.kind}</Badge> {s.repository_id}@{s.revision}:{s.path} — {s.purpose}</p>)}</section><section><h3 className="font-semibold">Models, memory, and data</h3><p className="text-sm">{current.models.map(m=>`${m.provider}/${m.name}@${m.version}`).join(", ")}</p><p className="mt-1 text-sm">Memory: {current.memory_policy}</p><p className="mt-1 text-sm">Data: {current.data_use_terms}</p></section><section><h3 className="font-semibold">Deployment boundary</h3>{current.deployment_boundaries.map((b,i)=><p key={i} className="text-sm">{b.environment}: repository {b.repository_access}; network {b.network_access}; human approval required</p>)}</section><section><h3 className="font-semibold">Budget and escalation</h3><p className="text-sm">${current.budget.max_cost_usd} · {current.budget.max_tokens} tokens · {current.budget.max_tool_actions} actions · {current.budget.max_runtime_seconds}s</p>{current.escalations.map((x,i)=><p key={i} className="mt-1 text-sm">When {x.trigger}: {x.action} ({x.owner_ids.join(", ")||"missing owner"})</p>)}</section></div>
 {selected.diagnostics.map((d,i)=><p key={i} className="rounded-lg border p-3 text-sm"><Badge tone={d.severity==="blocking"?"danger":"warning"}>{d.kind}</Badge> {d.message} <span className="text-[var(--muted)]">Attributed to {d.attributed_to}</span></p>)}<details><summary className="cursor-pointer font-semibold">Change history</summary>{selected.revisions.map(r=><p key={r.version} className="mt-2 text-sm">v{r.version} · {r.change_summary} · {r.created_by} · {new Date(r.created_at).toLocaleString()}</p>)}</details></Card>}
 <Card className="p-6"><h2 className="font-semibold">{selected?"Publish successor revision":"Define an agent project"}</h2><form onSubmit={publish} className="mt-4 grid gap-3 md:grid-cols-2"><Field name="title" label="Project title"/><Field name="purpose" label="Intended purpose"/><Field name="owner" label="Owner IDs" placeholder={user?.id}/><Field name="source_repo" label="Source repository ID" placeholder={repositoryID}/><Field name="revision" label="Exact 40-character revision"/><Field name="path" label="Reviewed prompt/instructions path"/><Field name="tool" label="Tool"/><Field name="tool_purpose" label="Tool purpose"/><Field name="actions" label="Permitted tool actions (comma-separated)"/><Field name="tool_boundary" label="Tool boundary"/><Field name="provider" label="Model provider"/><Field name="model" label="Model name"/><Field name="model_version" label="Model version"/><Field name="tasks" label="Supported tasks"/><Field name="outputs" label="Expected outputs"/><Field name="prohibited" label="Prohibited actions"/><Field name="memory" label="Memory policy"/><Field name="data_terms" label="Data-use terms"/><Field name="guarantees" label="Claimed guarantees"/><Field name="environment" label="Deployment environment"/><Field name="repository_access" label="Repository boundary"/><Field name="network_access" label="Network boundary"/><Field name="data_classes" label="Permitted data classes"/><Field name="escalation_trigger" label="Human escalation trigger"/><Field name="escalation_action" label="Escalation action"/><Field name="cost" label="Maximum cost USD"/><Field name="tokens" label="Maximum tokens"/><Field name="tool_actions" label="Maximum tool actions"/><Field name="runtime" label="Maximum runtime seconds"/><Field name="change_summary" label="Change summary"/><div className="md:col-span-2"><Button type="submit">Publish immutable revision</Button></div></form></Card></div>
}
