"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { useAuth } from "@/components/auth";
import { Badge, Button, Card } from "@/components/ui";

type Event={id:string;kind:string;actor_id:string;body:string;status?:string;created_at:string};
type Assessment={id:string;title:string;owner_id:string;assessor:{user_id:string;kind:string;organization?:string;conflict_disclosure:string;conflict_status:string};scope:{control_ids:string[];system_ids:string[];release_ids:string[];period_starts_at:string;period_ends_at:string};status:string;version:number;expires_at:string;events:Event[]};
const value=(f:FormData,n:string)=>String(f.get(n)||"").trim();
const list=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);

export function AssuranceAssessments({repositoryID,programID,programVersion,controlID}:{repositoryID:string;programID?:string;programVersion?:number;controlID?:string}){
  const {token,user}=useAuth(),[items,setItems]=useState<Assessment[]>([]),[error,setError]=useState("");
  const load=useCallback(async()=>{if(!token)return;try{const out=await api<{assessments:Assessment[]}>(`/repositories/${repositoryID}/assurance-assessments`,{},token);setItems(out.assessments);setError("")}catch(e){setError(e instanceof Error?e.message:"Assessments could not be loaded.")}},[repositoryID,token]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/repositories/${repositoryID}/assurance-assessments`,{method:"POST",body:JSON.stringify({program_id:value(f,"program"),program_version:Number(value(f,"version")),title:value(f,"title"),assessor:{user_id:value(f,"assessor"),kind:value(f,"kind"),organization:value(f,"organization"),conflict_disclosure:value(f,"conflict")},scope:{control_ids:list(value(f,"controls")),system_ids:list(value(f,"systems")),release_ids:list(value(f,"releases")),period_starts_at:new Date(value(f,"period_start")).toISOString(),period_ends_at:new Date(value(f,"period_end")).toISOString()},evidence_package_ids:list(value(f,"packages")),starts_at:new Date(value(f,"starts")).toISOString(),expires_at:new Date(value(f,"expires")).toISOString()})},token);await load()}catch(x){setError(x instanceof Error?x.message:"Assessment could not be opened.")}}
  async function append(e:FormEvent<HTMLFormElement>,a:Assessment){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/repositories/${repositoryID}/assurance-assessments/${a.id}/events`,{method:"POST",body:JSON.stringify({expected_version:a.version,kind:value(f,"kind"),body:value(f,"body"),status:value(f,"status"),parent_id:value(f,"parent"),control_id:value(f,"control"),evidence_package_ids:list(value(f,"evidence"))})},token);e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Assessment event could not be recorded.")}}
  return <section className="space-y-4" aria-labelledby="assessment-heading"><div><h2 id="assessment-heading" className="text-xl font-semibold">Independent assessments</h2><p className="mt-1 text-sm text-[var(--muted)]">Invite an identified reviewer into an expiring, explicitly selected evidence view. This workspace grants no code, production, delivery, or project mutation authority.</p></div>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
    <div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-4">{items.length===0?<Card className="p-5 text-sm text-[var(--muted)]">No assessment is visible to this account.</Card>:items.map(a=><Card key={a.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">{a.title}</h3><p className="text-xs text-[var(--muted)]">{a.assessor.kind} assessor · access ends {new Date(a.expires_at).toLocaleString()}</p></div><Badge tone={a.status==="open"?"success":"warning"}>{a.status.replaceAll("_"," ")}</Badge></div><p className="mt-3 text-sm">Controls: {a.scope.control_ids.join(", ")} · conflict: {a.assessor.conflict_status}</p>{a.events.map(x=><article key={x.id} className="mt-3 border-l-2 pl-3 text-sm"><strong>{x.kind.replaceAll("_"," ")}</strong> · {x.actor_id===user?.id?"you":x.actor_id}<p className="mt-1 text-[var(--muted)]">{x.body}</p></article>)}
      <form onSubmit={e=>append(e,a)} className="mt-4 grid gap-2 sm:grid-cols-2"><label className="text-sm">Action<select name="kind" className="mt-1 w-full rounded-lg border bg-transparent p-2">{(a.owner_id===user?.id?["response","sample_response","walkthrough_response","finding_response","disagreement","resolution","appeal","appeal_decision","scope_change","conflict_resolution","close"]:["question","sample_request","walkthrough_request","attestation_verification","finding","disagreement","resolution","appeal","scope_acknowledgement"]).map(k=><option key={k}>{k}</option>)}</select></label><label className="text-sm">Control ID<input name="control" className="mt-1 w-full rounded-lg border bg-transparent p-2"/></label><label className="text-sm sm:col-span-2">Statement<textarea name="body" required className="mt-1 min-h-20 w-full rounded-lg border bg-transparent p-2"/></label><input name="parent" placeholder="Prior event ID (for response or appeal)" className="rounded-lg border bg-transparent p-2 text-sm"/><input name="evidence" placeholder="Evidence package IDs" className="rounded-lg border bg-transparent p-2 text-sm"/><select name="status" className="rounded-lg border bg-transparent p-2 text-sm">{["","open","pending","accepted","contested","resolved","rejected","unavailable","cleared","upheld","overturned"].map(s=><option key={s} value={s}>{s||"No disposition"}</option>)}</select><Button type="submit">Record attributed action</Button></form></Card>)}</div>
      <Card className="p-5"><h3 className="font-semibold">Open bounded review</h3><form onSubmit={create} className="mt-3 space-y-3">{[["title","Assessment title",""],["program","Program ID",programID||""],["version","Exact program version",String(programVersion||"")],["assessor","Assessor user ID",""],["organization","Assessor organization",""],["controls","Control IDs",controlID||""],["systems","System scope IDs",""],["releases","Release scope IDs",""],["packages","Evidence package IDs",""]].map(([n,l,d])=><label key={n} className="block text-sm">{l}<input name={n} required={!(["organization","systems","releases","packages"].includes(n))} defaultValue={d} className="mt-1 w-full rounded-lg border bg-transparent p-2"/></label>)}<label className="block text-sm">Assessor relationship<select name="kind" className="mt-1 w-full rounded-lg border bg-transparent p-2"><option>external</option><option>internal</option></select></label><label className="block text-sm">Conflict disclosure<input name="conflict" required defaultValue="none" className="mt-1 w-full rounded-lg border bg-transparent p-2"/></label>{[["period_start","Evidence period starts"],["period_end","Evidence period ends"],["starts","Access starts"],["expires","Access expires (maximum 90 days)"]].map(([n,l])=><label key={n} className="block text-sm">{l}<input name={n} type="datetime-local" required className="mt-1 w-full rounded-lg border bg-transparent p-2"/></label>)}<Button type="submit">Open assessment and invite</Button></form></Card></div>
  </section>
}
