"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import {api} from "@/lib/api";
import {useAuth} from "./auth";
import {Badge,Button,Card} from "./ui";

type Diagnostic={code:string;message:string;blocking:boolean};
type Scope={commit_count:number;files:string[];additions:number;deletions:number};
type Member={id:string;position:number;title:string;source_branch:string;pull_request_id?:string;revision?:string;base_revision?:string;expected_base_revision?:string;depends_on?:string[];acceptance_criteria:string[];authors:string[];individual_scope:Scope;cumulative_scope:Scope;effective_permissions:{read:boolean;publish:boolean;review:boolean;push:boolean};diagnostics:Diagnostic[];review_state:string};
type Stack={id:string;title:string;outcome:string;target_branch:string;target_revision?:string;members:Member[];diagnostics:Diagnostic[];created_by:string;created_at:string;authority:string};
const lines=(v:FormDataEntryValue|null)=>String(v??"").split("\n").map(x=>x.trim()).filter(Boolean);
export function ChangeStacksWorkspace({repositoryID}:{repositoryID:string}){const{token}=useAuth(),[items,setItems]=useState<Stack[]>([]),[error,setError]=useState(""),[saving,setSaving]=useState(false),requestID=useRef(crypto.randomUUID());
 const load=useCallback(async()=>{if(!token)return;try{const x=await api<{change_stacks:Stack[]}>(`/repositories/${repositoryID}/change-stacks`,{},token);setItems(x.change_stacks);setError("")}catch(e){setError(e instanceof Error?e.message:"Stacks could not be loaded.")}},[repositoryID,token]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const form=event.currentTarget,f=new FormData(form);try{const members=lines(f.get("members")).map((line,index)=>{const [id,title,branch,pull="",dependencies="",criteria=""]=line.split("|").map(x=>x.trim());return{id:id||`change-${index+1}`,title,source_branch:branch,pull_request_id:pull,depends_on:dependencies.split(",").map(x=>x.trim()).filter(Boolean),acceptance_criteria:criteria.split(";").map(x=>x.trim()).filter(Boolean)}});const out=await api<Stack>(`/repositories/${repositoryID}/change-stacks`,{method:"POST",body:JSON.stringify({request_id:requestID.current,title:String(f.get("title")),outcome:String(f.get("outcome")),target_branch:String(f.get("target")),members})},token);setItems(x=>[out,...x]);requestID.current=crypto.randomUUID();form.reset();setError("")}catch(e){setError(e instanceof Error?e.message:"Stack could not be published.")}finally{setSaving(false)}}
 return <main className="mx-auto max-w-6xl space-y-7 p-5 sm:p-8"><header><Badge tone="info">Collaborative delivery</Badge><h1 className="mt-3 text-3xl font-semibold">Change stacks</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Publish a large outcome as exact, ordered review layers. The platform reads Git ancestry; it never rebases or moves a branch.</p></header>
 <Card className="p-6"><h2 className="text-lg font-semibold">Publish an ordered stack</h2><form onSubmit={create} className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Stack title<input name="title" required maxLength={200} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label><label className="text-sm font-semibold">Target branch<input name="target" required defaultValue="main" className="mt-1 min-h-10 w-full rounded-lg border px-3 font-mono font-normal"/></label><label className="text-sm font-semibold md:col-span-2">Shared outcome<textarea name="outcome" required rows={3} className="mt-1 w-full rounded-lg border p-3 font-normal"/></label><label className="text-sm font-semibold md:col-span-2">Ordered changes <span className="font-normal text-[var(--muted)]">— one per line: id | title | branch | existing pull ID (optional) | dependency IDs | criteria separated by ;</span><textarea name="members" required rows={6} placeholder="schema | Add storage contract | feature/schema | | | migration is reversible; tests pass&#10;api | Expose the endpoint | feature/api | | schema | API preserves old clients" className="mt-1 w-full rounded-lg border p-3 font-mono text-xs font-normal"/></label><div><Button disabled={saving}>{saving?"Publishing…":"Publish exact revisions"}</Button></div></form>{error&&<p role="alert" className="mt-4 rounded-lg bg-[var(--danger-soft)] p-3 text-sm text-[var(--danger)]">{error}</p>}</Card>
 <section className="space-y-5" aria-label="Published change stacks">{items.map(stack=><Card key={stack.id} className="overflow-hidden"><div className="border-b p-5"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold">{stack.title}</h2><Badge>{stack.members.length} changes</Badge><Badge tone={stack.diagnostics.some(x=>x.blocking)?"warning":"success"}>{stack.diagnostics.some(x=>x.blocking)?"needs attention":"reviewable"}</Badge></div><p className="mt-2 text-sm">{stack.outcome}</p><p className="mt-2 font-mono text-xs text-[var(--muted)]">{stack.target_branch} @ {stack.target_revision?.slice(0,12)||"missing"}</p></div><ol className="divide-y">{stack.members.map(member=><li key={member.id} className="p-5"><div className="flex flex-wrap items-center gap-2"><Badge>{member.position}</Badge><h3 className="font-semibold">{member.title}</h3><Badge tone={member.diagnostics.some(x=>x.blocking)?"warning":"success"}>{member.review_state||"blocked"}</Badge>{member.pull_request_id&&<Link className="text-xs font-semibold text-[var(--brand)] hover:underline" href={`/pulls/${repositoryID}/${member.pull_request_id}`}>Pull request</Link>}</div><p className="mt-2 font-mono text-xs text-[var(--muted)]">{member.base_revision?.slice(0,10)||"?"} → {member.revision?.slice(0,10)||"missing"} · {member.source_branch}</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><ScopeView label="This change" scope={member.individual_scope}/><ScopeView label="Cumulative outcome" scope={member.cumulative_scope}/></div><p className="mt-3 text-xs"><strong>Authors:</strong> {member.authors?.join(", ")||"unavailable"}</p><p className="mt-1 text-xs"><strong>Depends on:</strong> {member.depends_on?.join(", ")||"target"}</p><p className="mt-1 text-xs"><strong>Acceptance:</strong> {member.acceptance_criteria.join(" · ")}</p><div className="mt-2 flex flex-wrap gap-1">{Object.entries(member.effective_permissions).map(([key,value])=><Badge key={key} tone={value?"success":"neutral"}>{key}: {value?"yes":"no"}</Badge>)}</div>{member.diagnostics.map(d=><p key={d.code+d.message} className="mt-2 rounded bg-[var(--warning-soft)] p-2 text-xs text-[var(--warning)]"><strong>{d.code.replaceAll("_"," ")}:</strong> {d.message}</p>)}</li>)}</ol><p className="border-t p-4 text-xs text-[var(--muted)]">{stack.authority}</p></Card>)}</section></main>}
function ScopeView({label,scope}:{label:string;scope:Scope}){return <div className="rounded-lg border p-3"><p className="text-xs font-semibold">{label}</p><p className="mt-1 text-xs text-[var(--muted)]">{scope?.commit_count??0} commits · <span className="text-[var(--brand)]">+{scope?.additions??0}</span> / <span className="text-[var(--danger)]">-{scope?.deletions??0}</span> · {scope?.files?.length??0} files</p><p className="mt-1 truncate font-mono text-[10px]">{scope?.files?.join(", ")||"No readable scope"}</p></div>}
