"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "@/components/auth";
import { Badge, Button, Card } from "@/components/ui";

type Authority={step_id:string;principal:string;grants:string[];boundary:string};
type Definition={name:string;outcome:string;description:string;owner_ids:string[];triggers:{id:string;kind:string;event:string}[];steps:{id:string;name:string;needs?:string[];owner_ids:string[];retries:number;timeout_seconds:number;budget_actions:number;completion:string[];invocation:{kind:string;action?:string;component?:string;agent_id?:string;workflow_id?:string}}[];outputs:string[];completion:string[];budget_actions:number};
type Preview={definition:Definition;source:{revision:string;path:string;sha256:string};subscriptions:string[];effective_authority:Authority[];execution_order:string[][];diagnostics:{kind:string;message:string;attributed_to:string;step_id?:string}[];activatable:boolean};
type Workflow={id:string;current_version:number;status:string;revisions:{version:number;definition:Definition;source:{revision:string;path:string;sha256:string};subscriptions:string[];effective_authority:Authority[];execution_order:string[][];activated_by:string;activated_at:string}[]};

const short=(v:string)=>v.slice(0,8);
export function CollaborationWorkflowsWorkspace({repositoryID}:{repositoryID:string}){
  const {token,loading}=useAuth(),[workflows,setWorkflows]=useState<Workflow[]>([]),[preview,setPreview]=useState<Preview>(),[selected,setSelected]=useState<Workflow>(),[source,setSource]=useState({revision:"",path:".vivarium/workflow.json"}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(loading||!token)return;try{const x=await api<{workflows:Workflow[]}>(`/repositories/${repositoryID}/collaboration-workflows`,{},token);setWorkflows(x.workflows);setSelected((old)=>x.workflows.find(w=>w.id===old?.id)??x.workflows[0])}catch(e){setError(e instanceof Error?e.message:"Workflows could not be loaded")}},[loading,repositoryID,token]);
  useEffect(()=>{if(loading||!token)return;let cancelled=false;void api<{workflows:Workflow[]}>(`/repositories/${repositoryID}/collaboration-workflows`,{},token).then(x=>{if(!cancelled){setWorkflows(x.workflows);setSelected(x.workflows[0])}}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:"Workflows could not be loaded")});return()=>{cancelled=true}},[loading,repositoryID,token]);
  async function inspect(e:FormEvent){e.preventDefault();if(!token)return;setBusy(true);setError("");try{setPreview(await api<Preview>(`/repositories/${repositoryID}/collaboration-workflows/preview`,{method:"POST",body:JSON.stringify(source)},token))}catch(x){setError(x instanceof Error?x.message:"Configuration could not be previewed")}finally{setBusy(false)}}
  async function activate(){if(!token||!preview?.activatable)return;setBusy(true);try{const path=selected?`/repositories/${repositoryID}/collaboration-workflows/${selected.id}/revisions`:`/repositories/${repositoryID}/collaboration-workflows`;await api(path,{method:"POST",body:JSON.stringify({...source,expected_version:selected?.current_version??0})},token);setPreview(undefined);await load()}catch(x){setError(x instanceof Error?x.message:"Workflow could not be activated")}finally{setBusy(false)}}
  const revision=selected?.revisions.at(-1);
  return <main className="mx-auto max-w-6xl space-y-6 p-6">
    <header><p className="text-sm font-semibold text-[var(--brand)]">Repository collaboration</p><h1 className="mt-1 text-3xl font-semibold">Collaboration workflows</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Explain what will run, why, with whose authority, and toward which shared outcome before repository activity can trigger it.</p></header>
    <Card className="p-5"><form onSubmit={inspect} className="grid gap-4 md:grid-cols-[1fr_1fr_auto]"><label className="text-sm font-medium">Exact reviewed commit<input required pattern="[0-9a-f]{40}" value={source.revision} onChange={e=>setSource({...source,revision:e.target.value})} className="mt-1 w-full rounded-lg border bg-transparent p-2.5" placeholder="40-character commit"/></label><label className="text-sm font-medium">Workflow configuration path<input required value={source.path} onChange={e=>setSource({...source,path:e.target.value})} className="mt-1 w-full rounded-lg border bg-transparent p-2.5"/></label><Button disabled={busy} className="self-end">{busy?"Resolving…":"Preview configuration"}</Button></form>{error&&<p role="alert" className="mt-3 text-sm text-[var(--danger)]">{error}</p>}</Card>
    {preview&&<Card className="space-y-5 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{preview.definition.name}</h2><p className="mt-1 text-sm text-[var(--muted)]">Outcome: {preview.definition.outcome}</p><p className="mt-1 text-xs text-[var(--muted)]">{preview.source.path} · {short(preview.source.revision)} · SHA-256 {short(preview.source.sha256)}</p></div><Badge tone={preview.activatable?"success":"danger"}>{preview.activatable?"Ready to activate":"Activation blocked"}</Badge></div>
      <section><h3 className="font-semibold">Event subscriptions</h3><div className="mt-2 flex flex-wrap gap-2">{preview.subscriptions.map(x=><Badge key={x}>{x}</Badge>)}</div></section>
      <section><h3 className="font-semibold">Execution graph</h3><ol className="mt-2 space-y-2">{preview.execution_order.map((level,i)=><li key={i} className="rounded-lg border p-3 text-sm"><span className="font-medium">Stage {i+1}</span> · {level.join(" in parallel · ")}</li>)}</ol></section>
      <section><h3 className="font-semibold">Effective authority</h3><div className="mt-2 grid gap-2 md:grid-cols-2">{preview.effective_authority.map(a=><div key={a.step_id} className="rounded-lg border p-3 text-sm"><p className="font-medium">{a.step_id} · {a.principal}</p><p>{a.grants.join(", ")}</p><p className="mt-1 text-xs text-[var(--muted)]">{a.boundary}</p></div>)}</div></section>
      {preview.diagnostics.length>0&&<section><h3 className="font-semibold text-[var(--danger)]">Attributable blockers</h3><ul className="mt-2 space-y-2">{preview.diagnostics.map((d,i)=><li key={i} className="rounded-lg border border-[var(--danger)] p-3 text-sm"><strong>{d.kind}</strong> · {d.message}<span className="block text-xs">Attributed to {d.attributed_to}{d.step_id?` · step ${d.step_id}`:""}</span></li>)}</ul></section>}
      <Button type="button" disabled={!preview.activatable||busy} onClick={activate}>{selected?`Activate revision ${selected.current_version+1}`:"Activate workflow"}</Button>
    </Card>}
    <section><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">Active workflows</h2><Button type="button" onClick={()=>{setSelected(undefined);setPreview(undefined)}}>Define new workflow</Button></div>{workflows.length===0?<p className="mt-2 text-sm text-[var(--muted)]">No recurring collaboration is active.</p>:<div className="mt-3 grid gap-3 md:grid-cols-3">{workflows.map(w=>{const r=w.revisions.at(-1)!;return <button key={w.id} onClick={()=>setSelected(w)} className="rounded-xl border p-4 text-left"><span className="font-semibold">{r.definition.name}</span><span className="mt-1 block text-sm">v{w.current_version} · {w.status}</span><span className="mt-2 block text-xs text-[var(--muted)]">{r.definition.outcome}</span></button>})}</div>}</section>
    {revision&&<Card className="p-5"><h2 className="text-xl font-semibold">Version {revision.version} review record</h2><p className="mt-2 text-sm">{revision.definition.description}</p><p className="mt-2 text-sm"><strong>Completion:</strong> {revision.definition.completion.join(" · ")}</p><p className="mt-1 text-sm"><strong>Budget:</strong> {revision.definition.budget_actions} platform actions</p><p className="mt-1 text-sm"><strong>Source:</strong> {revision.source.path} at {short(revision.source.revision)}</p></Card>}
  </main>
}
