"use client";
import {FormEvent,useEffect,useState} from "react";
import {api,APIError,ContributionHelp as Help,DevelopmentWorkspace} from "@/lib/api";
import {useAuth} from "./auth";import {Badge,Button,Card} from "./ui";
type Projection={workspace:DevelopmentWorkspace;scope_changed:boolean;mentor_access_revoked:string[]};
export function ContributionHelp({workspace,onWorkspace}:{workspace:DevelopmentWorkspace;onWorkspace:(v:DevelopmentWorkspace)=>void}){
 const {token,user}=useAuth(),context=workspace.contributor_context;const [view,setView]=useState<Projection>(),[error,setError]=useState(""),[pending,setPending]=useState(false);const help=view?.workspace.contributor_context?.help??context?.help,mentor=!!user&&!!context?.mentor_ids.includes(user.id);
 useEffect(()=>{if(token&&context)void api<Projection>(`/workspaces/${workspace.id}/contribution-help`,{},token).then(setView).catch(()=>{});},[token,workspace.id,context]);if(!context||!help)return null;
 const update=(value:Help)=>onWorkspace({...workspace,contributor_context:{...context,help:value}});
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;setPending(true);const d=new FormData(e.currentTarget),due=String(d.get("due_at")||"");try{update(await api<Help>(`/workspaces/${workspace.id}/contribution-help/entries`,{method:"POST",body:JSON.stringify({expected_version:help!.version,kind:d.get("kind"),body:d.get("body"),decision_owner:d.get("decision_owner"),due_at:due?new Date(due).toISOString():undefined})},token));e.currentTarget.reset();setError("")}catch(x){setError(x instanceof APIError?x.message:"Guidance could not be retained.")}finally{setPending(false)}}
 async function resolve(id:string,status:string){if(!token)return;setPending(true);try{update(await api<Help>(`/workspaces/${workspace.id}/contribution-help/entries/${id}/status`,{method:"POST",body:JSON.stringify({expected_version:help!.version,status})},token))}catch(x){setError(x instanceof APIError?x.message:"Advice status could not be updated.")}finally{setPending(false)}}
 async function exit(state:string){if(!token)return;const reason=window.prompt(state==="exited"?"Why are you leaving? Legitimate progress stays retained.":"Why is reassignment needed?");if(!reason)return;setPending(true);try{update(await api<Help>(`/workspaces/${workspace.id}/contribution-help/state`,{method:"PUT",body:JSON.stringify({expected_version:help!.version,state,reason})},token))}catch(x){setError(x instanceof APIError?x.message:"Exit path could not be retained.")}finally{setPending(false)}}
 return <Card className="mt-5 p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-[var(--brand)]">Shared contribution help</p><h3 className="mt-1 font-semibold">Questions, checkpoints, and accountable guidance</h3><p className="mt-1 text-xs text-[var(--muted)]">Authorship stays with the contributor. Each item names who still owns its decision; agent edits require explicit edit control.</p></div><Badge tone={help.state==="active"?"success":"warning"}>{help.state.replaceAll("_"," ")}</Badge></div>
 {(view?.scope_changed||view?.mentor_access_revoked.length)?<p role="status" className="mt-3 rounded-lg bg-[var(--warning-soft)] p-3 text-sm text-[var(--warning)]">{view.scope_changed?"The opportunity scope changed. ":""}{view.mentor_access_revoked.length?"A designated mentor lost access. ":""}Request reassignment or exit without losing retained progress.</p>:null}{help.state_reason&&<p className="mt-3 text-sm"><b>Current path:</b> {help.state_reason}</p>}
 <div className="mt-4 grid gap-2 sm:grid-cols-2">{help.mentor_availability.map(x=><div key={x.mentor_id} className="rounded-lg border p-3 text-xs"><b>Mentor {x.mentor_id.slice(0,8)}</b> · {x.status}{x.response_hours?` · within ${x.response_hours}h`:""}<p>{x.note}</p></div>)}</div>
 <div className="mt-4 space-y-3">{help.entries.map(x=><article key={x.id} className="rounded-lg bg-[var(--canvas)] p-3"><div className="flex flex-wrap gap-2 text-xs"><Badge tone={x.status==="open"?"warning":"neutral"}>{x.kind.replaceAll("_"," ")}</Badge><span>{x.actor_id.slice(0,8)} · {new Date(x.created_at).toLocaleString()}</span><span>decision: {x.decision_owner}</span>{x.due_at&&<span>requested by {new Date(x.due_at).toLocaleString()}</span>}</div><p className="mt-2 whitespace-pre-wrap text-sm">{x.body}</p>{x.status==="open"&&((x.decision_owner==="contributor"&&!mentor)||(x.decision_owner==="maintainer"&&mentor))&&<div className="mt-2 flex gap-2"><Button disabled={pending} onClick={()=>void resolve(x.id,"resolved")}>Resolve</Button><Button variant="quiet" disabled={pending} onClick={()=>void resolve(x.id,"superseded")}>Supersede</Button></div>}</article>)}</div>
 <form onSubmit={submit} className="mt-5 grid gap-3 rounded-lg border p-4"><label className="text-sm font-semibold">Help item<select name="kind" className="mt-1 w-full rounded-lg border p-2 font-normal">{mentor?<><option value="advice">Clarify scope</option><option value="checkpoint_request">Request checkpoint</option><option value="intervention">Intervene early</option><option value="handoff">Handoff</option></>:<><option value="question">Ask a question</option><option value="checkpoint_response">Share checkpoint</option></>}</select></label><label className="text-sm font-semibold">Who owns the decision?<select name="decision_owner" className="mt-1 w-full rounded-lg border p-2 font-normal"><option value="contributor">Contributor</option><option value="maintainer">Maintainer</option></select></label><label className="text-sm font-semibold">Context<textarea name="body" required maxLength={4000} className="mt-1 min-h-24 w-full rounded-lg border p-3 font-normal"/></label>{mentor&&<label className="text-sm font-semibold">Response requested by<input name="due_at" type="datetime-local" className="mt-1 w-full rounded-lg border p-2 font-normal"/></label>}<Button disabled={pending}>Add to help thread</Button></form>
 {!mentor&&help.state!=="exited"&&<div className="mt-4 flex gap-2"><Button variant="secondary" disabled={pending} onClick={()=>void exit("reassignment_requested")}>Request reassignment</Button><Button variant="quiet" disabled={pending} onClick={()=>void exit("exited")}>Exit contribution</Button></div>}{error&&<p role="alert" className="mt-3 text-sm text-[var(--danger)]">{error}</p>}</Card>}
