"use client";

import Link from "next/link";
import {useCallback,useEffect,useState,type FormEvent} from "react";
import {api} from "@/lib/api";
import {useAuth} from "./auth";
import {Badge,Button,Card} from "./ui";

type Use={id:string;category:string;subjects:string[];purposes:string[];collection:string;processing:string[];sharing:string[];retention:string;residency:string[];deletion:string;consent:string;owner_ids:string[];guarantee?:string;supported:boolean;conflicts_with?:string[]};
type Revision={version:number;title:string;summary:string;scopes:{kind:string;resource_id?:string;name:string}[];data_uses:Use[];owner_ids:string[];links:{kind:string;url:string;label:string}[];exceptions:{id:string;data_use_id:string;reason:string;mitigation:string;approved_by:string;expires_at:string}[];rationale:string;created_by:string;created_at:string};
type Commitment={id:string;current_version:number;revisions:Revision[];diagnostics:{kind:string;severity:string;message:string;resource_id?:string;attributed_to:string}[]};
const val=(f:FormData,n:string)=>String(f.get(n)??"").trim(), list=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);

export function DataCommitmentsWorkspace({repositoryID}:{repositoryID:string}){
 const {token,user}=useAuth(),[items,setItems]=useState<Commitment[]>([]),[selected,setSelected]=useState<Commitment>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!token)return;try{const out=await api<{commitments:Commitment[]}>(`/repositories/${repositoryID}/data-commitments`,{},token);setItems(out.commitments);setSelected(x=>out.commitments.find(v=>v.id===x?.id)??out.commitments[0])}catch(e){setError(e instanceof Error?e.message:"Commitments could not be loaded.")}},[repositoryID,token]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
 const current=selected?.revisions.at(-1), use=current?.data_uses[0];
 function build(f:FormData){const owners=list(val(f,"owners")),scopeKind=val(f,"scope_kind"),exception=val(f,"exception_id");return {title:val(f,"title"),summary:val(f,"summary"),scopes:[{kind:scopeKind,resource_id:val(f,"scope_id"),name:val(f,"scope_name")},...(current?.scopes.slice(1)??[])],owner_ids:owners,data_uses:[{id:val(f,"use_id"),category:val(f,"category"),subjects:list(val(f,"subjects")),purposes:list(val(f,"purposes")),collection:val(f,"collection"),processing:list(val(f,"processing")),sharing:list(val(f,"sharing")),retention:val(f,"retention"),residency:list(val(f,"residency")),deletion:val(f,"deletion"),consent:val(f,"consent"),owner_ids:owners,guarantee:val(f,"guarantee"),supported:val(f,"supported")==="yes",conflicts_with:list(val(f,"conflicts"))},...(current?.data_uses.slice(1)??[])],links:[{kind:"policy",url:val(f,"policy_url"),label:val(f,"policy_label")},{kind:"notice",url:val(f,"notice_url"),label:val(f,"notice_label")},...(current?.links.slice(2)??[])],exceptions:[...(exception?[{id:exception,data_use_id:val(f,"use_id"),reason:val(f,"exception_reason"),mitigation:val(f,"mitigation"),approved_by:user?.id??"",expires_at:new Date(val(f,"expires")).toISOString()}]:[]),...(current?.exceptions.slice(1)??[])],rationale:val(f,"rationale")}}
 async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;setBusy(true);setError("");try{const path=selected?`/repositories/${repositoryID}/data-commitments/${selected.id}/revisions`:`/repositories/${repositoryID}/data-commitments`;const out=await api<Commitment>(path,{method:"POST",body:JSON.stringify({revision:build(new FormData(e.currentTarget)),...(selected?{expected_version:selected.current_version}:{})})},token);setSelected(out);setItems(v=>[out,...v.filter(x=>x.id!==out.id)])}catch(e){setError(e instanceof Error?e.message:"Commitment could not be published.")}finally{setBusy(false)}}
 return <main id="main-content" className="space-y-6"><header><Link href={`/repositories/${repositoryID}`} className="text-sm text-[var(--muted)] hover:text-[var(--brand)]">Repository</Link><h1 className="mt-2 text-2xl font-semibold">Permitted data handling</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Make allowed data use, purpose, responsibility, guarantees, policy, and user notice explicit before implementation.</p></header>
 <Card className="p-5"><div className="flex justify-between"><h2 className="font-semibold">{selected?"Publish a complete successor":"Define a data commitment"}</h2>{selected&&<Button type="button" variant="secondary" onClick={()=>setSelected(undefined)}>New commitment</Button>}</div><form className="mt-4 space-y-4" onSubmit={publish}><Grid><Field n="title" l="Commitment title" v={current?.title}/><Field n="owners" l="Accountable owner IDs" v={current?.owner_ids.join(", ")??user?.id}/><Select n="scope_kind" l="Applies to" v={current?.scopes[0]?.kind??"repository"} options={["repository","release","extension","experiment","environment"]}/><Field n="scope_id" l="Resource ID (required outside repository)" v={current?.scopes[0]?.resource_id} required={false}/><Field n="scope_name" l="Scope name" v={current?.scopes[0]?.name}/></Grid><Area n="summary" l="Commitment summary" v={current?.summary}/><Area n="rationale" l="Revision rationale" v={current?.rationale}/>
 <Group title="Permitted use"><Field n="use_id" l="Data use key" v={use?.id}/><Field n="category" l="Data category" v={use?.category}/><Field n="subjects" l="Data subjects (comma separated)" v={use?.subjects.join(", ")}/><Field n="purposes" l="Purposes" v={use?.purposes.join(", ")}/><Field n="collection" l="Collection method" v={use?.collection}/><Field n="processing" l="Processing operations" v={use?.processing.join(", ")}/><Field n="sharing" l="Sharing recipients (use none if prohibited)" v={use?.sharing.join(", ")??"none"}/><Field n="retention" l="Retention rule" v={use?.retention}/><Field n="residency" l="Residency locations" v={use?.residency.join(", ")}/><Field n="deletion" l="Deletion guarantee" v={use?.deletion}/><Field n="consent" l="Consent basis and withdrawal" v={use?.consent}/><Field n="guarantee" l="Guarantee" v={use?.guarantee} required={false}/><Select n="supported" l="Guarantee supported" v={use?.supported===false?"no":"yes"} options={["yes","no"]}/><Field n="conflicts" l="Conflicting use keys" v={use?.conflicts_with?.join(", ")} required={false}/></Group>
 <Group title="Applicable policy and notice"><Field n="policy_url" l="Policy URL" type="url" v={current?.links.find(x=>x.kind==="policy")?.url}/><Field n="policy_label" l="Policy label" v={current?.links.find(x=>x.kind==="policy")?.label}/><Field n="notice_url" l="User-facing notice URL" type="url" v={current?.links.find(x=>x.kind==="notice")?.url}/><Field n="notice_label" l="Notice label" v={current?.links.find(x=>x.kind==="notice")?.label}/></Group>
 <Group title="Permitted exception (optional)"><Field n="exception_id" l="Exception key" v={current?.exceptions[0]?.id} required={false}/><Field n="exception_reason" l="Reason" v={current?.exceptions[0]?.reason} required={false}/><Field n="mitigation" l="Mitigation" v={current?.exceptions[0]?.mitigation} required={false}/><Field n="expires" l="Expires" type="datetime-local" v={current?.exceptions[0]?.expires_at?.slice(0,16)} required={false}/></Group><Button disabled={busy}>{busy?"Publishing…":selected?`Publish version ${selected.current_version+1}`:"Create commitment"}</Button></form></Card>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
 {selected&&current&&<Card className="p-5"><div className="flex gap-2"><h2 className="text-lg font-semibold">{current.title}</h2><Badge>version {selected.current_version}</Badge><Badge tone={selected.diagnostics.some(x=>x.severity==="blocking")?"danger":"success"}>{selected.diagnostics.length?`${selected.diagnostics.length} explicit issue(s)`:"permitted use is explicit"}</Badge></div><p className="mt-2 text-sm text-[var(--muted)]">{current.scopes.map(x=>`${x.kind}: ${x.name}`).join(" · ")} · accountable to {current.owner_ids.join(", ")}</p>{selected.diagnostics.map((x,i)=><p className="mt-3 rounded-lg border p-3 text-sm" key={`${x.kind}-${i}`}><Badge tone={x.severity==="blocking"?"danger":"warning"}>{x.kind.replaceAll("_"," ")}</Badge> {x.message} <span className="text-[var(--muted)]">Attributed to {x.attributed_to}</span></p>)}<details className="mt-4"><summary className="cursor-pointer font-semibold">Version history</summary>{selected.revisions.map(x=><p className="mt-2 text-sm" key={x.version}>v{x.version} · {x.rationale} · {x.created_by} · {new Date(x.created_at).toLocaleString()}</p>)}</details></Card>}
 <section><h2 className="font-semibold">Repository commitments</h2>{items.map(x=><button type="button" onClick={()=>setSelected(x)} className="mt-2 w-full rounded-xl border bg-white p-4 text-left hover:border-[var(--brand)]" key={x.id}><strong>{x.revisions.at(-1)?.title}</strong><span className="block text-xs text-[var(--muted)]">v{x.current_version} · {x.diagnostics.length} explicit issue(s)</span></button>)}</section></main>;
}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-3 md:grid-cols-3">{children}</div>} function Group({title,children}:{title:string;children:React.ReactNode}){return <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">{title}</legend>{children}</fieldset>}
function Field({n,l,v,type="text",required=true}:{n:string;l:string;v?:string;type?:string;required?:boolean}){return <label className="text-xs font-semibold">{l}<input key={v} name={n} type={type} required={required} defaultValue={v} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label>} function Area({n,l,v}:{n:string;l:string;v?:string}){return <label className="text-xs font-semibold">{l}<textarea key={v} name={n} required defaultValue={v} className="mt-1 w-full rounded-lg border p-3 font-normal"/></label>} function Select({n,l,v,options}:{n:string;l:string;v:string;options:string[]}){return <label className="text-xs font-semibold">{l}<select name={n} defaultValue={v} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
