"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/auth";
import { Badge, Button, Card } from "@/components/ui";
import { api } from "@/lib/api";

type Observation = {
  id: string; version: number; signal_kind: string; severity: string; status: string;
  scope: { revision: string; release_id: string; environment_id: string; deployment_id: string; extension_installation_id?: string; data_use_id: string };
  owner_ids: string[];
  evidence: { kind: string; digest: string; window_start: string; window_end: string; sample_count: number }[];
  actions: { id: string; kind: string; rationale: string; participant_ids?: string[]; expires_at?: string; created_by: string; created_at: string }[];
  repair?: { proposal_id: string; task_id: string; assignee_type: string; assignee_id: string };
};
const csv = (value: FormDataEntryValue | null) => String(value ?? "").split(",").map(x => x.trim()).filter(Boolean);

export function DataObservationsWorkspace({ repositoryID }: { repositoryID: string }) {
  const { token, user } = useAuth();
  const [items, setItems] = useState<Observation[]>([]), [selected, setSelected] = useState<Observation>(), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!token) return; try { const out = await api<{data_observations: Observation[]}>(`/repositories/${repositoryID}/data-observations`, {}, token); setItems(out.data_observations); setSelected(current => out.data_observations.find(x => x.id === current?.id) ?? out.data_observations[0]); } catch (e) { setError(e instanceof Error ? e.message : "Production observations could not be loaded."); } }, [repositoryID, token]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  async function act(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token || !selected) return; setBusy(true); setError(""); const form = new FormData(event.currentTarget), expires = String(form.get("expires_at") ?? ""); try { const out = await api<Observation>(`/repositories/${repositoryID}/data-observations/${selected.id}/actions`, {method:"POST", body:JSON.stringify({expected_version:selected.version, action:{kind:form.get("kind"), rationale:form.get("rationale"), participant_ids:csv(form.get("participants")), ...(expires ? {expires_at:new Date(expires).toISOString()} : {})}})}, token); setSelected(out); setItems(values => [out, ...values.filter(x => x.id !== out.id)]); event.currentTarget.reset(); } catch (e) { setError(e instanceof Error ? e.message : "Action could not be retained."); } finally { setBusy(false); } }
  async function repair(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token || !selected) return; setBusy(true); setError(""); const form = new FormData(event.currentTarget); try { const out = await api<{data_observation:Observation}>(`/repositories/${repositoryID}/data-observations/${selected.id}/repair`, {method:"POST", body:JSON.stringify({expected_version:selected.version,title:form.get("title"),body:form.get("body"),task_title:form.get("task_title"),outcome:form.get("outcome"),verification_plan:form.get("verification_plan"),assignee_type:form.get("assignee_type"),assignee_id:form.get("assignee_id")})}, token); setSelected(out.data_observation); setItems(values => [out.data_observation, ...values.filter(x => x.id !== out.data_observation.id)]); } catch (e) { setError(e instanceof Error ? e.message : "Repair could not be delegated."); } finally { setBusy(false); } }
  return <section className="space-y-5 border-t pt-6">
    <header><h2 className="text-xl font-semibold">Production data-use alignment</h2><p className="mt-1 max-w-3xl text-sm text-[var(--muted)]">Private, sanitized signals connect observed handling to the exact promise, release, environment, deployment, extension, and accountable owners. Aggregate evidence never includes the people whose data revealed the gap.</p></header>
    {error && <p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]"><div>{items.length === 0 && <Card className="p-4 text-sm text-[var(--muted)]">No permitted production signal has detected a data-use gap.</Card>}{items.map(item => <button key={item.id} type="button" onClick={() => setSelected(item)} className="mb-2 w-full rounded-xl border bg-white p-4 text-left hover:border-[var(--brand)]"><span className="flex gap-2"><Badge tone={item.severity === "blocking" ? "danger" : "warning"}>{item.signal_kind.replaceAll("_", " ")}</Badge><Badge>{item.status.replaceAll("_", " ")}</Badge></span><span className="mt-2 block text-xs text-[var(--muted)]">release {item.scope.release_id} · {item.evidence.length} sanitized evidence item(s)</span></button>)}</div>
    {selected && <div className="space-y-4"><Card className="p-5"><div className="flex flex-wrap gap-2"><Badge tone={selected.severity === "blocking" ? "danger" : "warning"}>{selected.signal_kind.replaceAll("_", " ")}</Badge><Badge>{selected.status.replaceAll("_", " ")}</Badge></div><p className="mt-3 text-sm">Accountable owners: {selected.owner_ids.join(", ")}</p><p className="mt-1 text-xs text-[var(--muted)]">Revision {selected.scope.revision} · release {selected.scope.release_id} · environment {selected.scope.environment_id} · deployment {selected.scope.deployment_id}{selected.scope.extension_installation_id ? ` · extension ${selected.scope.extension_installation_id}` : ""}</p>{selected.evidence.map(e => <p key={e.digest} className="mt-3 rounded-lg border p-3 text-sm"><strong>{e.kind.replaceAll("_", " ")}</strong> · {e.sample_count} aggregate sample(s) · <span className="font-mono text-xs">{e.digest.slice(0,12)}…</span><span className="block text-xs text-[var(--muted)]">{new Date(e.window_start).toLocaleString()}–{new Date(e.window_end).toLocaleString()}</span></p>)}{selected.actions.map(a => <p key={a.id} className="mt-3 text-sm"><Badge>{a.kind.replaceAll("_", " ")}</Badge> {a.rationale} <span className="text-xs text-[var(--muted)]">— {a.created_by}</span></p>)}{selected.repair && <p className="mt-4 text-sm"><Badge tone="success">ordinary repair planned</Badge> <Link className="text-[var(--brand)]" href={`/proposals/${repositoryID}/${selected.repair.proposal_id}`}>Review proposal and assigned task</Link></p>}</Card>
    <Card className="p-5"><h3 className="font-semibold">Contain and coordinate</h3><form onSubmit={act} className="mt-3 grid gap-3 md:grid-cols-2"><Select n="kind" l="Action" options={["contain","notify","private_incident","governed_exception"]}/><Field n="participants" l="Participant IDs to notify" required={false} v={selected.owner_ids.join(", ")}/><Area n="rationale" l="Rationale and safe next step"/><Field n="expires_at" l="Exception expiry (exceptions only)" type="datetime-local" required={false}/><Button disabled={busy}>Retain action</Button></form></Card>
    {!selected.repair && <Card className="p-5"><h3 className="font-semibold">Delegate ordinary repair</h3><p className="mt-1 text-xs text-[var(--muted)]">The task receives only the sanitized evidence above. Its assignment grants no data, environment, review, release, or deployment authority.</p><form onSubmit={repair} className="mt-3 grid gap-3 md:grid-cols-2"><Field n="title" l="Proposal title" v={`Repair ${selected.signal_kind.replaceAll("_", " ")}`}/><Field n="task_title" l="Task title" v="Correct observed data handling"/><Area n="body" l="Review context"/><Area n="outcome" l="Expected outcome"/><Area n="verification_plan" l="Verification and release plan"/><Select n="assignee_type" l="Owner type" options={["human","agent"]}/><Field n="assignee_id" l="Human or approved-agent ID" v={user?.id}/><Button disabled={busy}>Create assigned repair</Button></form></Card>}</div>}</div>
  </section>;
}
function Field({n,l,v,type="text",required=true}:{n:string;l:string;v?:string;type?:string;required?:boolean}) { return <label className="text-xs font-semibold">{l}<input name={n} type={type} required={required} defaultValue={v} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label>; }
function Area({n,l}:{n:string;l:string}) { return <label className="text-xs font-semibold">{l}<textarea name={n} required className="mt-1 w-full rounded-lg border p-3 font-normal"/></label>; }
function Select({n,l,options}:{n:string;l:string;options:string[]}) { return <label className="text-xs font-semibold">{l}<select name={n} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal">{options.map(x => <option key={x} value={x}>{x.replaceAll("_", " ")}</option>)}</select></label>; }
