"use client";
import {useCallback,useEffect,useState,type FormEvent} from "react";
import {api} from "@/lib/api";
import {useAuth} from "./auth";
import {Badge,Button,Card} from "./ui";
type Ref={kind:string;resource_id?:string;revision?:string;label:string};
type W={id:string;version:number;title:string;summary:string;trigger:Ref;release:Ref;environment:Ref;time_start:string;time_end:string;user_journey:string;owner_ids:string[];severity:string;audience:string;status:string;source:Ref;packages:Ref[];configuration:Ref;infrastructure:Ref;permitted_evidence:{id:string;kind:string;label:string;visibility:string;available:boolean;unavailable_reason?:string}[];unavailable_context:string[];hypotheses:{id:string;statement:string;status:string;created_by:string}[];history:{id:string;kind:string;actor_id:string;message?:string;created_at:string}[]};
const field="rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm";
const val=(f:FormData,n:string)=>String(f.get(n)||"").trim();const list=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);
export function DebuggingWorkspace({repositoryID}:{repositoryID:string}){const {token,user}=useAuth();const [items,setItems]=useState<W[]>([]),[selected,setSelected]=useState<W>(),[error,setError]=useState("");const load=useCallback(async()=>{try{const x=await api<{debugging_workspaces:W[]}>(`/repositories/${repositoryID}/debugging-workspaces`,{},token);setItems(x.debugging_workspaces);setSelected(s=>x.debugging_workspaces.find(v=>v.id===s?.id)??x.debugging_workspaces[0]);setError("")}catch(e){setError(e instanceof Error?e.message:"Debugging workspaces could not be loaded")}},[repositoryID,token]);useEffect(()=>{
// This effect synchronizes repository and identity changes with the API-backed workspace list.
// eslint-disable-next-line react-hooks/set-state-in-effect
void load()},[load]);
async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;const f=new FormData(e.currentTarget),releaseRevision=val(f,"release_revision"),evidenceRef=val(f,"evidence_reference"),infraID=val(f,"infrastructure_id"),packageID=val(f,"package_id");const evidenceLabel=val(f,"evidence_label");try{const out=await api<W>(`/repositories/${repositoryID}/debugging-workspaces`,{method:"POST",body:JSON.stringify({title:val(f,"title"),summary:val(f,"summary"),trigger:{kind:val(f,"trigger_kind"),resource_id:val(f,"trigger_id")||undefined,label:val(f,"trigger_label")},release:{kind:"release",resource_id:val(f,"release_id"),revision:releaseRevision,label:val(f,"release_label")},environment:{kind:"environment",resource_id:val(f,"environment_id"),label:val(f,"environment_label")},time_start:new Date(val(f,"time_start")).toISOString(),time_end:new Date(val(f,"time_end")).toISOString(),user_journey:val(f,"journey"),owner_ids:list(val(f,"owners")),severity:val(f,"severity"),audience:val(f,"audience"),access_user_ids:list(val(f,"access")),source:{kind:"commit",resource_id:repositoryID,revision:releaseRevision,label:"Released source"},packages:packageID?[{kind:"package",resource_id:packageID,revision:val(f,"package_version"),label:val(f,"package_label")}]:[],configuration:{kind:"configuration",revision:releaseRevision,label:"Configuration at release"},infrastructure:{kind:"infrastructure",resource_id:infraID||undefined,revision:infraID?val(f,"infrastructure_version"):undefined,label:infraID?"Infrastructure definition":"Unavailable"},permitted_evidence:evidenceLabel?[{kind:val(f,"evidence_kind"),reference:evidenceRef,label:evidenceLabel,visibility:val(f,"evidence_visibility"),sanitization:val(f,"sanitization"),available:Boolean(evidenceRef),unavailable_reason:evidenceRef?undefined:val(f,"evidence_gap")}]:[],unavailable_context:list(val(f,"unavailable"))})},token);setItems(x=>[out,...x]);setSelected(out);setError("");e.currentTarget.reset()}catch(x){setError(x instanceof Error?x.message:"Workspace could not be opened")}}
async function event(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!selected)return;const f=new FormData(e.currentTarget);try{const out=await api<W>(`/repositories/${repositoryID}/debugging-workspaces/${selected.id}/events`,{method:"POST",body:JSON.stringify({expected_version:selected.version,kind:val(f,"kind"),value:val(f,"value"),message:val(f,"message")})},token);setSelected(out);setItems(xs=>xs.map(x=>x.id===out.id?out:x));e.currentTarget.reset()}catch(x){setError(x instanceof Error?x.message:"History could not be appended")}}
return <main id="main-content" className="mx-auto max-w-7xl px-6 py-8"><p className="font-mono text-xs font-semibold uppercase tracking-[.16em] text-[var(--brand)]">Runtime collaboration</p><h1 className="mt-2 text-3xl font-semibold">Production debugging</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Establish the exact running behavior and released code under investigation. This shared context grants no observability, deployment, Git, or environment authority.</p>{error&&<p className="mt-4 text-sm text-[var(--danger)]">{error}</p>}
{token&&<Card className="mt-6 p-5"><h2 className="font-semibold">Open a debugging workspace</h2><form onSubmit={create} className="mt-4 grid gap-3 md:grid-cols-3"><I n="title" p="Workspace title"/><I n="summary" p="Observed behavior and impact"/><S n="trigger_kind" a={["issue","incident","support_thread","deployment","service_objective","trace","manual_observation"]}/><I n="trigger_id" p="Trigger ID (optional for trace/manual)" req={false}/><I n="trigger_label" p="Trigger label"/><I n="release_id" p="Affected release ID"/><I n="release_revision" p="Exact 40-character release commit"/><I n="release_label" p="Release label"/><I n="environment_id" p="Environment ID"/><I n="environment_label" p="Environment label"/><I n="time_start" type="datetime-local" p="Window start"/><I n="time_end" type="datetime-local" p="Window end"/><I n="journey" p="Affected user journey"/><I n="owners" p="Owner IDs, comma separated"/><S n="severity" a={["low","medium","high","critical"]}/><S n="audience" a={["repository","restricted"]}/><I n="access" p="Restricted reader IDs" req={false}/><I n="package_id" p="Affected package ID" req={false}/><I n="package_version" p="Exact package version" req={false}/><I n="package_label" p="Package label" req={false}/><I n="infrastructure_id" p="Infrastructure definition ID" req={false}/><I n="infrastructure_version" p="Infrastructure version" req={false}/><I n="evidence_label" p="Permitted evidence label" req={false}/><S n="evidence_kind" a={["observation","trace","log","metric","report","link","profile","snapshot"]}/><I n="evidence_reference" p="Sanitized evidence reference" req={false}/><S n="evidence_visibility" a={["repository","restricted"]}/><I n="sanitization" p="Redaction/sanitization applied" req={false}/><I n="evidence_gap" p="Why evidence is unavailable" req={false}/><I n="unavailable" p="Other unavailable context, comma separated" req={false}/><div><Button>Open workspace</Button></div></form></Card>}
<div className="mt-6 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><Card className="p-4"><h2 className="font-semibold">Shared workspaces</h2>{items.length===0&&<p className="mt-3 text-sm text-[var(--muted)]">No visible debugging workspace yet.</p>}{items.map(x=><button key={x.id} onClick={()=>setSelected(x)} className="mt-3 block w-full rounded-lg border p-3 text-left"><div className="flex gap-2"><Badge tone={x.severity==="critical"?"danger":"neutral"}>{x.severity}</Badge><Badge>{x.status}</Badge></div><strong className="mt-2 block text-sm">{x.title}</strong><span className="text-xs text-[var(--muted)]">{x.trigger.kind.replaceAll("_"," ")} · {x.user_journey}</span></button>)}</Card>
{selected&&<Card className="p-5"><div className="flex flex-wrap gap-2"><Badge>{selected.audience}</Badge><Badge>{selected.status}</Badge><Badge tone={selected.severity==="critical"?"danger":"warning"}>{selected.severity}</Badge></div><h2 className="mt-3 text-xl font-semibold">{selected.title}</h2><p className="mt-2 text-sm">{selected.summary}</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><D k="Running release" v={`${selected.release.label} · ${selected.release.revision?.slice(0,12)}`}/><D k="Environment" v={selected.environment.label}/><D k="Observed window" v={`${new Date(selected.time_start).toLocaleString()} — ${new Date(selected.time_end).toLocaleString()}`}/><D k="Journey" v={selected.user_journey}/><D k="Owners" v={selected.owner_ids.join(", ")}/><D k="Source and configuration" v={selected.configuration.revision?.slice(0,12)||"unavailable"}/><D k="Packages" v={selected.packages.map(x=>`${x.label} ${x.revision}`).join(", ")||"none declared"}/><D k="Infrastructure" v={selected.infrastructure.resource_id?`${selected.infrastructure.label} v${selected.infrastructure.revision}`:"unavailable"}/></dl><h3 className="mt-5 font-semibold">Permitted evidence</h3>{selected.permitted_evidence.map(x=><p key={x.id} className="mt-2 rounded-lg bg-[var(--surface-soft)] p-3 text-sm">{x.kind}: {x.label} · {x.available?x.visibility:`unavailable — ${x.unavailable_reason}`}</p>)}{selected.unavailable_context.map(x=><p key={x} className="mt-2 text-sm text-[var(--warning)]">Unavailable: {x}</p>)}
{user&&<form onSubmit={event} className="mt-5 grid gap-2 sm:grid-cols-3"><S n="kind" a={["hypothesis","status"]}/><I n="value" p="Hypothesis or status"/><I n="message" p="Attributable note" req={false}/><div><Button>Append history</Button></div></form>}<h3 className="mt-5 font-semibold">Hypotheses and history</h3>{selected.hypotheses.map(x=><p key={x.id} className="mt-2 text-sm"><Badge>{x.status}</Badge> {x.statement} <span className="text-[var(--muted)]">— {x.created_by}</span></p>)}{[...selected.history].reverse().map(x=><p key={x.id} className="mt-2 border-t pt-2 text-xs text-[var(--muted)]">{x.kind} by {x.actor_id} · {new Date(x.created_at).toLocaleString()} {x.message}</p>)}</Card>}</div></main>}
function I({n,p,req=true,type="text"}:{n:string;p:string;req?:boolean;type?:string}){return <input className={field} name={n} type={type} required={req} placeholder={p} aria-label={p}/>};function S({n,a}:{n:string;a:string[]}){return <select className={field} name={n} aria-label={n}>{a.map(x=><option key={x}>{x}</option>)}</select>};function D({k,v}:{k:string;v:string}){return <div><dt className="text-xs font-semibold uppercase text-[var(--muted)]">{k}</dt><dd className="mt-1 break-all">{v}</dd></div>}
