"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api, type DeliveryTeam, type Repository } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

const field = "mt-1 min-h-10 w-full rounded-lg border border-[var(--line-strong)] bg-white px-3 py-2 text-sm";
const parsePeople = (value: string, repositoryId: string) => value.split("\n").map(x=>x.trim()).filter(Boolean).map((line,index)=>{const [principal_type,principal_id,role,responsibility,why,escalation,level="read"] = line.split("|").map(x=>x.trim());return {id:`invite-${Date.now()}-${index}`,principal_type,principal_id,role,responsibility,why,escalation,required_access:[{repository_id:repositoryId,level}]};});
export function DeliveryTeamsWorkspace() {
  const {token,loading:authLoading}=useAuth();
  const [teams,setTeams]=useState<DeliveryTeam[]>([]),[repos,setRepos]=useState<Repository[]>([]),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{if(authLoading)return;if(!token){setLoading(false);return}try{const [a,b]=await Promise.all([api<{delivery_teams:DeliveryTeam[]}>("/delivery-teams",{},token),api<{repositories:Repository[]}>("/repositories?limit=100",{},token)]);setTeams(a.delivery_teams);setRepos(b.repositories)}catch(e){setError(e instanceof Error?e.message:"Delivery teams could not be loaded.")}finally{setLoading(false)}},[authLoading,token]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setPending(true);setError("");const d=new FormData(e.currentTarget),repositoryId=String(d.get("repository_id")),localDeadline=String(d.get("deadline")??"");try{await api(`/repositories/${repositoryId}/delivery-teams`,{method:"POST",body:JSON.stringify({outcome:{kind:d.get("outcome_kind"),resource_id:d.get("outcome_id"),title:d.get("outcome_title")},charter:{name:d.get("name"),purpose:d.get("purpose"),deadline:localDeadline?new Date(localDeadline).toISOString():undefined,escalation_path:d.get("escalation_path"),overall_budget:d.get("budget")?{unit:d.get("budget_unit"),limit:Number(d.get("budget"))}:undefined,participants:parsePeople(String(d.get("participants")),repositoryId)}})},token);e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Delivery team could not be created.")}finally{setPending(false)}}
  async function respond(team:DeliveryTeam,participantId:string,decision:string){setPending(true);try{await api(`/delivery-teams/${team.id}/participants/${participantId}/response`,{method:"POST",body:JSON.stringify({expected_version:team.version,decision})},token);await load()}catch(e){setError(e instanceof Error?e.message:"Invitation response failed.")}finally{setPending(false)}}
  if(loading)return <p className="text-sm text-[var(--muted)]">Loading delivery teams…</p>;
  if(!token)return <Card className="p-6"><p>Sign in to assemble and review delivery teams.</p></Card>;
  return <div className="space-y-8"><header><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--brand-strong)]">Shared outcomes</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Delivery teams</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Agree on responsibility, limits, resources, and escalation before coordinated work starts. Charters describe authority; they never create it.</p></header>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}
  <Card className="p-5"><h2 className="text-lg font-semibold">Form a team</h2><form onSubmit={create} className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm">Repository<select required name="repository_id" className={field}>{repos.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="text-sm">Outcome type<select name="outcome_kind" className={field}><option value="proposal">Proposal</option><option value="initiative">Initiative</option><option value="decision">Decision</option><option value="incident_follow_up">Incident follow-up</option><option value="planned_outcome">Other planned outcome</option></select></label><label className="text-sm">Outcome ID<input required name="outcome_id" className={field}/></label><label className="text-sm">Outcome title<input required name="outcome_title" className={field}/></label><label className="text-sm">Team name<input required name="name" className={field}/></label><label className="text-sm">Deadline<input type="datetime-local" name="deadline" className={field}/></label><label className="text-sm md:col-span-2">Purpose<textarea required name="purpose" className={field}/></label><label className="text-sm">Budget<input min="1" type="number" name="budget" className={field}/></label><label className="text-sm">Budget unit<select name="budget_unit" className={field}><option value="minutes">Agent minutes</option><option value="credits">Credits</option><option value="usd">USD</option></select></label><label className="text-sm md:col-span-2">Team escalation path<textarea required name="escalation_path" className={field} placeholder="Who decides when scope, risk, or budget changes?"/></label><label className="text-sm md:col-span-2">Participants <span className="text-[var(--muted)]">— one per line: human|ID|role|responsibility|why involved|escalation|read or write</span><textarea required rows={5} name="participants" className={field}/></label><div className="md:col-span-2"><Button disabled={pending}>Create charter and invite</Button></div></form></Card>
  <section className="space-y-4"><h2 className="text-xl font-semibold">Current charters</h2>{teams.length===0?<Card className="p-6 text-sm text-[var(--muted)]">No delivery teams yet.</Card>:teams.map(team=><Card key={team.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{team.name}</h3><p className="mt-1 text-sm text-[var(--muted)]">{team.outcome.title} · organized by {team.organizer_id}</p></div><Badge tone="info">v{team.version}</Badge></div><p className="mt-3 text-sm">{team.purpose}</p><p className="mt-2 text-xs text-[var(--muted)]">Escalation: {team.escalation_path}{team.deadline?` · Due ${new Date(team.deadline).toLocaleString()}`:""}</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{team.participants.map(p=><div key={p.id} className="rounded-lg border border-[var(--line)] p-4"><div className="flex items-center justify-between"><strong className="text-sm">{p.role}</strong><Badge tone={p.status==="accepted"?"success":p.status==="declined"?"danger":"warning"}>{p.status}</Badge></div><p className="mt-1 text-xs text-[var(--muted)]">{p.principal_type} · {p.principal_id}</p><p className="mt-2 text-sm">{p.responsibility}</p><p className="mt-1 text-xs text-[var(--muted)]">Why: {p.why} · Escalate: {p.escalation}</p>{p.access_preview.map(a=><p key={a.repository_id} className={`mt-2 text-xs ${a.sufficient?"text-emerald-700":"text-amber-700"}`}>{a.sufficient?"Access ready":"Access gap"}: needs {a.required}, has {a.effective} ({a.source})</p>)}{p.can_respond&&<div className="mt-3 flex gap-2"><Button disabled={pending} onClick={()=>respond(team,p.id,"accepted")}>Accept</Button><Button variant="secondary" disabled={pending} onClick={()=>respond(team,p.id,"declined")}>Decline</Button></div>}</div>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm font-medium">Attributable charter history</summary><ul className="mt-2 space-y-1 text-xs text-[var(--muted)]">{team.events.map(e=><li key={e.id}>{new Date(e.created_at).toLocaleString()} · {e.actor_id} · {e.summary}</li>)}</ul></details></Card>)}</section></div>;
}
