"use client";

import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { api, APIError, type DependencyInventory, type PackageUpdate, type PackageUpdatePolicy } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

export function DependencyInventoryWorkspace({ repositoryID }: { repositoryID: string }) {
  const { token } = useAuth();
  const [items, setItems] = useState<DependencyInventory[]>([]);
  const [error, setError] = useState("");
  const [policies, setPolicies] = useState<PackageUpdatePolicy[]>([]);
  const [updates, setUpdates] = useState<PackageUpdate[]>([]);
  useEffect(() => { void api<{ inventories: DependencyInventory[] }>(`/repositories/${repositoryID}/dependency-inventories`, {}, token).then((value) => setItems(value.inventories ?? [])).catch((reason: unknown) => setError(reason instanceof APIError ? reason.message : "Dependency inventories could not be loaded.")); }, [repositoryID, token]);
  useEffect(() => { void api<{ policies: PackageUpdatePolicy[]; updates: PackageUpdate[] }>(`/repositories/${repositoryID}/package-updates`, {}, token).then((value) => { setPolicies(value.policies ?? []); setUpdates(value.updates ?? []); }).catch(() => undefined); }, [repositoryID, token]);
  async function record(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setError(""); try { const created = await api<DependencyInventory>(`/repositories/${repositoryID}/dependency-inventories`, { method: "POST", body: JSON.stringify({ commit_id: data.get("commit_id") }) }, token); setItems((current) => [created, ...current.filter((value) => value.inventory.id !== created.inventory.id)]); } catch (reason) { setError(reason instanceof APIError ? reason.message : "Inventory could not be recorded."); } }
  async function savePolicy(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setError(""); try { const policy = await api<PackageUpdatePolicy>(`/repositories/${repositoryID}/package-update-policies/${data.get("package_name")}`, { method: "PUT", body: JSON.stringify({ strategy: data.get("strategy"), action: "proposal" }) }, token); setPolicies((current) => [...current.filter((value) => value.package_name !== policy.package_name), policy].sort((a, b) => a.package_name.localeCompare(b.package_name))); form.reset(); } catch (reason) { setError(reason instanceof APIError ? reason.message : "Update policy could not be saved."); } }
  async function scan() { setError(""); try { const result = await api<{ updates: PackageUpdate[] }>(`/repositories/${repositoryID}/package-updates/scan`, { method: "POST", body: "{}" }, token); setUpdates(result.updates ?? []); } catch (reason) { setError(reason instanceof APIError ? reason.message : "Package releases could not be scanned."); } }
  return <div className="space-y-6"><header className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--brand)]">Repository supply chain</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Exact dependency inventory</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Reviewed manifest and lock state connects direct and transitive packages to source, release artifacts, and running environments.</p></header>
    {token && <Card className="p-4"><form onSubmit={(event) => void record(event)} className="flex flex-wrap items-end gap-3"><label className="grow text-sm font-semibold">Verified commit containing .vivarium/packages.json<input name="commit_id" required minLength={40} maxLength={40} className="mt-2 min-h-10 w-full rounded-lg border border-[var(--line-strong)] px-3 font-mono text-xs font-normal" /></label><Button type="submit">Record lock state</Button></form></Card>}
    {token && <Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-bold">Verified update policies</h2><p className="mt-1 max-w-2xl text-sm text-[var(--muted)]">Consumer-owned policy turns eligible releases into ordinary proposals and tasks. Publishers receive no repository authority.</p></div><Button type="button" onClick={() => void scan()}>Scan releases</Button></div><form onSubmit={(event) => void savePolicy(event)} className="mt-4 flex flex-wrap items-end gap-3"><label className="grow text-sm font-semibold">Package name<input name="package_name" required className="mt-2 min-h-10 w-full rounded-lg border border-[var(--line-strong)] px-3 font-mono text-xs font-normal" /></label><label className="text-sm font-semibold">Allowed update<select name="strategy" defaultValue="minor" className="mt-2 block min-h-10 rounded-lg border border-[var(--line-strong)] px-3 font-normal"><option value="patch">Patch</option><option value="minor">Minor</option><option value="major">Major</option></select></label><Button type="submit">Save policy</Button></form><div className="mt-3 flex flex-wrap gap-2">{policies.map((policy) => <Badge key={policy.package_name}>{policy.package_name} · {policy.strategy}</Badge>)}</div></Card>}
    {error && <p role="alert" className="rounded-lg bg-[var(--danger-soft)] p-3 text-sm text-[var(--danger)]">{error}</p>}
    {updates.map((update) => <Card key={update.id} className="p-5"><div className="flex flex-wrap items-center gap-2"><Badge tone="success">reviewable update</Badge><Link href={`/proposals/${repositoryID}/${update.proposal_id}`} className="font-semibold text-[var(--brand)] hover:underline">{update.package_name} {update.from_version} → {update.to_version}</Link></div><p className="mt-2 text-sm text-[var(--muted)]">{update.release_notes}</p><p className="mt-3 text-xs">Compatibility: {update.compatibility_evidence.step} succeeded in {update.compatibility_evidence.image} · affected paths: {update.affected_dependency_paths.join(", ")}</p><pre className="mt-3 overflow-x-auto rounded-lg bg-[var(--surface-subtle)] p-3 text-xs">{JSON.stringify(update.manifest, null, 2)}</pre></Card>)}
    {items.length === 0 ? <Card className="p-8 text-center text-sm text-[var(--muted)]">No dependency lock evidence has been recorded.</Card> : items.map((item) => <Card key={item.inventory.id} className="p-5"><div className="flex flex-wrap items-center gap-2"><Badge tone={item.current ? "success" : "warning"}>{item.current ? "current source" : "stale source"}</Badge><span className="font-mono text-xs">{item.inventory.commit_id}</span></div><p className="mt-2 text-xs text-[var(--muted)]">Recorded by {item.inventory.recorded_by} · {item.releases.length} releases · {item.builds.length} builds · {item.deployments.filter((value) => value.current).length} current environments · {item.deployments.filter((value) => value.state === "succeeded" && !value.current).length} historical successes</p><div className="mt-4 grid gap-3">{item.inventory.entries.map((entry) => <div key={entry.name} className="rounded-lg border border-[var(--line)] p-3 text-sm"><div className="flex flex-wrap items-center gap-2"><Link href={`/packages`} className="font-semibold text-[var(--brand)] hover:underline">{entry.name} {entry.version || "not locked"}</Link><Badge tone={entry.state === "resolved" ? "success" : entry.state === "stale" ? "warning" : "danger"}>{entry.state}</Badge><Badge>{entry.direct ? "direct" : "transitive"}</Badge></div><p className="mt-1 text-xs text-[var(--muted)]">{entry.paths.join(", ")} · license {entry.license || "gap"} · support {entry.support || "gap"}</p>{entry.provenance_gaps?.length ? <p className="mt-2 text-xs text-[var(--warning)]">{entry.provenance_gaps.join(" · ")}</p> : null}</div>)}</div></Card>)}</div>;
}
