"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api, type ExplanationConversation, type ExplanationEntry } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type ContextKind = ExplanationConversation["context"]["kind"];
type EntryKind = ExplanationEntry["kind"];

export function ExplanationWorkspace({ repositoryID, initialRef = "", initialPath = "", initialKind = "repository", initialResourceID = "" }: { repositoryID:string; initialRef?:string; initialPath?:string; initialKind?:ContextKind; initialResourceID?:string }) {
  const { token } = useAuth();
  const [history,setHistory]=useState<ExplanationConversation[]>([]);
  const [selected,setSelected]=useState<ExplanationConversation|null>(null);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  const load=useCallback(async()=>{if(!token)return;try{const result=await api<{conversations:ExplanationConversation[]}>(`/repositories/${repositoryID}/explanations`,{},token);setHistory(result.conversations);}catch(reason){setError(reason instanceof Error?reason.message:"Investigations could not be loaded.");}},[repositoryID,token]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);

  async function mutate(path:string, body:unknown){if(!token||!selected)return;setBusy(true);setError("");try{const next=await api<ExplanationConversation>(`/repositories/${repositoryID}/explanations/${selected.id}/${path}`,{method:"POST",body:JSON.stringify(body)},token);setSelected(next);setHistory(current=>current.map(item=>item.id===next.id?next:item));}catch(reason){setError(reason instanceof Error?reason.message:"Investigation could not be updated.");}finally{setBusy(false);}}
  async function open(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;setBusy(true);setError("");const form=new FormData(event.currentTarget);const kind=String(form.get("kind")) as ContextKind;try{const response=await fetch(`/api/repositories/${repositoryID}/explanations`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({question:String(form.get("question")),ref:String(form.get("ref")),context:{kind,resource_id:String(form.get("resource_id")||"")||undefined,path:String(form.get("path")||"")||undefined}})});if(!response.ok||!response.body)throw new Error("Investigation could not be opened.");const reader=response.body.getReader(),decoder=new TextDecoder();let pending="";for(;;){const {done,value}=await reader.read();pending+=decoder.decode(value,{stream:!done});const lines=pending.split("\n");pending=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const item=JSON.parse(line) as {event:string;conversation?:ExplanationConversation};if(item.event==="done"&&item.conversation){setSelected(item.conversation);setHistory(current=>[item.conversation!,...current]);}}if(done)break;}}catch(reason){setError(reason instanceof Error?reason.message:"Investigation could not be opened.");}finally{setBusy(false);}}
  function addEntry(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const kind=String(form.get("kind")) as EntryKind;void mutate("entries",{kind,body:String(form.get("body")),path:String(form.get("path")||"")||undefined,start_line:Number(form.get("start_line"))||undefined,resource_id:String(form.get("resource_id")||"")||undefined,supersedes_id:String(form.get("supersedes_id")||"")||undefined});event.currentTarget.reset();}
  const staleCount=selected?.entries.flatMap(entry=>entry.citations??[]).filter(citation=>citation.stale).length??0;

  return <div className="space-y-6">
    <header><Link href={`/repositories/${repositoryID}`} className="text-sm text-[var(--muted)] hover:text-[var(--brand)]">Repository</Link><h1 className="mt-2 text-2xl font-semibold">Code investigations</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Build a shared, revision-pinned trail of evidence, questions, observations, hypotheses, challenges, agent findings, and conclusions that a peer can verify midway.</p></header>
    <Card className="p-5"><form onSubmit={open} className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><label className="text-xs font-semibold">Context<select name="kind" defaultValue={initialKind} className="mt-1 min-h-10 w-full rounded-lg border border-[var(--line-strong)] bg-white px-3 font-normal"><option value="repository">Repository</option><option value="file">File</option><option value="proposal">Proposal</option><option value="task">Task</option><option value="pull_request">Pull request</option><option value="incident">Incident</option><option value="workspace">Workspace</option></select></label><label className="text-xs font-semibold">Context ID<input name="resource_id" defaultValue={initialResourceID} className="mt-1 min-h-10 w-full rounded-lg border border-[var(--line-strong)] px-3 font-mono font-normal"/></label><label className="text-xs font-semibold">File path<input name="path" defaultValue={initialPath} className="mt-1 min-h-10 w-full rounded-lg border border-[var(--line-strong)] px-3 font-mono font-normal"/></label></div><label className="block text-xs font-semibold">Revision or branch<input name="ref" defaultValue={initialRef} className="mt-1 min-h-10 w-full rounded-lg border border-[var(--line-strong)] px-3 font-mono font-normal"/></label><label className="block text-xs font-semibold">Framing question<textarea name="question" required maxLength={2000} rows={3} className="mt-1 w-full rounded-lg border border-[var(--line-strong)] p-3 font-normal" placeholder="Where does this authorization path fail closed?"/></label><Button disabled={busy}>Open investigation</Button></form></Card>
    {error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
    {selected&&<section className="space-y-4"><Card className="p-5"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{selected.question}</h2><Badge tone={selected.analysis_status==="complete"?"success":"warning"}>{selected.analysis_status}</Badge>{staleCount>0&&<Badge tone="warning">{staleCount} stale citations</Badge>}</div><p className="mt-2 text-xs text-[var(--muted)]"><code>{selected.revision}</code> · {selected.participants.length} participant{selected.participants.length===1?"":"s"}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void mutate("participants",{user_id:String(form.get("user_id"))});event.currentTarget.reset();}} className="flex gap-2"><input name="user_id" required placeholder="Repository participant ID" className="min-h-10 min-w-0 flex-1 rounded-lg border border-[var(--line-strong)] px-3 text-sm"/><Button disabled={busy}>Invite peer</Button></form><form onSubmit={event=>{event.preventDefault();void mutate("reruns",{ref:String(new FormData(event.currentTarget).get("ref"))});}} className="flex gap-2"><input name="ref" required placeholder="New revision or branch" className="min-h-10 min-w-0 flex-1 rounded-lg border border-[var(--line-strong)] px-3 font-mono text-sm"/><Button disabled={busy}>Rerun analysis</Button></form></div></Card>
      <div className="space-y-3">{selected.entries.map((entry,index)=><Card key={entry.id} className="p-4"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-[var(--muted)]">{index+1}</span><Badge tone={entry.kind==="challenge"?"warning":entry.kind==="conclusion"?"success":"info"}>{entry.kind.replaceAll("_"," ")}</Badge><span className="text-xs text-[var(--muted)]">{entry.actor_id} · {new Date(entry.created_at).toLocaleString()}</span>{entry.supersedes_id&&<span className="text-xs text-[var(--muted)]">challenges #{selected.entries.findIndex(item=>item.id===entry.supersedes_id)+1}</span>}</div><p className="mt-3 text-sm leading-6">{entry.body}</p>{entry.citations?.map((citation,citationIndex)=><div key={citationIndex} className="mt-2 text-xs"><Badge tone={citation.stale?"warning":"success"}>{citation.stale?"stale":"current"}</Badge>{citation.path?<Link className="ml-2 font-mono text-[var(--brand)] hover:underline" href={`/repositories/${repositoryID}?ref=${citation.revision}&path=${encodeURIComponent(citation.path)}${citation.start_line?`#L${citation.start_line}`:""}`}>{citation.path}{citation.start_line?`:${citation.start_line}`:""}</Link>:<code className="ml-2">{citation.revision.slice(0,12)}</code>}<span className="ml-2 text-[var(--muted)]">{citation.label}</span></div>)}</Card>)}</div>
      <Card className="p-5"><h2 className="font-semibold">Add to the canvas</h2><form onSubmit={addEntry} className="mt-3 space-y-3"><div className="grid gap-3 md:grid-cols-3"><select name="kind" className="min-h-10 rounded-lg border border-[var(--line-strong)] bg-white px-3 text-sm"><option value="query">Query</option><option value="code_reference">Code reference</option><option value="runtime_observation">Runtime observation</option><option value="hypothesis">Hypothesis</option><option value="challenge">Challenge</option><option value="conclusion">Conclusion</option></select><input name="path" placeholder="Code path (for reference)" className="min-h-10 rounded-lg border border-[var(--line-strong)] px-3 text-sm"/><input name="start_line" type="number" min="1" placeholder="Start line" className="min-h-10 rounded-lg border border-[var(--line-strong)] px-3 text-sm"/><input name="resource_id" placeholder="Bounded workspace ID" className="min-h-10 rounded-lg border border-[var(--line-strong)] px-3 text-sm"/><select name="supersedes_id" className="min-h-10 rounded-lg border border-[var(--line-strong)] bg-white px-3 text-sm"><option value="">Does not supersede</option>{selected.entries.map((entry,index)=><option key={entry.id} value={entry.id}>Challenge #{index+1}</option>)}</select></div><textarea name="body" required maxLength={4000} rows={3} placeholder="Record what another participant needs to verify…" className="w-full rounded-lg border border-[var(--line-strong)] p-3 text-sm"/><Button disabled={busy}>Add entry</Button></form></Card>
    </section>}
    <section><h2 className="text-lg font-semibold">Your investigations</h2>{history.length?<div className="mt-3 space-y-2">{history.map(item=><button key={item.id} type="button" onClick={()=>setSelected(item)} className="w-full rounded-xl border border-[var(--line)] bg-white p-4 text-left hover:border-[var(--brand)]"><span className="text-sm font-semibold">{item.question}</span><span className="mt-1 block text-xs text-[var(--muted)]">Opened by {item.asked_by} · {item.entries.length} canvas entries · <code>{item.revision.slice(0,12)}</code></span></button>)}</div>:<Card className="mt-3 p-5 text-sm text-[var(--muted)]">No investigations yet.</Card>}</section>
  </div>;
}
