"use client";

import { useEffect, useState, type FormEvent } from "react";
import { api, type Repository } from "@/lib/api";
import { AccessGate, useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Extension = { id:string; principal_type:"extension"; name:string; description:string; owner_id:string; operator_contact:string; capabilities:string[]; callback_endpoint:{url:string;verified_at:string}; action_endpoint:{url:string;verified_at:string}; requested_permissions:{resource:string;actions:string[]}[]; supported_events:string[]; credential_rotation:{interval_days:number;overlap_hours:number}; authority_preview:{installed:boolean;summary:string;items:{resource:string;requested_actions:string[];effective_actions:string[];decision:string;reason:string}[]}; status:string; created_at:string };
type Installation={id:string;extension_id:string;extension_name:string;owner_type:string;owner_id:string;repository_ids:string[];resource_types:string[];capability_decisions:{capability:string;decision:string;reason?:string}[];settings:Record<string,string>;effective_access:{resource:string;actions:string[]}[];status:string;version:number;events:{type:string;actor_id:string;at:string}[]};
const lines=(value:FormDataEntryValue|null)=>String(value??"").split(/[,\n]/).map(x=>x.trim()).filter(Boolean);

export function ExtensionsWorkspace(){return <AccessGate><Workspace/></AccessGate>}
function Workspace(){
  const {token}=useAuth();const [items,setItems]=useState<Extension[]>([]);const [selected,setSelected]=useState<Extension|null>(null);const [installations,setInstallations]=useState<Installation[]>([]);const [repositories,setRepositories]=useState<Repository[]>([]);const [error,setError]=useState("");const [pending,setPending]=useState(false);
  useEffect(()=>{if(!token)return;void Promise.all([api<{extensions:Extension[]}>("/extensions",{},token),api<{installations:Installation[]}>("/extension-installations",{},token),api<{repositories:Repository[]}>("/repositories",{},token)]).then(([x,y,z])=>{setItems(x.extensions);setInstallations(y.installations);setRepositories(z.repositories)}).catch(e=>setError(e instanceof Error?e.message:"Extensions unavailable."))},[token]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;setPending(true);setError("");const d=new FormData(event.currentTarget);try{const resource=String(d.get("resource")??"").trim();const created=await api<Extension>("/extensions",{method:"POST",body:JSON.stringify({name:d.get("name"),description:d.get("description"),operator_contact:d.get("operator_contact"),capabilities:lines(d.get("capabilities")),callback_endpoint:d.get("callback_endpoint"),action_endpoint:d.get("action_endpoint"),requested_permissions:[{resource,actions:lines(d.get("actions"))}],supported_events:lines(d.get("supported_events")),credential_rotation:{interval_days:Number(d.get("interval_days")),overlap_hours:Number(d.get("overlap_hours"))}})},token);setItems(x=>[created,...x]);setSelected(created);event.currentTarget.reset()}catch(e){setError(e instanceof Error?e.message:"Registration failed.")}finally{setPending(false)}}
  async function install(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token||!selected)return;setPending(true);setError("");const d=new FormData(event.currentTarget),repositoryID=String(d.get("repository_id"));try{const created=await api<Installation>(`/extensions/${selected.id}/installations`,{method:"POST",body:JSON.stringify({owner_type:"repository",owner_id:repositoryID,repository_ids:[repositoryID],resource_types:lines(d.get("resource_types")),capability_decisions:selected.capabilities.map(capability=>({capability,decision:d.get(`capability:${capability}`)})),settings:Object.fromEntries(lines(d.get("settings")).map(x=>x.split("=").map(y=>y.trim())).filter(x=>x.length===2))})},token);setInstallations(x=>[created,...x])}catch(e){setError(e instanceof Error?e.message:"Installation failed.")}finally{setPending(false)}}
  async function lifecycle(x:Installation,action:string){if(!token)return;setPending(true);setError("");try{const changed=await api<Installation>(`/extension-installations/${x.id}/${action}`,{method:"POST",body:JSON.stringify({version:x.version})},token);setInstallations(all=>all.map(v=>v.id===changed.id?changed:v))}catch(e){setError(e instanceof Error?e.message:"Lifecycle change failed.")}finally{setPending(false)}}
  return <div className="space-y-6"><header><p className="font-mono text-xs font-semibold uppercase tracking-[.16em] text-[var(--brand)]">External collaborators</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em]">Extensions</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Register who operates an integration and what it will request before any project shares context. Registration verifies both service endpoints but grants no installation or user authority.</p></header>
  <div className="grid gap-6 xl:grid-cols-[minmax(0,.85fr)_minmax(24rem,1.15fr)]"><Card className="p-5"><h2 className="font-semibold">Register extension</h2><form onSubmit={submit} className="mt-4 space-y-3"><Field name="name" label="Extension name" placeholder="Review lens"/><Field name="description" label="Purpose" placeholder="Adds independently operated review evidence"/><Field name="operator_contact" label="Operator contact" type="email" placeholder="ops@example.com"/><Field name="capabilities" label="Declared capabilities" placeholder="review annotations, risk summaries" hint="Comma-separated"/><Field name="callback_endpoint" label="Callback endpoint" type="url" placeholder="https://service.example/events"/><Field name="action_endpoint" label="Action endpoint" type="url" placeholder="https://service.example/actions"/><div className="grid gap-3 sm:grid-cols-2"><Field name="resource" label="Requested resource" placeholder="pull_requests"/><Field name="actions" label="Requested actions" placeholder="read, comment"/></div><Field name="supported_events" label="Supported events" placeholder="pull_request.opened, pull_request.synchronized"/><div className="grid gap-3 sm:grid-cols-2"><Field name="interval_days" label="Rotate every (days)" type="number" min="1" max="365" defaultValue="30"/><Field name="overlap_hours" label="Credential overlap (hours)" type="number" min="0" max="168" defaultValue="2"/></div><p className="rounded-lg bg-[var(--canvas)] p-3 text-xs leading-5 text-[var(--muted)]">Each endpoint must echo the request&apos;s <code>Vivarium-Extension-Challenge</code> value in a response header. HTTPS and publicly routable addresses are required.</p>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}<Button type="submit" disabled={pending}>{pending?"Verifying endpoints…":"Verify and register"}</Button></form></Card>
  <section className="space-y-4"><Card className="p-5"><h2 className="font-semibold">Verified identities</h2>{items.length===0?<p className="mt-3 text-sm text-[var(--muted)]">No extensions registered yet.</p>:<div className="mt-3 space-y-2">{items.map(x=><button key={x.id} onClick={()=>setSelected(x)} className="flex w-full items-center justify-between rounded-lg border border-[var(--line)] p-3 text-left"><span><strong className="block text-sm">{x.name}</strong><span className="font-mono text-xs text-[var(--muted)]">extension:{x.id}</span></span><Badge tone="success">verified</Badge></button>)}</div>}</Card>{selected&&<Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{selected.name}</h2><p className="mt-1 text-sm text-[var(--muted)]">Operated via {selected.operator_contact}</p></div><Badge tone="info">distinct extension identity</Badge></div><dl className="mt-5 grid gap-3 text-xs sm:grid-cols-2"><Info label="Callback" value={selected.callback_endpoint.url}/><Info label="Actions" value={selected.action_endpoint.url}/><Info label="Events" value={selected.supported_events.join(", ")}/><Info label="Verified" value={new Date(selected.callback_endpoint.verified_at).toLocaleString()}/></dl><form onSubmit={install} className="mt-5 space-y-3 border-t border-[var(--line)] pt-4"><h3 className="font-semibold">Install with exact access</h3><label className="block text-xs font-semibold">Owned repository<select required name="repository_id" className="mt-1.5 min-h-10 w-full rounded-lg border px-3 font-normal">{repositories.filter(x=>x.owner_id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Field name="resource_types" label="Permitted resource types" placeholder={selected.requested_permissions.map(x=>x.resource).join(", ")}/>{selected.capabilities.map(x=><label key={x} className="flex items-center justify-between gap-3 text-xs font-semibold"><span>{x}</span><select name={`capability:${x}`} className="min-h-9 rounded-lg border px-2 font-normal"><option value="approved">Approve</option><option value="denied">Deny</option></select></label>)}<Field name="settings" label="Non-secret settings" placeholder="label=extension-review" hint="Comma-separated key=value; secret/token/password keys are rejected"/><Button type="submit" disabled={pending||repositories.length===0}>Install extension</Button></form></Card>}</section></div>
  <Card className="p-5"><h2 className="font-semibold">Effective installations</h2><div className="mt-3 grid gap-3 lg:grid-cols-2">{installations.map(x=><article key={x.id} className="rounded-lg border border-[var(--line)] p-4"><div className="flex justify-between gap-3"><div><strong className="text-sm">{x.extension_name}</strong><p className="font-mono text-xs text-[var(--muted)]">{x.owner_type}:{x.owner_id}</p></div><Badge tone={x.status==="active"?"success":x.status==="removed"?"danger":"warning"}>{x.status}</Badge></div><p className="mt-3 text-xs"><strong>Repositories:</strong> {x.repository_ids.join(", ")}</p><p className="mt-1 text-xs"><strong>Effective:</strong> {x.effective_access.length?x.effective_access.map(a=>`${a.resource} (${a.actions.join(", ")})`).join("; "):"none"}</p><p className="mt-1 text-xs"><strong>Decisions:</strong> {x.capability_decisions.map(d=>`${d.capability}: ${d.decision}`).join("; ")}</p><p className="mt-1 text-xs text-[var(--muted)]">{x.events.length} retained actor event{x.events.length===1?"":"s"}</p><div className="mt-3 flex gap-2">{x.status==="active"&&<><Button variant="secondary" onClick={()=>void lifecycle(x,"suspend")} disabled={pending}>Suspend</Button><Button variant="quiet" onClick={()=>void lifecycle(x,"remove")} disabled={pending}>Remove</Button></>}{x.status==="suspended"&&<Button onClick={()=>void lifecycle(x,"resume")} disabled={pending}>Resume</Button>}</div></article>)}</div></Card></div>
}
function Field({label,hint,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;hint?:string}){return <label className="block text-xs font-semibold">{label}<input required className="mt-1.5 min-h-10 w-full rounded-lg border border-[var(--line-strong)] px-3 text-sm font-normal" {...props}/>{hint&&<span className="mt-1 block font-normal text-[var(--muted)]">{hint}</span>}</label>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="font-semibold uppercase tracking-wide text-[var(--muted)]">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>}
