"use client";

import { useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { AccessGate, useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Extension = { id:string; principal_type:"extension"; name:string; description:string; owner_id:string; operator_contact:string; capabilities:string[]; callback_endpoint:{url:string;verified_at:string}; action_endpoint:{url:string;verified_at:string}; requested_permissions:{resource:string;actions:string[]}[]; supported_events:string[]; credential_rotation:{interval_days:number;overlap_hours:number}; authority_preview:{installed:boolean;summary:string;items:{resource:string;requested_actions:string[];effective_actions:string[];decision:string;reason:string}[]}; status:string; created_at:string };
const lines=(value:FormDataEntryValue|null)=>String(value??"").split(/[,\n]/).map(x=>x.trim()).filter(Boolean);

export function ExtensionsWorkspace(){return <AccessGate><Workspace/></AccessGate>}
function Workspace(){
  const {token}=useAuth();const [items,setItems]=useState<Extension[]>([]);const [selected,setSelected]=useState<Extension|null>(null);const [error,setError]=useState("");const [pending,setPending]=useState(false);
  useEffect(()=>{if(!token)return;void api<{extensions:Extension[]}>("/extensions",{},token).then(x=>setItems(x.extensions)).catch(e=>setError(e instanceof Error?e.message:"Extensions unavailable."))},[token]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;setPending(true);setError("");const d=new FormData(event.currentTarget);try{const resource=String(d.get("resource")??"").trim();const created=await api<Extension>("/extensions",{method:"POST",body:JSON.stringify({name:d.get("name"),description:d.get("description"),operator_contact:d.get("operator_contact"),capabilities:lines(d.get("capabilities")),callback_endpoint:d.get("callback_endpoint"),action_endpoint:d.get("action_endpoint"),requested_permissions:[{resource,actions:lines(d.get("actions"))}],supported_events:lines(d.get("supported_events")),credential_rotation:{interval_days:Number(d.get("interval_days")),overlap_hours:Number(d.get("overlap_hours"))}})},token);setItems(x=>[created,...x]);setSelected(created);event.currentTarget.reset()}catch(e){setError(e instanceof Error?e.message:"Registration failed.")}finally{setPending(false)}}
  return <div className="space-y-6"><header><p className="font-mono text-xs font-semibold uppercase tracking-[.16em] text-[var(--brand)]">External collaborators</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em]">Extensions</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Register who operates an integration and what it will request before any project shares context. Registration verifies both service endpoints but grants no installation or user authority.</p></header>
  <div className="grid gap-6 xl:grid-cols-[minmax(0,.85fr)_minmax(24rem,1.15fr)]"><Card className="p-5"><h2 className="font-semibold">Register extension</h2><form onSubmit={submit} className="mt-4 space-y-3"><Field name="name" label="Extension name" placeholder="Review lens"/><Field name="description" label="Purpose" placeholder="Adds independently operated review evidence"/><Field name="operator_contact" label="Operator contact" type="email" placeholder="ops@example.com"/><Field name="capabilities" label="Declared capabilities" placeholder="review annotations, risk summaries" hint="Comma-separated"/><Field name="callback_endpoint" label="Callback endpoint" type="url" placeholder="https://service.example/events"/><Field name="action_endpoint" label="Action endpoint" type="url" placeholder="https://service.example/actions"/><div className="grid gap-3 sm:grid-cols-2"><Field name="resource" label="Requested resource" placeholder="pull_requests"/><Field name="actions" label="Requested actions" placeholder="read, comment"/></div><Field name="supported_events" label="Supported events" placeholder="pull_request.opened, pull_request.synchronized"/><div className="grid gap-3 sm:grid-cols-2"><Field name="interval_days" label="Rotate every (days)" type="number" min="1" max="365" defaultValue="30"/><Field name="overlap_hours" label="Credential overlap (hours)" type="number" min="0" max="168" defaultValue="2"/></div><p className="rounded-lg bg-[var(--canvas)] p-3 text-xs leading-5 text-[var(--muted)]">Each endpoint must echo the request&apos;s <code>Vivarium-Extension-Challenge</code> value in a response header. HTTPS and publicly routable addresses are required.</p>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}<Button type="submit" disabled={pending}>{pending?"Verifying endpoints…":"Verify and register"}</Button></form></Card>
  <section className="space-y-4"><Card className="p-5"><h2 className="font-semibold">Owned identities</h2>{items.length===0?<p className="mt-3 text-sm text-[var(--muted)]">No extensions registered yet.</p>:<div className="mt-3 space-y-2">{items.map(x=><button key={x.id} onClick={()=>setSelected(x)} className="flex w-full items-center justify-between rounded-lg border border-[var(--line)] p-3 text-left"><span><strong className="block text-sm">{x.name}</strong><span className="font-mono text-xs text-[var(--muted)]">extension:{x.id}</span></span><Badge tone="success">verified</Badge></button>)}</div>}</Card>{selected&&<Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{selected.name}</h2><p className="mt-1 text-sm text-[var(--muted)]">Operated via {selected.operator_contact}</p></div><Badge tone="info">distinct extension identity</Badge></div><dl className="mt-5 grid gap-3 text-xs sm:grid-cols-2"><Info label="Callback" value={selected.callback_endpoint.url}/><Info label="Actions" value={selected.action_endpoint.url}/><Info label="Events" value={selected.supported_events.join(", ")}/><Info label="Rotation" value={`${selected.credential_rotation.interval_days} days · ${selected.credential_rotation.overlap_hours}h overlap`}/></dl><div className="mt-5 rounded-lg bg-[var(--warning-soft)] p-4"><p className="text-sm font-semibold">Effective authority: none</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{selected.authority_preview.summary}</p>{selected.authority_preview.items.map(x=><p key={x.resource} className="mt-2 text-xs"><strong>{x.resource}</strong>: requested {x.requested_actions.join(", ")} · effective {x.effective_actions.length?x.effective_actions.join(", "):"none"}</p>)}</div><p className="mt-4 text-xs leading-5 text-[var(--muted)]">This principal cannot authenticate as owner <code>{selected.owner_id}</code>, a user, or an approved agent. Registration issues no bearer credential.</p></Card>}</section></div></div>
}
function Field({label,hint,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;hint?:string}){return <label className="block text-xs font-semibold">{label}<input required className="mt-1.5 min-h-10 w-full rounded-lg border border-[var(--line-strong)] px-3 text-sm font-normal" {...props}/>{hint&&<span className="mt-1 block font-normal text-[var(--muted)]">{hint}</span>}</label>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="font-semibold uppercase tracking-wide text-[var(--muted)]">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>}
