"use client";
import { useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Action={id:string;label:string;description:string;inputs:{name:string;label:string;required:boolean;default?:string}[];effects:string[]};
type Contribution={id:string;extension_name:string;kind:string;state?:string;title:string;body?:string;revision:string;trusted:boolean;trust_reason:string;annotations?:string[];artifacts?:{name:string;url:string;sha256:string}[];links?:string[];actions?:Action[];invocations:{id:string;action_id:string;actor_id:string;status:string;created_at:string}[]};
export function ExtensionContributions({repositoryID,pullRequestID,revision}:{repositoryID:string;pullRequestID:string;revision:string}){
 const {token}=useAuth(),[items,setItems]=useState<Contribution[]>([]),[error,setError]=useState("");
 async function load(){if(!token)return;try{const v=await api<{contributions:Contribution[]}>(`/repositories/${repositoryID}/extension-contributions/pull_requests/${pullRequestID}`,{},token);setItems(v.contributions)}catch(e){setError(e instanceof Error?e.message:"Extension contributions unavailable.")}}
 useEffect(()=>{if(!token)return;void api<{contributions:Contribution[]}>(`/repositories/${repositoryID}/extension-contributions/pull_requests/${pullRequestID}`,{},token).then(v=>setItems(v.contributions)).catch(e=>setError(e instanceof Error?e.message:"Extension contributions unavailable."))},[token,repositoryID,pullRequestID]);
 async function invoke(event:FormEvent<HTMLFormElement>,item:Contribution,action:Action){event.preventDefault();if(!token)return;const data=new FormData(event.currentTarget);try{await api(`/repositories/${repositoryID}/extension-contributions/pull_requests/${pullRequestID}/${item.id}/actions/${action.id}`,{method:"POST",body:JSON.stringify({revision,inputs:Object.fromEntries(action.inputs.map(x=>[x.name,String(data.get(x.name)??x.default??"")]))})},token);await load()}catch(e){setError(e instanceof Error?e.message:"Action request failed.")}}
 if(!items.length&&!error)return null;
 return <section className="scroll-mt-24 space-y-3"><div className="flex items-baseline justify-between gap-3"><h2 className="text-lg font-semibold">Extension collaborators</h2><span className="text-xs text-[var(--muted)]">Attributed evidence, never implicit authority</span></div>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}{items.map(item=><Card key={item.id} className="p-5"><div className="flex flex-wrap items-center gap-2"><Badge tone="info">extension · {item.extension_name}</Badge><Badge tone={item.state==="success"?"success":"neutral"}>{item.kind}{item.state?` · ${item.state}`:""}</Badge><code className="text-xs text-[var(--muted)]">{item.revision.slice(0,7)}</code></div><h3 className="mt-3 font-semibold">{item.title}</h3>{item.body&&<p className="mt-2 whitespace-pre-wrap text-sm leading-6">{item.body}</p>}<p className="mt-3 text-xs text-[var(--muted)]">{item.trusted?item.trust_reason:"Untrusted historical output"}</p>{item.actions?.map(action=><form key={action.id} onSubmit={e=>void invoke(e,item,action)} className="mt-4 rounded-lg border border-[var(--line)] p-4"><strong className="text-sm">{action.label}</strong><p className="mt-1 text-xs text-[var(--muted)]">{action.description}</p>{action.inputs.map(input=><label key={input.name} className="mt-3 block text-xs font-semibold">{input.label}<input name={input.name} required={input.required} defaultValue={input.default} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label>)}<div className="mt-3 rounded bg-[var(--canvas)] p-3 text-xs"><strong>Effect preview</strong><ul className="mt-1 list-disc pl-4">{action.effects.map(x=><li key={x}>{x}</li>)}</ul></div><Button className="mt-3" type="submit">Request action</Button></form>)}</Card>)}</section>
}
