"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "./auth";
import { api } from "@/lib/api";

type Document = { instance_id:string;name:string;version:number;issued_at:string;endpoints:{kind:string;url:string}[];capabilities:string[];operators:string[];keys:{id:string;algorithm:string;public_key:string;retired_at?:string}[] };
type Peer = { instance_id:string;discovery_url:string;status:"trusted"|"changed"|"unreachable"|"revoked";trust_version:number;document:Document;last_checked_at:string;last_verified_at:string;last_error?:string };

export function FederationWorkspace() {
  const { token } = useAuth(); const [peers,setPeers]=useState<Peer[]>([]); const [url,setURL]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!token)return;try{setPeers((await api<{peers:Peer[]}>("/federation/peers",{},token)).peers);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load federation peers.")}},[token]);
  useEffect(()=>{if(!token)return;let active=true;api<{peers:Peer[]}>("/federation/peers",{},token).then(result=>{if(active)setPeers(result.peers)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load federation peers.")});return()=>{active=false}},[token]);
  async function discover(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await api<Peer>("/federation/peers",{method:"POST",body:JSON.stringify({discovery_url:url})},token);setURL("");await load()}catch(e){setError(e instanceof Error?e.message:"Could not discover peer.")}finally{setBusy(false)}}
  async function act(peer:Peer,action:"refresh"|"trust"|"revoke"){setBusy(true);setError("");try{if(action==="refresh")await api(`/federation/peers/${peer.instance_id}/refresh`,{method:"POST"},token);else await api(`/federation/peers/${peer.instance_id}`,{method:"PATCH",body:JSON.stringify({version:peer.trust_version,action})},token);await load()}catch(e){setError(e instanceof Error?e.message:"Could not update peer.")}finally{setBusy(false)}}
  return <div className="space-y-8"><header><p className="text-sm font-semibold text-[var(--brand-strong)]">Independent communities</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Federation identities</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Discover signed instance identities and retain explicit local trust. Remote identities provide attribution only—they never become local accounts or inherit local authority.</p></header>
    <form onSubmit={discover} className="rounded-xl border border-[var(--line)] bg-white p-5"><label htmlFor="peer-url" className="text-sm font-semibold">Peer instance URL</label><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input id="peer-url" type="url" required value={url} onChange={e=>setURL(e.target.value)} placeholder="https://community.example" className="min-h-10 flex-1 rounded-lg border border-[var(--line-strong)] px-3 text-sm outline-none focus:ring-2 focus:ring-[var(--brand)]"/><button disabled={busy||!token} className="min-h-10 rounded-lg bg-[var(--brand)] px-4 text-sm font-semibold text-white disabled:opacity-50">Discover identity</button></div>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</form>
    <section aria-labelledby="peers-heading"><div className="flex items-end justify-between"><h2 id="peers-heading" className="text-xl font-semibold">Known peers</h2><span className="text-xs text-[var(--muted)]">{peers.length} instance{peers.length===1?"":"s"}</span></div><div className="mt-3 grid gap-4">{peers.map(p=><article key={p.instance_id} className="rounded-xl border border-[var(--line)] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{p.document.name}</h3><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${p.status==="trusted"?"bg-emerald-50 text-emerald-700":p.status==="revoked"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-800"}`}>{p.status}</span></div><p className="mt-1 font-mono text-xs text-[var(--muted)]">{p.instance_id}</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>act(p,"refresh")} className="rounded-lg border border-[var(--line-strong)] px-3 py-1.5 text-xs font-semibold">Refresh</button>{p.status!=="trusted"&&p.status!=="revoked"&&<button disabled={busy} onClick={()=>act(p,"trust")} className="rounded-lg bg-[var(--brand)] px-3 py-1.5 text-xs font-semibold text-white">Accept change</button>}{p.status!=="revoked"&&<button disabled={busy} onClick={()=>act(p,"revoke")} className="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-700">Revoke trust</button>}</div></div>{p.last_error&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{p.last_error}</p>}<dl className="mt-4 grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">Capabilities</dt><dd className="mt-1">{p.document.capabilities.join(", ")}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">Operators</dt><dd className="mt-1">{p.document.operators.join(", ")||"Not declared"}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">Signing key</dt><dd className="mt-1 break-all font-mono text-xs">{p.document.keys.find(k=>!k.retired_at)?.id}</dd></div></dl></article>)}{token&&peers.length===0&&<p className="rounded-xl border border-dashed border-[var(--line-strong)] p-8 text-center text-sm text-[var(--muted)]">No peers have been discovered yet.</p>}{!token&&<p className="rounded-xl border border-dashed border-[var(--line-strong)] p-8 text-center text-sm text-[var(--muted)]">Sign in to manage this instance&apos;s peer trust.</p>}</div></section></div>;
}
