"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "./auth";
import { api } from "@/lib/api";

type Document = { instance_id:string;name:string;version:number;issued_at:string;endpoints:{kind:string;url:string}[];capabilities:string[];operators:string[];keys:{id:string;algorithm:string;public_key:string;retired_at?:string}[] };
type Peer = { instance_id:string;discovery_url:string;status:"trusted"|"changed"|"unreachable"|"revoked";trust_version:number;document:Document;last_checked_at:string;last_verified_at:string;last_error?:string };
type RemoteRepository = { reference:string;status:"current"|"unreachable"|"inaccessible"|"unsupported"|"invalid-signature";remote_revision?:string;signature_verified:boolean;identity_document_version?:number;fetched_at?:string;stale_since?:string;last_error?:string;snapshot?:{name:string;visibility:string;default_branch:string;revision:string;branches:{name:string;revision:string}[];releases:{id:string;version:string;notes:string;revision:string;published_at:string}[];contributor_guidance?:{version:number;goals:string;prerequisites:string[];setup_summary:string;communication:string;review_policy:string};issues:{id:string;title:string;severity:string;status:string;version:number;updated_at:string}[];opportunities:{id:string;title:string;expected_outcome:string;scope:string;risk:string;revision:string;status:string;version:number;estimated_minutes:number;required_skills:string[];agent_assistance:boolean}[];capabilities:string[];authoritative_url:string;generated_at:string} };
type Followed = { follow:{reference:string};repository:RemoteRepository };

export function FederationWorkspace() {
  const { token } = useAuth(); const [peers,setPeers]=useState<Peer[]>([]); const [url,setURL]=useState(""); const [reference,setReference]=useState(""); const [remote,setRemote]=useState<RemoteRepository>(); const [follows,setFollows]=useState<Followed[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!token)return;try{setPeers((await api<{peers:Peer[]}>("/federation/peers",{},token)).peers);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load federation peers.")}},[token]);
  useEffect(()=>{if(!token)return;let active=true;api<{peers:Peer[]}>("/federation/peers",{},token).then(result=>{if(active)setPeers(result.peers)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load federation peers.")});return()=>{active=false}},[token]);
  useEffect(()=>{if(!token)return;api<{repositories:Followed[]}>("/federation/follows",{},token).then(v=>setFollows(v.repositories)).catch(()=>setFollows([]))},[token]);
  async function discover(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await api<Peer>("/federation/peers",{method:"POST",body:JSON.stringify({discovery_url:url})},token);setURL("");await load()}catch(e){setError(e instanceof Error?e.message:"Could not discover peer.")}finally{setBusy(false)}}
  async function act(peer:Peer,action:"refresh"|"trust"|"revoke"){setBusy(true);setError("");try{if(action==="refresh")await api(`/federation/peers/${peer.instance_id}/refresh`,{method:"POST"},token);else await api(`/federation/peers/${peer.instance_id}`,{method:"PATCH",body:JSON.stringify({version:peer.trust_version,action})},token);await load()}catch(e){setError(e instanceof Error?e.message:"Could not update peer.")}finally{setBusy(false)}}
  async function resolve(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{setRemote(await api<RemoteRepository>("/federation/repositories/resolve",{method:"POST",body:JSON.stringify({reference})},token))}catch(e){setError(e instanceof Error?e.message:"Could not resolve repository.")}finally{setBusy(false)}}
  async function follow(value:boolean){if(!remote)return;setBusy(true);try{const [peer,repository]=remote.reference.split(":");await api(`/federation/repositories/${peer}/${repository}/follow`,{method:"PUT",body:JSON.stringify({follow:value})},token);setFollows((await api<{repositories:Followed[]}>("/federation/follows",{},token)).repositories)}finally{setBusy(false)}}
  return <div className="space-y-8"><header><p className="text-sm font-semibold text-[var(--brand-strong)]">Independent communities</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Federation identities</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Discover signed instance identities and retain explicit local trust. Remote identities provide attribution only—they never become local accounts or inherit local authority.</p></header>
    <form onSubmit={discover} className="rounded-xl border border-[var(--line)] bg-white p-5"><label htmlFor="peer-url" className="text-sm font-semibold">Peer instance URL</label><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input id="peer-url" type="url" required value={url} onChange={e=>setURL(e.target.value)} placeholder="https://community.example" className="min-h-10 flex-1 rounded-lg border border-[var(--line-strong)] px-3 text-sm outline-none focus:ring-2 focus:ring-[var(--brand)]"/><button disabled={busy||!token} className="min-h-10 rounded-lg bg-[var(--brand)] px-4 text-sm font-semibold text-white disabled:opacity-50">Discover identity</button></div>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</form>
    <section className="space-y-3" aria-labelledby="remote-heading"><h2 id="remote-heading" className="text-xl font-semibold">Remote collaboration targets</h2><form onSubmit={resolve} className="flex gap-2"><input required value={reference} onChange={e=>setReference(e.target.value)} placeholder="instance-id:repository-id" className="min-h-10 flex-1 rounded-lg border px-3 font-mono text-sm"/><button disabled={busy||!token} className="rounded-lg bg-[var(--brand)] px-4 text-sm font-semibold text-white">Resolve</button></form>{remote&&<RemoteCard value={remote} followed={follows.some(v=>v.follow.reference===remote.reference)} onFollow={follow}/>} {follows.length>0&&<div><h3 className="text-sm font-semibold">Following locally</h3><div className="mt-2 grid gap-2">{follows.map(v=><button className="rounded-lg border bg-white p-3 text-left" key={v.follow.reference} onClick={()=>setRemote(v.repository)}><strong>{v.repository.snapshot?.name??v.follow.reference}</strong><span className="ml-2 text-xs text-[var(--muted)]">{v.repository.status} · {v.repository.remote_revision?.slice(0,10)}</span></button>)}</div></div>}</section>
    <section aria-labelledby="peers-heading"><div className="flex items-end justify-between"><h2 id="peers-heading" className="text-xl font-semibold">Known peers</h2><span className="text-xs text-[var(--muted)]">{peers.length} instance{peers.length===1?"":"s"}</span></div><div className="mt-3 grid gap-4">{peers.map(p=><article key={p.instance_id} className="rounded-xl border border-[var(--line)] bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{p.document.name} · {p.status}</h3><p className="font-mono text-xs text-[var(--muted)]">{p.instance_id}</p></div><div className="flex gap-2"><button onClick={()=>act(p,"refresh")}>Refresh</button>{p.status!=="trusted"&&p.status!=="revoked"&&<button onClick={()=>act(p,"trust")}>Accept change</button>}{p.status!=="revoked"&&<button onClick={()=>act(p,"revoke")} className="text-red-700">Revoke</button>}</div></div><p className="mt-3 text-xs text-[var(--muted)]">{p.document.capabilities.join(" · ")}</p>{p.last_error&&<p className="mt-2 text-sm text-amber-800">{p.last_error}</p>}</article>)}</div></section></div>;
}

function RemoteCard({value,followed,onFollow}:{value:RemoteRepository;followed:boolean;onFollow:(v:boolean)=>void}){const s=value.snapshot;return <article className="rounded-xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-[var(--brand)]">Remote · {value.status}</p><h3 className="text-xl font-semibold">{s?.name??value.reference}</h3><p className="font-mono text-xs text-[var(--muted)]">{value.reference} · revision {value.remote_revision?.slice(0,12)??"unavailable"}</p></div><button onClick={()=>onFollow(!followed)} className="rounded-lg border px-3 text-sm font-semibold">{followed?"Unfollow":"Follow updates"}</button></div>{value.last_error&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm">{value.last_error}{value.stale_since?" · showing stale cached metadata":""}</p>}{s&&<><p className="mt-3 text-sm">Authoritative at <a className="text-[var(--brand)] underline" href={s.authoritative_url}>{s.authoritative_url}</a>. This metadata is signed (identity document v{value.identity_document_version}) and is not locally controlled.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><section><h4 className="font-semibold">Branches</h4>{s.branches.map(v=><p className="text-sm" key={v.name}>{v.name} <code>{v.revision.slice(0,10)}</code></p>)}</section><section><h4 className="font-semibold">Releases</h4>{s.releases.map(v=><p className="text-sm" key={v.id}>{v.version} · {v.notes}</p>)}{!s.releases.length&&<p className="text-sm text-[var(--muted)]">Not published or unsupported</p>}</section><section><h4 className="font-semibold">Contributor guidance</h4><p className="text-sm">{s.contributor_guidance?.goals??"Not published or unsupported"}</p>{s.contributor_guidance?.prerequisites.map(v=><p className="text-xs" key={v}>• {v}</p>)}</section><section><h4 className="font-semibold">Issues</h4>{s.issues.map(v=><p className="text-sm" key={v.id}>{v.title} · {v.status}</p>)}{!s.issues.length&&<p className="text-sm text-[var(--muted)]">No permitted issues</p>}</section></div><section className="mt-4"><h4 className="font-semibold">Contribution opportunities</h4>{s.opportunities.map(v=><div className="mt-2 rounded-lg border p-3" key={v.id}><strong>{v.title}</strong><p className="text-sm">{v.expected_outcome}</p><p className="text-xs text-[var(--muted)]">{v.risk} risk · {v.estimated_minutes} minutes · revision {v.revision.slice(0,10)}</p></div>)}{!s.opportunities.length&&<p className="text-sm text-[var(--muted)]">No open permitted opportunities</p>}</section></>}</article>}
