"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Remediation={id:string;title:string;content_description:string;reason:string;source:{kind:string;resource_id:string;revision?:string};scopes:{repository_id:string;kind:string;object_id:string;revision?:string;ref?:string;release_id?:string;package?:string;artifact_digest?:string;environment_id?:string}[];discovery_evidence:{id:string;kind:string;resource_id:string;sha256:string;state:string;note?:string;attributed_to:string}[];constraints:{id:string;kind:string;state:string;reason:string;attributed_to:string}[];audience_ids:string[];owner_ids:string[];required_approvals:{role:string;approver_ids:string[];required:number}[];created_by:string;created_at:string;authority:string};
const rows=(v:FormDataEntryValue|null)=>String(v??"").split("\n").map(x=>x.trim()).filter(Boolean);
const ids=(v:FormDataEntryValue|null)=>String(v??"").split(",").map(x=>x.trim()).filter(Boolean);
export function HistoryRemediationWorkspace({repositoryID}:{repositoryID:string}){
 const {token}=useAuth(),[items,setItems]=useState<Remediation[]>([]),[error,setError]=useState(""),[saving,setSaving]=useState(false),requestID=useRef(crypto.randomUUID());
 const load=useCallback(async()=>{if(!token)return;try{const x=await api<{history_remediations:Remediation[]}>(`/repositories/${repositoryID}/history-remediations`,{},token);setItems(x.history_remediations);setError("")}catch(e){setError(e instanceof Error?e.message:"Restricted remediations could not be loaded.")}},[repositoryID,token]);
 useEffect(()=>{void Promise.resolve().then(load)},[load]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const form=e.currentTarget,f=new FormData(form);try{
  const scopes=rows(f.get("scopes")).map((line)=>{const [repo,kind,object_id,revision="",ref="",release_id="",pkg="",artifact_digest="",environment_id=""]=line.split("|").map(x=>x.trim());return{repository_id:repo,kind,object_id,revision,ref,release_id,package:pkg,artifact_digest,environment_id}});
  const evidence=rows(f.get("evidence")).map((line,i)=>{const [kind,resource_id,sha256,state,note="",attributed_to]=line.split("|").map(x=>x.trim());return{id:`evidence-${i+1}`,kind,resource_id,sha256,state,note,attributed_to}});
  const constraints=rows(f.get("constraints")).map((line,i)=>{const [kind,state,reason,attributed_to]=line.split("|").map(x=>x.trim());return{id:`constraint-${i+1}`,kind,state,reason,attributed_to}});
  const approvals=rows(f.get("approvals")).map(line=>{const [role,people,required]=line.split("|").map(x=>x.trim());return{role,approver_ids:ids(people),required:Number(required)}});
  const out=await api<Remediation>(`/repositories/${repositoryID}/history-remediations`,{method:"POST",body:JSON.stringify({request_id:requestID.current,title:String(f.get("title")),source:{kind:String(f.get("source_kind")),resource_id:String(f.get("source_id")),revision:String(f.get("source_revision"))},content_description:String(f.get("content")),reason:String(f.get("reason")),scopes,discovery_evidence:evidence,constraints,audience_ids:ids(f.get("audience")),owner_ids:ids(f.get("owners")),required_approvals:approvals})},token);setItems(x=>[out,...x]);requestID.current=crypto.randomUUID();form.reset();setError("")
 }catch(x){setError(x instanceof Error?x.message:"Remediation could not be opened.")}finally{setSaving(false)}}
 return <main className="mx-auto max-w-6xl space-y-6 p-6"><div><Badge tone="danger">restricted</Badge><h1 className="mt-2 text-2xl font-semibold">Sensitive history remediation</h1><p className="mt-1 text-sm text-[var(--muted)]">Agree on exact objects, responders, and approvals without copying unsafe content into another discussion.</p></div>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
 <Card className="p-5"><h2 className="font-semibold">Open a governed boundary</h2><form onSubmit={create} className="mt-4 grid gap-3 md:grid-cols-2">
  <input name="title" required className="rounded-lg border p-2" placeholder="Restricted title"/><select name="source_kind" className="rounded-lg border p-2"><option value="security_finding">Security finding</option><option value="privacy_incident">Privacy incident</option><option value="support_case">Support case</option><option value="selected_object">Selected object</option></select>
  <input name="source_id" required className="rounded-lg border p-2" placeholder="Source object ID"/><input name="source_revision" className="rounded-lg border p-2" placeholder="Source revision, when exact"/>
  <textarea name="content" required className="rounded-lg border p-2 md:col-span-2" placeholder="Content to remove — describe category and identifying digests only; do not paste payloads"/><textarea name="reason" required className="rounded-lg border p-2 md:col-span-2" placeholder="Why removal is required"/>
  <textarea name="scopes" required className="rounded-lg border p-2 md:col-span-2" placeholder="One exact object per line: repository | kind | object ID | revision | ref | release | package | artifact digest | environment"/>
  <textarea name="evidence" required className="rounded-lg border p-2 md:col-span-2" placeholder="Discovery only: kind | resource ID | SHA-256 | matched/false_match/inaccessible | safe note | attributable user"/>
  <textarea name="constraints" className="rounded-lg border p-2 md:col-span-2" placeholder="legal_hold/retention_commitment/continuity_commitment/inaccessible_resource/false_match | state | reason | attributable user"/>
  <input name="audience" required className="rounded-lg border p-2" placeholder="Disclosure audience IDs, comma separated"/><input name="owners" required className="rounded-lg border p-2" placeholder="Response owner IDs, comma separated"/>
  <textarea name="approvals" required className="rounded-lg border p-2 md:col-span-2" placeholder="One per line: role | approver IDs comma separated | required count"/><div><Button disabled={saving}>{saving?"Opening…":"Open restricted remediation"}</Button></div>
 </form></Card>
 <section className="space-y-3">{items.map(v=><Card key={v.id} className="p-5"><div className="flex flex-wrap gap-2"><Badge tone="danger">restricted</Badge><Badge>{v.source.kind.replaceAll("_"," ")}</Badge><strong>{v.title}</strong></div><p className="mt-3 text-sm">{v.content_description}</p><p className="mt-1 text-sm text-[var(--muted)]">{v.reason}</p><div className="mt-3 text-xs"><strong>Exact scope</strong>{v.scopes.map((x,i)=><p key={i}><code>{x.repository_id}:{x.kind}:{x.object_id}</code>{x.revision&&<> at <code>{x.revision}</code></>}</p>)}</div><p className="mt-3 text-xs"><strong>Coordination:</strong> owners {v.owner_ids.join(", ")} · audience {v.audience_ids.join(", ")} · approvals {v.required_approvals.map(a=>`${a.role} ${a.required}/${a.approver_ids.length}`).join("; ")}</p>{v.discovery_evidence.map(x=><p className="mt-2 text-xs" key={x.id}><Badge tone={x.state==="matched"?"warning":"neutral"}>{x.state.replaceAll("_"," ")}</Badge> {x.kind} <code>{x.sha256.slice(0,12)}…</code> — {x.attributed_to}</p>)}{v.constraints.map(x=><p className="mt-2 text-xs text-[var(--danger)]" key={x.id}>{x.kind.replaceAll("_"," ")}: {x.state} — {x.reason} ({x.attributed_to})</p>)}<p className="mt-3 text-xs text-[var(--muted)]">{v.authority}</p></Card>)}</section></main>
}
