"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Finding={id:string;copy_kind:string;resource_id:string;repository_id?:string;object_ids:string[];derived_kinds?:string[];state:string;independently_controlled?:boolean;restricted?:boolean;citation_kind:string;citation_resource_id:string;citation_sha256:string;note?:string;uncertainty?:string;attributed_to:string};
type Scenario={id:string;kind:string;image?:string;command?:string;expectation:string;timeout_seconds:number};
type Candidate={id:string;rules:{id:string;affected_object_id:string;action:string;replacement_object_id?:string;reason:string}[];candidate_refs:{name:string;old_tip:string;new_tip:string}[];commit_map:{old_commit_id:string;new_commit_id:string;changed:boolean}[];object_map:{old_object_id:string;new_object_id?:string;action:string}[];broken_signatures:string[];broken_links:string[];unrewritable_resources:string[];original_bytes:number;candidate_bytes:number;rollback_limit:string;collaborator_actions:string[];rehearsals:{id:string;state:string;scenarios:Scenario[];outcomes:{scenario_id:string;kind:string;ref_name:string;state:string;exit_code:number;output?:string}[];compute_seconds:number}[]};
type Publication={state:string;published_by:string;published_at:string;quarantined_objects:string[];paused_systems:string[];migration_targets:{id:string;kind:string;resource_id:string;owner_id:string;repository_id?:string;independently_controlled?:boolean;state:string;instructions:string;replacement_ref:string;replacement_revision:string}[]};
type Pass={id:string;state:string;erasure_claim:boolean;blockers:string[];checked_by:string;checked_at:string;observations:{kind:string;resource_id:string;state:string;evidence_sha256:string;summary:string;independently_controlled?:boolean;exception_expires_at?:string}[]};
type Remediation={id:string;version:number;title:string;content_description:string;reason:string;source:{kind:string;resource_id:string;revision?:string};scopes:{repository_id:string;kind:string;object_id:string;revision?:string;ref?:string;release_id?:string;package?:string;artifact_digest?:string;environment_id?:string}[];discovery_evidence:{id:string;kind:string;resource_id:string;sha256:string;state:string;note?:string;attributed_to:string}[];constraints:{id:string;kind:string;state:string;reason:string;attributed_to:string}[];exposure_map:Finding[];rewrite_candidates:Candidate[];publication_approvals:{role:string;approver_id:string;approved_at:string}[];publication?:Publication;completion_policy:{required_kinds:string[];minimum_passing:number};containment_passes:Pass[];migration_actions:{id:string;kind:string;resource_id:string;action:string;replacement_revision:string;actor_id:string}[];restorations:{id:string;systems:string[];state:string;restored_by:string}[];audience_ids:string[];owner_ids:string[];required_approvals:{role:string;approver_ids:string[];required:number}[];created_by:string;created_at:string;authority:string};
const rows=(v:FormDataEntryValue|null)=>String(v??"").split("\n").map(x=>x.trim()).filter(Boolean);
const ids=(v:FormDataEntryValue|null)=>String(v??"").split(",").map(x=>x.trim()).filter(Boolean);
export function HistoryRemediationWorkspace({repositoryID}:{repositoryID:string}){
 const {token}=useAuth(),[items,setItems]=useState<Remediation[]>([]),[error,setError]=useState(""),[saving,setSaving]=useState(false),requestID=useRef(crypto.randomUUID());
 const load=useCallback(async()=>{if(!token)return;try{const x=await api<{history_remediations:Remediation[]}>(`/repositories/${repositoryID}/history-remediations`,{},token);setItems(x.history_remediations);setError("")}catch(e){setError(e instanceof Error?e.message:"Restricted remediations could not be loaded.")}},[repositoryID,token]);
 useEffect(()=>{void Promise.resolve().then(load)},[load]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const form=e.currentTarget,f=new FormData(form);try{
  const scopes=rows(f.get("scopes")).map((line)=>{const [repo,kind,object_id,revision="",ref="",release_id="",pkg="",artifact_digest="",environment_id=""]=line.split("|").map(x=>x.trim());return{repository_id:repo,kind,object_id,revision,ref,release_id,package:pkg,artifact_digest,environment_id}});
  const evidence=rows(f.get("evidence")).map((line,i)=>{const [kind,resource_id,sha256,state,note="",attributed_to]=line.split("|").map(x=>x.trim());return{id:`evidence-${i+1}`,kind,resource_id,sha256,state,note,attributed_to}});
  const constraints=rows(f.get("constraints")).map((line,i)=>{const [kind,state,reason,attributed_to]=line.split("|").map(x=>x.trim());return{id:`constraint-${i+1}`,kind,state,reason,attributed_to}});
  const approvals=rows(f.get("approvals")).map(line=>{const [role,people,required]=line.split("|").map(x=>x.trim());return{role,approver_ids:ids(people),required:Number(required)}});
  const out=await api<Remediation>(`/repositories/${repositoryID}/history-remediations`,{method:"POST",body:JSON.stringify({request_id:requestID.current,title:String(f.get("title")),source:{kind:String(f.get("source_kind")),resource_id:String(f.get("source_id")),revision:String(f.get("source_revision"))},content_description:String(f.get("content")),reason:String(f.get("reason")),scopes,discovery_evidence:evidence,constraints,audience_ids:ids(f.get("audience")),owner_ids:ids(f.get("owners")),required_approvals:approvals})},token);setItems(x=>[out,...x]);requestID.current=crypto.randomUUID();form.reset();setError("")
 }catch(x){setError(x instanceof Error?x.message:"Remediation could not be opened.")}finally{setSaving(false)}}
 async function addFinding(e:FormEvent<HTMLFormElement>,v:Remediation){e.preventDefault();setSaving(true);const form=e.currentTarget,f=new FormData(form);try{const out=await api<Remediation>(`/repositories/${repositoryID}/history-remediations/${v.id}/exposure-findings`,{method:"POST",body:JSON.stringify({expected_version:v.version,finding:{request_id:crypto.randomUUID(),copy_kind:String(f.get("copy_kind")),resource_id:String(f.get("resource_id")),repository_id:String(f.get("repository_id")),object_ids:ids(f.get("object_ids")),derived_kinds:ids(f.get("derived_kinds")),state:String(f.get("state")),independently_controlled:f.get("independent")==="on",restricted:f.get("restricted")==="on",citation_kind:String(f.get("citation_kind")),citation_resource_id:String(f.get("citation_id")),citation_sha256:String(f.get("citation_sha256")),note:String(f.get("note")),uncertainty:String(f.get("uncertainty"))}})},token);setItems(x=>x.map(item=>item.id===out.id?out:item));form.reset();setError("")}catch(x){setError(x instanceof Error?x.message:"Exposure finding could not be added.")}finally{setSaving(false)}}
 async function assemble(e:FormEvent<HTMLFormElement>,v:Remediation){e.preventDefault();setSaving(true);const form=e.currentTarget,f=new FormData(form);try{const rules=rows(f.get("rules")).map((line,i)=>{const [affected_object_id,action,replacement_object_id="",reason]=line.split("|").map(x=>x.trim());return{id:`rule-${i+1}`,affected_object_id,action,replacement_object_id,reason}});const selected_refs=rows(f.get("refs")).map(line=>{const [name,expected_tip]=line.split("|").map(x=>x.trim());return{name,expected_tip}});const out=await api<Remediation>(`/repositories/${repositoryID}/history-remediations/${v.id}/rewrite-candidates`,{method:"POST",body:JSON.stringify({expected_version:v.version,candidate:{request_id:crypto.randomUUID(),rules,selected_refs,rollback_limit:String(f.get("rollback")),collaborator_actions:rows(f.get("actions"))}})},token);setItems(x=>x.map(item=>item.id===out.id?out:item));form.reset();setError("")}catch(x){setError(x instanceof Error?x.message:"Rewrite candidate could not be assembled.")}finally{setSaving(false)}}
 async function rehearse(e:FormEvent<HTMLFormElement>,v:Remediation,c:Candidate){e.preventDefault();setSaving(true);const form=e.currentTarget,f=new FormData(form);try{const commands=new Map(rows(f.get("commands")).map(line=>{const [kind,image,command]=line.split("|").map(x=>x.trim());return[kind,{image,command}]}));const kinds=["repository_integrity","build","check","release","dependency","clone","fetch"];const scenarios=kinds.map((kind,i)=>({id:`scenario-${i+1}`,kind,image:commands.get(kind)?.image||"",command:commands.get(kind)?.command||"",expectation:`${kind.replaceAll("_"," ")} remains usable`,timeout_seconds:120}));const out=await api<Remediation>(`/repositories/${repositoryID}/history-remediations/${v.id}/rewrite-candidates/${c.id}/rehearsals`,{method:"POST",body:JSON.stringify({expected_version:v.version,rehearsal:{request_id:crypto.randomUUID(),scenarios}})},token);setItems(x=>x.map(item=>item.id===out.id?out:item));form.reset();setError("")}catch(x){setError(x instanceof Error?x.message:"Bounded rehearsal could not run.")}finally{setSaving(false)}}
 async function approve(v:Remediation,role:string){if(!token)return;setSaving(true);try{const out=await api<Remediation>(`/repositories/${repositoryID}/history-remediations/${v.id}/publication-approvals`,{method:"POST",body:JSON.stringify({expected_version:v.version,role})},token);setItems(x=>x.map(item=>item.id===out.id?out:item));setError("")}catch(x){setError(x instanceof Error?x.message:"Approval could not be retained.")}finally{setSaving(false)}}
 async function publish(e:FormEvent<HTMLFormElement>,v:Remediation,c:Candidate){e.preventDefault();setSaving(true);const form=e.currentTarget,f=new FormData(form);try{const migration_targets=rows(f.get("migration_targets")).map((line,i)=>{const[kind,resource_id,owner_id,target_repository_id="",control="coordinated",replacement_ref,instructions]=line.split("|").map(x=>x.trim());return{id:`target-${i+1}`,kind,resource_id,owner_id,repository_id:target_repository_id,independently_controlled:control==="independent",replacement_ref,instructions}});const out=await api<Remediation>(`/repositories/${repositoryID}/history-remediations/${v.id}/rewrite-candidates/${c.id}/publish`,{method:"POST",body:JSON.stringify({expected_version:v.version,publication:{request_id:crypto.randomUUID(),paused_systems:["pushes"],migration_targets}})},token);setItems(x=>x.map(item=>item.id===out.id?out:item));setError("")}catch(x){setError(x instanceof Error?x.message:"Replacement refs could not be published.")}finally{setSaving(false)}}
 async function verify(e:FormEvent<HTMLFormElement>,v:Remediation){e.preventDefault();setSaving(true);const form=e.currentTarget,f=new FormData(form);try{const observations=rows(f.get("observations")).map(line=>{const[kind,resource_id,state,evidence_sha256,summary,control="coordinated",exception_expires_at=""]=line.split("|").map(x=>x.trim());return{kind,resource_id,state,evidence_sha256,summary,independently_controlled:control==="independent",exception_expires_at}});const out=await api<Remediation>(`/repositories/${repositoryID}/history-remediations/${v.id}/containment-passes`,{method:"POST",body:JSON.stringify({expected_version:v.version,pass:{request_id:crypto.randomUUID(),observations}})},token);setItems(x=>x.map(item=>item.id===out.id?out:item));form.reset();setError("")}catch(x){setError(x instanceof Error?x.message:"Containment could not be rechecked.")}finally{setSaving(false)}}
 async function migrate(e:FormEvent<HTMLFormElement>,v:Remediation){e.preventDefault();setSaving(true);const form=e.currentTarget,f=new FormData(form);try{const out=await api<Remediation>(`/repositories/${repositoryID}/history-remediations/${v.id}/migration-actions`,{method:"POST",body:JSON.stringify({expected_version:v.version,action:{request_id:crypto.randomUUID(),kind:String(f.get("kind")),resource_id:String(f.get("resource_id")),action:String(f.get("action")),replacement_revision:String(f.get("revision")),discussion_preserved:true,attribution_preserved:true}})},token);setItems(x=>x.map(item=>item.id===out.id?out:item));form.reset();setError("")}catch(x){setError(x instanceof Error?x.message:"Migration could not be retained.")}finally{setSaving(false)}}
 async function restore(v:Remediation,p:Pass){if(!token)return;setSaving(true);try{const out=await api<Remediation>(`/repositories/${repositoryID}/history-remediations/${v.id}/restorations`,{method:"POST",body:JSON.stringify({expected_version:v.version,restoration:{request_id:crypto.randomUUID(),containment_pass_id:p.id,systems:["pushes","automation","releases","contributions"]}})},token);setItems(x=>x.map(item=>item.id===out.id?out:item));setError("")}catch(x){setError(x instanceof Error?x.message:"Ordinary work remains contained.")}finally{setSaving(false)}}
 return <main className="mx-auto max-w-6xl space-y-6 p-6"><div><Badge tone="danger">restricted</Badge><h1 className="mt-2 text-2xl font-semibold">Sensitive history remediation</h1><p className="mt-1 text-sm text-[var(--muted)]">Agree on exact objects, responders, and approvals without copying unsafe content into another discussion.</p></div>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
 <Card className="p-5"><h2 className="font-semibold">Open a governed boundary</h2><form onSubmit={create} className="mt-4 grid gap-3 md:grid-cols-2">
  <input name="title" required className="rounded-lg border p-2" placeholder="Restricted title"/><select name="source_kind" className="rounded-lg border p-2"><option value="security_finding">Security finding</option><option value="privacy_incident">Privacy incident</option><option value="support_case">Support case</option><option value="selected_object">Selected object</option></select>
  <input name="source_id" required className="rounded-lg border p-2" placeholder="Source object ID"/><input name="source_revision" className="rounded-lg border p-2" placeholder="Source revision, when exact"/>
  <textarea name="content" required className="rounded-lg border p-2 md:col-span-2" placeholder="Content to remove — describe category and identifying digests only; do not paste payloads"/><textarea name="reason" required className="rounded-lg border p-2 md:col-span-2" placeholder="Why removal is required"/>
  <textarea name="scopes" required className="rounded-lg border p-2 md:col-span-2" placeholder="repository | git_object/release/package/environment/check_artifact | exact object ID | revision | ref | release | name@version | artifact SHA-256 | environment"/>
  <textarea name="evidence" required className="rounded-lg border p-2 md:col-span-2" placeholder="Discovery only: kind | resource ID | SHA-256 | matched/false_match/inaccessible | safe note | attributable user"/>
  <textarea name="constraints" className="rounded-lg border p-2 md:col-span-2" placeholder="legal_hold/retention_commitment/continuity_commitment/inaccessible_resource/false_match | state | reason | attributable user"/>
  <input name="audience" required className="rounded-lg border p-2" placeholder="Disclosure audience IDs, comma separated"/><input name="owners" required className="rounded-lg border p-2" placeholder="Response owner IDs, comma separated"/>
  <textarea name="approvals" required className="rounded-lg border p-2 md:col-span-2" placeholder="One per line: role | approver IDs comma separated | required count"/><div><Button disabled={saving}>{saving?"Opening…":"Open restricted remediation"}</Button></div>
 </form></Card>
 <section className="space-y-3">{items.map(v=><Card key={v.id} className="p-5"><div className="flex flex-wrap gap-2"><Badge tone="danger">restricted</Badge><Badge>{v.source.kind.replaceAll("_"," ")}</Badge><strong>{v.title}</strong></div><p className="mt-3 text-sm">{v.content_description}</p><p className="mt-1 text-sm text-[var(--muted)]">{v.reason}</p><div className="mt-3 text-xs"><strong>Exact scope</strong>{v.scopes.map((x,i)=><p key={i}><code>{x.repository_id}:{x.kind}:{x.object_id}</code>{x.revision&&<> at <code>{x.revision}</code></>}</p>)}</div><p className="mt-3 text-xs"><strong>Coordination:</strong> owners {v.owner_ids.join(", ")} · audience {v.audience_ids.join(", ")} · approvals {v.required_approvals.map(a=>`${a.role} ${a.required}/${a.approver_ids.length}`).join("; ")}</p>{v.discovery_evidence.map(x=><p className="mt-2 text-xs" key={x.id}><Badge tone={x.state==="matched"?"warning":"neutral"}>{x.state.replaceAll("_"," ")}</Badge> {x.kind} <code>{x.sha256.slice(0,12)}…</code> — {x.attributed_to}</p>)}{v.constraints.map(x=><p className="mt-2 text-xs text-[var(--danger)]" key={x.id}>{x.kind.replaceAll("_"," ")}: {x.state} — {x.reason} ({x.attributed_to})</p>)}
 <div className="mt-5 border-t pt-4"><h3 className="font-semibold">Exposure map</h3><p className="text-xs text-[var(--muted)]">Reachability and operational copies; restricted systems disclose status without contents.</p>{(v.exposure_map??[]).map(x=><div key={x.id} className="mt-2 rounded-lg border p-3 text-xs"><Badge tone={x.state==="confirmed"?"danger":x.state==="suspected"?"warning":"neutral"}>{x.state.replaceAll("_"," ")}</Badge> <strong>{x.copy_kind.replaceAll("_"," ")}</strong> · {x.resource_id}<p className="mt-1">Objects: {x.object_ids.map(id=><code key={id} className="mr-2">{id}</code>)}{x.derived_kinds?.length?` · derived ${x.derived_kinds.join(", ")}`:""}</p><p>{x.uncertainty||x.note} — {x.attributed_to}</p></div>)}
 <form onSubmit={e=>addFinding(e,v)} className="mt-3 grid gap-2 md:grid-cols-2"><select name="copy_kind" className="rounded-lg border p-2">{["branch","tag","pull_request","fork","federated_contribution","workspace","checkpoint","cache","package","release_artifact","documentation","deployment","backup","active_clone"].map(x=><option key={x}>{x}</option>)}</select><select name="state" className="rounded-lg border p-2">{["confirmed","suspected","unreachable","independently_controlled","unverifiable"].map(x=><option key={x}>{x}</option>)}</select><input required name="resource_id" className="rounded-lg border p-2" placeholder="Copy/resource ID"/><input name="repository_id" className="rounded-lg border p-2" placeholder="Repository ID, if permitted"/><input required name="object_ids" className="rounded-lg border p-2 md:col-span-2" placeholder="Affected object IDs, comma separated"/><input name="derived_kinds" className="rounded-lg border p-2" placeholder="credential, personal_data, confidential_data, generated_artifact"/><input required name="citation_kind" className="rounded-lg border p-2" placeholder="Citation kind"/><input required name="citation_id" className="rounded-lg border p-2" placeholder="Citation resource ID"/><input required name="citation_sha256" className="rounded-lg border p-2" placeholder="Citation SHA-256"/><input name="note" className="rounded-lg border p-2" placeholder="Bounded payload-free finding"/><input name="uncertainty" className="rounded-lg border p-2" placeholder="What remains uncertain"/><label className="text-xs"><input type="checkbox" name="independent"/> independently controlled</label><label className="text-xs"><input type="checkbox" name="restricted"/> hide copy and citation details</label><div><Button disabled={saving}>Add cited finding</Button></div></form></div>
 <div className="mt-5 border-t pt-4"><h3 className="font-semibold">Replacement history rehearsal</h3><p className="text-xs text-[var(--muted)]">Candidates remain unreferenced. Exact mappings are visible only inside this restricted workspace.</p>
 {v.publication&&<div className="mt-3 rounded-lg border border-[var(--warning)] p-3 text-xs"><Badge tone="warning">{v.publication.state.replaceAll("_"," ")}</Badge><p className="mt-2">Authoritative refs published by {v.publication.published_by}; affected objects are quarantined and {v.publication.paused_systems.join(", ")} remain paused.</p>{v.publication.migration_targets.map(t=><p key={t.id} className="mt-2"><strong>{t.kind.replaceAll("_"," ")} · {t.state.replaceAll("_"," ")}</strong> — <code>{t.replacement_ref||"unbound legacy target"}</code>{t.replacement_revision&&<> at <code>{t.replacement_revision.slice(0,12)}</code></>} · {t.instructions}{t.independently_controlled&&" (the owner must perform this rewrite under their own authority)"}</p>)}</div>}
 {v.publication&&<div className="mt-4 rounded-lg border p-3 text-xs"><h3 className="font-semibold">Containment and safe restoration</h3><p className="text-[var(--muted)]">Repository refs and object quarantine are rechecked by the server. Supply current digest evidence for the other eight policy dimensions; residuals never become an erasure claim.</p>{(v.containment_passes??[]).map(p=><div key={p.id} className="mt-2 rounded border p-2"><Badge tone={p.state==="passing"?"success":"danger"}>{p.state}</Badge> checked by {p.checked_by}{p.blockers.map(x=><p key={x} className="text-[var(--danger)]">{x}</p>)}{p.state==="passing"&&<Button type="button" disabled={saving} onClick={()=>void restore(v,p)}>Restore scoped collaboration flows</Button>}</div>)}<form onSubmit={e=>verify(e,v)} className="mt-3 grid gap-2"><textarea required name="observations" className="rounded-lg border p-2" placeholder="fork_acknowledgement/federation_acknowledgement/package_replacement/artifact_replacement/credential_rotation/deployment/cache/recovery_copy | resource | passed/failed/unreachable/independently_controlled/retained_legal/reintroduced/exception | evidence SHA-256 | safe summary | coordinated/independent | exception expiry"/><Button disabled={saving}>Recheck current containment</Button></form><form onSubmit={e=>migrate(e,v)} className="mt-3 grid gap-2 md:grid-cols-2"><select name="kind" className="rounded-lg border p-2"><option value="pull_request">Pull request</option><option value="workspace">Workspace</option></select><select name="action" className="rounded-lg border p-2"><option value="migrated">Migrate</option><option value="closed">Close as superseded</option></select><input required name="resource_id" className="rounded-lg border p-2" placeholder="Resource ID"/><input required name="revision" className="rounded-lg border p-2" placeholder="Exact replacement revision"/><Button disabled={saving}>Preserve discussion and attribution</Button></form></div>}
 {(v.rewrite_candidates??[]).map(c=><div key={c.id} className="mt-3 rounded-lg border p-3 text-xs"><div className="flex flex-wrap gap-2"><Badge tone={v.publication?"success":"info"}>{v.publication?"authoritative replacement":"unpublished candidate"}</Badge><Badge>{c.commit_map.filter(x=>x.changed).length} commits changed</Badge>{c.broken_signatures.length>0&&<Badge tone="warning">{c.broken_signatures.length} signatures broken</Badge>}</div>{c.candidate_refs.map(x=><p key={x.name} className="mt-2"><code>{x.name}</code>: <code>{x.old_tip.slice(0,12)}</code> → <code>{x.new_tip.slice(0,12)}</code></p>)}<p className="mt-2">Storage: {c.original_bytes} → {c.candidate_bytes} bytes · broken links {c.broken_links.length} · unrewritable resources {c.unrewritable_resources.length}</p><p className="mt-1 text-[var(--muted)]">{c.rollback_limit}</p>{c.unrewritable_resources.map(x=><p key={x} className="text-[var(--danger)]">Cannot rewrite: {x}</p>)}{c.rehearsals.map(r=><div key={r.id} className="mt-2 rounded border p-2"><Badge tone={r.state==="passed"?"success":"danger"}>{r.state}</Badge> bounded rehearsal · {r.compute_seconds}s{r.outcomes.map(o=><p key={`${o.ref_name}:${o.scenario_id}`}><code>{o.ref_name}</code> · {o.kind.replaceAll("_"," ")}: <strong>{o.state}</strong>{o.output?` — ${o.output}`:""}</p>)}</div>)}{!v.publication&&<><form onSubmit={e=>rehearse(e,v,c)} className="mt-3 grid gap-2"><textarea name="commands" required className="rounded-lg border p-2" placeholder="build | preinstalled-image:tag | bun run build&#10;check | preinstalled-image:tag | bun test&#10;release | preinstalled-image:tag | command&#10;dependency | preinstalled-image:tag | command"/><Button disabled={saving}>Run bounded rehearsal for every ref</Button></form>{c.rehearsals.some(r=>r.state==="passed")&&<div className="mt-3 border-t pt-3"><div className="flex flex-wrap gap-2">{v.required_approvals.map(a=><Button key={a.role} type="button" disabled={saving} variant="secondary" onClick={()=>void approve(v,a.role)}>Attest my {a.role} approval ({v.publication_approvals?.filter(x=>x.role===a.role).length??0}/{a.required})</Button>)}</div><form onSubmit={e=>publish(e,v,c)} className="mt-3 grid gap-2"><textarea name="migration_targets" required className="rounded-lg border p-2" placeholder="local_branch/fork/federated_copy/pull_request/integration | resource ID | owner ID | repository ID | coordinated/independent | audience-appropriate recovery instructions"/><Button disabled={saving} variant="secondary">Publish replacement refs and pause restoration paths</Button></form></div>}</>}</div>)}
 <form onSubmit={e=>assemble(e,v)} className="mt-3 grid gap-2"><textarea name="rules" required className="rounded-lg border p-2" placeholder="affected blob ID | remove/replace | replacement blob ID | payload-free reason"/><textarea name="refs" required className="rounded-lg border p-2" placeholder="refs/heads/main | exact current commit"/><textarea name="rollback" required className="rounded-lg border p-2" placeholder="Exact rollback limits"/><textarea name="actions" required className="rounded-lg border p-2" placeholder="One required collaborator action per line"/><Button disabled={saving}>Assemble unpublished candidate</Button></form></div>
 <p className="mt-3 text-xs text-[var(--muted)]">{v.authority}</p></Card>)}</section></main>
}
