"use client";

import Link from "next/link";
import { useCallback,useEffect,useState,type FormEvent } from "react";
import { api,type ImpactAssessment } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge,Button,Card } from "./ui";

export function ImpactWorkspace({repositoryID,initialRef="",initialPath="",initialStartLine=1}:{repositoryID:string;initialRef?:string;initialPath?:string;initialStartLine?:number}){
 const {token,user}=useAuth(),[history,setHistory]=useState<ImpactAssessment[]>([]),[selected,setSelected]=useState<ImpactAssessment|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{if(!token)return;try{const result=await api<{assessments:ImpactAssessment[]}>(`/repositories/${repositoryID}/impact-assessments`,{},token);setHistory(result.assessments)}catch(reason){setError(reason instanceof Error?reason.message:"Assessments could not be loaded.")}},[repositoryID,token]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;setBusy(true);setError("");const form=new FormData(event.currentTarget),kind=String(form.get("kind"));const source=kind==="selected_code"?{kind,path:String(form.get("path")),start_line:Number(form.get("start_line")),end_line:Number(form.get("end_line"))}:kind==="investigation_conclusion"?{kind,explanation_id:String(form.get("explanation_id")),entry_id:String(form.get("entry_id"))}:{kind,diff:String(form.get("diff"))};try{const next=await api<ImpactAssessment>(`/repositories/${repositoryID}/impact-assessments`,{method:"POST",body:JSON.stringify({title:String(form.get("title")),ref:String(form.get("ref")),query:String(form.get("query")),source})},token);setSelected(next);setHistory(current=>[next,...current])}catch(reason){setError(reason instanceof Error?reason.message:"Assessment could not be created.")}finally{setBusy(false)}}
 async function mutate(path:string,body:Record<string,unknown>){if(!token||!selected)return;setBusy(true);setError("");try{const next=await api<ImpactAssessment>(`/repositories/${repositoryID}/impact-assessments/${selected.id}/${path}`,{method:"POST",body:JSON.stringify({...body,version:selected.version})},token);setSelected(next);setHistory(current=>current.map(x=>x.id===next.id?next:x))}catch(reason){setError(reason instanceof Error?reason.message:"Assessment changed; reload and try again.")}finally{setBusy(false)}}
 const grouped=selected?selected.items.reduce<Record<string,ImpactAssessment["items"]>>((result,item)=>{(result[item.kind]??=[]).push(item);return result},{}):{};
 return <div className="space-y-6"><header><Link href={`/repositories/${repositoryID}`} className="text-sm text-[var(--muted)] hover:text-[var(--brand)]">Repository</Link><h1 className="mt-2 text-2xl font-semibold">Prospective change impact</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Freeze what you intend to change, review the visible blast radius, name verification work and unknowns, then ask affected owners to acknowledge the decision before implementation.</p></header>
 <Card className="p-5"><form onSubmit={create} className="space-y-3"><div className="grid gap-3 md:grid-cols-3"><label className="text-xs font-semibold">Source<select name="kind" className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal"><option value="selected_code">Selected code</option><option value="investigation_conclusion">Investigation conclusion</option><option value="proposed_diff">Proposed diff</option></select></label><label className="text-xs font-semibold">Revision or branch<input name="ref" defaultValue={initialRef} required className="mt-1 min-h-10 w-full rounded-lg border px-3 font-mono font-normal"/></label><label className="text-xs font-semibold">Assessment title<input name="title" required maxLength={200} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label><label className="text-xs font-semibold">Path<input name="path" defaultValue={initialPath} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-mono font-normal"/></label><label className="text-xs font-semibold">Lines<input name="start_line" type="number" min="1" defaultValue={initialStartLine} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/><input name="end_line" type="number" min="1" defaultValue={initialStartLine} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label><label className="text-xs font-semibold">Conclusion IDs<input name="explanation_id" placeholder="Investigation ID" className="mt-1 min-h-10 w-full rounded-lg border px-3 font-mono font-normal"/><input name="entry_id" placeholder="Conclusion entry ID" className="mt-1 min-h-10 w-full rounded-lg border px-3 font-mono font-normal"/></label></div><label className="block text-xs font-semibold">Optional behavior or symbol focus<input name="query" className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal" placeholder="authorizeRepositoryRead"/></label><label className="block text-xs font-semibold">Proposed diff<textarea name="diff" maxLength={20000} rows={4} className="mt-1 w-full rounded-lg border p-3 font-mono font-normal" placeholder="Paste a prospective unified diff…"/></label><Button disabled={busy}>Assess impact</Button></form></Card>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
 {selected&&<section className="space-y-4"><Card className="p-5"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{selected.title}</h2><Badge tone={selected.analysis_status==="complete"?"success":"warning"}>{selected.analysis_status}</Badge><Badge>version {selected.version}</Badge></div><p className="mt-2 text-xs text-[var(--muted)]"><code>{selected.revision}</code> · {selected.source.kind.replaceAll("_"," ")} · {selected.items.length} visible impact items</p>{selected.analysis_reason&&<p className="mt-2 text-sm text-[var(--muted)]">{selected.analysis_reason}</p>}<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void mutate("participants",{user_id:String(form.get("user_id"))});e.currentTarget.reset()}} className="mt-4 flex gap-2"><input name="user_id" required placeholder="Repository participant ID" className="min-h-10 min-w-0 flex-1 rounded-lg border px-3 text-sm"/><Button disabled={busy}>Invite collaborator</Button></form></Card>
 <div className="grid gap-4 lg:grid-cols-2">{Object.entries(grouped).map(([kind,items])=><Card key={kind} className="p-5"><h3 className="font-semibold capitalize">{kind.replaceAll("_"," ")} <Badge>{items?.length??0}</Badge></h3><div className="mt-3 space-y-3">{items?.map(item=><article key={item.id} className="rounded-lg border border-[var(--line)] p-3"><div className="flex gap-2"><Badge tone={item.status==="verification_required"?"warning":item.status==="accepted_risk"?"danger":"info"}>{item.status.replaceAll("_"," ")}</Badge></div><p className="mt-2 text-sm">{item.summary}</p>{item.evidence?.map((evidence,index)=><p key={index} className="mt-2 text-xs text-[var(--muted)]">{evidence.path?<Link href={`/repositories/${evidence.repository_id}?ref=${evidence.revision}&path=${encodeURIComponent(evidence.path)}${evidence.line?`#L${evidence.line}`:""}`} className="font-mono text-[var(--brand)] hover:underline">{evidence.path}{evidence.line?`:${evidence.line}`:""}</Link>:<code>{evidence.repository_id.slice(0,8)} · {evidence.label}</code>}{evidence.verification&&<> · {evidence.verification}</>}</p>)}</article>)}</div></Card>)}</div>
 <Card className="p-5"><h3 className="font-semibold">Refine the decision</h3><div className="mt-3 grid gap-4 md:grid-cols-2"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate("items",{kind:String(f.get("kind")),status:String(f.get("status")),summary:String(f.get("summary"))});e.currentTarget.reset()}} className="space-y-2"><select name="kind" className="min-h-10 w-full rounded-lg border bg-white px-3"><option value="risk">Risk</option><option value="unknown">Unknown</option><option value="test">Verification need</option></select><select name="status" className="min-h-10 w-full rounded-lg border bg-white px-3"><option value="accepted_risk">Accepted risk</option><option value="unknown">Unknown</option><option value="verification_required">Verification required</option></select><textarea name="summary" required rows={3} className="w-full rounded-lg border p-3" placeholder="What must reviewers know?"/><Button disabled={busy}>Record</Button></form><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate("acknowledgement-requests",{repository_id:String(f.get("repository_id")),note:String(f.get("note"))});e.currentTarget.reset()}} className="space-y-2"><input name="repository_id" required className="min-h-10 w-full rounded-lg border px-3 font-mono" placeholder="Affected repository ID"/><textarea name="note" rows={3} className="w-full rounded-lg border p-3" placeholder="What should its owner confirm?"/><Button disabled={busy}>Request owner acknowledgement</Button></form></div></Card>
 <Card className="p-5"><h3 className="font-semibold">Affected-owner acknowledgements</h3>{selected.acknowledgement_requests.length?<div className="mt-3 space-y-3">{selected.acknowledgement_requests.map(request=><div key={request.id} className="rounded-lg border p-3 text-sm"><Badge tone={request.acknowledged_by?"success":"warning"}>{request.acknowledged_by?"acknowledged":"requested"}</Badge><code className="ml-2">{request.repository_id}</code><p className="mt-2">{request.acknowledgement||request.note}</p>{request.owner_id===user?.id&&!request.acknowledged_by&&<Button className="mt-2" disabled={busy} onClick={()=>void mutate(`acknowledgement-requests/${request.id}`,{note:"Impact reviewed at the frozen revision"})}>Acknowledge impact</Button>}</div>)}</div>:<p className="mt-3 text-sm text-[var(--muted)]">No owner acknowledgements requested.</p>}</Card></section>}
 <section><h2 className="text-lg font-semibold">Assessments you can review</h2><div className="mt-3 space-y-2">{history.map(item=><button type="button" key={item.id} onClick={()=>setSelected(item)} className="w-full rounded-xl border bg-white p-4 text-left hover:border-[var(--brand)]"><span className="font-semibold">{item.title}</span><span className="mt-1 block text-xs text-[var(--muted)]">{item.items.length} visible impacts · <code>{item.revision.slice(0,12)}</code></span></button>)}</div></section></div>
}
