"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api, type Issue, type ReleaseCandidate, type Repository } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

const field = "mt-2 min-h-11 w-full rounded-lg border border-[var(--line-strong)] bg-white px-3 outline-none focus:border-[var(--brand)]";
const message = (reason: unknown) => reason instanceof Error ? reason.message : "The issue operation failed.";
const stamp = (value: string) => new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const tone = (severity: Issue["severity"]) => severity === "critical" || severity === "high" ? "danger" : severity === "medium" ? "warning" : "neutral";

export function IssuesWorkspace() {
  const {token,user,loading}=useAuth(); const router=useRouter();
  const [repositories,setRepositories]=useState<Repository[]>([]),[issues,setIssues]=useState<Issue[]>([]),[releases,setReleases]=useState<ReleaseCandidate[]>([]),[repoID,setRepoID]=useState(""),[suggestions,setSuggestions]=useState<Issue[]>([]),[error,setError]=useState(""),[pending,setPending]=useState(false);
  const load=useCallback(async()=>{if(!token)return;try{const page=await api<{repositories:Repository[]}>("/repositories?limit=100",{},token);setRepositories(page.repositories);const selected=repoID||page.repositories[0]?.id||"";if(selected){setRepoID(selected);const [found,versions]=await Promise.all([api<{issues:Issue[]}>(`/repositories/${selected}/issues`,{},token),api<{releases:ReleaseCandidate[]}>(`/repositories/${selected}/releases`,{},token).catch(()=>({releases:[]}))]);setIssues(found.issues);setReleases(versions.releases)}}catch(reason){setError(message(reason))}},[token,repoID]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function search(title:string){if(!token||title.trim().length<3){setSuggestions([]);return}try{const found=await api<{issues:Issue[]}>(`/repositories/${repoID}/issue-suggestions?q=${encodeURIComponent(title)}`,{},token);setSuggestions(found.issues)}catch{setSuggestions([])}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;setPending(true);setError("");const form=event.currentTarget,data=new FormData(form),files=data.getAll("attachments").filter((x):x is File=>x instanceof File&&x.size>0);try{const attachments=await Promise.all(files.map(async file=>{if(file.size>1048576)throw new Error(`${file.name} exceeds the 1 MiB attachment limit.`);const raw=new Uint8Array(await file.arrayBuffer());let binary="";raw.forEach(x=>binary+=String.fromCharCode(x));const kind=file.type.startsWith("image/")?"screenshot":file.name.endsWith(".json")?"trace":file.type==="text/plain"?"log":"sample";return{kind,name:file.name,media_type:file.type||"application/octet-stream",size:file.size,data:btoa(binary)}}));const created=await api<Issue>(`/repositories/${repoID}/issues`,{method:"POST",body:JSON.stringify({release_id:data.get("release_id")||undefined,title:data.get("title"),expected_behavior:data.get("expected_behavior"),observed_behavior:data.get("observed_behavior"),severity:data.get("severity"),environment:data.get("environment"),reproduction_steps:String(data.get("reproduction_steps")||"").split("\n").map(x=>x.trim()).filter(Boolean),visibility:data.get("visibility"),attachments})},token);router.push(`/repositories/${repoID}/issues/${created.id}`)}catch(reason){setError(message(reason));setPending(false)}}
  if(loading)return <Card className="p-8 text-sm text-[var(--muted)]">Loading issues…</Card>;
  if(!user)return <Card className="p-8 text-center"><h1 className="text-2xl font-semibold">Report unexpected behavior where maintainers work</h1><Link className="mt-5 inline-flex rounded-lg bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white" href="/?access=signin">Sign in</Link></Card>;
  return <div className="space-y-6"><header><p className="text-sm font-semibold text-[var(--brand)]">Repository collaboration</p><h1 className="mt-1 text-3xl font-semibold">Issues</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Give maintainers the expected result, actual failure, exact environment, and a path to reproduce it.</p></header>
    {error&&<p role="alert" className="rounded-lg bg-[var(--danger-soft)] p-3 text-sm text-[var(--danger)]">{error}</p>}
    <Card className="p-5"><form onSubmit={create} className="grid gap-4 lg:grid-cols-2"><label className="text-sm font-semibold">Repository<select className={field} value={repoID} onChange={e=>{setRepoID(e.target.value);setSuggestions([])}} required>{repositories.map(repo=><option key={repo.id} value={repo.id}>{repo.name}</option>)}</select></label><label className="text-sm font-semibold">Affected release <span className="font-normal text-[var(--muted)]">(optional)</span><select name="release_id" className={field}><option value="">Unreleased or unknown</option>{releases.map(x=><option key={x.id} value={x.id}>{x.version}</option>)}</select></label>
      <label className="text-sm font-semibold lg:col-span-2">Title<input name="title" className={field} required maxLength={180} onBlur={e=>void search(e.target.value)} placeholder="Upload exits after the progress reaches 100%" /></label>
      {suggestions.length>0&&<aside className="rounded-lg border border-[var(--line)] bg-[var(--surface)] p-3 text-sm lg:col-span-2"><p className="font-semibold">Could this already be reported?</p>{suggestions.map(x=><Link key={x.id} className="mt-2 block text-[var(--brand)] hover:underline" href={`/repositories/${x.repository_id}/issues/${x.id}`}>{x.title} · {x.status}</Link>)}</aside>}
      <label className="text-sm font-semibold">Expected behavior<textarea name="expected_behavior" className={`${field} min-h-28 py-2`} required /></label><label className="text-sm font-semibold">Observed behavior<textarea name="observed_behavior" className={`${field} min-h-28 py-2`} required /></label>
      <label className="text-sm font-semibold">Severity<select name="severity" className={field} defaultValue="medium"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label className="text-sm font-semibold">Visibility<select name="visibility" className={field} defaultValue="repository"><option value="repository">Repository participants</option><option value="public">Public report</option></select></label>
      <label className="text-sm font-semibold lg:col-span-2">Environment<input name="environment" className={field} required placeholder="OS, browser/runtime, architecture, relevant configuration" /></label><label className="text-sm font-semibold lg:col-span-2">Reproduction steps <span className="font-normal text-[var(--muted)]">(one per line)</span><textarea name="reproduction_steps" className={`${field} min-h-32 py-2`} required placeholder={"Install version 2.1.0\nCreate a 5 MB sample\nRun vivarium upload sample.bin"}/></label>
      <label className="text-sm font-semibold lg:col-span-2">Evidence <span className="font-normal text-[var(--muted)]">logs, PNG/JPEG/WebP screenshots, JSON traces, or sample inputs; 1 MiB each, up to 10</span><input name="attachments" type="file" multiple className={`${field} py-2`} accept="text/plain,image/png,image/jpeg,image/webp,application/json,application/octet-stream,.log,.trace" /></label><div className="lg:col-span-2"><Button disabled={pending||!repoID}>{pending?"Opening issue…":"Open issue"}</Button></div></form></Card>
    <section><h2 className="text-lg font-semibold">Reports in this repository</h2><div className="mt-3 space-y-3">{issues.map(x=><Link key={x.id} href={`/repositories/${x.repository_id}/issues/${x.id}`}><Card className="mb-3 p-4 transition hover:border-[var(--line-strong)]"><div className="flex flex-wrap items-center gap-2"><Badge tone={tone(x.severity)}>{x.severity}</Badge><Badge>{x.status.replaceAll("_"," ")}</Badge><span className="text-xs text-[var(--muted)]">{x.affected_version||"unreleased"}</span></div><h3 className="mt-2 font-semibold">{x.title}</h3><p className="mt-1 line-clamp-2 text-sm text-[var(--muted)]">{x.observed_behavior}</p></Card></Link>)}{issues.length===0&&<Card className="p-6 text-sm text-[var(--muted)]">No issues have been opened for this repository.</Card>}</div></section>
  </div>
}

export function IssueDetail({repositoryID,issueID}:{repositoryID:string;issueID:string}){
  const {token,loading}=useAuth();const [issue,setIssue]=useState<Issue|null>(null),[error,setError]=useState("");
  const load=useCallback(async()=>{if(!token)return;try{setIssue(await api<Issue>(`/repositories/${repositoryID}/issues/${issueID}`,{},token))}catch(reason){setError(message(reason))}},[token,repositoryID,issueID]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function comment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;const form=event.currentTarget,data=new FormData(form);try{setIssue(await api<Issue>(`/repositories/${repositoryID}/issues/${issueID}/comments`,{method:"POST",body:JSON.stringify({body:data.get("body")})},token));form.reset()}catch(reason){setError(message(reason))}}
  async function status(next:Issue["status"]){if(!token||!issue)return;try{setIssue(await api<Issue>(`/repositories/${repositoryID}/issues/${issueID}`,{method:"PATCH",body:JSON.stringify({status:next,expected_version:issue.version,message:`Marked ${next.replaceAll("_"," ")} from the issue workspace.`})},token))}catch(reason){setError(message(reason))}}
  if(loading||!issue)return <Card className="p-8 text-sm text-[var(--muted)]">{error||"Loading issue…"}</Card>;
  return <div className="space-y-6"><Link className="text-sm font-semibold text-[var(--brand)]" href="/issues">← All issues</Link><header><div className="flex flex-wrap gap-2"><Badge tone={tone(issue.severity)}>{issue.severity}</Badge><Badge>{issue.status.replaceAll("_"," ")}</Badge><Badge>{issue.visibility}</Badge></div><h1 className="mt-3 text-3xl font-semibold">{issue.title}</h1><p className="mt-2 text-sm text-[var(--muted)]">Reported by {issue.reporter_id} · {stamp(issue.created_at)} · {issue.affected_version||"unreleased or unknown version"}</p></header>{error&&<p role="alert" className="rounded-lg bg-[var(--danger-soft)] p-3 text-sm text-[var(--danger)]">{error}</p>}
    <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="font-semibold">Expected behavior</h2><p className="mt-2 whitespace-pre-wrap text-sm">{issue.expected_behavior}</p></Card><Card className="p-5"><h2 className="font-semibold">Observed behavior</h2><p className="mt-2 whitespace-pre-wrap text-sm">{issue.observed_behavior}</p></Card><Card className="p-5"><h2 className="font-semibold">Environment</h2><p className="mt-2 whitespace-pre-wrap text-sm">{issue.environment}</p></Card><Card className="p-5"><h2 className="font-semibold">Reproduction</h2><ol className="mt-2 list-decimal space-y-1 pl-5 text-sm">{issue.reproduction_steps.map((x,i)=><li key={i}>{x}</li>)}</ol></Card></div>
    {issue.attachments.length>0&&<Card className="p-5"><h2 className="font-semibold">Attached evidence</h2><div className="mt-3 flex flex-wrap gap-2">{issue.attachments.map(x=><a key={x.id} download={x.name} href={`data:${x.media_type};base64,${x.data}`} className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm text-[var(--brand)]">{x.name} · {Math.ceil(x.size/1024)} KiB</a>)}</div></Card>}
    <Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Maintainer status</h2><div className="flex flex-wrap gap-2">{(["triaged","in_progress","resolved","closed"] as const).filter(x=>x!==issue.status).map(x=><Button key={x} variant="secondary" onClick={()=>void status(x)}>{x.replaceAll("_"," ")}</Button>)}</div></div><div className="mt-4 space-y-2">{issue.history.map(x=><p key={x.id} className="text-xs text-[var(--muted)]">{stamp(x.created_at)} · {x.actor_id} · {x.kind.replaceAll("_"," ")}{x.to?` → ${x.to.replaceAll("_"," ")}`:""}</p>)}</div></Card>
    <Card className="p-5"><h2 className="font-semibold">Discussion</h2><div className="mt-3 space-y-3">{issue.discussion.map(x=><div key={x.id} className="rounded-lg bg-[var(--surface)] p-3"><p className="text-xs text-[var(--muted)]">{x.author_id} · {stamp(x.created_at)}</p><p className="mt-1 whitespace-pre-wrap text-sm">{x.body}</p></div>)}</div><form onSubmit={comment} className="mt-4"><label className="text-sm font-semibold">Add context<textarea name="body" required className={`${field} min-h-24 py-2`} /></label><Button className="mt-3">Comment</Button></form></Card>
  </div>
}
