"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Diagnostic={kind:string;severity:string;message:string;resource_id?:string;attributed_to:string};
type Revision={version:number;title:string;summary:string;subject:{kind:string;resource_id?:string;name:string};locales:{id:string;language:string;regions:string[];fallback_locale?:string;owner_ids:string[];reviewer_ids:string[]}[];terminology:{id:string;source:string;locale:string;preferred:string;avoid:string[];context:string}[];formatting_requirements:{locale:string;date:string;time:string;number:string;currency:string;units:string;direction:string}[];covered_journeys:{id:string;name:string;locale_ids:string[];owner_ids:string[];required:boolean}[];resources:{id:string;kind:string;path:string;format:string;source_revision:string;locale_ids:string[]}[];release_thresholds:{locale:string;minimum_percent:number;required_journey_ids:string[];require_owner_review:boolean;require_regional_review:boolean}[];rationale:string;created_by:string;created_at:string};
type Plan={id:string;current_version:number;revisions:Revision[];diagnostics:Diagnostic[]};
const val=(f:FormData,n:string)=>String(f.get(n)??"").trim(), list=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);

export function LocalePlansWorkspace({repositoryID}:{repositoryID:string}){
 const {token,user}=useAuth(),[plans,setPlans]=useState<Plan[]>([]),[selected,setSelected]=useState<Plan>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!token)return;try{const out=await api<{plans:Plan[]}>(`/repositories/${repositoryID}/locale-plans`,{},token);setPlans(out.plans);setSelected(x=>out.plans.find(p=>p.id===x?.id)??out.plans[0])}catch(e){setError(e instanceof Error?e.message:"Locale plans could not be loaded.")}},[repositoryID,token]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
 const current=selected?.revisions.at(-1);
 function build(f:FormData):Omit<Revision,"version"|"created_by"|"created_at">{const locale=val(f,"locale"),owners=list(val(f,"owners")),journey=val(f,"journey_id"),priorLocale=current?.locales[0]?.id,priorJourney=current?.covered_journeys[0]?.id;return {title:val(f,"title"),summary:val(f,"summary"),subject:{kind:val(f,"subject_kind"),resource_id:val(f,"subject_id"),name:val(f,"subject_name")},locales:[{id:locale,language:val(f,"language"),regions:list(val(f,"regions")),fallback_locale:val(f,"fallback"),owner_ids:owners,reviewer_ids:list(val(f,"reviewers"))},...(current?.locales.slice(1)??[])],terminology:[{id:val(f,"term_id"),source:val(f,"source_term"),locale,preferred:val(f,"preferred_term"),avoid:list(val(f,"avoid_terms")),context:val(f,"term_context")},...(current?.terminology.slice(1)??[])],formatting_requirements:[{locale,date:val(f,"date"),time:val(f,"time"),number:val(f,"number"),currency:val(f,"currency"),units:val(f,"units"),direction:val(f,"direction")},...(current?.formatting_requirements.slice(1)??[])],covered_journeys:[{id:journey,name:val(f,"journey_name"),locale_ids:replaceAssociation(current?.covered_journeys[0]?.locale_ids,priorLocale,locale),owner_ids:owners,required:true},...(current?.covered_journeys.slice(1)??[])],resources:[{id:val(f,"resource_id"),kind:val(f,"resource_kind"),path:val(f,"path"),format:val(f,"format"),source_revision:val(f,"revision"),locale_ids:replaceAssociation(current?.resources[0]?.locale_ids,priorLocale,locale)},...(current?.resources.slice(1)??[])],release_thresholds:[{locale,minimum_percent:Number(val(f,"percent")),required_journey_ids:replaceAssociation(current?.release_thresholds[0]?.required_journey_ids,priorJourney,journey),require_owner_review:val(f,"owner_review")==="yes",require_regional_review:val(f,"regional_review")==="yes"},...(current?.release_thresholds.slice(1)??[])],rationale:val(f,"rationale")}}
 async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;setBusy(true);setError("");const path=selected?`/repositories/${repositoryID}/locale-plans/${selected.id}/revisions`:`/repositories/${repositoryID}/locale-plans`;try{const out=await api<Plan>(path,{method:"POST",body:JSON.stringify({revision:build(new FormData(e.currentTarget)),...(selected?{expected_version:selected.current_version}:{})})},token);setSelected(out);setPlans(v=>[out,...v.filter(x=>x.id!==out.id)])}catch(e){setError(e instanceof Error?e.message:"Locale plan could not be published.")}finally{setBusy(false)}}
 return <div className="space-y-6"><header><Link href={`/repositories/${repositoryID}`} className="text-sm text-[var(--muted)] hover:text-[var(--brand)]">Repository</Link><h1 className="mt-2 text-2xl font-semibold">Locale coverage</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Define which languages, regions, resources, and journeys the project supports—and the quality bar a release must meet. Each successor is complete and revision-exact.</p></header>
 <Card className="p-5"><div className="flex justify-between"><h2 className="font-semibold">{selected?"Publish a complete successor":"Define a locale plan"}</h2>{selected&&<Button type="button" variant="secondary" onClick={()=>setSelected(undefined)}>New plan</Button>}</div><form className="mt-4 space-y-4" onSubmit={publish}><Group title="Scope and accountability"><Field n="title" l="Plan title" v={current?.title}/><Field n="subject_name" l="Supported experience" v={current?.subject.name}/><Select n="subject_kind" l="Scope" v={current?.subject.kind??"repository"} options={["repository","product","documentation_collection","release"]}/><Field n="subject_id" l="Scope resource ID" v={current?.subject.resource_id} required={false}/><Field n="owners" l="Locale owner IDs" v={current?.locales[0]?.owner_ids.join(", ")??user?.id}/><Field n="reviewers" l="Reviewer IDs" v={current?.locales[0]?.reviewer_ids.join(", ")}/></Group><Area n="summary" l="Support promise" v={current?.summary}/><Area n="rationale" l="Revision rationale" v={current?.rationale}/>
 <Group title="Target locale"><Field n="locale" l="Locale tag" v={current?.locales[0]?.id} placeholder="fr-CA"/><Field n="language" l="Language" v={current?.locales[0]?.language}/><Field n="regions" l="Regions (comma separated)" v={current?.locales[0]?.regions.join(", ")}/><Field n="fallback" l="Fallback locale" v={current?.locales[0]?.fallback_locale} required={false}/></Group>
 <Group title="Formatting"><Field n="date" l="Date format" v={current?.formatting_requirements[0]?.date}/><Field n="time" l="Time format" v={current?.formatting_requirements[0]?.time}/><Field n="number" l="Number format" v={current?.formatting_requirements[0]?.number}/><Field n="currency" l="Currency" v={current?.formatting_requirements[0]?.currency}/><Field n="units" l="Units" v={current?.formatting_requirements[0]?.units}/><Select n="direction" l="Text direction" v={current?.formatting_requirements[0]?.direction??"ltr"} options={["ltr","rtl"]}/></Group>
 <Group title="Terminology"><Field n="term_id" l="Term key" v={current?.terminology[0]?.id}/><Field n="source_term" l="Source term" v={current?.terminology[0]?.source}/><Field n="preferred_term" l="Preferred translation" v={current?.terminology[0]?.preferred}/><Field n="avoid_terms" l="Terms to avoid" v={current?.terminology[0]?.avoid.join(", ")} required={false}/><Field n="term_context" l="Usage context" v={current?.terminology[0]?.context}/></Group>
 <Group title="Covered journey and exact source"><Field n="journey_id" l="Journey key" v={current?.covered_journeys[0]?.id}/><Field n="journey_name" l="Journey name" v={current?.covered_journeys[0]?.name}/><Field n="resource_id" l="Resource key" v={current?.resources[0]?.id}/><Select n="resource_kind" l="Resource type" v={current?.resources[0]?.kind??"messages"} options={["messages","interface","documentation","release_notes","media"]}/><Field n="path" l="Source path" v={current?.resources[0]?.path}/><Select n="format" l="Format" v={current?.resources[0]?.format??"json"} options={["json","po","xliff","arb","yaml","markdown","mdx","other"]}/><Field n="revision" l="Exact source commit" v={current?.resources[0]?.source_revision}/></Group>
 <Group title="Release support threshold"><Field n="percent" l="Minimum translated percent" type="number" v={String(current?.release_thresholds[0]?.minimum_percent??100)}/><Select n="owner_review" l="Owner review required" v={current?.release_thresholds[0]?.require_owner_review===false?"no":"yes"} options={["yes","no"]}/><Select n="regional_review" l="Regional review required" v={current?.release_thresholds[0]?.require_regional_review===false?"no":"yes"} options={["yes","no"]}/></Group><Button disabled={busy}>{busy?"Publishing…":selected?`Publish version ${selected.current_version+1}`:"Create locale plan"}</Button></form></Card>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
 {selected&&current&&<Card className="p-5"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{current.title}</h2><Badge>version {selected.current_version}</Badge><Badge tone={selected.diagnostics.some(x=>x.severity==="blocking")?"danger":"success"}>{selected.diagnostics.length?`${selected.diagnostics.length} explicit gap(s)`:"coverage current"}</Badge></div><p className="mt-2 text-sm text-[var(--muted)]">{current.subject.kind.replaceAll("_"," ")} · {current.locales.map(x=>x.id).join(", ")} · {current.covered_journeys.length} journey(s)</p><div className="mt-4 grid gap-3 md:grid-cols-2">{selected.diagnostics.map((d,i)=><div className="rounded-lg border p-3" key={`${d.kind}-${i}`}><Badge tone={d.severity==="blocking"?"danger":"warning"}>{d.kind.replaceAll("_"," ")}</Badge><p className="mt-2 text-sm">{d.message}</p><p className="mt-1 text-xs text-[var(--muted)]">{d.resource_id} · attributed to {d.attributed_to}</p></div>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Version history</summary>{selected.revisions.map(r=><p className="mt-2 rounded-lg border p-3 text-sm" key={r.version}><strong>v{r.version}</strong> · {r.rationale} · {r.created_by} · {new Date(r.created_at).toLocaleString()}</p>)}</details></Card>}
 <section><h2 className="text-lg font-semibold">Repository locale plans</h2><div className="mt-3 space-y-2">{plans.map(p=>{const r=p.revisions.at(-1)!;return <button type="button" className="w-full rounded-xl border bg-white p-4 text-left hover:border-[var(--brand)]" key={p.id} onClick={()=>setSelected(p)}><span className="font-semibold">{r.title}</span><span className="block text-xs text-[var(--muted)]">{r.locales.map(x=>x.id).join(", ")} · v{p.current_version} · {p.diagnostics.length} explicit state(s)</span></button>})}</div></section></div>
}
function Group({title,children}:{title:string;children:React.ReactNode}){return <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">{title}</legend>{children}</fieldset>}
function Field({n,l,v,type="text",required=true,placeholder}:{n:string;l:string;v?:string;type?:string;required?:boolean;placeholder?:string}){return <label className="text-xs font-semibold">{l}<input key={v} name={n} type={type} required={required} defaultValue={v} placeholder={placeholder} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label>}
function Area({n,l,v}:{n:string;l:string;v?:string}){return <label className="text-xs font-semibold">{l}<textarea key={v} name={n} required rows={2} defaultValue={v} className="mt-1 w-full rounded-lg border p-3 font-normal"/></label>}
function Select({n,l,v,options}:{n:string;l:string;v:string;options:string[]}){return <label className="text-xs font-semibold">{l}<select key={v} name={n} defaultValue={v} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal">{options.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>}
function replaceAssociation(values:string[]|undefined,previous:string|undefined,next:string){if(!values?.length)return [next];return Array.from(new Set(values.map(value=>value===previous?next:value)))}
