"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api, type Organization, type OrganizationPortfolio, type Repository } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

function message(reason: unknown) { return reason instanceof Error ? reason.message : "The organization could not be updated."; }

export function OrganizationsWorkspace() {
  const { token, user } = useAuth();
  const [items,setItems]=useState<Organization[]>([]),[repositories,setRepositories]=useState<Repository[]>([]),[error,setError]=useState("");
  const load=useCallback(async()=>{if(!token)return;try{const [groups,repos]=await Promise.all([api<{organizations:Organization[]}>("/organizations",{},token),api<{repositories:Repository[]}>("/repositories?limit=100",{},token)]);setItems(groups.organizations??[]);setRepositories(repos.repositories??[])}catch(e){setError(message(e))}},[token]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{const created=await api<Organization>("/organizations",{method:"POST",body:JSON.stringify({name:data.get("name"),slug:data.get("slug"),description:data.get("description")})},token);setItems(x=>[...x,created]);form.reset()}catch(e){setError(message(e))}}
  async function accept(group:Organization,invitation:string){try{const changed=await api<Organization>(`/organizations/${group.id}/invitations/${invitation}/accept`,{method:"POST"},token);setItems(x=>x.map(v=>v.id===changed.id?changed:v))}catch(e){setError(message(e))}}
  async function transfer(event:FormEvent<HTMLFormElement>,group:Organization){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{const changed=await api<Organization>(`/organizations/${group.id}/repository-transfers`,{method:"POST",body:JSON.stringify({repository_id:data.get("repository_id")})},token);setItems(x=>x.map(v=>v.id===changed.id?changed:v));form.reset()}catch(e){setError(message(e))}}
  return <div className="space-y-7"><header className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--brand)]">Accountable groups</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Organizations</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Give collaborators a durable group identity without disconnecting repositories from the work and evidence already attached to them.</p></header>
    {error&&<p role="alert" className="rounded-lg bg-[var(--danger-soft)] p-3 text-sm text-[var(--danger)]">{error}</p>}
    <Card className="p-6"><h2 className="text-lg font-semibold">Create an organization</h2><form onSubmit={create} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Name<input name="name" required maxLength={100} className="mt-1 min-h-11 w-full rounded-lg border border-[var(--line-strong)] px-3 font-normal"/></label><label className="text-sm font-semibold">URL slug<input name="slug" required pattern="[a-z0-9-]+" maxLength={60} className="mt-1 min-h-11 w-full rounded-lg border border-[var(--line-strong)] px-3 font-mono font-normal"/></label><label className="text-sm font-semibold sm:col-span-2">Purpose<textarea name="description" maxLength={1000} className="mt-1 min-h-24 w-full rounded-lg border border-[var(--line-strong)] p-3 font-normal"/></label><div><Button type="submit">Create organization</Button></div></form></Card>
    <section className="grid gap-4">{items.length===0?<Card className="p-8 text-center text-sm text-[var(--muted)]">No organizations or invitations yet.</Card>:items.map(group=>{const invitation=group.invitations.find(x=>x.user_id===user?.id);const owned=repositories.filter(x=>x.owner_id===user?.id&&!x.organization_id);return <Card key={group.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-lg font-semibold">{group.name}</h2><Badge>{group.slug}</Badge></div><p className="mt-1 text-sm text-[var(--muted)]">{group.description||"Shared stewardship and portfolio evidence."}</p></div>{invitation?<Button onClick={()=>void accept(group,invitation.id)}>Accept invitation</Button>:<Link href={`/organizations/${group.id}`} className="text-sm font-semibold text-[var(--brand)] hover:underline">Open portfolio →</Link>}</div>{!invitation&&owned.length>0&&<form onSubmit={e=>void transfer(e,group)} className="mt-5 flex flex-wrap items-end gap-3 border-t border-[var(--line)] pt-4"><label className="grow text-xs font-semibold">Transfer an individually owned repository<select name="repository_id" required className="mt-1 min-h-10 w-full rounded-lg border border-[var(--line-strong)] bg-white px-3 font-normal">{owned.map(repo=><option key={repo.id} value={repo.id}>{repo.name}</option>)}</select></label><Button type="submit" variant="quiet">Request transfer</Button><p className="w-full text-xs text-[var(--muted)]">An organization owner must explicitly accept before the repository joins the portfolio.</p></form>}</Card>})}</section>
  </div>
}

export function OrganizationDetail({organizationID}:{organizationID:string}) {
  const {token,user}=useAuth();const [portfolio,setPortfolio]=useState<OrganizationPortfolio|null>(null),[error,setError]=useState("");
  const load=useCallback(async()=>{if(!token)return;try{setPortfolio(await api(`/organizations/${organizationID}/portfolio`,{},token))}catch(e){setError(message(e))}},[organizationID,token]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function submit(path:string,options:RequestInit){try{await api(path,options,token);await load()}catch(e){setError(message(e))}}
  if(!portfolio)return <p className="text-sm text-[var(--muted)]">{error||"Loading organization…"}</p>;const {organization:group}=portfolio;const owner=group.members.some(x=>x.user_id===user?.id&&x.role==="owner");
  return <div className="space-y-7"><header><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--brand)]">Organization portfolio</p><h1 className="mt-2 text-3xl font-bold">{group.name}</h1><p className="mt-2 text-sm text-[var(--muted)]">{group.description}</p></header>{error&&<p role="alert" className="rounded-lg bg-[var(--danger-soft)] p-3 text-sm text-[var(--danger)]">{error}</p>}
    <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Repositories",portfolio.repositories.length],["Packages",portfolio.packages.length],["Active proposals",portfolio.active_proposals.length],["Open pulls",portfolio.active_pulls.length],["Releases",portfolio.releases.length],["Incidents",portfolio.active_incidents.length]].map(([label,value])=><Card key={label} className="p-4"><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-[var(--muted)]">{label}</p></Card>)}</div>
    <div className="grid gap-6 xl:grid-cols-2"><Card className="p-5"><h2 className="text-lg font-semibold">Repository portfolio</h2>{portfolio.repositories.map(repo=><div key={repo.id} className="mt-3 flex justify-between border-t border-[var(--line)] pt-3 text-sm"><Link className="font-mono font-semibold text-[var(--brand)] hover:underline" href={`/repositories/${repo.id}`}>{repo.name}</Link><span>{repo.visibility}</span></div>)}{portfolio.repositories.length===0&&<p className="mt-3 text-sm text-[var(--muted)]">No repositories yet.</p>}{owner&&<form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f);void submit(`/organizations/${group.id}/repositories`,{method:"POST",body:JSON.stringify({name:d.get("name")})}).then(()=>f.reset())}} className="mt-5 flex gap-2"><input name="name" required pattern="[A-Za-z0-9._-]+" placeholder="new-repository" className="min-h-10 grow rounded-lg border border-[var(--line-strong)] px-3"/><Button type="submit">Create here</Button></form>}</Card>
      <Card className="p-5"><h2 className="text-lg font-semibold">Members</h2>{group.members.map(member=><div key={member.user_id} className="mt-3 flex items-center justify-between border-t border-[var(--line)] pt-3 text-sm"><span className="font-mono">{member.user_id}</span><div className="flex items-center gap-2"><Badge>{member.role}</Badge>{owner&&member.role!=="owner"&&<Button variant="quiet" onClick={()=>void submit(`/organizations/${group.id}/members/${member.user_id}`,{method:"DELETE"})}>Remove</Button>}</div></div>)}{owner&&<form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f);void submit(`/organizations/${group.id}/invitations`,{method:"POST",body:JSON.stringify({user_id:d.get("user_id")})}).then(()=>f.reset())}} className="mt-5 flex gap-2"><input name="user_id" required minLength={32} maxLength={32} placeholder="collaboration ID" className="min-h-10 grow rounded-lg border border-[var(--line-strong)] px-3 font-mono text-xs"/><Button type="submit">Invite</Button></form>}</Card></div>
    {owner&&group.transfers.some(x=>x.status==="pending")&&<Card className="p-5"><h2 className="text-lg font-semibold">Transfers awaiting acceptance</h2>{group.transfers.filter(x=>x.status==="pending").map(x=><div key={x.id} className="mt-3 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--line)] pt-3"><p className="text-sm"><code>{x.repository_id}</code><br/><span className="text-xs text-[var(--muted)]">Requested by {x.requested_by||x.from_owner_id}</span></p><Button onClick={()=>void submit(`/organizations/${group.id}/repository-transfers/${x.id}/accept`,{method:"POST"})}>Accept stewardship</Button></div>)}</Card>}
    <div className="grid gap-6 lg:grid-cols-2"><Evidence title="Active work" items={[...portfolio.active_proposals.map(x=>({id:x.id,label:x.title,href:`/proposals/${x.repository_id}/${x.id}`})),...portfolio.active_pulls.map(x=>({id:x.id,label:x.title,href:`/pulls/${x.repository_id}/${x.id}`}))]}/><Evidence title="Releases and incidents" items={[...portfolio.releases.map(x=>({id:x.id,label:`${x.version} · ${x.notes}`,href:`/repositories/${x.repository_id}/releases/${x.id}`})),...portfolio.active_incidents.map(x=>({id:x.id,label:x.title,href:`/incidents/${x.id}`}))]}/></div>
  </div>
}
function Evidence({title,items}:{title:string;items:{id:string;label:string;href:string}[]}){return <Card className="p-5"><h2 className="text-lg font-semibold">{title}</h2>{items.length===0?<p className="mt-3 text-sm text-[var(--muted)]">Nothing active.</p>:items.map(x=><Link key={x.id} href={x.href} className="mt-3 block border-t border-[var(--line)] pt-3 text-sm font-semibold text-[var(--brand)] hover:underline">{x.label}</Link>)}</Card>}
