"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/auth";
import { Badge, Button, Card } from "@/components/ui";
import { api } from "@/lib/api";

type Terms = {
  title: string;
  source: { kind: string; id: string; revision: string; visibility: string };
  scope: string;
  acceptance_criteria: string[];
  evidence_requirements: string[];
  budget: number;
  deadline: string;
  contributor_eligibility: string[];
  allocation_method: string;
  cancellation_terms: string;
  dependencies: string[];
  risks: string[];
  conflicts: string[];
  milestones: { id: string; title: string; budget: number; acceptance_criteria: string[]; evidence_requirements: string[]; dependencies: string[] }[];
};
type Outcome = {
  id: string; fund_id: string; version: number; status: string; pledged: number;
  milestone_pledged: Record<string, number>;
  revisions: { version: number; terms: Terms; actor_id: string; reason: string; created_at: string }[];
  pledges: { id: string; backer_id: string; amount: number; milestone_id?: string; status: string; note: string }[];
  replans: { kind: string; actor_id: string; reason: string; created_at: string }[];
  diagnostics: { kind: string; message: string }[];
  authority_note: string;
  delivery_proposals: DeliveryProposal[];
  delivery_selections: DeliverySelection[];
};
type DeliveryProposal = { id: string; applicant: { kind: string; id: string; submitted_by: string }; terms: { approach: string; milestones: string[]; cost: number; dependencies: string[]; availability: string; required_access: string[]; relevant_work: { kind: string; id: string; url?: string; note: string }[] }; status: string; accepted_by?: string; selection_id?: string; authority_note: string };
type Resource = { kind: string; id: string; revision?: string; url?: string; status: string };
type DeliveryExecution = { status: string; budget: number; spent: number; pending_expenses: number; agent_minutes: number; progress: number; forecast_at?: string; last_activity_at?: string; blockers: string[]; spending_blocked: boolean; spending_blockers: string[]; updates: { id: string; task_id: string; actor_id: string; status: string; progress: number; summary: string; resources: Resource[]; evidence: { kind: string; summary: string; resource: Resource }[]; created_at: string }[]; expenses: { id: string; task_id: string; amount: number; category: string; description: string; status: string; requested_by: string; decided_by?: string; decision_reason?: string; evidence: Resource[] }[]; controls: { kind: string; actor_id: string; reason: string; amount?: number; created_at: string }[] };
type MilestoneReview = { id: string; decision: string; reviewer_id: string; rationale: string; dissent: string[]; award_amount: number; released_amount: number; payment_status: string; authorship: string[]; resources: Resource[]; outcome_measures: { name: string; status: string; value: string; evidence: Resource }[]; created_at: string };
type DeliveryTask = { id: string; title: string; recipient_kind: string; recipient_id: string; status: string; reviewer_ids: string[]; award_amount: number; reviews: MilestoneReview[]; recoveries: { id: string; kind: string; actor_id: string; reason: string; amount: number; created_at: string }[] };
type DeliverySelection = { id: string; proposal_ids: string[]; conflict_disclosure: string; rationale: string; reserved_amount: number; reservation_id: string; tasks: DeliveryTask[]; selected_by: string; execution: DeliveryExecution };

const lines = (v: FormDataEntryValue | null) => String(v || "").split("\n").map((x) => x.trim()).filter(Boolean);

export function OutcomeFundingWorkspace({ repositoryID }: { repositoryID: string }) {
  const { token, user } = useAuth();
  const [outcomes, setOutcomes] = useState<Outcome[]>([]);
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    try { setOutcomes((await api<{ funded_outcomes: Outcome[] }>(`/repositories/${repositoryID}/funded-outcomes`, {}, token)).funded_outcomes); setError(""); }
    catch (e) { setError(e instanceof Error ? e.message : "Unable to load funded outcomes"); }
  }, [repositoryID, token]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);

  async function create(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = e.currentTarget; const d = new FormData(form);
    const milestones = lines(d.get("milestones")).map((row) => { const [id, title, budget, criteria, evidence, dependencies = ""] = row.split("|").map((x) => x.trim()); return { id, title, budget: Number(budget), acceptance_criteria: criteria.split(";").filter(Boolean), evidence_requirements: evidence.split(";").filter(Boolean), dependencies: dependencies.split(";").filter(Boolean) }; });
    const terms: Terms = {
      title: String(d.get("title")), source: { kind: String(d.get("source_kind")), id: String(d.get("source_id")), revision: String(d.get("source_revision")), visibility: String(d.get("visibility")) },
      scope: String(d.get("scope")), acceptance_criteria: lines(d.get("criteria")), evidence_requirements: lines(d.get("evidence")), budget: Number(d.get("budget")), deadline: new Date(String(d.get("deadline"))).toISOString(), contributor_eligibility: lines(d.get("eligibility")), allocation_method: String(d.get("allocation")), cancellation_terms: String(d.get("cancellation")), dependencies: lines(d.get("dependencies")), risks: lines(d.get("risks")), conflicts: lines(d.get("conflicts")), milestones,
    };
    try { await api(`/repositories/${repositoryID}/funded-outcomes`, { method: "POST", body: JSON.stringify({ fund_id: d.get("fund_id"), terms }) }, token); form.reset(); await load(); }
    catch (x) { setError(x instanceof Error ? x.message : "Unable to publish funding contract"); }
  }

  async function pledge(e: FormEvent<HTMLFormElement>, outcome: Outcome) {
    e.preventDefault(); const form = e.currentTarget; const d = new FormData(form);
    try { await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/pledges`, { method: "POST", body: JSON.stringify({ expected_version: outcome.version, amount: Number(d.get("amount")), milestone_id: d.get("milestone_id"), idempotency_key: crypto.randomUUID(), note: d.get("note") }) }, token); form.reset(); await load(); }
    catch (x) { setError(x instanceof Error ? x.message : "Unable to record pledge"); }
  }

  async function changePledge(outcome: Outcome, pledgeID: string, action: "withdraw" | "reconfirm") {
    const reason = action === "withdraw" ? "Backing withdrawn under the declared cancellation terms." : "Backer accepts the current revised scope and evidence terms.";
    try { await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/pledges/${pledgeID}`, { method: "POST", body: JSON.stringify({ expected_version: outcome.version, action, reason }) }, token); await load(); }
    catch (x) { setError(x instanceof Error ? x.message : "Unable to update pledge"); }
  }

  async function cancel(e: FormEvent<HTMLFormElement>, outcome: Outcome) {
    e.preventDefault(); const form = e.currentTarget; const d = new FormData(form);
    try { await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/cancel`, { method: "POST", body: JSON.stringify({ expected_version: outcome.version, reason: d.get("reason") }) }, token); await load(); }
    catch (x) { setError(x instanceof Error ? x.message : "Unable to cancel funding"); }
  }

  async function propose(e: FormEvent<HTMLFormElement>, outcome: Outcome) {
    e.preventDefault(); const form = e.currentTarget; const d = new FormData(form);
    const relevant_work = lines(d.get("relevant_work")).map((row) => { const [kind, id, url = "", note = ""] = row.split("|").map((x) => x.trim()); return { kind, id, url, note }; });
    try { await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/delivery-proposals`, { method: "POST", body: JSON.stringify({ applicant: { kind: d.get("applicant_kind"), id: d.get("applicant_id") }, terms: { approach: d.get("approach"), milestones: lines(d.get("delivery_milestones")), cost: Number(d.get("cost")), dependencies: lines(d.get("delivery_dependencies")), availability: d.get("availability"), required_access: lines(d.get("required_access")), relevant_work } }) }, token); form.reset(); await load(); }
    catch (x) { setError(x instanceof Error ? x.message : "Unable to submit delivery proposal"); }
  }

  async function acceptProposal(outcome: Outcome, proposalID: string) {
    try { await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/delivery-proposals/${proposalID}/accept`, { method: "POST", body: JSON.stringify({ expected_version: outcome.version }) }, token); await load(); }
    catch (x) { setError(x instanceof Error ? x.message : "Unable to accept delivery proposal"); }
  }

  async function selectProposals(e: FormEvent<HTMLFormElement>, outcome: Outcome) {
    e.preventDefault(); const form = e.currentTarget; const d = new FormData(form);
    try { await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/delivery-selections`, { method: "POST", body: JSON.stringify({ expected_version: outcome.version, proposal_ids: d.getAll("proposal_id"), reviewer_ids: lines(d.get("reviewer_ids")), conflict_disclosure: d.get("conflict_disclosure"), rationale: d.get("selection_rationale") }) }, token); form.reset(); await load(); }
    catch (x) { setError(x instanceof Error ? x.message : "Unable to select recipients and reserve budget"); }
  }

  const resources = (value: FormDataEntryValue | null): Resource[] => lines(value).map((row) => { const [kind, id, revision = "", status = "linked", url = ""] = row.split("|").map((x) => x.trim()); return { kind, id, revision, status, url }; });
  async function updateDelivery(e: FormEvent<HTMLFormElement>, outcome: Outcome, selection: DeliverySelection) {
    e.preventDefault(); const form = e.currentTarget; const d = new FormData(form); const linked = resources(d.get("resources"));
    try { await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/delivery-selections/${selection.id}/updates`, { method: "POST", body: JSON.stringify({ expected_version: outcome.version, recipient: { kind: "human", id: user?.id }, update: { task_id: d.get("task_id"), status: d.get("status"), progress: Number(d.get("progress")), summary: d.get("summary"), blockers: lines(d.get("blockers")), resources: linked, evidence: linked.map((resource) => ({ kind: resource.kind === "check" || resource.kind === "preview" ? resource.kind : "work", summary: `Evidence from ${resource.kind} ${resource.id}`, resource })), forecast_at: d.get("forecast") ? new Date(String(d.get("forecast"))).toISOString() : null, agent_minutes: Number(d.get("agent_minutes")) } }) }, token); form.reset(); await load(); }
    catch (x) { setError(x instanceof Error ? x.message : "Unable to report delivery progress"); }
  }
  async function requestExpense(e: FormEvent<HTMLFormElement>, outcome: Outcome, selection: DeliverySelection) {
    e.preventDefault(); const form=e.currentTarget; const d=new FormData(form);
    try { await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/delivery-selections/${selection.id}/expenses`, { method:"POST", body:JSON.stringify({ expected_version:outcome.version, recipient:{kind:"human",id:user?.id}, expense:{task_id:d.get("task_id"),amount:Number(d.get("expense_amount")),category:d.get("category"),description:d.get("description"),evidence:resources(d.get("expense_evidence"))} }) }, token); form.reset(); await load(); }
    catch(x){setError(x instanceof Error?x.message:"Unable to request expense approval");}
  }
  async function decideExpense(outcome:Outcome, selection:DeliverySelection, expenseID:string, decision:"approved"|"rejected") { try { await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/delivery-selections/${selection.id}/expenses/${expenseID}`,{method:"POST",body:JSON.stringify({expected_version:outcome.version,decision,reason:decision==="approved"?"Evidence is bounded to selected delivery.":"Expense does not meet the funded evidence boundary."})},token);await load(); } catch(x){setError(x instanceof Error?x.message:"Unable to decide expense");} }
  async function control(e:FormEvent<HTMLFormElement>,outcome:Outcome,selection:DeliverySelection){e.preventDefault();const form=e.currentTarget;const d=new FormData(form);const action=String(d.get("control_action"));const replacement=action==="replace_recipient"?{kind:d.get("replacement_kind"),id:d.get("replacement_id")}:undefined;try{await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/delivery-selections/${selection.id}/controls`,{method:"POST",body:JSON.stringify({expected_version:outcome.version,action,reason:d.get("control_reason"),amount:Number(d.get("control_amount")||0),replacement})},token);form.reset();await load();}catch(x){setError(x instanceof Error?x.message:"Unable to intervene in delivery");}}
  async function reviewMilestone(e:FormEvent<HTMLFormElement>,outcome:Outcome,selection:DeliverySelection,task:DeliveryTask){e.preventDefault();const form=e.currentTarget;const d=new FormData(form);const outcome_measures=lines(d.get("outcome_measures")).map((row)=>{const [name,status,value,kind,id,revision="",resourceStatus="linked",url=""]=row.split("|").map((x)=>x.trim());return{name,status,value,evidence:{kind,id,revision,status:resourceStatus,url}};});try{await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/delivery-selections/${selection.id}/tasks/${task.id}/reviews`,{method:"POST",body:JSON.stringify({expected_version:outcome.version,review:{decision:d.get("review_decision"),rationale:d.get("review_rationale"),dissent:lines(d.get("review_dissent")),award_amount:Number(d.get("award_amount")||0),outcome_measures}})},token);form.reset();await load();}catch(x){setError(x instanceof Error?x.message:"Unable to record milestone acceptance");}}
  async function recoverMilestone(e:FormEvent<HTMLFormElement>,outcome:Outcome,selection:DeliverySelection,task:DeliveryTask){e.preventDefault();const form=e.currentTarget;const d=new FormData(form);try{await api(`/repositories/${repositoryID}/funded-outcomes/${outcome.id}/delivery-selections/${selection.id}/tasks/${task.id}/recoveries`,{method:"POST",body:JSON.stringify({expected_version:outcome.version,action:d.get("recovery_action"),reason:d.get("recovery_reason")})},token);form.reset();await load();}catch(x){setError(x instanceof Error?x.message:"Unable to apply milestone recovery");}}

  return <main id="main-content" className="mx-auto max-w-6xl space-y-6 p-6">
    <div><Badge>Evaluable outcomes</Badge><h1 className="mt-2 text-3xl font-semibold">Outcome funding</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Decide whether funded work is worth pursuing from its exact scope, acceptance evidence, backing, dependencies, risks, and cancellation terms.</p></div>
    {user && <Card className="p-5"><h2 className="text-lg font-semibold">Publish a funding contract</h2><p className="mt-1 text-xs text-[var(--muted)]">Amounts use the linked fund&apos;s minor unit. Lists use one item per line. Milestones use <code>id | title | amount | criterion;criterion | evidence;evidence | dependency IDs</code>.</p>
      <form onSubmit={create} className="mt-4 grid gap-3 md:grid-cols-3">
        <Field name="title" label="Outcome title"/><Field name="fund_id" label="Governed fund ID"/><Select name="source_kind" label="Outcome source" values={["issue","roadmap_outcome","proposal","stewardship_opportunity","incident_follow_up","security_repair"]}/>
        <Field name="source_id" label="Source ID"/><Field name="source_revision" label="Exact source revision"/><Select name="visibility" label="Visibility" values={["public","participants","embargoed"]}/>
        <Field name="budget" label="Budget (minor units)" type="number"/><Field name="deadline" label="Deadline" type="datetime-local"/><Select name="allocation" label="Allocation method" values={["milestone_claim","first_accepted","proportional","maintainer_selection"]}/>
        <Area name="scope" label="Bounded scope"/><Area name="criteria" label="Acceptance criteria"/><Area name="evidence" label="Required evidence"/><Area name="eligibility" label="Contributor eligibility"/><Area name="dependencies" label="Dependencies"/><Area name="risks" label="Risks"/><Area name="conflicts" label="Known conflicts"/><Area name="cancellation" label="Cancellation and return terms"/><Area name="milestones" label="Declared milestones"/>
        <Button>Publish exact terms</Button>
      </form></Card>}
    {error && <p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
    {outcomes.map((outcome) => { const revision = outcome.revisions.at(-1)!; const terms = revision.terms; return <Card key={outcome.id} className="p-5">
      <div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold">{terms.title}</h2><Badge tone={outcome.status === "open" ? "success" : "neutral"}>{outcome.status}</Badge><Badge>v{outcome.version}</Badge><Badge>{terms.source.kind.replaceAll("_", " ")} · {terms.source.id}@{terms.source.revision}</Badge></div>
      <p className="mt-3">{terms.scope}</p><div className="mt-4 grid gap-4 md:grid-cols-3"><Fact title="Backing" values={[`${outcome.pledged} / ${terms.budget} minor units`, `Deadline ${new Date(terms.deadline).toLocaleString()}`, terms.allocation_method.replaceAll("_", " ")]}/><Fact title="Acceptance criteria" values={terms.acceptance_criteria}/><Fact title="Evidence required" values={terms.evidence_requirements}/><Fact title="Eligible contributors" values={terms.contributor_eligibility}/><Fact title="Dependencies" values={terms.dependencies}/><Fact title="Risks and conflicts" values={[...terms.risks, ...terms.conflicts]}/></div>
      <p className="mt-4 rounded-lg bg-[var(--surface-sunken)] p-3 text-sm"><strong>Cancellation:</strong> {terms.cancellation_terms}</p>
      {terms.milestones.length > 0 && <div className="mt-4"><h3 className="font-semibold">Milestones</h3>{terms.milestones.map((m) => <div key={m.id} className="mt-2 rounded-lg border p-3 text-sm"><strong>{m.title}</strong> · {outcome.milestone_pledged[m.id] || 0} / {m.budget}<span className="block text-xs text-[var(--muted)]">Accept: {m.acceptance_criteria.join("; ")} · Evidence: {m.evidence_requirements.join("; ")}{m.dependencies.length ? ` · After ${m.dependencies.join(", ")}` : ""}</span></div>)}</div>}
      {outcome.diagnostics.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{outcome.diagnostics.map((d) => <span key={d.kind} title={d.message}><Badge tone="warning">{d.kind.replaceAll("_", " ")}</Badge></span>)}</div>}
      {outcome.pledges.length > 0 && <div className="mt-4"><h3 className="font-semibold">Backing</h3>{outcome.pledges.map((p) => <div key={p.id} className="mt-2 flex flex-wrap items-center gap-2 rounded-lg border p-3 text-sm"><Badge tone={p.status === "active" ? "success" : "warning"}>{p.status.replaceAll("_", " ")}</Badge><span>{p.amount} · {p.milestone_id || "whole outcome"} · {p.backer_id}</span>{p.backer_id === user?.id && p.status === "reconfirmation_required" && <Button type="button" variant="secondary" onClick={() => void changePledge(outcome, p.id, "reconfirm")}>Reconfirm current terms</Button>}{p.backer_id === user?.id && p.status !== "withdrawn" && <Button type="button" variant="quiet" onClick={() => void changePledge(outcome, p.id, "withdraw")}>Withdraw backing</Button>}</div>)}</div>}
      {user && outcome.status === "open" && <form onSubmit={(e) => pledge(e, outcome)} className="mt-5 grid gap-3 rounded-lg border p-4 md:grid-cols-4"><Field name="amount" label="Pledge amount" type="number"/><label className="text-xs font-semibold">Pledge target<select name="milestone_id" className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal"><option value="">Whole outcome</option>{terms.milestones.map((m) => <option key={m.id} value={m.id}>{m.title}</option>)}</select></label><Field name="note" label="Backing rationale"/><Button>Back declared terms</Button></form>}
      {user && outcome.status === "open" && <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-[var(--danger)]">Cancel and replan</summary><form onSubmit={(e) => cancel(e, outcome)} className="mt-2 flex flex-wrap gap-2"><Field name="reason" label="Attributed cancellation reason"/><Button variant="secondary">Apply cancellation terms</Button></form></details>}
      <section className="mt-6 border-t pt-5"><h3 className="text-lg font-semibold">Delivery proposals</h3><p className="mt-1 text-sm text-[var(--muted)]">Compare capability, availability, evidence, cost, and requested access. Requested access is planning information—not a grant.</p>
        {user && outcome.status === "open" && <details className="mt-3"><summary className="cursor-pointer text-sm font-semibold text-[var(--brand)]">Submit as an eligible human, team, or approved agent</summary><form onSubmit={(e) => propose(e, outcome)} className="mt-3 grid gap-3 rounded-lg border p-4 md:grid-cols-3"><Select name="applicant_kind" label="Applicant kind" values={["human","team","approved_agent"]}/><Field name="applicant_id" label="Human, team, or agent ID"/><Field name="cost" label="Proposed cost" type="number"/><Area name="approach" label="Approach"/><Area name="delivery_milestones" label="Milestones (one per line)"/><Area name="delivery_dependencies" label="Dependencies"/><Area name="availability" label="Availability"/><Area name="required_access" label="Access needed (separately approved)"/><Area name="relevant_work" label="Attributed work: kind | id | URL | note"/><Button>Submit attributable proposal</Button></form></details>}
        <div className="mt-3 grid gap-3 md:grid-cols-2">{(outcome.delivery_proposals || []).map((p) => <div key={p.id} className="rounded-lg border p-4 text-sm"><div className="flex flex-wrap gap-2"><Badge>{p.applicant.kind.replaceAll("_", " ")}</Badge><Badge tone={p.status === "selected" ? "success" : p.status === "accepted" ? "warning" : "neutral"}>{p.status}</Badge><strong>{p.applicant.id}</strong><span>{p.terms.cost} minor units</span></div><p className="mt-2">{p.terms.approach}</p><Fact title="Milestones" values={p.terms.milestones}/><Fact title="Availability" values={[p.terms.availability]}/><Fact title="Dependencies" values={p.terms.dependencies}/><Fact title="Requested—not granted—access" values={p.terms.required_access}/><Fact title="Attributed work" values={p.terms.relevant_work.map((w) => `${w.kind}: ${w.id} — ${w.note}`)}/>{user && p.status === "submitted" && <Button type="button" variant="secondary" onClick={() => void acceptProposal(outcome, p.id)}>Accept proposed delivery</Button>}<p className="mt-3 text-xs text-[var(--muted)]">{p.authority_note}</p></div>)}</div>
        {user && (outcome.delivery_proposals || []).some((p) => p.status === "accepted") && <form onSubmit={(e) => selectProposals(e, outcome)} className="mt-4 rounded-lg border p-4"><h4 className="font-semibold">Steward selection and reservation</h4><p className="mt-1 text-xs text-[var(--muted)]">Choose one recipient or a complementary mix and designate current project participants to review results. Review standing governs compensation only.</p><div className="my-3 flex flex-wrap gap-3">{outcome.delivery_proposals.filter((p) => p.status === "accepted").map((p) => <label key={p.id} className="rounded-lg border px-3 py-2 text-sm"><input required={false} type="checkbox" name="proposal_id" value={p.id} className="mr-2"/>{p.applicant.id} · {p.terms.cost}</label>)}</div><div className="grid gap-3 md:grid-cols-2"><Area name="reviewer_ids" label="Designated reviewer IDs (one per line)"/><Area name="conflict_disclosure" label="Conflict disclosure (state none if none)"/><Area name="selection_rationale" label="Comparative rationale"/><Button>Reserve budget and create planned tasks</Button></div></form>}
        {(outcome.delivery_selections || []).map((s) => { const execution=s.execution || {status:"active",budget:s.reserved_amount,spent:0,pending_expenses:0,agent_minutes:0,progress:0,blockers:[],spending_blocked:false,spending_blockers:[],updates:[],expenses:[],controls:[]}; return <div key={s.id} className="mt-4 rounded-lg bg-[var(--surface-sunken)] p-4 text-sm"><div className="flex flex-wrap gap-2"><Badge tone={execution.spending_blocked?"warning":"success"}>{execution.spending_blocked?"new spending stopped":execution.status}</Badge><strong>{execution.progress}% progress</strong><span>{execution.spent} spent · {execution.pending_expenses} awaiting approval · {execution.budget-execution.spent} reserved</span><span>{execution.agent_minutes} agent minutes</span>{execution.forecast_at&&<span>forecast {new Date(execution.forecast_at).toLocaleString()}</span>}</div>{execution.spending_blockers.length>0&&<p className="mt-2 text-[var(--danger)]">Spending blockers: {execution.spending_blockers.join(", ")}</p>}<p className="mt-2"><strong>Comparison:</strong> {s.rationale}</p><p><strong>Conflicts:</strong> {s.conflict_disclosure}</p><h4 className="mt-3 font-semibold">Connected delivery tasks</h4><ul className="mt-1 list-disc pl-5">{s.tasks.map((task) => <li key={task.id}>{task.title} — {task.recipient_kind.replaceAll("_", " ")} {task.recipient_id} ({task.status})</li>)}</ul>
          {execution.updates.map((u)=><div key={u.id} className="mt-3 rounded-lg border bg-white p-3"><strong>{u.progress}% · {u.status}</strong> — {u.summary}<p className="text-xs text-[var(--muted)]">{u.resources.map((r)=>`${r.kind} ${r.id}${r.revision?`@${r.revision}`:""} (${r.status})`).join(" · ")}</p></div>)}
          {s.tasks.map((task)=><div key={`${task.id}-acceptance`} className="mt-3 rounded-lg border bg-white p-3"><div className="flex flex-wrap gap-2"><strong>{task.title}</strong><Badge>{task.status.replaceAll("_"," ")}</Badge><span>{task.award_amount} allocated</span><span>reviewers: {(task.reviewer_ids||[]).join(", ")}</span></div>{(task.reviews||[]).map((review)=><div key={review.id} className="mt-2 rounded-lg bg-[var(--surface-sunken)] p-3"><div className="flex flex-wrap gap-2"><Badge tone={review.payment_status==="paid"?"success":review.decision==="disputed"?"warning":"neutral"}>{review.decision.replaceAll("_"," ")}</Badge><span>{review.award_amount} awarded · {review.released_amount||0} released · {review.payment_status.replaceAll("_"," ")}</span></div><p className="mt-1">{review.rationale}</p><p className="text-xs text-[var(--muted)]">Authorship: {review.authorship.join(", ")} · Evidence: {review.resources.map((r)=>`${r.kind} ${r.id}@${r.revision||"current"} (${r.status})`).join(" · ")}</p><p className="text-xs text-[var(--muted)]">Measures: {review.outcome_measures.map((m)=>`${m.name}: ${m.value} (${m.status})`).join(" · ")||"none declared"}</p>{review.dissent.length>0&&<p className="text-xs">Retained dissent: {review.dissent.join(" · ")}</p>}</div>)}{user&&(task.reviewer_ids||[]).includes(user.id)&&!task.reviews.some((r)=>r.payment_status==="paid")&&<form onSubmit={(e)=>reviewMilestone(e,outcome,s,task)} className="mt-3 grid gap-2 md:grid-cols-2"><Select name="review_decision" label="Governed review decision" values={["accepted","rejected","correction_requested","partial_award","disputed"]}/><Field name="award_amount" label="Partial award amount" type="number" required={false}/><Area name="review_rationale" label="Retained rationale"/><Area name="review_dissent" label="Dissent (one per line)" required={false}/><Area name="outcome_measures" label="Measures: name | met/not_met/inconclusive | value | evidence kind | ID | revision | status | URL" required={false}/><Button>Record evidence-bound decision</Button></form>}{user&&<form onSubmit={(e)=>recoverMilestone(e,outcome,s,task)} className="mt-3 grid gap-2 md:grid-cols-3"><Select name="recovery_action" label="Recovery path" values={["appeal","withdraw","timeout","payment_failed","retry_payment","refund"]}/><Area name="recovery_reason" label="Retained recovery rationale"/><Button variant="secondary">Apply eligible recovery</Button></form>}</div>)}
          {execution.expenses.map((x)=><div key={x.id} className="mt-3 flex flex-wrap items-center gap-2 rounded-lg border bg-white p-3"><Badge tone={x.status==="approved"?"success":x.status==="pending"?"warning":"neutral"}>{x.status}</Badge><strong>{x.amount} · {x.category.replaceAll("_"," ")}</strong><span>{x.description}</span>{user&&x.status==="pending"&&<><Button type="button" variant="secondary" onClick={()=>void decideExpense(outcome,s,x.id,"approved")}>Approve bounded expense</Button><Button type="button" variant="quiet" onClick={()=>void decideExpense(outcome,s,x.id,"rejected")}>Reject</Button></>}</div>)}
          {user&&execution.status!=="cancelled"&&s.tasks.some((t)=>t.recipient_kind==="human"&&t.recipient_id===user.id)&&<div className="mt-4 grid gap-3 lg:grid-cols-2"><form onSubmit={(e)=>updateDelivery(e,outcome,s)} className="grid gap-2 rounded-lg border bg-white p-3"><h5 className="font-semibold">Report milestone delivery</h5><Select name="task_id" label="Connected task" values={s.tasks.filter((t)=>t.recipient_kind==="human"&&t.recipient_id===user.id).map((t)=>t.id)}/><Select name="status" label="Status" values={["active","blocked","completed","handoff_failed"]}/><Field name="progress" label="Progress percent" type="number"/><Area name="summary" label="Work and evidence summary"/><Area name="resources" label="Resources: kind | ID | revision | status | URL"/><Area name="blockers" label="Blockers (one per line)" required={false}/><Field name="forecast" label="Forecast completion" type="datetime-local"/><Field name="agent_minutes" label="Agent compute minutes" type="number"/><Button>Publish attributable progress</Button></form><form onSubmit={(e)=>requestExpense(e,outcome,s)} className="grid gap-2 rounded-lg border bg-white p-3"><h5 className="font-semibold">Request a bounded expense</h5><Select name="task_id" label="Connected task" values={s.tasks.filter((t)=>t.recipient_kind==="human"&&t.recipient_id===user.id).map((t)=>t.id)}/><Field name="expense_amount" label="Amount" type="number"/><Select name="category" label="Category" values={["labor","agent_compute","service","materials","other"]}/><Area name="description" label="Expense rationale"/><Area name="expense_evidence" label="Evidence: kind | ID | revision | status | URL"/><Button variant="secondary">Request steward approval</Button></form></div>}
          {user&&<form onSubmit={(e)=>control(e,outcome,s)} className="mt-3 grid gap-2 rounded-lg border bg-white p-3 md:grid-cols-3"><Select name="control_action" label="Steward intervention" values={["pause","resume","access_revoked","increase_budget","replace_recipient","cancel_remaining"]}/><Field name="control_amount" label="Budget increase (when applicable)" type="number" required={false}/><Select name="replacement_kind" label="Replacement kind" values={["human","team","approved_agent"]}/><Field name="replacement_id" label="Replacement principal ID" required={false}/><Area name="control_reason" label="Bounded intervention reason"/><Button variant="secondary">Apply intervention</Button></form>}
          <p className="mt-3 text-xs text-[var(--muted)]">Reservation {s.reservation_id} governs compensation only; linked tasks, sessions, workspaces, forks, pulls, checks, previews, and teams retain their own authority.</p></div>;})}
      </section>
      <details className="mt-4"><summary className="cursor-pointer font-semibold">Attributable replanning · {outcome.replans.length}</summary>{outcome.replans.map((r, i) => <p key={`${r.created_at}-${i}`} className="mt-2 text-sm"><Badge>{r.kind.replaceAll("_", " ")}</Badge> {r.reason} · {r.actor_id}</p>)}</details><p className="mt-4 text-xs text-[var(--muted)]">{outcome.authority_note}</p>
    </Card>; })}
  </main>;
}

function Fact({ title, values }: { title: string; values: string[] }) { return <div><h3 className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">{title}</h3>{values.length ? <ul className="mt-1 list-disc pl-5 text-sm">{values.map((x, i) => <li key={`${x}-${i}`}>{x}</li>)}</ul> : <p className="mt-1 text-sm text-[var(--muted)]">None declared</p>}</div>; }
function Field({ name, label, type = "text", required = true }: { name: string; label: string; type?: string; required?: boolean }) { return <label className="text-xs font-semibold">{label}<input required={required} name={name} type={type} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label>; }
function Area({ name, label, required = true }: { name: string; label: string; required?: boolean }) { return <label className="text-xs font-semibold">{label}<textarea required={required} name={name} rows={3} className="mt-1 w-full rounded-lg border p-3 font-normal"/></label>; }
function Select({ name, label, values }: { name: string; label: string; values: string[] }) { return <label className="text-xs font-semibold">{label}<select name={name} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal">{values.map((v) => <option key={v} value={v}>{v.replaceAll("_", " ")}</option>)}</select></label>; }
