"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Diagnostic={kind:string;severity:string;message:string;metric?:string;attributed_to:string};
type Revision={version:number;title:string;summary:string;subject:{kind:string;resource_id?:string;name:string};workloads:{name:string;description:string;inputs:string;warmup:number;samples:number}[];metrics:{name:string;unit:string;direction:string;minimum?:number;maximum?:number;baseline:{value?:number;environment:string;measured_at?:string;source?:string}}[];correctness_constraints:{name:string;requirement:string;verification:string}[];supported_environments:{name:string;os:string;architecture:string;runtime:string;hardware:string}[];owners:string[];budgets:{kind:string;limit:number;unit:string}[];links:{kind:string;resource_id:string;label:string;added_by:string}[];baseline_max_age_days:number;created_by:string;created_at:string;rationale:string};
type Goal={id:string;current_version:number;revisions:Revision[];diagnostics:Diagnostic[];updated_at:string};
const text=(form:FormData,name:string)=>String(form.get(name)??"").trim();
const optionalNumber=(value:string)=>value===""?undefined:Number(value);

export function PerformanceGoalsWorkspace({repositoryID}:{repositoryID:string}){
 const {token,user}=useAuth();const [goals,setGoals]=useState<Goal[]>([]);const [selected,setSelected]=useState<Goal>();const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!token)return;try{const result=await api<{goals:Goal[]}>(`/repositories/${repositoryID}/performance-goals`,{},token);setGoals(result.goals);setSelected(current=>result.goals.find(goal=>goal.id===current?.id)??result.goals[0])}catch(reason){setError(reason instanceof Error?reason.message:"Performance goals could not be loaded.")}},[repositoryID,token]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
 function revision(form:FormData):Omit<Revision,"version"|"created_by"|"created_at">{const baselineValue=optionalNumber(text(form,"baseline_value")),measuredAt=text(form,"measured_at"),minimum=optionalNumber(text(form,"minimum")),maximum=optionalNumber(text(form,"maximum"));const prior=current;const firstLink=text(form,"link_id")?{kind:text(form,"link_kind"),resource_id:text(form,"link_id"),label:text(form,"link_label"),added_by:""}:undefined;return {title:text(form,"title"),summary:text(form,"summary"),subject:{kind:text(form,"subject_kind"),resource_id:text(form,"subject_id"),name:text(form,"subject_name")},workloads:[{name:text(form,"workload_name"),description:text(form,"workload_description"),inputs:text(form,"inputs"),warmup:Number(text(form,"warmup")||0),samples:Number(text(form,"samples"))},...(prior?.workloads.slice(1)??[])],metrics:[{name:text(form,"metric_name"),unit:text(form,"unit"),direction:text(form,"direction"),minimum,maximum,baseline:{value:baselineValue,environment:text(form,"baseline_environment"),measured_at:measuredAt||undefined,source:text(form,"baseline_source")}},...(prior?.metrics.slice(1)??[])],correctness_constraints:[{name:text(form,"constraint_name"),requirement:text(form,"requirement"),verification:text(form,"verification")},...(prior?.correctness_constraints.slice(1)??[])],supported_environments:[{name:text(form,"environment_name"),os:text(form,"os"),architecture:text(form,"architecture"),runtime:text(form,"runtime"),hardware:text(form,"hardware")},...(prior?.supported_environments.slice(1)??[])],owners:text(form,"owners").split(",").map(x=>x.trim()).filter(Boolean),budgets:[{kind:text(form,"budget_kind"),limit:Number(text(form,"budget_limit")),unit:text(form,"budget_unit")},...(prior?.budgets.slice(1)??[])],links:[...(firstLink?[firstLink]:[]),...(prior?.links.slice(1)??[])],baseline_max_age_days:Number(text(form,"baseline_age")),rationale:text(form,"rationale")}}
 async function publish(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;setBusy(true);setError("");const body={revision:revision(new FormData(event.currentTarget)),...(selected?{expected_version:selected.current_version}:{})};const path=selected?`/repositories/${repositoryID}/performance-goals/${selected.id}/revisions`:`/repositories/${repositoryID}/performance-goals`;try{const goal=await api<Goal>(path,{method:"POST",body:JSON.stringify(body)},token);setSelected(goal);setGoals(items=>[goal,...items.filter(item=>item.id!==goal.id)])}catch(reason){setError(reason instanceof Error?reason.message:"The contract could not be published.")}finally{setBusy(false)}}
 const current=selected?.revisions.at(-1);
 return <div className="space-y-6"><header><Link href={`/repositories/${repositoryID}`} className="text-sm text-[var(--muted)] hover:text-[var(--brand)]">Repository</Link><h1 className="mt-2 text-2xl font-semibold">Performance goals</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Agree on workloads, measurable targets, correctness, environments, ownership, and cost before judging an optimization. Every successor remains attributable and earlier contracts stay inspectable.</p></header>
 <Card className="p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">{selected?"Publish a complete successor":"Define a performance contract"}</h2>{selected&&<Button type="button" variant="secondary" onClick={()=>setSelected(undefined)}>New goal</Button>}</div><form onSubmit={publish} className="mt-4 space-y-4">
 <div className="grid gap-3 md:grid-cols-3"><Field name="title" label="Goal title" value={current?.title}/><Field name="subject_name" label="Measured surface" value={current?.subject.name}/><label className="text-xs font-semibold">Subject type<select name="subject_kind" defaultValue={current?.subject.kind??"repository"} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal"><option value="repository">Repository</option><option value="release">Release</option><option value="user_journey">User journey</option><option value="api">API</option><option value="command">Command</option><option value="service">Service</option></select></label><Field name="subject_id" label="Subject resource ID" value={current?.subject.resource_id}/><Field name="owners" label="Owner IDs (comma separated)" value={current?.owners.join(", ")??user?.id}/><Field name="baseline_age" label="Baseline max age (days)" type="number" value={String(current?.baseline_max_age_days??30)}/></div><Area name="summary" label="Shared outcome" value={current?.summary}/><Area name="rationale" label="Revision rationale" value={current?.rationale}/>
 <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">Workload</legend><Field name="workload_name" label="Name" value={current?.workloads[0]?.name}/><Field name="samples" label="Samples" type="number" value={String(current?.workloads[0]?.samples??30)}/><Field name="warmup" label="Warmup runs" type="number" value={String(current?.workloads[0]?.warmup??2)}/><Field name="inputs" label="Inputs / fixture" value={current?.workloads[0]?.inputs}/><div className="md:col-span-2"><Area name="workload_description" label="Reproduction description" value={current?.workloads[0]?.description}/></div></fieldset>
 <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-4"><legend className="px-2 text-sm font-semibold">Metric, target, and baseline</legend><Field name="metric_name" label="Metric" value={current?.metrics[0]?.name}/><Field name="unit" label="Unit" value={current?.metrics[0]?.unit}/><label className="text-xs font-semibold">Direction<select name="direction" defaultValue={current?.metrics[0]?.direction??"lower"} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal"><option value="lower">Lower is better</option><option value="higher">Higher is better</option><option value="range">Stay in range</option></select></label><Field name="minimum" label="Target minimum" type="number" value={String(current?.metrics[0]?.minimum??"")}/><Field name="maximum" label="Target maximum" type="number" value={String(current?.metrics[0]?.maximum??"")}/><Field name="baseline_value" label="Baseline value (optional)" type="number" value={String(current?.metrics[0]?.baseline.value??"")} required={false}/><Field name="baseline_environment" label="Baseline environment" value={current?.metrics[0]?.baseline.environment}/><Field name="measured_at" label="Measured at" type="datetime-local" value={current?.metrics[0]?.baseline.measured_at?.slice(0,16)} required={false}/><Field name="baseline_source" label="Measurement source" value={current?.metrics[0]?.baseline.source} required={false}/></fieldset>
 <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">Supported environment</legend>{(["environment_name","os","architecture","runtime","hardware"] as const).map((name,index)=><Field key={name} name={name} label={["Environment name","OS","Architecture","Runtime","Hardware"][index]} value={[current?.supported_environments[0]?.name,current?.supported_environments[0]?.os,current?.supported_environments[0]?.architecture,current?.supported_environments[0]?.runtime,current?.supported_environments[0]?.hardware][index]}/>)}</fieldset>
 <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">Correctness and budget</legend><Field name="constraint_name" label="Constraint" value={current?.correctness_constraints[0]?.name}/><Field name="requirement" label="Must not regress" value={current?.correctness_constraints[0]?.requirement}/><Field name="verification" label="Verification" value={current?.correctness_constraints[0]?.verification}/><Field name="budget_kind" label="Budget kind" value={current?.budgets[0]?.kind}/><Field name="budget_limit" label="Budget limit" type="number" value={String(current?.budgets[0]?.limit??"")}/><Field name="budget_unit" label="Budget unit" value={current?.budgets[0]?.unit}/></fieldset>
 <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">Project context (optional)</legend><label className="text-xs font-semibold">Link type<select name="link_kind" defaultValue={current?.links[0]?.kind??"issue"} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal"><option>issue</option><option>incident</option><option>preview</option><option>release</option><option>decision</option></select></label><Field name="link_id" label="Resource ID" value={current?.links[0]?.resource_id} required={false}/><Field name="link_label" label="Link label" value={current?.links[0]?.label} required={false}/></fieldset><Button disabled={busy}>{busy?"Publishing…":selected?`Publish version ${selected.current_version+1}`:"Create goal"}</Button></form></Card>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
 {selected&&current&&<Card className="p-5"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{current.title}</h2><Badge>version {selected.current_version}</Badge><Badge tone={selected.diagnostics.some(d=>d.severity==="blocking")?"danger":"success"}>{selected.diagnostics.length?`${selected.diagnostics.length} explicit states`:"comparable"}</Badge></div><p className="mt-2 text-sm text-[var(--muted)]">{current.subject.kind.replaceAll("_"," ")} · {current.subject.name} · owned by {current.owners.join(", ")}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{selected.diagnostics.map((item,index)=><div key={`${item.kind}-${index}`} className="rounded-lg border p-3"><Badge tone={item.severity==="blocking"?"danger":"warning"}>{item.kind.replaceAll("_"," ")}</Badge><p className="mt-2 text-sm">{item.metric&&<strong>{item.metric}: </strong>}{item.message}</p><p className="mt-1 text-xs text-[var(--muted)]">Attributed to {item.attributed_to}</p></div>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Version history</summary><div className="mt-2 space-y-2">{selected.revisions.map(item=><p key={item.version} className="rounded-lg border p-3 text-sm"><strong>v{item.version}</strong> · {item.rationale} · {item.created_by} · {new Date(item.created_at).toLocaleString()}</p>)}</div></details></Card>}
 <section><h2 className="text-lg font-semibold">Repository contracts</h2><div className="mt-3 space-y-2">{goals.map(goal=>{const latest=goal.revisions.at(-1)!;return <button key={goal.id} type="button" onClick={()=>setSelected(goal)} className="w-full rounded-xl border bg-white p-4 text-left hover:border-[var(--brand)]"><span className="font-semibold">{latest.title}</span><span className="mt-1 block text-xs text-[var(--muted)]">{latest.subject.name} · v{goal.current_version} · {goal.diagnostics.length} explicit state(s)</span></button>})}</div></section></div>
}
function Field({name,label,value,type="text",required=true}:{name:string;label:string;value?:string;type?:string;required?:boolean}){return <label className="text-xs font-semibold">{label}<input key={value} name={name} type={type} required={required} step={type==="number"?"any":undefined} defaultValue={value} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label>}
function Area({name,label,value}:{name:string;label:string;value?:string}){return <label className="block text-xs font-semibold">{label}<textarea key={value} name={name} required rows={2} defaultValue={value} className="mt-1 w-full rounded-lg border p-3 font-normal"/></label>}
