"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Diagnostic={kind:string;severity:string;message:string;metric?:string;attributed_to:string};
type Revision={version:number;title:string;summary:string;subject:{kind:string;resource_id?:string;name:string};workloads:{name:string;description:string;inputs:string;warmup:number;samples:number}[];metrics:{name:string;unit:string;direction:string;minimum?:number;maximum?:number;baseline:{value?:number;environment:string;measured_at?:string;source?:string}}[];correctness_constraints:{name:string;requirement:string;verification:string}[];supported_environments:{name:string;os:string;architecture:string;runtime:string;hardware:string}[];owners:string[];budgets:{kind:string;limit:number;unit:string}[];links:{kind:string;resource_id:string;label:string;added_by:string}[];baseline_max_age_days:number;created_by:string;created_at:string;rationale:string};
type Goal={id:string;current_version:number;revisions:Revision[];diagnostics:Diagnostic[];updated_at:string};
type Trial={id:string;workload:string;source:{revision:string};environment:{name:string};timings:{metric:string;unit:string;mean:number}[]};
type Finding={id:string;kind:string;body:string;confidence:string;created_by:string;stale:boolean;stale_reasons?:string[];flamegraph?:{frames:{name:string}[];value:number;unit:string}[];challenges:{id:string}[];confirmations:{id:string}[]};
type Investigation={id:string;title:string;trial_ids:string[];invitee_ids:string[];references:{kind:string;id:string;revision?:string;symbol?:string;path?:string;label:string}[];findings:Finding[]};
const text=(form:FormData,name:string)=>String(form.get(name)??"").trim();
const optionalNumber=(value:string)=>value===""?undefined:Number(value);

export function PerformanceGoalsWorkspace({repositoryID}:{repositoryID:string}){
 const {token,user}=useAuth();const [goals,setGoals]=useState<Goal[]>([]);const [selected,setSelected]=useState<Goal>();const [trials,setTrials]=useState<Trial[]>([]);const [investigations,setInvestigations]=useState<Investigation[]>([]);const [active,setActive]=useState<Investigation>();const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!token)return;try{const result=await api<{goals:Goal[]}>(`/repositories/${repositoryID}/performance-goals`,{},token);setGoals(result.goals);setSelected(current=>result.goals.find(goal=>goal.id===current?.id)??result.goals[0])}catch(reason){setError(reason instanceof Error?reason.message:"Performance goals could not be loaded.")}},[repositoryID,token]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
 function revision(form:FormData):Omit<Revision,"version"|"created_by"|"created_at">{const baselineValue=optionalNumber(text(form,"baseline_value")),measuredAt=text(form,"measured_at"),minimum=optionalNumber(text(form,"minimum")),maximum=optionalNumber(text(form,"maximum"));const prior=current;const firstLink=text(form,"link_id")?{kind:text(form,"link_kind"),resource_id:text(form,"link_id"),label:text(form,"link_label"),added_by:""}:undefined;return {title:text(form,"title"),summary:text(form,"summary"),subject:{kind:text(form,"subject_kind"),resource_id:text(form,"subject_id"),name:text(form,"subject_name")},workloads:[{name:text(form,"workload_name"),description:text(form,"workload_description"),inputs:text(form,"inputs"),warmup:Number(text(form,"warmup")||0),samples:Number(text(form,"samples"))},...(prior?.workloads.slice(1)??[])],metrics:[{name:text(form,"metric_name"),unit:text(form,"unit"),direction:text(form,"direction"),minimum,maximum,baseline:{value:baselineValue,environment:text(form,"baseline_environment"),measured_at:measuredAt||undefined,source:text(form,"baseline_source")}},...(prior?.metrics.slice(1)??[])],correctness_constraints:[{name:text(form,"constraint_name"),requirement:text(form,"requirement"),verification:text(form,"verification")},...(prior?.correctness_constraints.slice(1)??[])],supported_environments:[{name:text(form,"environment_name"),os:text(form,"os"),architecture:text(form,"architecture"),runtime:text(form,"runtime"),hardware:text(form,"hardware")},...(prior?.supported_environments.slice(1)??[])],owners:text(form,"owners").split(",").map(x=>x.trim()).filter(Boolean),budgets:[{kind:text(form,"budget_kind"),limit:Number(text(form,"budget_limit")),unit:text(form,"budget_unit")},...(prior?.budgets.slice(1)??[])],links:[...(firstLink?[firstLink]:[]),...(prior?.links.slice(1)??[])],baseline_max_age_days:Number(text(form,"baseline_age")),rationale:text(form,"rationale")}}
 async function publish(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;setBusy(true);setError("");const body={revision:revision(new FormData(event.currentTarget)),...(selected?{expected_version:selected.current_version}:{})};const path=selected?`/repositories/${repositoryID}/performance-goals/${selected.id}/revisions`:`/repositories/${repositoryID}/performance-goals`;try{const goal=await api<Goal>(path,{method:"POST",body:JSON.stringify(body)},token);setSelected(goal);setGoals(items=>[goal,...items.filter(item=>item.id!==goal.id)])}catch(reason){setError(reason instanceof Error?reason.message:"The contract could not be published.")}finally{setBusy(false)}}
 const current=selected?.revisions.at(-1);
 useEffect(()=>{if(!token)return;void Promise.all([api<{trials:Trial[]}>(`/repositories/${repositoryID}/performance-trials`,{},token),api<{investigations:Investigation[]}>(`/repositories/${repositoryID}/performance-investigations`,{},token)]).then(([a,b])=>{setTrials(a.trials);setInvestigations(b.investigations);setActive(x=>b.investigations.find(i=>i.id===x?.id)??b.investigations[0])}).catch(reason=>setError(reason instanceof Error?reason.message:"Diagnosis evidence could not be loaded."))},[repositoryID,token]);
 async function createInvestigation(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;const form=new FormData(event.currentTarget);try{const revision=text(form,"reference_revision"),created=await api<Investigation>(`/repositories/${repositoryID}/performance-investigations`,{method:"POST",body:JSON.stringify({title:text(form,"investigation_title"),trial_ids:form.getAll("trial_ids"),invitee_ids:text(form,"invitees").split(",").map(x=>x.trim()).filter(Boolean),references:[{kind:text(form,"reference_kind"),id:text(form,"reference_id"),revision:revision||undefined,symbol:text(form,"symbol")||undefined,path:text(form,"runtime_path")||undefined,label:text(form,"reference_label")} ]})},token);setInvestigations(x=>[created,...x]);setActive(created)}catch(reason){setError(reason instanceof Error?reason.message:"Investigation could not be created.")}}
 async function publishFinding(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token||!active)return;const form=new FormData(event.currentTarget),stack=text(form,"flame_stack").split(";").map(x=>x.trim()).filter(Boolean);try{const updated=await api<Investigation>(`/repositories/${repositoryID}/performance-investigations/${active.id}/findings`,{method:"POST",body:JSON.stringify({kind:text(form,"finding_kind"),body:text(form,"finding_body"),confidence:text(form,"confidence"),citation_ids:form.getAll("citation_ids"),flamegraph:stack.length?[{frames:stack.map(name=>({name})),value:Number(text(form,"flame_value")),unit:text(form,"flame_unit")}]:[]})},token);setActive(updated);setInvestigations(x=>x.map(i=>i.id===updated.id?updated:i));event.currentTarget.reset()}catch(reason){setError(reason instanceof Error?reason.message:"Finding could not be published.")}}
 return <div className="space-y-6"><header><Link href={`/repositories/${repositoryID}`} className="text-sm text-[var(--muted)] hover:text-[var(--brand)]">Repository</Link><h1 className="mt-2 text-2xl font-semibold">Performance goals</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Agree on workloads, measurable targets, correctness, environments, ownership, and cost before judging an optimization. Every successor remains attributable and earlier contracts stay inspectable.</p></header>
 <Card className="p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">{selected?"Publish a complete successor":"Define a performance contract"}</h2>{selected&&<Button type="button" variant="secondary" onClick={()=>setSelected(undefined)}>New goal</Button>}</div><form onSubmit={publish} className="mt-4 space-y-4">
 <div className="grid gap-3 md:grid-cols-3"><Field name="title" label="Goal title" value={current?.title}/><Field name="subject_name" label="Measured surface" value={current?.subject.name}/><label className="text-xs font-semibold">Subject type<select name="subject_kind" defaultValue={current?.subject.kind??"repository"} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal"><option value="repository">Repository</option><option value="release">Release</option><option value="user_journey">User journey</option><option value="api">API</option><option value="command">Command</option><option value="service">Service</option></select></label><Field name="subject_id" label="Subject resource ID" value={current?.subject.resource_id}/><Field name="owners" label="Owner IDs (comma separated)" value={current?.owners.join(", ")??user?.id}/><Field name="baseline_age" label="Baseline max age (days)" type="number" value={String(current?.baseline_max_age_days??30)}/></div><Area name="summary" label="Shared outcome" value={current?.summary}/><Area name="rationale" label="Revision rationale" value={current?.rationale}/>
 <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">Workload</legend><Field name="workload_name" label="Name" value={current?.workloads[0]?.name}/><Field name="samples" label="Samples" type="number" value={String(current?.workloads[0]?.samples??30)}/><Field name="warmup" label="Warmup runs" type="number" value={String(current?.workloads[0]?.warmup??2)}/><Field name="inputs" label="Inputs / fixture" value={current?.workloads[0]?.inputs}/><div className="md:col-span-2"><Area name="workload_description" label="Reproduction description" value={current?.workloads[0]?.description}/></div></fieldset>
 <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-4"><legend className="px-2 text-sm font-semibold">Metric, target, and baseline</legend><Field name="metric_name" label="Metric" value={current?.metrics[0]?.name}/><Field name="unit" label="Unit" value={current?.metrics[0]?.unit}/><label className="text-xs font-semibold">Direction<select name="direction" defaultValue={current?.metrics[0]?.direction??"lower"} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal"><option value="lower">Lower is better</option><option value="higher">Higher is better</option><option value="range">Stay in range</option></select></label><Field name="minimum" label="Target minimum" type="number" value={String(current?.metrics[0]?.minimum??"")}/><Field name="maximum" label="Target maximum" type="number" value={String(current?.metrics[0]?.maximum??"")}/><Field name="baseline_value" label="Baseline value (optional)" type="number" value={String(current?.metrics[0]?.baseline.value??"")} required={false}/><Field name="baseline_environment" label="Baseline environment" value={current?.metrics[0]?.baseline.environment}/><Field name="measured_at" label="Measured at" type="datetime-local" value={current?.metrics[0]?.baseline.measured_at?.slice(0,16)} required={false}/><Field name="baseline_source" label="Measurement source" value={current?.metrics[0]?.baseline.source} required={false}/></fieldset>
 <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">Supported environment</legend>{(["environment_name","os","architecture","runtime","hardware"] as const).map((name,index)=><Field key={name} name={name} label={["Environment name","OS","Architecture","Runtime","Hardware"][index]} value={[current?.supported_environments[0]?.name,current?.supported_environments[0]?.os,current?.supported_environments[0]?.architecture,current?.supported_environments[0]?.runtime,current?.supported_environments[0]?.hardware][index]}/>)}</fieldset>
 <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">Correctness and budget</legend><Field name="constraint_name" label="Constraint" value={current?.correctness_constraints[0]?.name}/><Field name="requirement" label="Must not regress" value={current?.correctness_constraints[0]?.requirement}/><Field name="verification" label="Verification" value={current?.correctness_constraints[0]?.verification}/><Field name="budget_kind" label="Budget kind" value={current?.budgets[0]?.kind}/><Field name="budget_limit" label="Budget limit" type="number" value={String(current?.budgets[0]?.limit??"")}/><Field name="budget_unit" label="Budget unit" value={current?.budgets[0]?.unit}/></fieldset>
 <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">Project context (optional)</legend><label className="text-xs font-semibold">Link type<select name="link_kind" defaultValue={current?.links[0]?.kind??"issue"} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal"><option>issue</option><option>incident</option><option>preview</option><option>release</option><option>decision</option></select></label><Field name="link_id" label="Resource ID" value={current?.links[0]?.resource_id} required={false}/><Field name="link_label" label="Link label" value={current?.links[0]?.label} required={false}/></fieldset><Button disabled={busy}>{busy?"Publishing…":selected?`Publish version ${selected.current_version+1}`:"Create goal"}</Button></form></Card>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
 {selected&&current&&<Card className="p-5"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{current.title}</h2><Badge>version {selected.current_version}</Badge><Badge tone={selected.diagnostics.some(d=>d.severity==="blocking")?"danger":"success"}>{selected.diagnostics.length?`${selected.diagnostics.length} explicit states`:"comparable"}</Badge></div><p className="mt-2 text-sm text-[var(--muted)]">{current.subject.kind.replaceAll("_"," ")} · {current.subject.name} · owned by {current.owners.join(", ")}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{selected.diagnostics.map((item,index)=><div key={`${item.kind}-${index}`} className="rounded-lg border p-3"><Badge tone={item.severity==="blocking"?"danger":"warning"}>{item.kind.replaceAll("_"," ")}</Badge><p className="mt-2 text-sm">{item.metric&&<strong>{item.metric}: </strong>}{item.message}</p><p className="mt-1 text-xs text-[var(--muted)]">Attributed to {item.attributed_to}</p></div>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Version history</summary><div className="mt-2 space-y-2">{selected.revisions.map(item=><p key={item.version} className="rounded-lg border p-3 text-sm"><strong>v{item.version}</strong> · {item.rationale} · {item.created_by} · {new Date(item.created_at).toLocaleString()}</p>)}</div></details></Card>}
 <section><h2 className="text-lg font-semibold">Repository contracts</h2><div className="mt-3 space-y-2">{goals.map(goal=>{const latest=goal.revisions.at(-1)!;return <button key={goal.id} type="button" onClick={()=>setSelected(goal)} className="w-full rounded-xl border bg-white p-4 text-left hover:border-[var(--brand)]"><span className="font-semibold">{latest.title}</span><span className="mt-1 block text-xs text-[var(--muted)]">{latest.subject.name} · v{goal.current_version} · {goal.diagnostics.length} explicit state(s)</span></button>})}</div></section>
 <Card className="p-5"><h2 className="text-lg font-semibold">Diagnose from evidence</h2><p className="mt-1 text-sm text-[var(--muted)]">Select exact trials, connect revision-aware code and runtime context, and invite owners before proposing an optimization.</p><form onSubmit={createInvestigation} className="mt-4 grid gap-3 md:grid-cols-3"><Field name="investigation_title" label="Question to investigate"/><Field name="invitees" label="Owner IDs to invite"/><label className="text-xs font-semibold">Evidence trials<select name="trial_ids" required multiple className="mt-1 min-h-24 w-full rounded-lg border bg-white p-2 font-normal">{trials.map(t=><option key={t.id} value={t.id}>{t.workload} · {t.environment.name} · {t.source.revision.slice(0,8)}</option>)}</select></label><Field name="reference_kind" label="Reference type" value="symbol"/><Field name="reference_id" label="Reference identity"/><Field name="reference_label" label="Inspectable label"/><Field name="reference_revision" label="Exact commit (optional)" required={false}/><Field name="symbol" label="Symbol (optional)" required={false}/><Field name="runtime_path" label="Dependency / runtime path" required={false}/><div><Button>Open investigation</Button></div></form></Card>
 {active&&<Card className="p-5"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{active.title}</h2><Badge>{active.trial_ids.length} trials</Badge><Badge>{active.invitee_ids.length} owners invited</Badge></div><div className="mt-3 flex flex-wrap gap-2">{active.references.map(r=><Badge key={r.id}>{r.kind}: {r.label}</Badge>)}</div><form onSubmit={publishFinding} className="mt-5 grid gap-3 md:grid-cols-3"><label className="text-xs font-semibold">Claim type<select name="finding_kind" className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal"><option>hypothesis</option><option>comparison</option><option>uncertainty</option><option>conclusion</option></select></label><label className="text-xs font-semibold">Confidence<select name="confidence" className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal"><option>low</option><option>medium</option><option>high</option></select></label><label className="text-xs font-semibold">Citations<select name="citation_ids" required multiple className="mt-1 min-h-20 w-full rounded-lg border bg-white p-2 font-normal">{active.trial_ids.map(id=><option key={id}>{id}</option>)}{active.references.map(r=><option key={r.id}>{r.id}</option>)}</select></label><div className="md:col-span-3"><Area name="finding_body" label="Evidence-backed explanation and uncertainty"/></div><Field name="flame_stack" label="Flame stack (root; child; leaf)" required={false}/><Field name="flame_value" label="Stack value" type="number" required={false}/><Field name="flame_unit" label="Stack unit" value="samples" required={false}/><div><Button>Publish cited finding</Button></div></form><div className="mt-5 space-y-3">{active.findings.map(f=><article key={f.id} className="rounded-lg border p-4"><div className="flex flex-wrap gap-2"><Badge>{f.kind}</Badge><Badge tone={f.stale?"warning":"success"}>{f.stale?`stale: ${f.stale_reasons?.join(", ")}`:"current"}</Badge><Badge>{f.confidence} confidence</Badge></div><p className="mt-2 text-sm">{f.body}</p>{f.flamegraph?.map((stack,i)=><div key={i} className="mt-3 flex h-8 overflow-hidden rounded border" title={`${stack.value} ${stack.unit}`}>{stack.frames.map((frame,j)=><span key={j} className="flex-1 border-r bg-[var(--brand-soft)] px-2 py-1 text-xs">{frame.name}</span>)}</div>)}<p className="mt-2 text-xs text-[var(--muted)]">{f.created_by} · {f.challenges.length} challenges · {f.confirmations.length} confirmations</p></article>)}</div></Card>}
 <section><h2 className="text-lg font-semibold">Investigations</h2><div className="mt-3 space-y-2">{investigations.map(item=><button key={item.id} type="button" onClick={()=>setActive(item)} className="w-full rounded-xl border bg-white p-4 text-left hover:border-[var(--brand)]"><span className="font-semibold">{item.title}</span><span className="block text-xs text-[var(--muted)]">{item.findings.length} findings · {item.trial_ids.length} selected trials</span></button>)}</div></section></div>
}
function Field({name,label,value,type="text",required=true}:{name:string;label:string;value?:string;type?:string;required?:boolean}){return <label className="text-xs font-semibold">{label}<input key={value} name={name} type={type} required={required} step={type==="number"?"any":undefined} defaultValue={value} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label>}
function Area({name,label,value}:{name:string;label:string;value?:string}){return <label className="block text-xs font-semibold">{label}<textarea key={value} name={name} required rows={2} defaultValue={value} className="mt-1 w-full rounded-lg border p-3 font-normal"/></label>}
