"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Source = { kind:string; resource_id:string; parent_id?:string; revision:string; label:string; claim:string; relationship:string; audience:string; stale:boolean; stale_reason?:string; detached_at?:string };
type Opportunity = { id:string; version:number; current_version:number; duplicate_of?:string; revisions:{version:number;title:string;need:string;affected_audiences:string[];severity:string;reach:string;confidence:string;expected_value:string;uncertainty:string[];minority_needs:string[];contradictions:string[];sources:Source[];created_by:string;actor_type:string;created_at:string}[]; challenges:{id:string;body:string;actor_id:string;created_at:string}[]; corrections:{id:string;field:string;from:string;to:string;reason:string;actor_id:string}[] };
const val=(f:FormData,n:string)=>String(f.get(n)??"").trim();
const lines=(v:string)=>v.split("\n").map(x=>x.trim()).filter(Boolean);
export function ProductOpportunitiesWorkspace({repositoryID}:{repositoryID:string}){
 const {token}=useAuth();const [items,setItems]=useState<Opportunity[]>([]),[selected,setSelected]=useState<Opportunity>(),[error,setError]=useState("");
 const load=useCallback(async()=>{if(!token)return;try{const r=await api<{opportunities:Opportunity[]}>(`/repositories/${repositoryID}/product-opportunities`,{},token);setItems(r.opportunities);setSelected(x=>r.opportunities.find(y=>y.id===x?.id)??r.opportunities[0]);setError("")}catch(e){setError(e instanceof Error?e.message:"Opportunities could not be loaded.")}},[repositoryID,token]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;const f=new FormData(e.currentTarget);try{await api(`/repositories/${repositoryID}/product-opportunities`,{method:"POST",body:JSON.stringify({title:val(f,"title"),need:val(f,"need"),affected_audiences:lines(val(f,"audiences")),severity:val(f,"severity"),reach:val(f,"reach"),confidence:val(f,"confidence"),expected_value:val(f,"value"),uncertainty:lines(val(f,"uncertainty")),minority_needs:lines(val(f,"minority")),contradictions:lines(val(f,"contradictions")),sources:[{kind:val(f,"kind"),resource_id:val(f,"resource"),parent_id:val(f,"parent"),revision:val(f,"revision"),label:val(f,"label"),claim:val(f,"claim"),relationship:val(f,"relationship"),audience:val(f,"source_audience")}]} )},token);e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Opportunity could not be created.")}}
 async function challenge(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!selected)return;const f=new FormData(e.currentTarget);try{await api(`/repositories/${repositoryID}/product-opportunities/${selected.id}/challenges`,{method:"POST",body:JSON.stringify({expected_version:selected.version,body:val(f,"body"),source_ids:lines(val(f,"sources"))})},token);e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Challenge could not be retained.")}}
 const current=selected?.revisions.at(-1);
 return <main id="main-content" className="mx-auto grid w-full max-w-6xl gap-6 px-6 py-8 lg:grid-cols-[1fr_1.2fr]">
  <section><p className="text-sm font-semibold text-[var(--accent)]">Product discovery</p><h1 className="mt-2 text-3xl font-semibold">Evidence-backed opportunities</h1><p className="mt-2 text-sm text-[var(--muted)]">Cluster recurring needs without hiding contradictions, minority audiences, uncertainty, or the exact evidence behind the interpretation.</p>
   <Card className="mt-6"><form className="grid gap-3" onSubmit={create}><h2 className="font-semibold">Synthesize permitted evidence</h2><input className="input" name="title" placeholder="Opportunity title" required/><textarea className="input" name="need" placeholder="Unmet need, in your own explicit interpretation" required/><textarea className="input" name="audiences" placeholder="Affected audiences, one per line" required/><div className="grid gap-3 sm:grid-cols-3"><select className="input" name="severity"><option>low</option><option>medium</option><option>high</option><option>critical</option></select><select className="input" name="reach"><option>individual</option><option>segment</option><option>broad</option><option>unknown</option></select><select className="input" name="confidence"><option>low</option><option>medium</option><option>high</option><option>uncertain</option></select></div><textarea className="input" name="value" placeholder="Expected value" required/><textarea className="input" name="uncertainty" placeholder="Uncertainties, one per line"/><textarea className="input" name="minority" placeholder="Minority needs, one per line"/><textarea className="input" name="contradictions" placeholder="Contradictions, one per line"/>
   <fieldset className="grid gap-3 rounded-xl border border-[var(--line)] p-4"><legend>Exact source citation</legend><select className="input" name="kind"><option value="feedback">Feedback</option><option value="issue">Issue</option><option value="preview_finding">Preview finding</option><option value="support_signal">Support signal</option><option value="usage_evidence">Usage evidence</option><option value="experiment_outcome">Experiment outcome</option></select><input className="input" name="resource" placeholder="Source resource ID" required/><input className="input" name="parent" placeholder="Parent preview/experiment ID, when needed"/><input className="input" name="revision" placeholder="Exact source revision" required/><input className="input" name="label" placeholder="Source label" required/><textarea className="input" name="claim" placeholder="What this source says" required/><select className="input" name="relationship"><option>supports</option><option>contradicts</option><option>minority_need</option><option>duplicate</option></select><input className="input" name="source_audience" placeholder="Audience represented" required/></fieldset><Button>Create transparent synthesis</Button></form></Card>
  </section><section><h2 className="text-xl font-semibold">Opportunity evidence</h2>{error&&<p role="alert" className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-4 flex flex-wrap gap-2">{items.map(x=><Button key={x.id} variant="secondary" onClick={()=>setSelected(x)}>{x.revisions.at(-1)?.title}</Button>)}</div>{selected&&current&&<Card className="mt-4"><div className="flex flex-wrap gap-2"><Badge>{current.severity}</Badge><Badge tone="info">{current.reach} reach</Badge><Badge>{current.confidence} confidence</Badge><Badge>revision {current.version}</Badge></div><h3 className="mt-3 text-xl font-semibold">{current.title}</h3><p className="mt-2">{current.need}</p><p className="mt-3 text-sm"><strong>Expected value:</strong> {current.expected_value}</p><p className="mt-2 text-sm"><strong>Affected audiences:</strong> {current.affected_audiences.join(", ")}</p>{current.uncertainty.length>0&&<p className="mt-2 text-sm"><strong>Uncertainty:</strong> {current.uncertainty.join(" · ")}</p>}{current.minority_needs.length>0&&<p className="mt-2 text-sm"><strong>Minority needs:</strong> {current.minority_needs.join(" · ")}</p>}{current.contradictions.length>0&&<p className="mt-2 text-sm"><strong>Contradictions:</strong> {current.contradictions.join(" · ")}</p>}<div className="mt-4 grid gap-3">{current.sources.map((s,i)=><div key={`${s.kind}-${s.resource_id}-${i}`} className="rounded-xl border border-[var(--line)] p-3"><div className="flex gap-2"><Badge>{s.kind}</Badge><Badge tone={s.stale?"danger":"success"}>{s.detached_at?"detached":s.stale?"stale":"current"}</Badge><Badge>{s.relationship}</Badge></div><p className="mt-2 font-semibold">{s.label}</p><p className="text-sm">{s.claim}</p><code className="mt-2 block break-all text-xs">{s.resource_id} @ {s.revision}</code>{s.stale_reason&&<p className="mt-1 text-xs text-red-600">{s.stale_reason}</p>}</div>)}</div><form className="mt-5 grid gap-2" onSubmit={challenge}><h4 className="font-semibold">Challenge this synthesis</h4><textarea className="input" name="body" placeholder="Explain what the interpretation misses" required/><textarea className="input" name="sources" placeholder="Related source IDs, one per line"/><Button variant="secondary">Retain challenge</Button></form>{selected.challenges.map(c=><p key={c.id} className="mt-3 border-l-2 border-[var(--accent)] pl-3 text-sm">{c.body}</p>)}</Card>}</section>
 </main>
}
