"use client";

import { useEffect, useState } from "react";
import { api } from "../lib/api";
import { Badge, Card } from "./ui";

type Metrics={samples:number;task_success_rate:number;policy_adherence_rate:number;human_corrections:number;mean_uncertainty:number;mean_latency_ms:number;mean_cost:number};
type PilotEvent={id:string;kind:"guidance"|"stop"|"result"|"policy_denial"|"escalation";summary:string;cost?:number;minutes?:number;unsafe?:boolean;created_at:string};
type Pilot={pilot:{id:string;candidate_revision:string;expires_at:string;version:number;budget:{max_minutes:number;max_actions:number;max_cost:number};sessions:{id:string;task_kind:string;task_id:string;expected_outcome:string;status:string;events:PilotEvent[]}[];feedback:{id:string;outcome:string;expected_outcome:string;correction:string;created_at:string}[]};effective_access:{status:"active"|"paused";pause_reasons:string[];actions:string[];repository_ids:string[];task_kinds:string[];used:{max_minutes:number;max_actions:number;max_cost:number};remaining:{max_minutes:number;max_actions:number;max_cost:number};authority_note:string}};
type Candidate={id:string;pull_revision:string;project_version:number;stale:boolean;runs:{id:string;contaminated:boolean;nondeterministic:boolean}[];comparison:{baseline_candidate_id?:string;comparable_suites:string[];invalidated_suites:string[];candidate:Metrics;delta:Metrics;contaminated:boolean;nondeterministic:boolean};pilots?:Pilot[]};
const pct=(v:number)=>`${Math.round(v*100)}%`;

export function PullAgentCandidates({repositoryID,pullRequestID}:{repositoryID:string;pullRequestID:string}) {
  const [items,setItems]=useState<Candidate[]>([]);const [unavailable,setUnavailable]=useState(false);
  useEffect(()=>{void api<{candidates:Candidate[]}>(`/repositories/${repositoryID}/pulls/${pullRequestID}/agent-candidates`).then(async x=>Promise.all(x.candidates.map(async c=>{const p=await api<{pilots:Pilot[]}>(`/repositories/${repositoryID}/pulls/${pullRequestID}/agent-candidates/${c.id}/pilots`).catch(()=>({pilots:[]}));return {...c,pilots:p.pilots}}))).then(setItems).catch(()=>setUnavailable(true));},[repositoryID,pullRequestID]);
  if(unavailable)return <p className="text-sm text-[var(--muted)]">Agent candidate evidence is temporarily unavailable.</p>;
  if(!items.length)return null;
  return <section id="agent-candidates" className="scroll-mt-24 space-y-4" aria-label="Agent behavior candidates"><h2 className="text-lg font-semibold">Agent behavior candidates</h2>{items.map(c=><Card className="p-5" key={c.id}><div className="flex flex-wrap gap-2"><Badge tone={c.stale?"warning":"success"}>{c.stale?"stale revision":"exact revision"}</Badge><Badge>{c.pull_revision.slice(0,12)}</Badge><Badge>contract v{c.project_version}</Badge>{c.comparison.contaminated&&<Badge tone="danger">contaminated</Badge>}{c.comparison.nondeterministic&&<Badge tone="warning">nondeterministic</Badge>}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Task success" value={pct(c.comparison.candidate.task_success_rate)} delta={c.comparison.delta.task_success_rate}/><Metric label="Policy adherence" value={pct(c.comparison.candidate.policy_adherence_rate)} delta={c.comparison.delta.policy_adherence_rate}/><Metric label="Human corrections" value={c.comparison.candidate.human_corrections.toFixed(1)} delta={-c.comparison.delta.human_corrections}/><Metric label="Uncertainty" value={pct(c.comparison.candidate.mean_uncertainty)} delta={-c.comparison.delta.mean_uncertainty}/><Metric label="Mean latency" value={`${Math.round(c.comparison.candidate.mean_latency_ms)} ms`} delta={-c.comparison.delta.mean_latency_ms}/><Metric label="Mean cost" value={`$${c.comparison.candidate.mean_cost.toFixed(2)}`} delta={-c.comparison.delta.mean_cost}/></div><p className="mt-4 text-xs text-[var(--muted)]">{c.comparison.candidate.samples} retained attempts · {c.runs.length} isolated runs · {c.comparison.comparable_suites.length} comparable suites{c.comparison.invalidated_suites.length?` · ${c.comparison.invalidated_suites.length} changed suites excluded`:""}. Statistical limits remain attached to each run.</p>{c.pilots?.map(p=><PilotCard key={p.pilot.id} value={p}/>)}</Card>)}</section>;
}
function Metric({label,value,delta}:{label:string;value:string;delta:number}){return <div className="rounded-lg border border-[var(--line)] p-3"><p className="text-xs text-[var(--muted)]">{label}</p><p className="mt-1 font-semibold">{value}</p>{delta!==0&&<p className={`text-xs ${delta>0?"text-emerald-700":"text-red-700"}`}>{delta>0?"improved":"regressed"} vs baseline</p>}</div>}
function PilotCard({value:{pilot:p,effective_access:a}}:{value:Pilot}){const events=p.sessions.flatMap(s=>s.events);const denials=events.filter(e=>e.kind==="policy_denial");const escalations=events.filter(e=>e.kind==="escalation");return <div className="mt-5 rounded-xl border border-[var(--line)] bg-[var(--surface-muted)] p-4"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">Collaboration pilot</h3><Badge tone={a.status==="active"?"success":"warning"}>{a.status}</Badge><Badge>expires {new Date(p.expires_at).toLocaleDateString()}</Badge></div>{a.pause_reasons.length>0&&<p className="mt-2 text-sm text-amber-800">Paused: {a.pause_reasons.join(", ").replaceAll("_"," ")}</p>}<div className="mt-3 grid gap-3 sm:grid-cols-3"><Metric label="Cost used" value={`$${a.used.max_cost.toFixed(2)} / $${p.budget.max_cost.toFixed(2)}`} delta={0}/><Metric label="Actions" value={`${a.used.max_actions} / ${p.budget.max_actions}`} delta={0}/><Metric label="Agent minutes" value={`${a.used.max_minutes} / ${p.budget.max_minutes}`} delta={0}/></div><p className="mt-3 text-xs text-[var(--muted)]">Effective actions: {a.actions.join(", ")||"none"} · Tasks: {a.task_kinds.join(", ")||"none"}. {a.authority_note}</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><div><h4 className="text-sm font-semibold">Live sessions</h4>{p.sessions.length===0?<p className="mt-1 text-sm text-[var(--muted)]">No delegated runs yet.</p>:p.sessions.map(s=><div key={s.id} className="mt-2 rounded-lg border border-[var(--line)] p-3"><div className="flex justify-between gap-3 text-sm"><span>{s.task_kind} {s.task_id}</span><Badge>{s.status}</Badge></div><p className="mt-1 text-xs text-[var(--muted)]">Expected: {s.expected_outcome}</p>{s.events.slice(-2).map(e=><p key={e.id} className="mt-2 text-xs"><span className="font-medium">{e.kind.replaceAll("_"," ")}:</span> {e.summary}</p>)}</div>)}</div><div><h4 className="text-sm font-semibold">Control evidence</h4><p className="mt-1 text-sm">{escalations.length} escalations · {denials.length} policy denials · {p.feedback.length} feedback items</p>{p.feedback.slice(-2).map(f=><div key={f.id} className="mt-2 rounded-lg border border-[var(--line)] p-3 text-xs"><p><span className="font-medium">Observed:</span> {f.outcome}</p><p className="mt-1"><span className="font-medium">Expected:</span> {f.expected_outcome}</p><p className="mt-1"><span className="font-medium">Correction:</span> {f.correction}</p></div>)}</div></div></div>}
