"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Revision={version:number;title:string;summary:string;scopes:{kind:string;resource_id?:string;name:string}[];supported_environments:{id:string;name:string;description:string;supported:boolean}[];requirements:{id:string;source_kind:string;source_id:string;title:string;rationale:string;expected_behavior:string;risk:string;test_levels:string[];representative_data:string;coverage_goal:string;owner_ids:string[];judge_ids:string[];environment_ids:string[];schedule:string;release_threshold:string;evidence_ids:string[];conflicts_with:string[];verification?:string}[];evidence:{id:string;kind:string;resource_kind:string;resource_id:string;revision?:string;summary:string;status:string;added_by?:string}[];exceptions:{id:string;requirement_id:string;rationale:string;granted_by:string;expires_at:string;follow_up:string}[];owner_ids:string[];review_schedule:string;rationale:string;created_by:string;created_at:string};
type Plan={id:string;current_version:number;revisions:Revision[];diagnostics:{kind:string;severity:string;message:string;requirement_id?:string;attributed_to:string}[]};
const value=(f:FormData,n:string)=>String(f.get(n)??"").trim();const list=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);

export function QualityPlansWorkspace({repositoryID}:{repositoryID:string}){
 const {token,user}=useAuth(),[plans,setPlans]=useState<Plan[]>([]),[selected,setSelected]=useState<Plan>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!token)return;try{const out=await api<{plans:Plan[]}>(`/repositories/${repositoryID}/quality-plans`,{},token);setPlans(out.plans);setSelected(old=>out.plans.find(x=>x.id===old?.id)??out.plans[0])}catch(reason){setError(reason instanceof Error?reason.message:"Quality plans could not be loaded.")}},[repositoryID,token]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
 const current=selected?.revisions.at(-1),requirement=current?.requirements[0],evidence=current?.evidence[0],environment=current?.supported_environments[0];
 function build(f:FormData):Omit<Revision,"version"|"created_by"|"created_at">{const requirementID=value(f,"requirement_id"),environmentID=value(f,"environment_id"),evidenceID=value(f,"evidence_id"),expiry=value(f,"exception_expiry");return {title:value(f,"title"),summary:value(f,"summary"),scopes:[{kind:value(f,"scope_kind"),resource_id:value(f,"scope_id"),name:value(f,"scope_name")}],supported_environments:[{id:environmentID,name:value(f,"environment_name"),description:value(f,"environment_description"),supported:true}],requirements:[{id:requirementID,source_kind:value(f,"source_kind"),source_id:value(f,"source_id"),title:value(f,"requirement_title"),rationale:value(f,"requirement_rationale"),expected_behavior:value(f,"expected_behavior"),risk:value(f,"risk"),test_levels:list(value(f,"test_levels")),representative_data:value(f,"representative_data"),coverage_goal:value(f,"coverage_goal"),owner_ids:list(value(f,"requirement_owners")),judge_ids:list(value(f,"judges")),environment_ids:[environmentID],schedule:value(f,"schedule"),release_threshold:value(f,"release_threshold"),evidence_ids:evidenceID?[evidenceID]:[],conflicts_with:list(value(f,"conflicts_with")),verification:value(f,"verification")},...(current?.requirements.slice(1)??[])],evidence:evidenceID?[{id:evidenceID,kind:value(f,"evidence_kind"),resource_kind:value(f,"evidence_resource_kind"),resource_id:value(f,"evidence_resource_id"),revision:value(f,"evidence_revision"),summary:value(f,"evidence_summary"),status:value(f,"evidence_status")},...(current?.evidence.slice(1)??[])]:[],exceptions:expiry?[{id:value(f,"exception_id"),requirement_id:requirementID,rationale:value(f,"exception_rationale"),granted_by:value(f,"exception_grantor"),expires_at:new Date(expiry).toISOString(),follow_up:value(f,"exception_follow_up")},...(current?.exceptions.slice(1)??[])]:[],owner_ids:list(value(f,"plan_owners")),review_schedule:value(f,"review_schedule"),rationale:value(f,"revision_rationale")}}
 async function publish(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;setBusy(true);setError("");try{const path=selected?`/repositories/${repositoryID}/quality-plans/${selected.id}/revisions`:`/repositories/${repositoryID}/quality-plans`;const out=await api<Plan>(path,{method:"POST",body:JSON.stringify({revision:build(new FormData(event.currentTarget)),...(selected?{expected_version:selected.current_version}:{})})},token);setSelected(out);setPlans(items=>[out,...items.filter(x=>x.id!==out.id)])}catch(reason){setError(reason instanceof Error?reason.message:"Quality plan could not be published.")}finally{setBusy(false)}}
 return <div className="space-y-6"><header><Link href={`/repositories/${repositoryID}`} className="text-sm text-[var(--muted)] hover:text-[var(--brand)]">Repository</Link><h1 className="mt-2 text-2xl font-semibold">Quality plans</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Name the behavior worth protecting, its source and risk, who owns and judges it, and the evidence a release must provide. Gaps remain visible even when checks pass.</p></header>
 <Card className="p-5"><div className="flex justify-between"><h2 className="font-semibold">{selected?"Publish a complete successor":"Define quality intent"}</h2>{selected&&<Button type="button" variant="secondary" onClick={()=>setSelected(undefined)}>New plan</Button>}</div><form key={selected?`${selected.id}:${selected.current_version}`:"new"} className="mt-4 space-y-4" onSubmit={publish}>
 <Group title="Plan and scope"><Field n="title" l="Plan title" v={current?.title}/><Select n="scope_kind" l="Scope" v={current?.scopes[0]?.kind??"repository"} options={["repository","release","journey","interface"]}/><Field n="scope_name" l="Scope name" v={current?.scopes[0]?.name}/><Field n="scope_id" l="Scope resource ID" v={current?.scopes[0]?.resource_id} required={false}/><Field n="plan_owners" l="Plan owner IDs" v={current?.owner_ids.join(", ")??user?.id} required={false}/><Field n="review_schedule" l="Review schedule" v={current?.review_schedule} placeholder="Before every release"/></Group><Area n="summary" l="Quality promise" v={current?.summary}/><Area n="revision_rationale" l="Revision rationale" v={current?.rationale}/>
 <Group title="Supported environment"><Field n="environment_id" l="Environment key" v={environment?.id}/><Field n="environment_name" l="Environment name" v={environment?.name}/><Field n="environment_description" l="Support boundary" v={environment?.description}/></Group>
 <Group title="Expected behavior"><Field n="requirement_id" l="Requirement key" v={requirement?.id}/><Field n="requirement_title" l="Behavior title" v={requirement?.title}/><Select n="source_kind" l="Requirement source" v={requirement?.source_kind??"issue"} options={["issue","decision","design","accessibility","privacy","performance","reliability"]}/><Field n="source_id" l="Source resource ID" v={requirement?.source_id}/><Select n="risk" l="Risk" v={requirement?.risk??"high"} options={["low","medium","high","critical"]}/><Field n="test_levels" l="Test levels" v={requirement?.test_levels.join(", ")} placeholder="unit, end_to_end, manual"/><Field n="requirement_owners" l="Behavior owner IDs" v={requirement?.owner_ids.join(", ")??user?.id} required={false}/><Field n="judges" l="Release judge IDs" v={requirement?.judge_ids.join(", ")??user?.id} required={false}/><Field n="schedule" l="Test schedule" v={requirement?.schedule}/><Field n="coverage_goal" l="Coverage goal" v={requirement?.coverage_goal}/><Field n="release_threshold" l="Release threshold" v={requirement?.release_threshold}/><Field n="conflicts_with" l="Conflicting requirement IDs" v={requirement?.conflicts_with.join(", ")} required={false}/></Group><Area n="requirement_rationale" l="Why this behavior matters" v={requirement?.rationale}/><Area n="expected_behavior" l="Expected behavior" v={requirement?.expected_behavior}/><Area n="representative_data" l="Representative, privacy-safe data" v={requirement?.representative_data}/><Area n="verification" l="Observable verification method (blank remains an explicit untestable claim)" v={requirement?.verification} required={false}/>
 <Group title="Existing evidence (optional)"><Field n="evidence_id" l="Evidence key" v={evidence?.id} required={false}/><Select n="evidence_kind" l="Evidence type" v={evidence?.kind??"automated"} options={["automated","manual"]}/><Field n="evidence_resource_kind" l="Resource type" v={evidence?.resource_kind??"check_run"} required={false}/><Field n="evidence_resource_id" l="Resource ID" v={evidence?.resource_id} required={false}/><Field n="evidence_revision" l="Exact revision" v={evidence?.revision} required={false}/><Select n="evidence_status" l="Current status" v={evidence?.status??"passing"} options={["passing","failing","missing","stale","unknown"]}/><Field n="evidence_summary" l="What it demonstrates" v={evidence?.summary} required={false}/></Group>
 <Group title="Bounded exception (optional)"><Field n="exception_id" l="Exception key" v={current?.exceptions[0]?.id} required={false}/><Field n="exception_expiry" l="Expiry" type="datetime-local" v={localDate(current?.exceptions[0]?.expires_at)} required={false}/><Field n="exception_grantor" l="Grantor ID" v={current?.exceptions[0]?.granted_by??user?.id} required={false}/><Field n="exception_rationale" l="Rationale" v={current?.exceptions[0]?.rationale} required={false}/><Field n="exception_follow_up" l="Follow-up work" v={current?.exceptions[0]?.follow_up} required={false}/></Group><Button disabled={busy}>{busy?"Publishing…":selected?`Publish version ${selected.current_version+1}`:"Create quality plan"}</Button></form></Card>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
 {selected&&current&&<Card className="p-5"><div className="flex flex-wrap gap-2"><h2 className="text-lg font-semibold">{current.title}</h2><Badge>version {selected.current_version}</Badge><Badge tone={selected.diagnostics.some(x=>x.severity==="blocking")?"danger":"success"}>{selected.diagnostics.length?`${selected.diagnostics.length} explicit gap(s)`:"intent complete"}</Badge></div><p className="mt-2 text-sm text-[var(--muted)]">{current.requirements.length} behavior(s) · {current.supported_environments.length} environment(s) · {current.evidence.length} evidence link(s)</p><div className="mt-4 grid gap-3 md:grid-cols-2">{selected.diagnostics.map((d,i)=><div className="rounded-lg border p-3" key={`${d.kind}-${i}`}><Badge tone={d.severity==="blocking"?"danger":"warning"}>{d.kind.replaceAll("_"," ")}</Badge><p className="mt-2 text-sm">{d.message}</p><p className="mt-1 text-xs text-[var(--muted)]">{d.requirement_id||"plan"} · attributed to {d.attributed_to}</p></div>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Version history</summary>{selected.revisions.map(r=><p className="mt-2 rounded-lg border p-3 text-sm" key={r.version}><strong>v{r.version}</strong> · {r.rationale} · {r.created_by} · {new Date(r.created_at).toLocaleString()}</p>)}</details></Card>}
 <section><h2 className="text-lg font-semibold">Repository quality plans</h2><div className="mt-3 space-y-2">{plans.map(plan=>{const r=plan.revisions.at(-1)!;return <button type="button" className="w-full rounded-xl border bg-white p-4 text-left hover:border-[var(--brand)]" key={plan.id} onClick={()=>setSelected(plan)}><span className="font-semibold">{r.title}</span><span className="block text-xs text-[var(--muted)]">v{plan.current_version} · {r.requirements.length} protected behavior(s) · {plan.diagnostics.length} explicit state(s)</span></button>})}</div></section></div>
}
function Group({title,children}:{title:string;children:React.ReactNode}){return <fieldset className="grid gap-3 rounded-lg border p-4 md:grid-cols-3"><legend className="px-2 text-sm font-semibold">{title}</legend>{children}</fieldset>}
function Field({n,l,v,type="text",required=true,placeholder}:{n:string;l:string;v?:string;type?:string;required?:boolean;placeholder?:string}){return <label className="text-xs font-semibold">{l}<input name={n} type={type} required={required} defaultValue={v} placeholder={placeholder} className="mt-1 min-h-10 w-full rounded-lg border px-3 font-normal"/></label>}
function Area({n,l,v,required=true}:{n:string;l:string;v?:string;required?:boolean}){return <label className="block text-xs font-semibold">{l}<textarea name={n} required={required} rows={2} defaultValue={v} className="mt-1 w-full rounded-lg border p-3 font-normal"/></label>}
function Select({n,l,v,options}:{n:string;l:string;v:string;options:string[]}){return <label className="text-xs font-semibold">{l}<select name={n} defaultValue={v} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 font-normal">{options.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>}
function localDate(value?:string){if(!value)return undefined;const date=new Date(value);const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
