"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Decision={opportunity_id:string;opportunity_version:number;outcome:string;reason:string;goal_fit:string;capacity:string;dependencies:string[];risks:string[];governance_decision_ids:string[];commitment_ids:string[]};
type Item={id:string;opportunity_id:string;title:string;owner_ids:string[];target_horizon:string;success_measures:string[];depends_on:string[];position:number;status:string};
type Revision={version:number;goals:string[];capacity:string;decisions:Decision[];items:Item[];change_reason:string;replan_triggers:string[];created_by:string;created_at:string};
type Roadmap={version:number;revisions:Revision[];scenarios:{id:string;rationale:string;actor_id:string;actor_type:string;revision:Revision}[];comments:{id:string;body:string;actor_id:string;actor_type:string;created_at:string}[]};
const value=(f:FormData,n:string)=>String(f.get(n)??"").trim();const lines=(x:string)=>x.split("\n").map(v=>v.trim()).filter(Boolean);
function draft(f:FormData):Revision {const outcome=value(f,"outcome");return {version:0,goals:lines(value(f,"goals")),capacity:value(f,"capacity"),decisions:[{opportunity_id:value(f,"opportunity"),opportunity_version:Number(value(f,"opportunity_version")),outcome,reason:value(f,"reason"),goal_fit:value(f,"goal_fit"),capacity:value(f,"decision_capacity"),dependencies:lines(value(f,"dependencies")),risks:lines(value(f,"risks")),governance_decision_ids:lines(value(f,"governance")),commitment_ids:lines(value(f,"commitments"))}],items:outcome==="accepted"?[{id:value(f,"item_id"),opportunity_id:value(f,"opportunity"),title:value(f,"title"),owner_ids:lines(value(f,"owners")),target_horizon:value(f,"horizon"),success_measures:lines(value(f,"measures")),depends_on:lines(value(f,"sequence")),position:1,status:"planned"}]:[],change_reason:value(f,"change_reason"),replan_triggers:lines(value(f,"triggers")),created_by:"",created_at:""}}
export function RoadmapWorkspace({repositoryID}:{repositoryID:string}){
 const {token}=useAuth();const [roadmap,setRoadmap]=useState<Roadmap>();const [error,setError]=useState("");
 const load=useCallback(async()=>{if(!token)return;try{setRoadmap(await api<Roadmap>(`/repositories/${repositoryID}/roadmap`,{},token));setError("")}catch(e){const message=e instanceof Error?e.message:"Roadmap unavailable";if(message.toLowerCase().includes("not found")){setRoadmap(undefined);setError("")}else setError(message)}},[repositoryID,token]);useEffect(()=>{void Promise.resolve().then(load)},[load]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;const form=e.currentTarget,f=new FormData(form),scenario=value(f,"action")==="scenario";try{await api(`/repositories/${repositoryID}/roadmap${scenario?"/scenarios":""}`,{method:scenario?"POST":"PUT",body:JSON.stringify({expected_version:roadmap?.version??0,revision:draft(f),rationale:value(f,"scenario_reason")})},token);form.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Direction could not be retained.")}}
 async function comment(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!roadmap)return;const form=e.currentTarget;try{await api(`/repositories/${repositoryID}/roadmap/comments`,{method:"POST",body:JSON.stringify({expected_version:roadmap.version,body:value(new FormData(form),"body")})},token);form.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Tradeoff could not be discussed.")}}
 const current=roadmap?.revisions.at(-1);
 return <main id="main-content" className="mx-auto w-full max-w-6xl px-6 py-8"><p className="text-sm font-semibold text-[var(--accent)]">Product direction</p><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="mt-2 text-3xl font-semibold">Accountable roadmap</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">See what the project chose, declined, and deferred—and the evidence, capacity, dependencies, risks, governance, and commitments that shaped each promise.</p></div><Link className="text-sm text-[var(--accent)]" href={`/repositories/${repositoryID}/opportunities`}>Inspect opportunity evidence →</Link></div>{error&&<p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}
 <div className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_1fr]"><section>{current?<Card><div className="flex gap-2"><Badge>revision {current.version}</Badge><Badge tone="info">by {current.created_by}</Badge></div><h2 className="mt-3 text-xl font-semibold">Current direction</h2><p className="mt-2"><strong>Goals:</strong> {current.goals.join(" · ")}</p><p className="mt-2 text-sm"><strong>Capacity:</strong> {current.capacity}</p>{current.change_reason&&<p className="mt-2 text-sm"><strong>Replan:</strong> {current.change_reason} ({current.replan_triggers.join(", ")})</p>}<div className="mt-4 grid gap-3">{current.decisions.map(d=><div key={d.opportunity_id} className="rounded-xl border border-[var(--line)] p-3"><Badge tone={d.outcome==="accepted"?"success":d.outcome==="rejected"?"danger":"info"}>{d.outcome}</Badge><code className="ml-2 text-xs">{d.opportunity_id} @ {d.opportunity_version}</code><p className="mt-2">{d.reason}</p><p className="text-sm"><strong>Goal fit:</strong> {d.goal_fit} · <strong>Capacity:</strong> {d.capacity}</p><p className="text-sm"><strong>Dependencies/risks:</strong> {[...d.dependencies,...d.risks].join(" · ")||"None stated"}</p></div>)}</div><h3 className="mt-5 font-semibold">Sequenced outcomes</h3>{current.items.map(x=><div key={x.id} className="mt-2 border-l-2 border-[var(--accent)] pl-3"><strong>{x.position}. {x.title}</strong><p className="text-sm">{x.target_horizon} · {x.status} · owners {x.owner_ids.join(", ")}</p><p className="text-sm">Success: {x.success_measures.join(" · ")}</p></div>)}</Card>:<Card>No committed roadmap yet. A maintainer can publish one; collaborators and agents can first propose a scenario.</Card>}
 {roadmap&&<Card className="mt-5"><h2 className="font-semibold">Tradeoff discussion</h2><form className="mt-3 flex gap-2" onSubmit={comment}><input className="input grow" name="body" placeholder="Question an assumption or surface a conflict" required/><Button variant="secondary">Discuss</Button></form>{roadmap.comments.map(c=><p key={c.id} className="mt-3 border-l-2 border-[var(--line)] pl-3 text-sm">{c.body} — {c.actor_id}</p>)}{roadmap.scenarios.map(s=><p key={s.id} className="mt-3 text-sm"><Badge>{s.actor_type} scenario</Badge> {s.rationale} — {s.actor_id}</p>)}</Card>}</section>
 <Card><form className="grid gap-3" onSubmit={submit}><h2 className="font-semibold">Compare and propose direction</h2><textarea className="input" name="goals" placeholder="Project goals, one per line" required/><textarea className="input" name="capacity" placeholder="Available capacity and horizon" required/><input className="input" name="opportunity" placeholder="Exact opportunity ID" required/><input className="input" name="opportunity_version" type="number" min="1" placeholder="Opportunity version" required/><select className="input" name="outcome"><option>accepted</option><option>deferred</option><option>rejected</option></select><textarea className="input" name="reason" placeholder="Why prioritize, defer, or reject" required/><textarea className="input" name="goal_fit" placeholder="Fit against project goals" required/><textarea className="input" name="decision_capacity" placeholder="Capacity assessment" required/><textarea className="input" name="dependencies" placeholder="Dependencies, one per line"/><textarea className="input" name="risks" placeholder="Risks, one per line"/><textarea className="input" name="governance" placeholder="Governance decision IDs, one per line"/><textarea className="input" name="commitments" placeholder="Existing commitment IDs, one per line"/><fieldset className="grid gap-3 rounded-xl border border-[var(--line)] p-3"><legend>Accepted outcome</legend><input className="input" name="item_id" placeholder="Stable roadmap item ID"/><input className="input" name="title" placeholder="Outcome title"/><textarea className="input" name="owners" placeholder="Accountable owner IDs, one per line"/><input className="input" name="horizon" placeholder="Target horizon"/><textarea className="input" name="measures" placeholder="Success measures, one per line"/><textarea className="input" name="sequence" placeholder="Preceding roadmap item IDs"/></fieldset><textarea className="input" name="change_reason" placeholder="Required reason when replanning a published roadmap"/><textarea className="input" name="triggers" placeholder="Scope, conflict, owner, or slip triggers"/><select className="input" name="action"><option value="scenario">Propose non-binding scenario</option><option value="commit">Commit or replan (maintainers only)</option></select><textarea className="input" name="scenario_reason" placeholder="Scenario rationale (required for scenarios)"/><Button>Retain direction</Button></form></Card></div></main>
}
