"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Diagnostic = { kind: string; severity: string; message: string; step_id?: string; resource_id?: string; attributed_to: string };
type Runbook = { id: string; current_version: number; revisions: Array<Record<string, unknown>>; diagnostics: Diagnostic[]; updated_at: string };
const template = (owner = "") => ({
  title: "Service response procedure", purpose: "Give responders a safe, reviewable path from signal to recovery",
  scope: { kind: "service", resource_id: "checkout", name: "Checkout service" },
  preconditions: ["Confirm the signal and affected revision"], owner_ids: owner ? [owner] : [], required_skills: ["service operations"],
  rollback_criteria: ["Stop when user impact grows or evidence contradicts the diagnosis"], policy_revision_ids: [],
  escalations: owner ? [{ condition: "A precondition fails or authority is unavailable", owner_id: owner, path: "Repository owner", expected_action: "Choose a safe next action" }] : [],
  steps: [{ id: "inspect-health", position: 1, kind: "diagnostic", title: "Inspect service health", purpose: "Test the suspected failure before changing state", instructions: "Run the reviewed health workflow and retain its digest-addressed output.", preconditions: ["Read access is current"], expected_evidence: ["Revision-bound health summary"], rollback_criteria: ["Stop if the evidence source is stale"], owner_ids: owner ? [owner] : [], required_skills: ["service operations"], references: [{ kind: "documentation", resource_id: "docs/operations.md", revision: "main", label: "Operations guide", reviewed: true, accessible: true }], authority: { required_access: ["service:read"], inspects: ["service health"], changes: [], prohibited_actions: ["deploy or disclose"], human_approval_required: false }, assumptions: [], policy_rule_ids: [] }],
  change_reason: "Publish the initial operational procedure",
});

export function RunbooksWorkspace({ repositoryID }: { repositoryID: string }) {
  const { token, user } = useAuth(); const [items,setItems]=useState<Runbook[]>([]); const [selected,setSelected]=useState<Runbook>(); const [draft,setDraft]=useState(""); const [error,setError]=useState(""); const [pending,setPending]=useState(false);
  const load=useCallback(async()=>{if(!token)return;try{const out=await api<{runbooks:Runbook[]}>(`/repositories/${repositoryID}/runbooks`,{},token);setItems(out.runbooks);setSelected((old)=>old?out.runbooks.find(x=>x.id===old.id):out.runbooks[0]);setDraft((old)=>old||JSON.stringify(out.runbooks[0]?.revisions.at(-1)??template(user?.id),null,2));}catch(x){setError(x instanceof Error?x.message:"Runbooks could not be loaded")}},[repositoryID,token,user?.id]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function publish(e:FormEvent){e.preventDefault();if(!token)return;setPending(true);try{const revision=JSON.parse(draft);const path=selected?`/repositories/${repositoryID}/runbooks/${selected.id}/revisions`:`/repositories/${repositoryID}/runbooks`;const storageKey=`runbook-publication:${repositoryID}:${selected?.id??"new"}`;const signature=JSON.stringify({path,expected_version:selected?.current_version??0,revision});let retained:{signature:string;request_id:string}|undefined;try{retained=JSON.parse(localStorage.getItem(storageKey)??"")}catch{}if(!retained||retained.signature!==signature){retained={signature,request_id:crypto.randomUUID()};localStorage.setItem(storageKey,JSON.stringify(retained))}const out=await api<Runbook>(path,{method:"POST",body:JSON.stringify({request_id:retained.request_id,expected_version:selected?.current_version??0,revision})},token);localStorage.removeItem(storageKey);setSelected(out);setItems(xs=>[out,...xs.filter(x=>x.id!==out.id)]);setDraft(JSON.stringify(out.revisions.at(-1),null,2));setError("");}catch(x){setError(x instanceof Error?x.message:"Runbook could not be published")}finally{setPending(false)}}
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold">Operational runbooks</h1><p className="mt-2 text-sm text-[var(--muted)]">Review purpose, evidence, decisions, rollback, ownership, and effective authority before an emergency. Runbooks coordinate procedure only and grant no repository, secret, environment, agent, workflow, or operational authority.</p></header><div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><Card className="p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Versioned procedures</h2><Button type="button" onClick={()=>{setSelected(undefined);setDraft(JSON.stringify(template(user?.id),null,2))}}>New</Button></div><div className="mt-4 space-y-2">{items.map(x=><button key={x.id} onClick={()=>{setSelected(x);setDraft(JSON.stringify(x.revisions.at(-1),null,2))}} className="w-full rounded-lg border border-[var(--line)] p-3 text-left"><span className="font-medium">{String(x.revisions.at(-1)?.title??x.id)}</span><span className="ml-2"><Badge>v{x.current_version}</Badge></span><p className="mt-1 text-xs text-[var(--muted)]">{x.diagnostics.length} explicit gap{x.diagnostics.length===1?"":"s"}</p></button>)}</div></Card><Card className="p-5"><h2 className="font-semibold">{selected?"Publish a successor revision":"Define a runbook"}</h2><p className="mt-1 text-xs text-[var(--muted)]">Structured JSON keeps every step and referenced immutable resource explicit.</p><form className="mt-4" onSubmit={publish}><label className="text-sm font-medium" htmlFor="runbook-revision">Complete revision</label><textarea id="runbook-revision" value={draft} onChange={e=>setDraft(e.target.value)} className="mt-2 min-h-[32rem] w-full rounded-lg border border-[var(--line-strong)] bg-white p-3 font-mono text-xs"/><Button type="submit" disabled={pending} className="mt-3">{pending?"Publishing…":"Publish immutable revision"}</Button></form></Card></div>{selected&&<Card className="p-5"><h2 className="font-semibold">Safety and authority preview</h2><div className="mt-3 space-y-2">{selected.diagnostics.length===0?<p className="text-sm text-[var(--muted)]">No projected gaps. Referenced systems still enforce their own live authority.</p>:selected.diagnostics.map((d,i)=><div key={`${d.kind}-${i}`} className="rounded-lg border border-[var(--line)] p-3"><Badge tone={d.severity==="blocking"?"danger":"warning"}>{d.kind}</Badge><p className="mt-2 text-sm">{d.message}</p><p className="mt-1 text-xs text-[var(--muted)]">Attributed to {d.attributed_to}{d.step_id?` · step ${d.step_id}`:""}</p></div>)}</div></Card>}{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}</div>
}
