"use client";

import { useCallback, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Card } from "./ui";

type Attempt={id:string;revision:string;execution_kind:string;result:string;cost_units:number;coverage:{abuse_attempted:boolean;containment_ids:string[];detection_ids:string[];recovery_ids:string[];gaps:string[]};unsafe_reasons:string[];non_reproducible_reasons:string[];commands:{exit_code:number;log:string}[];artifacts:{kind:string;name:string;sha256:string;sanitized:boolean}[];provenance:string[]};
type Scenario={id:string;title:string;threat_model_id:string;threat_model_version:number;abuse_path_id:string;attacker_preconditions:string[];bounded_capabilities:string[];actions:string[];containment:{id:string;description:string;expected:string}[];detection:{id:string;description:string;expected:string}[];recovery:{id:string;description:string;expected:string}[];fixtures:{description:string;data_class:string;generator:string}[];commit_id:string;command:string;isolation:string;created_by:string;created_by_type:string;review?:{reviewer_id:string;decision:string;note:string};attempts:Attempt[]};

export function SecurityScenariosWorkspace({repositoryID}:{repositoryID:string}) {
  const {token}=useAuth(),[items,setItems]=useState<Scenario[]>([]),[error,setError]=useState("");
  const load=useCallback(async()=>{if(!token)return;try{const out=await api<{security_scenarios:Scenario[]}>(`/repositories/${repositoryID}/security-scenarios`,{},token);setItems(out.security_scenarios)}catch(e){setError(e instanceof Error?e.message:"Security evidence could not be loaded.")}},[repositoryID,token]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  return <section className="space-y-5" aria-labelledby="security-scenarios-heading"><header><h2 id="security-scenarios-heading" className="text-xl font-semibold">Executable abuse and defense scenarios</h2><p className="mt-1 max-w-3xl text-sm text-[var(--muted)]">Reproduce an attempted abuse and its promised containment in an isolated exact-revision workspace or preview. Evidence is retained even when a scenario is unsafe or cannot be reproduced.</p></header>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
    <div className="space-y-4">{items.map(s=><Card key={s.id} className="space-y-5 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{s.title}</h3><p className="mt-1 text-xs text-[var(--muted)]">Threat {s.threat_model_id} v{s.threat_model_version} · path {s.abuse_path_id} · candidate {s.commit_id}</p></div><div className="flex gap-2"><Badge>{s.isolation}</Badge><Badge tone={s.review?.decision==="approved"?"success":s.review?"warning":"neutral"}>{s.review?.decision??"awaiting review"}</Badge></div></div>
      <div className="grid gap-3 md:grid-cols-3"><Evidence title="Attempt" values={[...s.attacker_preconditions,...s.bounded_capabilities,...s.actions]}/><Evidence title="Defense" values={[...s.containment.map(x=>`Contain: ${x.description} → ${x.expected}`),...s.detection.map(x=>`Detect: ${x.description} → ${x.expected}`),...s.recovery.map(x=>`Recover: ${x.description} → ${x.expected}`)]}/><Evidence title="Safe inputs" values={s.fixtures.map(x=>`${x.description} · ${x.data_class} · ${x.generator}`)}/></div><p className="rounded-lg bg-[var(--surface-subtle)] p-3 font-mono text-xs">{s.command}</p>
      {s.review&&<p className="text-sm">Reviewed by {s.review.reviewer_id}: {s.review.note}</p>}{s.attempts.map(a=><div key={a.id} className="rounded-lg border border-[var(--line)] p-4 text-sm"><div className="flex flex-wrap gap-2"><Badge tone={a.result==="passed"?"success":a.result==="failed"?"danger":"warning"}>{a.result.replaceAll("_"," ")}</Badge><Badge>{a.execution_kind}</Badge><Badge>{a.cost_units} cost units</Badge></div><p className="mt-2">Abuse attempted: {a.coverage.abuse_attempted?"yes":"no"}; containment {a.coverage.containment_ids.join(", ")||"gap"}; detection {a.coverage.detection_ids.join(", ")||"gap"}; recovery {a.coverage.recovery_ids.join(", ")||"gap"}.</p>{[...a.coverage.gaps,...a.unsafe_reasons,...a.non_reproducible_reasons].map(x=><p key={x} className="mt-1 text-[var(--warning)]">{x}</p>)}<p className="mt-2 text-xs text-[var(--muted)]">Provenance: {a.provenance.join(" · ")} · {a.artifacts.length} sanitized artifacts · {a.commands.length} retained commands</p></div>)}</Card>)}{items.length===0&&<Card className="p-5 text-sm text-[var(--muted)]">No reviewed security scenario evidence has been published.</Card>}</div>
  </section>
}
function Evidence({title,values}:{title:string;values:string[]}){return <section><h4 className="text-sm font-semibold">{title}</h4><ul className="mt-2 space-y-1 text-sm">{values.map((x,i)=><li key={`${i}-${x}`}>{x}</li>)}</ul></section>}
