"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Revision = { version:number; title:string; summary:string; scopes:{kind:string;resource_id?:string;name:string}[]; protected_assets:{id:string;name:string;classification:string;protection:string;owner_ids:string[]}[]; trust_boundaries:{id:string;name:string;from:string;to:string;direction:string;asset_ids:string[];guarantees:string[];conflicts_with?:string[]}[]; actors:{id:string;name:string;kind:string;trust:string;capabilities:string[]}[]; abuse_cases:{id:string;title:string;actor_ids:string[];asset_ids:string[];boundary_ids:string[];scenario:string;impact:string;severity:string;control_ids:string[];owner_ids:string[]}[]; required_controls:{id:string;name:string;requirement:string;kind:string;owner_ids:string[];evidence?:string;status:string}[]; severity_policy:{level:string;response:string;release_rule:string}[]; commitment_links:{kind:string;resource_id:string;revision?:string;summary:string}[]; exceptions:{id:string;abuse_case_id:string;rationale:string;granted_by:string;expires_at:string;follow_up:string}[]; owner_ids:string[]; rationale:string; created_by:string; created_at:string };
type Expectation = { id:string; current_version:number; revisions:Revision[]; diagnostics:{kind:string;severity:string;message:string;resource_id?:string;attributed_to:string}[] };
const val=(f:FormData,n:string)=>String(f.get(n)??"").trim();
const list=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);

export function SecurityExpectationsWorkspace({repositoryID}:{repositoryID:string}) {
  const {token}=useAuth(),[items,setItems]=useState<Expectation[]>([]),[selected,setSelected]=useState<Expectation>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!token)return;try{const out=await api<{expectations:Expectation[]}>(`/repositories/${repositoryID}/security-expectations`,{},token);setItems(out.expectations);setSelected(old=>out.expectations.find(x=>x.id===old?.id)??out.expectations[0])}catch(reason){setError(reason instanceof Error?reason.message:"Security expectations could not be loaded.")}},[repositoryID,token]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  const current=selected?.revisions.at(-1),asset=current?.protected_assets[0],boundary=current?.trust_boundaries[0],actor=current?.actors[0],abuse=current?.abuse_cases[0],control=current?.required_controls[0],policy=current?.severity_policy[0],link=current?.commitment_links[0],exception=current?.exceptions[0];
  async function publish(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;setBusy(true);setError("");const f=new FormData(event.currentTarget),expiry=val(f,"exception_expiry");const revision={title:val(f,"title"),summary:val(f,"summary"),scopes:[{kind:val(f,"scope_kind"),resource_id:val(f,"scope_id"),name:val(f,"scope_name")},...(current?.scopes.slice(1)??[])],protected_assets:[{id:val(f,"asset_id"),name:val(f,"asset_name"),classification:val(f,"classification"),protection:val(f,"protection"),owner_ids:list(val(f,"asset_owners"))},...(current?.protected_assets.slice(1)??[])],trust_boundaries:[{id:val(f,"boundary_id"),name:val(f,"boundary_name"),from:val(f,"boundary_from"),to:val(f,"boundary_to"),direction:val(f,"direction"),asset_ids:list(val(f,"boundary_assets")),guarantees:list(val(f,"guarantees")),conflicts_with:list(val(f,"conflicts"))},...(current?.trust_boundaries.slice(1)??[])],actors:[{id:val(f,"actor_id"),name:val(f,"actor_name"),kind:val(f,"actor_kind"),trust:val(f,"trust"),capabilities:list(val(f,"capabilities"))},...(current?.actors.slice(1)??[])],abuse_cases:[{id:val(f,"abuse_id"),title:val(f,"abuse_title"),actor_ids:list(val(f,"abuse_actors")),asset_ids:list(val(f,"abuse_assets")),boundary_ids:list(val(f,"abuse_boundaries")),scenario:val(f,"scenario"),impact:val(f,"impact"),severity:val(f,"severity"),control_ids:list(val(f,"abuse_controls")),owner_ids:list(val(f,"abuse_owners"))},...(current?.abuse_cases.slice(1)??[])],required_controls:[{id:val(f,"control_id"),name:val(f,"control_name"),requirement:val(f,"requirement"),kind:val(f,"control_kind"),owner_ids:list(val(f,"control_owners")),evidence:val(f,"evidence"),status:val(f,"control_status")},...(current?.required_controls.slice(1)??[])],severity_policy:[{level:val(f,"policy_level"),response:val(f,"response"),release_rule:val(f,"release_rule")},...(current?.severity_policy.slice(1)??[])],commitment_links:[{kind:val(f,"link_kind"),resource_id:val(f,"link_id"),revision:val(f,"link_revision"),summary:val(f,"link_summary")},...(current?.commitment_links.slice(1)??[])],exceptions:expiry?[{id:val(f,"exception_id"),abuse_case_id:val(f,"exception_abuse"),rationale:val(f,"exception_rationale"),granted_by:val(f,"exception_grantor"),expires_at:new Date(expiry).toISOString(),follow_up:val(f,"follow_up")},...(current?.exceptions.slice(1)??[])]:current?.exceptions.slice(1)??[],owner_ids:list(val(f,"owners")),rationale:val(f,"rationale")};try{const path=selected?`/repositories/${repositoryID}/security-expectations/${selected.id}/revisions`:`/repositories/${repositoryID}/security-expectations`;const out=await api<Expectation>(path,{method:"POST",body:JSON.stringify({revision,...(selected?{expected_version:selected.current_version}:{})})},token);setSelected(out);setItems(values=>[out,...values.filter(x=>x.id!==out.id)])}catch(reason){setError(reason instanceof Error?reason.message:"Security expectation could not be published.")}finally{setBusy(false)}}
  return <div className="space-y-6"><header><Link href={`/repositories/${repositoryID}`} className="text-sm text-[var(--muted)] hover:text-[var(--brand)]">Repository</Link><h1 className="mt-2 text-2xl font-semibold">Security expectations</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">State what must be protected, which actors can cross each trust boundary, how abuse is controlled, and who owns the outcome before implementation hides the assumption.</p></header>
    <Card className="p-5"><div className="flex justify-between"><h2 className="font-semibold">{selected?"Publish a complete successor":"Define security intent"}</h2>{selected&&<Button type="button" variant="secondary" onClick={()=>setSelected(undefined)}>New expectation</Button>}</div><form key={selected?`${selected.id}:${selected.current_version}`:"new"} onSubmit={publish} className="mt-4 space-y-5">
      <Group title="Expectation and scope"><Field n="title" l="Title" v={current?.title}/><Field n="summary" l="Summary" v={current?.summary}/><Select n="scope_kind" l="Scope kind" v={current?.scopes[0]?.kind??"repository"} a={["repository","service","interface","package","extension","environment","journey"]}/><Field n="scope_id" l="Scope resource ID" v={current?.scopes[0]?.resource_id} req={false}/><Field n="scope_name" l="Scope name" v={current?.scopes[0]?.name}/><Field n="owners" l="Expectation owner IDs" v={current?.owner_ids.join(", ")}/></Group>
      <Group title="Protected asset"><Field n="asset_id" l="Asset ID" v={asset?.id}/><Field n="asset_name" l="Asset name" v={asset?.name}/><Field n="classification" l="Classification" v={asset?.classification}/><Field n="protection" l="Property to preserve" v={asset?.protection}/><Field n="asset_owners" l="Asset owner IDs" v={asset?.owner_ids.join(", ")}/></Group>
      <Group title="Trust boundary"><Field n="boundary_id" l="Boundary ID" v={boundary?.id}/><Field n="boundary_name" l="Boundary name" v={boundary?.name}/><Field n="boundary_from" l="From zone" v={boundary?.from}/><Field n="boundary_to" l="To zone" v={boundary?.to}/><Select n="direction" l="Direction" v={boundary?.direction??"inbound"} a={["inbound","outbound","bidirectional"]}/><Field n="boundary_assets" l="Asset IDs" v={boundary?.asset_ids.join(", ")}/><Field n="guarantees" l="Boundary guarantees" v={boundary?.guarantees.join(", ")}/><Field n="conflicts" l="Conflicting boundary IDs" v={boundary?.conflicts_with?.join(", ")} req={false}/></Group>
      <Group title="Actor and capability"><Field n="actor_id" l="Actor ID" v={actor?.id}/><Field n="actor_name" l="Actor name" v={actor?.name}/><Select n="actor_kind" l="Actor kind" v={actor?.kind??"attacker"} a={["human","agent","service","external","attacker"]}/><Select n="trust" l="Trust" v={actor?.trust??"untrusted"} a={["trusted","partially_trusted","untrusted"]}/><Field n="capabilities" l="Capabilities" v={actor?.capabilities.join(", ")}/></Group>
      <Group title="Abuse case"><Field n="abuse_id" l="Abuse case ID" v={abuse?.id}/><Field n="abuse_title" l="Title" v={abuse?.title}/><Field n="abuse_actors" l="Actor IDs" v={abuse?.actor_ids.join(", ")}/><Field n="abuse_assets" l="Asset IDs" v={abuse?.asset_ids.join(", ")}/><Field n="abuse_boundaries" l="Boundary IDs" v={abuse?.boundary_ids.join(", ")}/><Field n="scenario" l="Abuse scenario" v={abuse?.scenario}/><Field n="impact" l="Impact" v={abuse?.impact}/><Select n="severity" l="Severity" v={abuse?.severity??"high"} a={["low","medium","high","critical"]}/><Field n="abuse_controls" l="Required control IDs" v={abuse?.control_ids.join(", ")}/><Field n="abuse_owners" l="Owner IDs" v={abuse?.owner_ids.join(", ")}/></Group>
      <Group title="Required control"><Field n="control_id" l="Control ID" v={control?.id}/><Field n="control_name" l="Control name" v={control?.name}/><Field n="requirement" l="Required behavior" v={control?.requirement}/><Select n="control_kind" l="Control kind" v={control?.kind??"prevent"} a={["prevent","detect","respond","recover"]}/><Field n="control_owners" l="Owner IDs" v={control?.owner_ids.join(", ")}/><Field n="evidence" l="Supporting evidence" v={control?.evidence} req={false}/><Select n="control_status" l="Support status" v={control?.status??"planned"} a={["supported","planned","unsupported"]}/></Group>
      <Group title="Severity and linked commitments"><Select n="policy_level" l="Policy level" v={policy?.level??"critical"} a={["low","medium","high","critical"]}/><Field n="response" l="Required response" v={policy?.response}/><Field n="release_rule" l="Release rule" v={policy?.release_rule}/><Select n="link_kind" l="Commitment kind" v={link?.kind??"design"} a={["design","privacy","infrastructure","api","quality","release"]}/><Field n="link_id" l="Commitment ID" v={link?.resource_id}/><Field n="link_revision" l="Commitment revision" v={link?.revision} req={false}/><Field n="link_summary" l="Commitment relationship" v={link?.summary}/></Group>
      <Group title="Permitted exception (optional)"><Field n="exception_id" l="Exception ID" v={exception?.id} req={false}/><Field n="exception_abuse" l="Abuse case ID" v={exception?.abuse_case_id} req={false}/><Field n="exception_rationale" l="Rationale" v={exception?.rationale} req={false}/><Field n="exception_grantor" l="Grantor user ID" v={exception?.granted_by} req={false}/><Field n="exception_expiry" l="Expiry" type="datetime-local" v={exception?.expires_at?.slice(0,16)} req={false}/><Field n="follow_up" l="Follow-up work" v={exception?.follow_up} req={false}/></Group><Field n="rationale" l="Revision rationale" v={current?.rationale}/><Button disabled={busy}>{busy?"Publishing…":"Publish version"}</Button></form></Card>
    {error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}<section><h2 className="font-semibold">Versioned expectations</h2><div className="mt-3 grid gap-3">{items.map(x=>{const r=x.revisions.at(-1);return <Card key={x.id} className="p-4"><button className="w-full text-left" onClick={()=>setSelected(x)}><div className="flex flex-wrap items-center gap-2"><strong>{r?.title}</strong><Badge>v{x.current_version}</Badge>{x.diagnostics.map((d,i)=><Badge key={`${d.kind}-${i}`} tone={d.severity==="blocking"?"danger":"warning"}>{d.kind.replaceAll("_"," ")}</Badge>)}</div><p className="mt-2 text-sm text-[var(--muted)]">{r?.summary}</p><p className="mt-2 text-xs text-[var(--muted)]">{r?.protected_assets.length} assets · {r?.trust_boundaries.length} boundaries · {r?.abuse_cases.length} abuse cases · {r?.required_controls.length} controls</p></button></Card>})}{items.length===0&&<p className="text-sm text-[var(--muted)]">No security expectation has been published.</p>}</div></section>
  </div>
}
function Group({title,children}:{title:string;children:React.ReactNode}){return <fieldset className="grid gap-3 rounded-lg border border-[var(--line)] p-4 md:grid-cols-2"><legend className="px-2 text-sm font-semibold">{title}</legend>{children}</fieldset>}
function Field({n,l,v,req=true,type="text"}:{n:string;l:string;v?:string;req?:boolean;type?:string}){return <label className="text-sm font-medium">{l}<input name={n} type={type} required={req} defaultValue={v} className="mt-1 block min-h-10 w-full rounded-lg border border-[var(--line-strong)] bg-white px-3 text-sm"/></label>}
function Select({n,l,v,a}:{n:string;l:string;v:string;a:string[]}){return <label className="text-sm font-medium">{l}<select name={n} defaultValue={v} className="mt-1 block min-h-10 w-full rounded-lg border border-[var(--line-strong)] bg-white px-3 text-sm">{a.map(x=><option key={x}>{x}</option>)}</select></label>}
