"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button, Card } from "./ui";

type Revision={version:number;title:string;source:{kind:string;resource_id:string;revision:string;summary:string};entry_points:{id:string;name:string;access:string;boundary:string}[];privileges:{id:string;principal:string;capability:string;scope:string}[];data_flows:{id:string;from:string;to:string;data:string;protection:string}[];dependencies:{id:string;name:string;revision:string;trust:string}[];abuse_paths:{id:string;attacker_goal:string;steps:string[];impact:string;residual_risk:string;owner_ids:string[]}[];mitigations:{id:string;description:string;status:string;owner_ids:string[]}[];evidence:{id:string;summary:string;accessible:boolean;gap?:string}[];alternatives:{id:string;name:string;security_effect:string;tradeoffs:string[]}[];owner_ids:string[];assumptions:string[]};
type Model={id:string;current_version:number;revisions:Revision[];events:{id:string;kind:string;body:string;actor_id:string;actor_type:string;created_at:string}[];acknowledgements:{owner_id:string;decision:string;note:string}[];freshness:{fresh:boolean;reasons:string[]}};
const value=(f:FormData,n:string)=>String(f.get(n)??"").trim();
const csv=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);
const json=<T,>(f:FormData,n:string)=>JSON.parse(value(f,n)) as T;

export function ThreatModelsWorkspace({repositoryID}:{repositoryID:string}){
  const {token}=useAuth(),[models,setModels]=useState<Model[]>([]),[selected,setSelected]=useState<Model>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!token)return;try{const out=await api<{threat_models:Model[]}>(`/repositories/${repositoryID}/threat-models`,{},token);setModels(out.threat_models);setSelected(old=>out.threat_models.find(x=>x.id===old?.id)??out.threat_models[0])}catch(e){setError(e instanceof Error?e.message:"Threat models could not be loaded.")}},[repositoryID,token]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function open(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;setBusy(true);setError("");const f=new FormData(e.currentTarget);try{const revision={title:value(f,"title"),source:{kind:value(f,"source_kind"),resource_id:value(f,"source_id"),revision:value(f,"source_revision"),summary:value(f,"source_summary")},architecture_digest:value(f,"architecture_digest"),trust_boundary_digest:value(f,"trust_boundary_digest"),entry_points:json(f,"entry_points"),privileges:json(f,"privileges"),data_flows:json(f,"data_flows"),dependencies:json(f,"dependencies"),abuse_paths:json(f,"abuse_paths"),mitigations:json(f,"mitigations"),evidence:json(f,"evidence"),alternatives:json(f,"alternatives"),owner_ids:csv(value(f,"owners")),assumptions:csv(value(f,"assumptions"))};const out=await api<Model>(`/repositories/${repositoryID}/threat-models`,{method:"POST",body:JSON.stringify({revision})},token);setModels(x=>[out,...x]);setSelected(out)}catch(reason){setError(reason instanceof Error?reason.message:"Threat model could not be opened.")}finally{setBusy(false)}}
  async function contribute(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!selected)return;setBusy(true);setError("");const f=new FormData(e.currentTarget);try{const out=await api<Model>(`/repositories/${repositoryID}/threat-models/${selected.id}/events`,{method:"POST",body:JSON.stringify({expected_version:selected.current_version,event:{kind:value(f,"kind"),body:value(f,"body"),resource_ids:csv(value(f,"resource_ids")),evidence_ids:csv(value(f,"evidence_ids")),alternative_ids:csv(value(f,"alternative_ids")),requested_owner_ids:csv(value(f,"requested_owner_ids"))}})},token);setSelected(out);setModels(xs=>xs.map(x=>x.id===out.id?out:x));e.currentTarget.reset()}catch(reason){setError(reason instanceof Error?reason.message:"Contribution could not be retained.")}finally{setBusy(false)}}
  const current=selected?.revisions.at(-1);
  return <section className="space-y-5" aria-labelledby="threat-model-heading"><header><h2 id="threat-model-heading" className="text-xl font-semibold">Change threat models</h2><p className="mt-1 max-w-3xl text-sm text-[var(--muted)]">Inspect how a proposed revision may be attacked, compare safer designs, and keep every conclusion tied to visible evidence.</p></header>
    <Card className="p-5"><details><summary className="cursor-pointer font-semibold">Open a revision-bound threat model</summary><form onSubmit={open} className="mt-4 grid gap-3 md:grid-cols-2"><Field n="title" l="Title"/><Select n="source_kind" l="Proposed change" a={["design_proposal","pull_request","api_evolution","schema_evolution","infrastructure_plan","product_experiment"]}/><Field n="source_id" l="Source ID"/><Field n="source_revision" l="Exact source revision"/><Field n="source_summary" l="Source summary"/><Field n="architecture_digest" l="Architecture digest"/><Field n="trust_boundary_digest" l="Trust-boundary digest"/><Field n="owners" l="Affected owner IDs"/><Field n="assumptions" l="Assumptions (comma separated)"/><JsonField n="entry_points" l="Entry points JSON" sample='[{"id":"login","name":"Login","access":"public","boundary":"internet"}]'/><JsonField n="privileges" l="Privileges JSON" sample='[{"id":"session","principal":"user","capability":"create session","scope":"account"}]'/><JsonField n="data_flows" l="Data flows JSON" sample='[{"id":"credentials","from":"browser","to":"api","data":"password","protection":"TLS"}]'/><JsonField n="dependencies" l="Dependencies JSON" sample='[{"id":"identity","name":"Identity provider","revision":"1","trust":"partial"}]'/><JsonField n="evidence" l="Permitted evidence JSON" sample='[{"id":"source","kind":"pull","resource_id":"pull-id","revision":"commit","summary":"Visible diff","accessible":true}]'/><JsonField n="mitigations" l="Mitigations JSON" sample='[{"id":"rate","description":"Rate limit attempts","status":"proposed","evidence_ids":["source"],"owner_ids":["owner-id"]}]'/><JsonField n="alternatives" l="Alternatives JSON" sample='[{"id":"a","name":"Passwords","description":"Existing","security_effect":"phishable","tradeoffs":["familiar"],"evidence_ids":["source"]},{"id":"b","name":"Passkeys","description":"Bound","security_effect":"phishing resistant","tradeoffs":["recovery"],"evidence_ids":["source"]}]'/><JsonField n="abuse_paths" l="Abuse paths JSON" sample='[{"id":"stuffing","attacker_goal":"take over accounts","entry_point_ids":["login"],"privilege_ids":["session"],"data_flow_ids":["credentials"],"dependency_ids":["identity"],"steps":["submit leaked passwords"],"impact":"account access","mitigation_ids":["rate"],"residual_risk":"distributed attempts","owner_ids":["owner-id"]}]'/><div className="md:col-span-2"><Button disabled={busy}>{busy?"Opening…":"Open threat model"}</Button></div></form></details></Card>
    {error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}
    <div className="grid gap-4 lg:grid-cols-[minmax(14rem,0.35fr)_1fr]"><div className="space-y-2">{models.map(x=><button key={x.id} onClick={()=>setSelected(x)} className="w-full rounded-lg border border-[var(--line)] bg-white p-3 text-left"><span className="font-semibold">{x.revisions.at(-1)?.title}</span><span className="mt-2 flex gap-2"><Badge>v{x.current_version}</Badge><Badge tone={x.freshness.fresh?"success":"warning"}>{x.freshness.fresh?"current":"stale"}</Badge></span></button>)}{models.length===0&&<p className="text-sm text-[var(--muted)]">No threat model has been opened.</p>}</div>
      {current&&selected&&<Card className="space-y-5 p-5"><div><div className="flex flex-wrap gap-2"><h3 className="font-semibold">{current.title}</h3><Badge>{current.source.kind.replaceAll("_"," ")}</Badge></div><p className="mt-1 text-sm text-[var(--muted)]">{current.source.summary} · revision {current.source.revision}</p>{!selected.freshness.fresh&&<p className="mt-2 text-sm text-[var(--warning)]">Reanalysis required: {selected.freshness.reasons.join(", ")}. Restricted source context remains hidden.</p>}</div><Grid title="Attack surface" values={[...current.entry_points.map(x=>`${x.name}: ${x.access} across ${x.boundary}`),...current.privileges.map(x=>`${x.principal}: ${x.capability} (${x.scope})`),...current.data_flows.map(x=>`${x.from} → ${x.to}: ${x.data} / ${x.protection}`)]}/><Grid title="Abuse paths and residual risk" values={current.abuse_paths.map(x=>`${x.attacker_goal} — ${x.steps.join(" → ")} — ${x.impact}; residual: ${x.residual_risk}`)}/><Grid title="Mitigations and alternatives" values={[...current.mitigations.map(x=>`${x.description} · ${x.status} · owners ${x.owner_ids.join(", ")}`),...current.alternatives.map(x=>`${x.name}: ${x.security_effect}; ${x.tradeoffs.join(", ")}`)]}/><form onSubmit={contribute} className="grid gap-3 rounded-lg border border-[var(--line)] p-4 md:grid-cols-2"><Select n="kind" l="Contribution" a={["finding","challenge","alternative_comparison","acknowledgement_request"]}/><Field n="evidence_ids" l="Permitted evidence IDs"/><Field n="resource_ids" l="Affected graph IDs"/><Field n="alternative_ids" l="Compared alternative IDs" req={false}/><Field n="requested_owner_ids" l="Owners to acknowledge" req={false}/><label className="text-sm font-medium md:col-span-2">Finding or challenge<textarea name="body" required rows={3} className="mt-1 block w-full rounded-lg border border-[var(--line-strong)] bg-white p-3"/></label><div className="md:col-span-2"><Button disabled={busy}>Add cited contribution</Button></div></form>{selected.events.map(x=><div key={x.id} className="border-t border-[var(--line)] pt-3 text-sm"><Badge>{x.kind.replaceAll("_"," ")}</Badge><p className="mt-2">{x.body}</p><p className="mt-1 text-xs text-[var(--muted)]">{x.actor_type} {x.actor_id}</p></div>)}</Card>}</div>
  </section>
}
function Field({n,l,req=true}:{n:string;l:string;req?:boolean}){return <label className="text-sm font-medium">{l}<input name={n} required={req} className="mt-1 block min-h-10 w-full rounded-lg border border-[var(--line-strong)] bg-white px-3"/></label>};
function Select({n,l,a}:{n:string;l:string;a:string[]}){return <label className="text-sm font-medium">{l}<select name={n} className="mt-1 block min-h-10 w-full rounded-lg border border-[var(--line-strong)] bg-white px-3">{a.map(x=><option key={x}>{x}</option>)}</select></label>};
function JsonField({n,l,sample}:{n:string;l:string;sample:string}){return <label className="text-sm font-medium">{l}<textarea name={n} required rows={4} defaultValue={sample} className="mt-1 block w-full rounded-lg border border-[var(--line-strong)] bg-white p-3 font-mono text-xs"/></label>};
function Grid({title,values}:{title:string;values:string[]}){return <section><h4 className="text-sm font-semibold">{title}</h4><ul className="mt-2 space-y-2 text-sm">{values.map((x,i)=><li key={i} className="rounded-lg bg-[var(--surface-subtle)] p-3">{x}</li>)}</ul></section>}
