"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useAuth } from "@/components/auth";
import { Badge, Button, Card } from "@/components/ui";
import { api } from "@/lib/api";

type Component = {
  id: string;
  diagnostics: string[];
  definition: {
    name: string; version: string; summary: string;
    contract: { inputs: {name:string;type:string;required:boolean}[]; outputs:{name:string;type:string;required:boolean}[] };
    requested_capabilities: {name:string;reason:string;optional?:boolean}[];
    data_use: {classification:string;purpose:string;retention:string;destinations:string[]}[];
    compatibility: {workflow_format:number;platforms:string[];predecessor?:string;breaking:boolean;migration?:string};
    tests: {name:string;outcome:string;revision:string;command_sha256:string}[];
    support: {policy:string;contact:string;until?:string;maintainer_ids:string[]};
  };
  source: {repository_id:string;revision:string;path:string;sha256:string;package_name:string;package_version:string;package_sha256:string;boundary:string;peer_id?:string};
  attestation: {publisher_id:string;published_at:string;definition_sha256:string;statement:string};
};
type Installation = {id:string;name:string;current_version:number;revisions:{version:number;component_id:string;component_version:string;pull_id:string;pull_revision:string;mappings:{capability:string;local_permission:string}[];configuration:Record<string,unknown>;accepted_data_use:string[];installed_at:string;status:string;diagnostics:string[]}[]};

export function WorkflowComponentsWorkspace({repositoryID}:{repositoryID:string}) {
  const {token,loading}=useAuth();
  const [components,setComponents]=useState<Component[]>([]), [installations,setInstallations]=useState<Installation[]>([]), [selected,setSelected]=useState<Component>(), [error,setError]=useState(""), [busy,setBusy]=useState(false);
  const [publish,setPublish]=useState({revision:"",path:".vivarium/component.json",package_name:"",package_version:"",boundary:"package",peer_id:""});
  const [install,setInstall]=useState({name:"",pull_id:""});
  const load=async()=>{if(!token)return;const [catalog,local]=await Promise.all([api<{components:Component[]}>("/workflow-components",{},token),api<{installations:Installation[]}>(`/repositories/${repositoryID}/workflow-component-installations`,{},token)]);setComponents(catalog.components);setInstallations(local.installations);setSelected(old=>catalog.components.find(x=>x.id===old?.id)??catalog.components[0]);};
  useEffect(()=>{if(loading||!token)return;let cancelled=false;void Promise.all([api<{components:Component[]}>("/workflow-components",{},token),api<{installations:Installation[]}>(`/repositories/${repositoryID}/workflow-component-installations`,{},token)]).then(([catalog,local])=>{if(cancelled)return;setComponents(catalog.components);setInstallations(local.installations);setSelected(catalog.components[0])}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:"Components could not be loaded")});return()=>{cancelled=true}},[loading,token,repositoryID]);
  const publishComponent=async(e:FormEvent)=>{e.preventDefault();if(!token)return;setBusy(true);setError("");try{await api(`/repositories/${repositoryID}/workflow-components`,{method:"POST",body:JSON.stringify(publish)},token);await load()}catch(x){setError(x instanceof Error?x.message:"Publication failed")}finally{setBusy(false)}};
  const installComponent=async(e:FormEvent)=>{e.preventDefault();if(!token||!selected)return;setBusy(true);setError("");try{const current=installations.find(x=>x.name===install.name);await api(`/repositories/${repositoryID}/workflow-component-installations`,{method:"POST",body:JSON.stringify({name:install.name,pull_id:install.pull_id,expected_version:current?.current_version??0})},token);await load()}catch(x){setError(x instanceof Error?x.message:"Installation failed")}finally{setBusy(false)}};
  return <section className="mb-8 space-y-4">
    <header><div className="flex items-center gap-2"><Badge>portable contracts</Badge><Badge>local authority only</Badge></div><h2 className="mt-2 text-2xl font-semibold">Workflow components</h2><p className="mt-1 max-w-4xl text-sm text-[var(--muted)]">Inspect immutable publisher evidence, pin an exact version through an ordinary pull, and map every requested capability to a permission owned by this repository. Component packages never import hidden executable code or publisher authority.</p></header>
    {error&&<Card className="border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</Card>}
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]">
      <Card className="p-4"><h3 className="font-semibold">Available versions</h3><div className="mt-3 space-y-2">{components.length===0&&<p className="text-sm text-[var(--muted)]">No visible attested components.</p>}{components.map(c=><button type="button" key={c.id} onClick={()=>setSelected(c)} className={`w-full rounded-lg border p-3 text-left ${selected?.id===c.id?"border-[var(--brand)]":""}`}><span className="font-medium">{c.definition.name}@{c.definition.version}</span><span className="mt-1 block text-xs text-[var(--muted)]">{c.definition.summary}</span></button>)}</div><h3 className="mt-5 font-semibold">Local pins</h3>{installations.map(x=>{const r=x.revisions.at(-1)!;return <div key={x.id} className="mt-2 rounded-lg bg-[var(--surface)] p-3 text-sm"><strong>{x.name}@{r.component_version}</strong><div className="text-xs text-[var(--muted)]">pull {r.pull_id} · revision {r.pull_revision.slice(0,8)} · {x.revisions.length} retained revision(s)</div></div>})}</Card>
      <div className="space-y-4">{selected&&<Card className="p-5"><div className="flex flex-wrap gap-2"><Badge>{selected.source.boundary}</Badge><Badge>package {selected.source.package_name}@{selected.source.package_version}</Badge>{selected.definition.compatibility.breaking&&<Badge tone="warning">breaking upgrade</Badge>}</div><h3 className="mt-3 text-xl font-semibold">{selected.definition.name}@{selected.definition.version}</h3><p className="mt-1 text-sm">{selected.definition.summary}</p>{selected.diagnostics?.map(x=><p key={x} className="mt-2 rounded-lg bg-amber-50 p-2 text-sm text-amber-900">{x}</p>)}<dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="font-medium">Exact provenance</dt><dd className="break-all text-[var(--muted)]">{selected.source.revision} · {selected.source.path}<br/>definition {selected.attestation.definition_sha256}</dd></div><div><dt className="font-medium">Support</dt><dd className="text-[var(--muted)]">{selected.definition.support.policy}<br/>{selected.definition.support.contact}</dd></div><div><dt className="font-medium">Contract</dt><dd className="text-[var(--muted)]">{selected.definition.contract.inputs.length} input(s) · {selected.definition.contract.outputs.length} output(s) · workflow format {selected.definition.compatibility.workflow_format}</dd></div><div><dt className="font-medium">Attested tests</dt><dd className="text-[var(--muted)]">{selected.definition.tests.map(x=>`${x.name}: ${x.outcome}`).join(" · ")}</dd></div></dl><h4 className="mt-4 font-medium">Requested local mappings</h4>{selected.definition.requested_capabilities.map(x=><p key={x.name} className="mt-1 text-sm"><code>{x.name}</code> — {x.reason}</p>)}<h4 className="mt-4 font-medium">Data terms</h4>{selected.definition.data_use.map(x=><p key={`${x.classification}:${x.purpose}`} className="mt-1 text-sm">{x.classification}: {x.purpose} · retain {x.retention} · {x.destinations.join(", ")}</p>)}</Card>}
        <div className="grid gap-4 md:grid-cols-2"><Card className="p-4"><h3 className="font-semibold">Publish from reviewed source</h3><form className="mt-3 space-y-2" onSubmit={publishComponent}>{Object.entries(publish).map(([key,value])=><input key={key} required={key!=="peer_id"} value={value} onChange={e=>setPublish({...publish,[key]:e.target.value})} placeholder={key.replaceAll("_"," ")} className="w-full rounded-lg border px-3 py-2 text-sm"/>)}<Button disabled={busy}>Attest immutable version</Button></form></Card><Card className="p-4"><h3 className="font-semibold">Pin or update through pull</h3><p className="mt-2 text-xs text-[var(--muted)]">The pull source must contain <code>.vivarium/workflow-components/&lt;local-name&gt;.json</code>; the server derives the component, mappings, configuration, and accepted data terms from that reviewed file.</p><form className="mt-3 space-y-2" onSubmit={installComponent}><input required value={install.name} onChange={e=>setInstall({...install,name:e.target.value})} placeholder="local installation name" className="w-full rounded-lg border px-3 py-2 text-sm"/><input required value={install.pull_id} onChange={e=>setInstall({...install,pull_id:e.target.value})} placeholder="open pull ID" className="w-full rounded-lg border px-3 py-2 text-sm"/><Button disabled={busy||!selected}>Pin pull declaration</Button></form></Card></div>
      </div>
    </div>
  </section>;
}
