"use client";
import { FormEvent, useEffect, useState } from "react";
import { api, APIError, CheckpointAnalysis, DevelopmentWorkspace, WorkspaceCheckpoint } from "@/lib/api";
import { useAuth } from "./auth";
import { Badge, Button } from "./ui";

export function WorkspaceCheckpoints({workspace,onWorkspace}:{workspace:DevelopmentWorkspace;onWorkspace:(w:DevelopmentWorkspace)=>void}) {
  const {token}=useAuth(), [items,setItems]=useState<WorkspaceCheckpoint[]>([]), [analysis,setAnalysis]=useState<CheckpointAnalysis>(), [allowConflicts,setAllowConflicts]=useState(false), [pending,setPending]=useState(false), [error,setError]=useState("");
  const load=async()=>{if(!token)return;try{const v=await api<{items:WorkspaceCheckpoint[]}>(`/workspaces/${workspace.id}/checkpoints`,{},token);setItems(v.items);setError("");}catch(e){setError(e instanceof APIError?e.message:"Checkpoints could not be loaded.")}};
  useEffect(()=>{if(!token)return;let active=true;void api<{items:WorkspaceCheckpoint[]}>(`/workspaces/${workspace.id}/checkpoints`,{},token).then(v=>{if(active)setItems(v.items)}).catch(e=>{if(active)setError(e instanceof APIError?e.message:"Checkpoints could not be loaded.")});return()=>{active=false}},[token,workspace.id]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;setPending(true);const form=e.currentTarget;const data=new FormData(form);try{await api(`/workspaces/${workspace.id}/checkpoints`,{method:"POST",body:JSON.stringify({title:String(data.get("title")),description:String(data.get("description")),expected_parent_checkpoint_id:workspace.head_checkpoint_id||"",reproducibility:{dependencies:workspace.definition.dependencies,notes:String(data.get("notes"))}})},token);form.reset();await load();const updated=await api<DevelopmentWorkspace>(`/workspaces/${workspace.id}`,{},token);onWorkspace(updated)}catch(x){setError(x instanceof APIError?x.message:"Checkpoint could not be created.")}finally{setPending(false)}}
  async function inspect(id:string){if(!token)return;setPending(true);setAllowConflicts(false);try{setAnalysis(await api<CheckpointAnalysis>(`/workspaces/${workspace.id}/checkpoints/${id}/restore`,{},token));setError("")}catch(x){setError(x instanceof APIError?x.message:"Restore could not be inspected.")}finally{setPending(false)}}
  async function restore(a:CheckpointAnalysis){if(!token)return;setPending(true);try{const v=await api<{workspace:DevelopmentWorkspace}>(`/workspaces/${workspace.id}/checkpoints/${a.checkpoint_id}/restore`,{method:"POST",body:JSON.stringify({preflight_token:a.preflight_token,allow_conflicts:allowConflicts})},token);onWorkspace(v.workspace);setAnalysis(undefined);setAllowConflicts(false);await load()}catch(x){setError(x instanceof APIError?x.message:"Checkpoint could not be restored.")}finally{setPending(false)}}
  async function publish(e:FormEvent<HTMLFormElement>,checkpoint:WorkspaceCheckpoint){e.preventDefault();if(!token)return;setPending(true);const data=new FormData(e.currentTarget);try{await api(`/workspaces/${workspace.id}/checkpoints/${checkpoint.id}/publish`,{method:"POST",body:JSON.stringify({branch:String(data.get("branch")),target_branch:String(data.get("target_branch")),expected_commit_id:checkpoint.base_commit_id,title:checkpoint.title,create_pull_request:data.get("create_pull_request")==="on"})},token);await load();setError("")}catch(x){setError(x instanceof APIError?x.message:"Checkpoint could not enter review.")}finally{setPending(false)}}
  return <section className="mt-6 border-t border-[var(--line)] pt-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[var(--brand)]">Durable unfinished work</p><h2 className="mt-1 text-lg font-semibold">Checkpoints and lineage</h2></div><Badge tone="info">{items.length} retained</Badge></div>
    <p className="mt-2 text-sm text-[var(--muted)]">Captures repository changes and the frozen environment only. Credentials, terminals, previews, and unrelated runtime data are never included.</p>
    {error&&<p role="alert" className="mt-3 text-sm text-[var(--danger)]">{error}</p>}
    <form onSubmit={create} className="mt-4 grid gap-2 rounded-xl border border-[var(--line)] p-4 md:grid-cols-3"><input required name="title" placeholder="Checkpoint title" className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm"/><input name="description" placeholder="What remains unfinished?" className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm"/><input name="notes" placeholder="Reproduction notes" className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm"/><Button disabled={pending} className="md:col-span-3">Create attributed checkpoint</Button></form>
    <ol className="mt-4 space-y-3">{[...items].reverse().map(c=><li key={c.id} className="rounded-xl border border-[var(--line)] p-4"><div className="flex justify-between gap-3"><div><b>{c.title}</b><p className="text-xs text-[var(--muted)]">{c.created_by.slice(0,8)} · {new Date(c.created_at).toLocaleString()} · base {c.base_commit_id.slice(0,8)}{c.parent_checkpoint_id?` · from ${c.parent_checkpoint_id.slice(0,8)}`:" · root"}</p></div><Button variant="secondary" disabled={pending} onClick={()=>void inspect(c.id)}>Inspect restore</Button></div>{c.description&&<p className="mt-2 text-sm">{c.description}</p>}<div className="mt-3 flex flex-wrap gap-2">{c.files.map(f=><Badge key={f.path} tone={f.operation==="delete"?"warning":"info"}>{f.operation} {f.path}</Badge>)}</div>{c.publication?<div className="mt-3 rounded-lg border border-[var(--line)] p-3 text-xs"><Badge tone="success">published</Badge><p className="mt-2 font-mono">{c.publication.branch} · {c.publication.commit_id.slice(0,8)}</p>{c.publication.pull_request_id&&<a className="mt-2 inline-block text-[var(--brand)] underline" href={`/pulls/${c.repository_id}/${c.publication.pull_request_id}`}>Open governed review</a>}</div>:<form onSubmit={e=>void publish(e,c)} className="mt-3 grid gap-2 rounded-lg border border-[var(--line)] p-3 md:grid-cols-2"><input required name="branch" placeholder="workspace/change-name" className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm"/><input required name="target_branch" defaultValue="main" className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" name="create_pull_request" defaultChecked/> Create ordinary pull request</label><Button disabled={pending||c.files.length===0}>Commit checkpoint and publish</Button><p className="text-xs text-[var(--muted)] md:col-span-2">Creates a branch from the exact checkpoint base. Only inspected checkpoint files enter Git; contributor and command digests remain review evidence.</p></form>}</li>)}</ol>
    {analysis&&<div className="mt-4 rounded-xl border border-[var(--line)] p-4"><h3 className="font-semibold">Restore preflight</h3><div className="mt-2 flex gap-2"><Badge tone={analysis.reproducible?"success":"danger"}>{analysis.reproducible?"reproducible":"non-reproducible"}</Badge>{analysis.base_diverged&&<Badge tone="warning">repository base diverged</Badge>}{analysis.conflicts.length>0&&<Badge tone="danger">{analysis.conflicts.length} conflicts</Badge>}</div>{analysis.reasons.map(x=><p key={x} className="mt-2 text-sm text-[var(--danger)]">{x}</p>)}{analysis.missing_dependencies.length>0&&<p className="mt-2 text-sm">Missing dependencies: {analysis.missing_dependencies.join(", ")}</p>}{analysis.conflicts.length>0&&<><p className="mt-2 text-sm">Conflicting live paths: {analysis.conflicts.join(", ")}</p><label className="mt-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={allowConflicts} onChange={e=>setAllowConflicts(e.target.checked)}/><span><b>Replace conflicting live paths</b><br/><span className="text-xs text-[var(--muted)]">The selected checkpoint becomes authoritative for these paths. Other checkpoint lineage remains retained.</span></span></label></>}<p className="mt-2 text-xs text-[var(--muted)]">Restoring moves the workspace lineage to this checkpoint; the next checkpoint branches from it.</p><Button className="mt-3" disabled={pending||(analysis.conflicts.length>0&&!allowConflicts)} onClick={()=>void restore(analysis)}>Restore and branch from checkpoint</Button></div>}
  </section>
}
